<?php
use Jet\Mvc_View;
use Jet\Form_Renderer;
/**
 * @var Mvc_View      $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if(!$r->getBaseCssClasses()) {
	$r->setBaseCssClass('form-group row');
}

if($r->getField()->getLastErrorMessage()) {
	$r->addCustomCssClass('has-error has-feedback');
}

?>
<div <?php
if($r->getCssClasses()) echo ' class="'.$r->getCssClasses().'"';
if($r->getCssStyles()) echo ' style="'.$r->getCssStyles().'"';
if($r->getJsActions()) echo $r->getJsActions();
?>>
