<?php
namespace JetStudio;


$current = DataModels::getCurrentModel();

if(!$current) {
	return;
}
?>
<?php $current->showSortPropertiesForm() ?>

<div id="property_sort_area">
	<?php foreach($current->getProperties() as $property):
		$this->setVar('property', $property);

 	?>
        <div class="property-sort-item"
             data-property-id="<?=$property->getInternalId()?>"
             data-priority="<?=$property->getInternalPriority()?>"
        >

            <div class="card panel-<?=$property->getHeadCssClass()?>" id="property_panel_<?=$property->getInternalId()?>">
                <div class="card-header" id="property_header_area_<?=$property->getInternalId()?>" data-toggle="collapse" data-target="#property_detail_area_<?=$property->getInternalId()?>">
					<?php require 'list/item-header.phtml';  ?>
                </div>

                <div class="card-body collapse" id="property_detail_area_<?=$property->getInternalId()?>">
                    <?php require 'list/item-body.phtml';  ?>
                </div>
            </div>

        </div>
	<?php endforeach; ?>
</div>
