<?php

use Jet\UI_searchField;
use Jet\UI;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var UI_searchField $f
 */
$f = $this->getRaw( 'element' );

if(!$f->getPlaceholder()) {
	$f->setPlaceholder(UI::_('Search for...'));
}

$f->setBaseCssClass('form-control');
$f->setCustomTagAttribute('type', 'text');
?>

<div class="input-group">
	<div class="input-group-prepend">
		<button class="btn btn-outline-secondary" type="button"
		        onclick="this.form.<?= $f->getName() ?>.value='';this.form.submit();">
			<?= UI::icon( 'times' ) ?>
		</button>
	</div>
	<input <?=$f->renderTagAttributes()?>/>
	<div class="input-group-append">
		<button class="btn btn-outline-secondary" type="submit">
			<?= UI::icon( 'search' ) ?>
		</button>
	</div>
</div>
