<?php
/**
 *
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license http://www.php-jet.net/license/license.txt
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
$prefix = '__profiler__';

require 'css.phtml';
require 'js.phtml';
?>
<div id="__profiler__spacer__">

</div>

<div id="__profiler__" class="__error">
	<div class="__close_btn" onclick="__profiler__close();">&#x2715;</div>
	<div class="__title">
		<b>PROFILER ERROR</b>
	</div>
	<div class="__error_msg">
		<?=$this->save_error;?>
	</div>
</div>
