<?php
use Jet\UI;
use Jet\Form;
use Jet\Mvc;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 4 ] );

?>
<?=$form->start()?>
<div class="row">
	<div class="col-md-12" style="padding: 0px">
		<div class="toolbar" id="main-toolbar">
			<?=UI::button_goBack()->setUrl( Mvc::getCurrentPage()->getURI() )?>

			<?php if( !$form->getIsReadonly() ): ?>
				<?=UI::button_save()?>
			<?php endif; ?>
		</div>

		<div class="container-fluid">
			<div class="row main-row">
				<div class="col-md-12 main-col">
					<?php foreach( $form->getFields() as $field ): ?>
						<?=$field?>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
	</div>
</div>
<?=$form->end()?>
