<?php
namespace %NAMESPACE%;

%ITEM_USE%
use Jet\UI_dataGrid;
use Jet\UI;
use Jet\UI_button;

use Jet\Tr;
use Jet\Mvc_View;

/**
 * @var Mvc_View               $this
 * @var %ROUTER_CLASS_NAME% $router
 * @var UI_dataGrid            $grid
 */
$router = $this->getController()->getControllerRouter();

$delete_uri = $router->getDeleteURI();

$grid = $this->getRaw( 'grid' );

if($delete_uri) {
	$grid->setCustomFooter( '<tr><td colspan="'.count($grid->getColumns()).'">'.UI::button_delete('%DELETE_BT_LABEL%')->setType('submit').'</td></tr>' );
}


%GRID_RENDERERS%
?>
<div class="row">
	<div class="col-md-12" style="padding: 0px">
		<div class="toolbar" id="main-toolbar">
			<div class="col-xs-7 col-md-3">
				<?=$this->getRaw( 'search_form' ) ?>
			</div>
			<div class="col-xs-5 col-md-3">
				<?php if( ( $add_uri = $router->getAddURI() ) ): ?>
					<?=UI::button_create( Tr::_( '%CRETE_BT_LABEL%' ) )->setUrl( $add_uri )?>
				<?php endif; ?>
			</div>
		</div>
	</div>
</div>

<div class="row main-row">
	<div class="col-md-12 main-col">
	<div class="col-md-12 main-col">
		<?php if($delete_uri): ?>
			<form action="<?=$router->getDeleteURI()?>" method="post">
				<?=$grid->render()?>
			</form>
		<?php else: ?>
			<?=$grid->render()?>
		<?php endif; ?>
	</div>
	</div>
</div>

