<?php
use JetApplicationModule\JetExample\UIElements\DataGrid;

/**
 * @var DataGrid $grid
 */
$grid = $this->grid;

$images_URI = $this->images_uri;
?>
<table class="table table-striped">

<thead>
<tr>
	<?php foreach( $grid->getColumns() as $column ):
		$style = $column->getCssStyle() ? ' style="'.$column->getCssStyle().'"':'';
		$class = $column->getCssClass() ? ' class="'.$column->getCssClass().'"':'';
		?>
		<th<?=$class;?><?=$style;?>>
			<?php if($column->getAllowSort()): ?>
				<a href="<?=$grid->getSortURL($column->getName());?>"><img src="<?=$images_URI;?>arrow_down.png"></a>
			<?php endif; ?>

			<?=$column->getTitle();?>
			<?php if($column->getAllowSort()): ?>
			<a href="<?=$grid->getSortURL($column->getName(), true);?>"><img src="<?=$images_URI;?>arrow_up.png"></a>
			<?php endif; ?>
		</th>
	<?php endforeach; ?>
</tr>
</thead>
