<?php
use Jet\Mvc_Layout;
use Jet\Mvc;
use Jet\Tr;

/**
 * @var Mvc_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html lang="<?=Mvc::getCurrentLocale()->getLanguage()?>">
<head>
	<title><?=Mvc::getCurrentSite()->getLocalizedData( Mvc::getCurrentLocale() )->getTitle()?> : <?=Mvc::getCurrentPage()->getTitle()?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="<?=Mvc::getCurrentLocale()->getLanguage()?>" />

	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>

</head>
<body>
<div class="container-fluid">
	<div class="page-header well well-large">
		<h1><?=Tr::_('Hello WORLD!')?></h1>
		<small><?=Tr::_("PHP Jet Example Application");?></small>
	</div>

	<jet_module module="UI.Web" action="breadcrumbNavigation" view="default" is_cacheable="true" />

	<div class="row">
		<div class="col-md-3">
			<jet_module module="UI.Web" action="main_menu" is_cacheable="true"/>
			<jet_layout_position name="left"/>
		</div>
		<div class="col-md-7" style="padding-top: 10px;padding-bottom: 20px;">
			<jet_layout_main_position/>
		</div>
		<div class="col-md-2">
			<div class="well well-small">
				<jet_module module="Test.MVC" action="test_mvc_info" is_cacheable="true" />
			</div>
			<jet_layout_position name="right"/>
		</div>
	</div>
</div>
</body>
</html>