<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

$dialog = UI::dialog('dialog_create_new_menu_namespace', Tr::_('Create a new Menu namespace'), 600);

echo $dialog->start();
	?>
	<div id="<?=Menus_MenuNamespace::getCreateForm()->getId()?>_form_area">
		<?php require 'form.phtml'; ?>
	</div>
	<?php
echo $dialog->footer();
	echo UI::button_save(Tr::_('Create'))->setOnclick('JetStudio.Menus.createNamespace.createSend()');
echo $dialog->end();

