<?php
namespace JetApplicationModule\JetExample\AdminRoles;
use Jet;
use JetApplicationModule\JetExample\UIElements;

/**
 * @var UIElements\DataGrid $grid
 */
$grid = $this->grid;

$c_edit = $grid->getColumn('_edit_');
$c_edit->setDisplayCallback( function( Jet\Auth_Role_Abstract $item ) {
	$ID = rawurlencode($item->getID());
	?>
	<a href="?ID=<?=$ID;?>" class="btn btn-default btn-xs"><?=Jet\Tr::_('Edit');?></a>
	&nbsp;
	<a href="?delete=<?=$ID;?>" class="btn btn-danger btn-xs"><?=Jet\Tr::_('Delete');?></a>
<?php
} );
$c_edit->setCssStyle( 'width:120px;' );

$grid->getColumn('ID')->setDisplayCallback( function( Jet\Auth_Role_Abstract $item ) {
	$ID = rawurlencode($item->getID());
	?>
	<a href="?ID=<?=$ID;?>"><?=$item->getID();?></a>
	<?php
} );

$grid->getColumn('name')->setDisplayCallback( function( Jet\Auth_Role_Abstract $item ) {
	echo $item->getName();
} );
$grid->getColumn('description')->setDisplayCallback( function( Jet\Auth_Role_Abstract $item ) {
	echo $item->getDescription();
} );



?>

<div style="padding: 10px;">

<a href="?new" class="btn btn-primary"><?=Jet\Tr::_('Add new role');?></a>

	<?=$grid->render();?>
</div>