<?php
namespace JetApplicationModule\JetExample\AdminRoles;
use Jet;
use JetApplicationModule\JetExample\UIElements;

/**
 * @var UIElements\DataGrid $grid
 */
$grid = $this->grid;

/**
 * @var Jet\Mvc_MicroRouter $router
 */
$router = $this->router;

$c_edit = $grid->getColumn('_edit_');
$c_edit->setDisplayCallback( function( Jet\Auth_Role_Abstract $item ) use ($router) {
	?>
	<?php if($router->getActionAllowed('edit')): ?>
		<a href="<?=$router->getActionURI('edit', $item);?>" class="btn btn-default btn-xs"><?=Jet\Tr::_('Edit');?></a>
	<?php endif; ?>
	&nbsp;
	<?php if($router->getActionAllowed('delete')): ?>
		<a href="<?=$router->getActionURI('delete', $item);?>" class="btn btn-danger btn-xs"><?=Jet\Tr::_('Delete');?></a>
	<?php endif; ?>
<?php
} );
$c_edit->setCssStyle( 'width:120px;' );

$grid->getColumn('ID')->setDisplayCallback( function( Jet\Auth_Role_Abstract $item ) use ($router) {
	?>
	<?php if($router->getActionAllowed('edit')): ?>
		<a href="<?=$router->getActionURI('edit', $item);?>"><?=$item->getName();?></a>
	<?php else: ?>
		<a href="<?=$router->getActionURI('view', $item);?>"><?=$item->getName();?></a>
	<?php endif; ?>
<?php
} );

$grid->getColumn('name')->setDisplayCallback( function( Jet\Auth_Role_Abstract $item ) {
	echo $item->getName();
} );
$grid->getColumn('description')->setDisplayCallback( function( Jet\Auth_Role_Abstract $item ) {
	echo $item->getDescription();
} );



?>

<div style="padding: 10px;">

	<?php if($router->getActionAllowed('add')): ?>
		<a href="<?=$router->getActionURI('add');?>" class="btn btn-primary"><?=Jet\Tr::_('Add new role');?></a>
	<?php endif; ?>


	<?=$grid->render();?>
</div>