<?php
namespace JetApplicationModule\JetExample\Articles;
use Jet;
use Jet\Auth_Role_Abstract;
use Jet\Mvc_MicroRouter;
use Jet\Mvc;
use Jet\Tr;

/**
 * @var Auth_Role_Abstract $role
 */
$role = $this->role;

/**
 * @var Mvc_MicroRouter $router
 */
$router = $this->router;

?>

<div style="padding: 10px;">

	<a href="<?=Mvc::getCurrentURI();?>" class="btn btn-default"><?=Tr::_('&lt Back');?></a>

	<p>
	<?=Tr::_('Do you really want to delete this role?');?>
	<br/>
	<a href="<?=$router->getActionURI('edit', $role);?>" style="font-weight: bolder;font-size: 20px;"><?=$role->getName();?> (<?=$role->getID();?>)</a>
	</p>

	<form action="?delete=<?=rawurlencode($role->getID());?>" method="post">
		<input type="hidden" name="delete" value="yes">
		<input type="submit" value="<?=Tr::_('YES! Delete it!');?>" class="btn btn-danger"/>
	</form>
</div>