<?php
namespace JetApplicationModule\JetExample\AdminRoles;
use Jet;

/**
 * @var Jet\Auth_Role_Default $role
 */
$role = $this->role;
/**
 * @var Jet\Form $form
 */
$form = $this->form;

/**
 * @var Jet\Auth_Role_Privilege_AvailablePrivilegesListItem[] $available_privileges_list
 */
$available_privileges_list = $this->available_privileges_list;
?>
[<a href="?#">X</a>]
<jet_form name="<?=$form->getName();?>"><table>
	<jet_form_field name="ID"/>
	<tr>
		<td valign="top"><jet_form_field_label name="name"/></td>
		<td><jet_form_field_error_msg name="name" class="error"/><jet_form_field name="name"/></td>
	</tr>
	<tr>
		<td valign="top"><jet_form_field_label name="description"/></td>
		<td><jet_form_field_error_msg name="description" class="error"/><jet_form_field name="description"/></td>
	</tr>
	<tr>
		<td valign="top"><jet_form_field_label name="/privileges/visit_page"/></td>
		<td><jet_form_field_error_msg name="/privileges/visit_page" class="error"/><jet_form_field name="/privileges/visit_page"/></td>
	</tr>
	<tr>
		<td valign="top"><jet_form_field_label name="/privileges/module_action"/></td>
		<td><jet_form_field_error_msg name="/privileges/module_action" class="error"/><jet_form_field name="/privileges/module_action"/></td>
	</tr>

	<?php foreach($available_privileges_list as $privilege=>$pd ): ?>
	<tr>
		<td valign="top"></td>
		<td>
			<jet_form_field_label name="/privileges/<?=$privilege;?>/values"/>
			<br/>
			<jet_form_field_error_msg name="/privileges/<?=$privilege;?>/values" class="error"/>
			<jet_form_field name="/privileges/<?=$privilege;?>/values"/>
		</td>
	</tr>
	<?php endforeach; ?>

	<tr><td colspan="2" align="center"><input type="submit" value="<?=Jet\Tr::_("Save");?>"/></td></tr>
</table>
</jet_form>

<?php if(!$role->getIsNew()): ?>
<div>
	Users:
	<table border="1">
	<?php foreach( $role->getUsers() as $user ):
		/**
		 * @var Jet\Auth_User_Abstract $user
		 */
		?>
		<tr>
			<td><a href="<?=Jet\Mvc_Pages::getURI('admin_classic_users');?>?ID=<?=(string)$user->getID(); ?>">EDIT</a></td>
			<td><?=$user->getLogin(); ?></td>
		</tr>
	<?php endforeach; ?>
	</table>
</div>
<?php endif; ?>
