<?php
namespace JetApplicationModule\JetExample\AdminRoles;
use Jet;
use Jet\Auth_Role;
use Jet\Form;
use Jet\Auth_Role_Privilege_AvailablePrivilegesListItem;
use Jet\Tr;
use Jet\Mvc_Page;
use Jet\Auth_User_Abstract;
use Jet\Mvc;

/**
 * @var Auth_Role $role
 */
$role = $this->role;
/**
 * @var Form $form
 */
$form = $this->form;

/**
 * @var Auth_Role_Privilege_AvailablePrivilegesListItem[] $available_privileges_list
 */
$available_privileges_list = $this->available_privileges_list;


?>

<div style="padding: 10px;">

<a href="<?=Mvc::getCurrentURI();?>" class="btn btn-warning"><?=Tr::_('&lt; go back');?></a>


<jet_form name="<?=$form->getName();?>" role="form">
	<jet_form_field name="ID"/>

	<div class="form-group">
			<jet_form_field_label name="name"/>
			<jet_form_field_error_msg name="name" class="error"/>
			<jet_form_field name="name" class="form-control"/>
	</div>

	<div class="form-group">
		<jet_form_field_label name="description"/>
		<jet_form_field_error_msg name="description" class="error"/>
		<jet_form_field name="description" class="form-control"/>
	</div>
	<fieldset>
		<legend><?=Tr::_('Privileges');?></legend>
		<?php foreach($available_privileges_list as $privilege=>$pd ): ?>
		<div class="form-group">
				<jet_form_field_label name="/privileges/<?=$privilege;?>/values"/>
				<jet_form_field_error_msg name="/privileges/<?=$privilege;?>/values" class="error"/>
				<jet_form_field name="/privileges/<?=$privilege;?>/values" class="form-control"/>
		</div>
		<?php endforeach; ?>
	</fieldset>

	<?php if($this->has_access): ?>
	<input type="submit" value="<?=Tr::_("Save");?>" class="btn btn-primary"/>
	<?php endif; ?>

</jet_form>

	<br/>
	<br/>
	<br/>
<?php if($role && count($role->getUsers())): ?>
	<fieldset>
		<legend><?=Tr::_('Users');?></legend>
			<table class="table table-striped">
				<thead>
					<tr>
						<th><?=Tr::_('Login');?></th>
					</tr>
				</thead>
				<tbody>
			<?php foreach( $role->getUsers() as $user ):
				/**
				 * @var Auth_User_Abstract $user
				 */
				?>
				<tr>
					<td><a href="<?=Mvc_Page::get('admin/classic/users')->getURL( ['ID'=>$user->getID()] );?>"><?=$user->getLogin(); ?></a></td>
				</tr>
			<?php endforeach; ?>
				</tbody>
			</table>
	</fieldset>
<?php endif; ?>

</div>