<?php
namespace JetApplicationModule\JetExample\AdminRoles;
use Jet;

/**
 * @var Jet\Auth_Role_Default $role
 */
$role = $this->role;
/**
 * @var Jet\Form $form
 */
$form = $this->form;

/**
 * @var Jet\Auth_Role_Privilege_AvailablePrivilegesListItem[] $available_privileges_list
 */
$available_privileges_list = $this->available_privileges_list;

?>

<div style="padding: 10px;">

<a href="?#" class="btn btn-warning"><?=Jet\Tr::_('&lt; go back');?></a>


<jet_form name="<?=$form->getName();?>" role="form">
	<jet_form_field name="ID"/>

	<div class="form-group">
			<jet_form_field_label name="name"/>
			<jet_form_field_error_msg name="name" class="error"/>
			<jet_form_field name="name" class="form-control"/>
	</div>

	<div class="form-group">
		<jet_form_field_label name="description"/>
		<jet_form_field_error_msg name="description" class="error"/>
		<jet_form_field name="description" class="form-control"/>
	</div>
	<fieldset>
		<legend><?=Jet\Tr::_('Privileges');?></legend>
		<?php foreach($available_privileges_list as $privilege=>$pd ): ?>
		<div class="form-group">
				<jet_form_field_label name="/privileges/<?=$privilege;?>/values"/>
				<jet_form_field_error_msg name="/privileges/<?=$privilege;?>/values" class="error"/>
				<jet_form_field name="/privileges/<?=$privilege;?>/values" class="form-control"/>
		</div>
		<?php endforeach; ?>
	</fieldset>

	<?php if($this->has_access): ?>
	<input type="submit" value="<?=Jet\Tr::_("Save");?>" class="btn btn-primary"/>
	<?php endif; ?>

</jet_form>

	<br/>
	<br/>
	<br/>
<?php if(!$role->getIsNew() && count($role->getUsers())): ?>
	<fieldset>
		<legend><?=Jet\Tr::_('Users');?></legend>
			<table class="table table-striped">
				<thead>
					<tr>
						<th><?=Jet\Tr::_('Login');?></th>
					</tr>
				</thead>
				<tbody>
			<?php foreach( $role->getUsers() as $user ):
				/**
				 * @var Jet\Auth_User_Abstract $user
				 */
				?>
				<tr>
					<td><a href="<?=Jet\Mvc_Pages::getURI('admin_classic_users');?>?ID=<?=(string)$user->getID(); ?>"><?=$user->getLogin(); ?></a></td>
				</tr>
			<?php endforeach; ?>
				</tbody>
			</table>
	</fieldset>
<?php endif; ?>

</div>