<?php
namespace JetApplicationModule\Admin\Content\Images;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

?>
<?php require 'parts/js.phtml'; ?>

<?php require 'parts/toolbar.phtml' ?>

<div class="row">
	<div class="col-md-3">
		<?php require 'parts/galleries.phtml'; ?>
	</div>

	<div class="col-md-9 main-col">
		<div id="edit_form_area">
			<?php require 'parts/edit-form.phtml' ?>
		</div>
	</div>
</div>
