<?php
use Jet\Tr;
use Jet\Mvc_View;
use Jet\Form;

/**
 * @var Mvc_View $this
 * @var Form $form
 */
$form = $this->getRaw('form');

$form->setDefaultLabelWidth(4);
$form->setDefaultFieldWidth(8);
?>
<div style="margin-top:50px;" class="col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2">
	<div class="panel panel-default" >
		<div class="panel-heading">
			<div class="panel-title"><?=Tr::_('Please change your password');?></div>
		</div>
		<div class="panel-body" style="padding-top: 20px;">
			<?=$form->start()?>

				<?=$form->field('current_password')?>
				<?=$form->field('password')?>

				<input type="submit" value="<?=Tr::_('Change password');?>" class="btn btn-primary" style="float: right"/>
			<?=$form->end()?>
		</div>
	</div>
</div>

