<?php
use Jet\Mvc_View;
use Jet\Form;
use Jet\Mvc_Site;
use Jet\Tr;
/**
 * @var Mvc_View $this
 * @var Mvc_Site $site
 * @var Form $create_form
 * @var Form $add_locale_form
 * @var Form $main_form
 */

$main_form = $this->getRaw('main_form');
$create_form = $this->getRaw('create_form');
$add_locale_form = $this->getRaw('add_locale_form');

$main_form->setDefaultLabelWidth(2);
$create_form->setDefaultLabelWidth(2);
$add_locale_form->setDefaultLabelWidth(2);

$site = $this->getRaw('site');

?>
<?=$add_locale_form->start()?>
	<?=$add_locale_form->message()?>

	<?=$add_locale_form->field('locale')?>

	<input type="submit" value="<?=Tr::_('Add locale');?>" class="btn btn-primary"/>
<?=$add_locale_form->end()?>

<?=$main_form->start()?>
	<?=$main_form->message()?>
	<fieldset>
		<?=$main_form->field('name')?>

		<?php foreach( $site->getLocales() as $locale ): ?>

		<table><tr>
			<td>
				<a href="?remove_locale=<?=$locale;?>" class="btn-xs btn-danger"><?=Tr::_('remove');?></a>
			</td>
			<td>
				&nbsp;<b><?=$locale->getName( $this->getRaw('current_locale') );?></b>
			</td>
		</tr></table>


			<?=$main_form->field('/'.$locale.'/nonSSL')?>
			<?=$main_form->field('/'.$locale.'/SSL')?>

		<?php endforeach; ?>

		<?php if( count($site->getLocales()) ): ?>
			<input type="submit" class="btn btn-default" value="<?=Tr::_('Save site settings');?>"/>
		<?php else: ?>
			<?=Tr::_('Please add at least one locale');?>
		<?php endif; ?>
	</fieldset>
<?=$main_form->end()?>

<?php if($create_form): ?>
	<?=$create_form->start()?>
		<?=$create_form->message()?>

		<fieldset>
			<?=$create_form->field('template')?>

			<input type="submit" class="btn btn-primary" value="<?=Tr::_('Create site');?>"/>
		</fieldset>
	<?=$create_form->end()?>
<?php endif; ?>
