<?php
namespace JetApplicationModule\Admin\EventViewer\Admin;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Listing  $listing
 */
$listing = $this->getRaw( 'listing' );
$filter_form = $listing->getFilterForm();
?>
<?= $filter_form->field( 'date_time_from' )->label() ?>
<div><?= $filter_form->field( 'date_time_from' )->input()?></div>
<div></div>
<?= $filter_form->field( 'date_time_till' )->label() ?>
<div><?= $filter_form->field( 'date_time_till' )->input()?></div>
