<?php
namespace JetStudio;

use Jet\Tr;
use Jet\UI;
use Jet\Form;

$namespace = Menus::getCurrentMenuNamespace();

$form = $namespace->getEditForm();


$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);
$form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 6
]);

$delete_namespace_dialog = UI::dialog('delete_namespace_dialog', Tr::_('Delete menu namespace'), 600);

?>

<?=$form->start()?>
<div class="toolbar" id="main-toolbar">
	<?=UI::button_save()?>
	<?=UI::button_create(Tr::_('Create a new menu'))->setOnclick("JetStudio.Menus.createMenu.openDialog();")?>
	<?=UI::button_delete(Tr::_('Delete this menu namespace'))->setOnclick("$('#delete_namespace_dialog').modal('show')") ?>
</div>

<div class="container-fluid" id="main-edit-area">
	<?=Application::getGeneralView()->render('messages');?>

	<?=$form->field('menu_namespace_name')?>

	<div class="row">
		<label class="col-md-2 control-label"><?=Tr::_('Menus:')?></label>
		<div class="col-md-6">
			<div id="items_sort_area">
				<?php foreach( $namespace->getMenus() as $item ): ?>
					<div class="list-group-item menu-item-sort-item" data-id="<?=$item->getId()?>">
						<input type="hidden" name="items_sort[]" value="<?=$item->getId()?>">
						<table>
							<tr>
								<td><span class="fa fa-arrows-v" style="font-size:16px;padding-right: 5px"></span></td>

								<td>
									<a href="<?=Menus::getActionUrl('', [], null, $item->getId())?>"><?=UI::icon('sitemap')?> <?=$item->getLabel()?></a>
								</td>
							</tr>
						</table>
					</div>
				<?php endforeach; ?>
			</div>
		</div>

	</div>

</div>

<?=$form->end()?>

<?php
echo $delete_namespace_dialog->start();
	echo Tr::_('Do you really want to delete this namespace?');
echo $delete_namespace_dialog->footer();
	echo UI::button_delete()->setUrl( Menus::getActionUrl('namespace/delete') );
echo $delete_namespace_dialog->end();
?>

<?=Application::getView()->render('create_menu/dialog');?>

<script type="text/javascript">
	$(document).ready( function() {
		JetStudio.Menus.initSort();
	} );
</script>

