<?php
namespace JetStudio;

use Jet\Tr;
use Jet\UI;

$form = Menus::getCurrentMenuItem()->getEditForm();

?>

<?=$form->start()?>
<div class="toolbar" id="main-toolbar">
	<?=UI::button_save()?>
	<?=UI::button_delete(Tr::_('Delete this menu item'))->setOnclick("$('#delete_menu_item_dialog').modal('show')") ?>
</div>

<div class="container-fluid" id="main-edit-area">
	<?=Application::getGeneralView()->render('messages');?>

	<?php require 'edit_menu_item/form.phtml'; ?>


</div>

<?=$form->end()?>

<?php
$delete_menu_item_dialog = UI::dialog('delete_menu_item_dialog', Tr::_('Delete menu'), 600);
echo $delete_menu_item_dialog->start();
	echo Tr::_('Do you really want to delete this menu item?');
echo $delete_menu_item_dialog->footer();
	echo UI::button_delete()->setUrl( Menus::getActionUrl('menu_item/delete') );
echo $delete_menu_item_dialog->end();
?>
