<?php
namespace JetStudio;
?>

<script type="text/javascript">
	if(!window['JetStudio']) {
		var JetStudio = {};
	}

	JetStudio.Menus = {
		createNamespace: {
			openDialog: function() {
				$('#dialog_create_new_menu_namespace').modal('show');
			},
			createSend: function() {
				JetAjaxForm.submit(
					'<?=Menus_MenuNamespace::getCreateForm()->getId()?>',
					{
						onSuccess: function( form, response_data ) {
							location = '?namespace='+encodeURIComponent(response_data['new_namespace_id'])
						}
					}
				);
			}
		},
		createMenu: {
			openDialog: function() {
				$('#dialog_create_new_menu').modal('show');
			},
			createSend: function() {
				JetAjaxForm.submit(
					'<?=Menus_MenuNamespace_Menu::getCreateForm()->getId()?>',
					{
						onSuccess: function( form, response_data ) {
							location = '?namespace=<?=Menus::getCurrentMenuNamespaceName()?>&menu='+encodeURIComponent(response_data['new_menu_id'])
						}
					}
				);
			},
			generateId: function( name ) {
				$.ajax({
					url: '<?=Menus::getActionUrl('menu/generate_id', [], false)?>&name='+encodeURIComponent(name),
					success: function(result) {
						$('#create_menu_form__id').val( result.id );
					}
				});
			}

		},
		createMenuItem: {
			openDialog: function() {
				$('#dialog_create_new_menu_item').modal('show');
			},
			createSend: function() {
				JetAjaxForm.submit(
					'<?=Menus_MenuNamespace_Menu_Item::getCreateForm()->getId()?>',
					{
						onSuccess: function( form, response_data ) {
							location = '?namespace=<?=Menus::getCurrentMenuNamespaceName()?>&menu=<?=Menus::getCurrentMenuId()?>&item='+encodeURIComponent(response_data['new_menu_item_id'])
						}
					}
				);
			},
			generateId: function( name ) {
				$.ajax({
					url: '<?=Menus::getActionUrl('menu_item/generate_id', [], false)?>&name='+encodeURIComponent(name),
					success: function(result) {
						$('#create_menu_item_form__id').val( result.id );
					}
				});
			}

		},

		initSort: function() {
			$('#items_sort_area').sortable({
				stop: function() {
				}

			});
		}



	}
</script>
