<?php
namespace JetStudio;

use Jet\MVC_View;
use Jet\UI;
use Jet\Tr;

/**
 * @var MVC_View $this
 */
?>
<?= Application::getView()->render( 'js' ); ?>

<?php if( Menus::getCurrentMenuSet() ):

	if( Menus::getCurrentMenu() ):
		if( Menus::getCurrentMenuItem() ):
			$what = 'item';
			$this->setVar( 'item', Menus::getCurrentMenuItem() );
		else:
			$what = 'menu';
		endif;
	else:
		$what = 'set';
	endif;
	?>
	<div class="row toolbar" id="main-toolbar">
		<div class="col-md-3">
			<?= UI::button_create( Tr::_( 'Create a new menu set' ) )->setOnClick( 'Menus.createSet.openDialog();' ); ?>
		</div>
		<div class="col-md-9">
			<?php require $what . '/toolbar.phtml'; ?>
		</div>
	</div>

	<div class="row" id="main-col">
		<div class="col-md-3" style="padding: 0;">
			<?= Application::getView()->render( 'tree' ); ?>
		</div>
		<div class="col-md-9" style="padding: 0;">
			<div class="container-fluid">
				<?= Application::getGeneralView()->render( 'messages' ); ?>
				<?php require $what . '/edit.phtml'; ?>
			</div>
		</div>
	</div>
<?php else: ?>
	<div class="row">
		<div class="col-md-12" style="padding: 0;">
			<div class="toolbar">
				<?= UI::button_create( Tr::_( 'Create a new menu set' ) )->setOnClick( 'Menus.createSet.openDialog();' ); ?>
			</div>
			<div style="padding: 10px;">
				<?= Application::getGeneralView()->render( 'messages' ); ?>

				<?= Application::getView()->render( 'tree' ); ?>
			</div>
		</div>
	</div>
<?php endif; ?>


<?= Application::getView()->render( 'set/create/dialog' ); ?>
