<?php
namespace JetStudio;

use Jet\UI;

$sets = Menus::getSets();

$set_icon = 'folder';
$menu_icon = 'sitemap';
?>
<table class="table table-striped">
	<?php foreach( $sets as $set ): ?>
		<?php if( $set->getName() == Menus::getCurrentMenuSetName() ): ?>
			<tr>
				<td>
					<?php if( Menus::getCurrentMenuId() ): ?>
						<a href="<?= Menus::getActionUrl( '', [], $set->getName(), false, false ) ?>"><b><?= UI::icon( $set_icon ) ?> <?= $set->getName() ?></b></a>
					<?php else: ?>
						<b><?= UI::icon( $set_icon ) ?> <?= $set->getName() ?></b>
					<?php endif; ?>
				</td>
			</tr>
			<?php foreach( $set->getMenus() as $menu ):
				/**
				 * @var Menus_Menu $menu
				 */
				?>
				<?php if( $menu->getId() == Menus::getCurrentMenuId() ): ?>
				<tr>
					<td style="padding-left: 30px;">
						<?php if( Menus::getCurrentMenuItemId() ): ?>
							<a href="<?= Menus::getActionUrl( '', [], $set->getName(), $menu->getId(), false ) ?>"><b><?= UI::icon( $menu_icon ) ?> <?= $menu->getLabel() ?></b></a>
						<?php else: ?>
							<b><?= UI::icon( $menu_icon ) ?> <?= $menu->getLabel() ?></b>
						<?php endif; ?>
					</td>
				</tr>
				<?php foreach( $menu->getItems() as $item ):
					$label = $item->getTitle();
					?>
					<tr>
						<td style="padding-left: 60px;">
							<?php if( $item->getId() == Menus::getCurrentMenuItemId() ): ?>
								<b><?= $label ?></b>
							<?php else: ?>
								<a href="<?= Menus::getActionUrl( '', [], $set->getName(), $menu->getId(), $item->getId() ) ?>"><?= $label ?></a>
							<?php endif; ?>
						</td>
					</tr>
				<?php endforeach; ?>
			<?php else: ?>
				<tr>
					<td style="padding-left: 30px;"><a
								href="<?= Menus::getActionUrl( '', [], $set->getName(), $menu->getId(), false ) ?>"><?= UI::icon( $menu_icon ) ?> <?= $menu->getLabel() ?></a>
					</td>
				</tr>
			<?php endif; ?>
			<?php endforeach; ?>

		<?php else: ?>
			<tr>
				<td>
					<a href="<?= Menus::getActionUrl( '', [], $set->getName(), false, false ) ?>"><?= UI::icon( $set_icon ) ?> <?= $set->getName() ?></a>
				</td>
			</tr>
		<?php endif; ?>
	<?php endforeach; ?>
</table>
