<?php
use Jet\Tr;
use JetUI\UI;
use Jet\Mvc;
use Jet\Mvc_Page;
?>

<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
	<div class="panel panel-default" >
		<div class="panel-heading">
			<div class="panel-title"><?=Tr::_('Account is blocked')?></div>
		</div>
		<div class="panel-body" >
			<div  class="row">
				<div class="col-sm-12 controls">
					<div style="float: right;margin: 15px">
						<?php foreach( Mvc::getCurrentLocalesList() as $locale ): ?>
							<?php if($locale->toString()==Mvc::getCurrentLocale()->toString()): ?>
								<?=UI::flag($locale)?>
							<?php else:
								$equal_page = Mvc_Page::get(null, $locale);
								if(!$equal_page) {
									$equal_page = Mvc_Page::get( Mvc_Page::HOMEPAGE_ID, $locale );
								}
								?>
								<a href="<?=$equal_page->getURL()?>"><?=UI::flag($locale)?></a>
							<?php endif; ?>
						<?php endforeach; ?>
					</div>
				</div>
			</div>

			<?=UI::icon('remove-sign')->setSize(50)->setTag('div')?>

			<div style="display: inline-block;position:relative;top:  -10px;">
				<?=Tr::_('<b>Your account is blocked!</b><br/>Please contact your system administrator.');?>
			</div>

			<div style="padding-top: 10px">
				<a href="?logout" class="btn btn-default"><?=Tr::_('Logout');?></a>
			</div>
		</div>
	</div>
</div>
