<?php
use Jet\Tr;
use JetExampleApp\UI;
use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form $form
 */
$form = $this->getRaw('login_form');

$form->field('login')->setPlaceholder('user name');
$form->field('password')->setPlaceholder('password');

?>

<div style="margin-top:25%;" class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
	<div class="panel panel-default" >
		<div class="panel-heading">
			<div class="panel-title"><?=Tr::_('Sign In')?></div>
		</div>

		<div class="panel-body" >

			<?=$form->start()?>

				<?php if($form->getCommonMessage()): ?>
					<div id="login-alert" class="alert alert-danger col-sm-12">
						<?=$form->getCommonMessage()?>
					</div>
				<?php endif; ?>

				<div style="margin-bottom: 25px" class="input-group">
					<span class="input-group-addon"><?=UI::icon('user')->setTag('i')?></span>
					<?=$form->field('login')->field()->noContainer()?>
				</div>

				<div style="margin-bottom: 25px" class="input-group">
					<span class="input-group-addon"><?=UI::icon('lock')->setTag('i')?></span>
					<?=$form->field('password')->field()->noContainer()?>
				</div>

				<div style="margin-top:10px" class="form-group">
					<div class="col-sm-12 controls">
						<div style="float: right">
							<input type="submit" class="btn btn-primary" value="<?=Tr::_('Login')?>"/>
						</div>
					</div>
				</div>

			<?=$form->end()?>

		</div>
	</div>
</div>
