<?php if($this->incorrect_login): ?>
	<?=Jet\Tr::_('Invalid user name or password!');?>
<?php endif; ?>

<div style="width: 400px;text-align: left;">

<jet_form name="login">
    <jet_form_common_error_message class="formError"/>
	<div class="form-group">
		<jet_form_field_label name="login"/>
		<jet_form_field_error_msg name="login" class="error"/>
		<jet_form_field name="login" class="form-control"/>
	</div>

	<div class="form-group">
		<jet_form_field_label name="password"/>
		<jet_form_field_error_msg name="password" class="error"/>
		<jet_form_field name="password" class="form-control"/>
	</div>

	<input type="submit" value="<?=Jet\Tr::_('Login');?>" class="btn btn-primary"/>

</jet_form>

</div>