<?php
use Jet\Tr;
?>
<p><?=Tr::_('Please change your password');?></p>

<p>
	<jet_form name="login">
		<div class="form-group">
			<jet_form_field_label name="password"/>
			<jet_form_field_error_msg name="password"/>
			<jet_form_field name="password" class="form-control"/>
		</div>
		<div class="form-group">
			<jet_form_field_check_label name="password"/>
			<jet_form_field_check name="password" class="form-control"/>
		</div>

		<input type="submit" value="<?=Tr::_('Set new password');?>" class="btn btn-default"/>

	</jet_form>
</p>

<a href="?logout" class="btn btn-primary"><?=Tr::_('Logout');?></a>