<?php
use Jet\Tr;
use JetExampleApp\UI;
use Jet\Mvc_View;
use Jet\Form;

/**
 * @var Mvc_View $this
 * @var Form $form
 */
$form = $this->getRaw('form');

?>
<div style="margin-top:22%;" class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
	<div class="panel panel-default" >
		<div class="panel-heading">
			<div class="panel-title"><?=Tr::_('Please change your password');?></div>
		</div>
		<div class="panel-body" >

			<?=UI::icon('remove-sign')->setSize(50)->setTag('div')?>
			<div style="display: inline-block;position:relative;top:  -10px;">
				<?=Tr::_('<b>Your password expired.</b><br/>Please change your password.');?>
			</div>

			<div style="padding-top: 30px">
			</div>

			<?=$form->start()?>

				<?=$form->field('password')?>

				<input type="submit" value="<?=Tr::_('Change password');?>" class="btn btn-primary"/>
				<a href="?logout" class="btn btn-default"><?=Tr::_('Logout');?></a>

			<?=$form->end()?>

		</div>
	</div>
</div>

