<?php

namespace JetApplication\Installer;

use Jet\Form;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Form $form
 */

$form = $this->getRaw( 'form' );
?>
<?= $form->start() ?>
<?= $form->message() ?>
	
	<div style="display: grid;grid-template-columns: 160px 400px;gap: 10px;">
		<?= $form->field( 'locale' ) ?>
		<?= $form->field( 'username' ) ?>
		<?= $form->field( 'password' ) ?>
		<?= $form->field( 'password_check' ) ?>
		<?= $form->field( 'email' ) ?>

		<div></div>
		<div><?= Installer::buttonNextSubmit(); ?></div>
	</div>

<?= $form->end() ?>