<?php
namespace JetStudio;

use Jet\Http_Request;
use Jet\Tr;
use Jet\UI;
use Jet\UI_badge;

$current = DataModels::getCurrentModel();

if(
	!$current ||
	!$current->getExternalRelations()
) {
	return;
}

$current_relation_name = DataModels::getCurrentRelationName();

?>
<table class="table table-striped">
	<thead>
	<tr>
		<th colspan="3"><?= Tr::_( 'External relations' ) ?></th>
	</tr>
	</thead>

	<?php foreach( $current->getExternalRelations() as $relation ): ?>
		<tr>
			<td>
				<?php if( $current_relation_name == $relation->getName() ):
					echo UI::badge(UI_badge::INFO, $relation->getName());
				else: ?>
					<a href="<?= Http_Request::currentURI( ['relation' => $relation->getName()], [
						'property',
						'key'
					] ) ?>"><?= $relation->getName() ?></a>
				<?php endif; ?>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
