<?php
namespace JetApplicationModule\Admin\Auth\Admin\Users;

use JetApplicationModule\Admin\Auth\Entity\Administrator;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Administrator $item
 */

$item = $this->getRaw('item');
$router = $this->getController()->getControllerRouter();

$edit_uri = $router->action( 'edit' )->URI( $item->getId() );
?>
<a href="<?= $edit_uri; ?>"><?= $item->getUsername(); ?></a>
