<?php
/**
 * @var Jet\Form $form
 */
$form = $this->form;

?>
<h1><?=Jet\Tr::_('Welcome!');?></h1>
<jet_form name="<?=$form->getName();?>">
	<jet_form_common_error_message class="formError"/>

	<div class="form-group">
		<jet_form_field_label name="locale"/>
		<jet_form_field_error_msg name="locale" class="form-error"/>
		<jet_form_field name="locale" class="form-control"/>
	</div>
	<input type="submit" class="btn btn-primary" value="<?=Jet\Tr::_('Select');?>"/>


</jet_form>