<?php
use JetUI\menu;
use JetUI\UI;
?>
<div class="col-md-12 main-col" style="padding-top: 5px;">

	<div class="row">

	<?php foreach( menu::getMenus() as $menu ): ?>
		<div class="col-md-2">
			<h3><?=$menu->getLabel()?></h3>
			<?php foreach( $menu->getItems() as $item ): ?>
				<div style="margin: 10px">
					<a href="<?=$item->getUrl()?>">
						<?=UI::icon($item->getIcon())->setWidth(35)->setSize(25)?>
						<span style="position: relative;top:-5px"><?=$item->getLabel()?></span>
					</a>
				</div>
			<?php endforeach; ?>

		</div>
	<?php endforeach; ?>

	</div>

</div>