<?php
use JetExampleApp\Mvc_Page;
use JetUI\UI;
use JetUI\menu;
use Jet\Auth;
use Jet\Tr;
use Jet\Locale;


?>

	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			<span class="sr-only"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="<?=Mvc_Page::get(Mvc_Page::HOMEPAGE_ID)->getURI()?>">JetExampleApp</a>
	</div>

	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<?php foreach( menu::getMenus() as $menu ): ?>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?=$menu->getLabel()?> <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<?php foreach( $menu->getItems() as $item ): ?>
							<li>

								<a href="<?=$item->getUrl()?>">
									<?=UI::icon($item->getIcon())->setWidth(20)?>
									<?=$item->getLabel()?>
								</a>
							</li>
						<?php endforeach; ?>
					</ul>
				</li>
			<?php endforeach; ?>
		</ul>

		<ul class="nav navbar-nav navbar-right">

			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
					<span><?=UI::flag(Locale::getCurrentLocale())?></span>
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<?php /*foreach(AdminMain::getUiLocalesList() as $locale ): ?>
						<li>
							<a href="<?=Mvc_Page::get(Mvc_Page::HOMEPAGE_ID)->getURL(['locale'=>$locale->toString()])?>">
								<?=UI::flag($locale)?>
								<?=$locale->getName($locale)?>
							</a>
						</li>
					<?php endforeach; */ ?>
				</ul>
			</li>

			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
					<?=UI::icon('user')?>
					<?=Auth::getCurrentUser()->getLogin()?>
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<?php /*
					<li><a href="<?=Page::get(Page::CHANGE_PASSWORD_ID)->getURL()?>">
							<?=UI::icon('cog')?>
							<?=Tr::_('Change password')?>
						</a></li>
					<li role="separator" class="divider"></li>
					<li><a href="<?=Page::get(Page::HOMEPAGE_ID)->getURL(['logout'=>'logout'])?>">
							<?=UI::icon('sign-out')?>
							<?=Tr::_('Logout')?>
						</a></li>
                    */ ?>
				</ul>
			</li>

		</ul>
	</div>
