<?php
use JetApplication\Mvc_Page;
use Jet\UI;
use Jet\Navigation_Menu;
use Jet\Auth;
use Jet\Tr;
use Jet\Locale;
use Jet\Mvc;

?>

<div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
	        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		<span class="sr-only"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="<?=Mvc_Page::get( Mvc_Page::HOMEPAGE_ID )->getURI()?>">JetApplication</a>
</div>

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<ul class="nav navbar-nav">
		<?php foreach( Navigation_Menu::getRootMenus() as $menu ): ?>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
				   aria-expanded="false"><?=$menu->getLabel()?> <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<?php foreach( $menu->getItems() as $item ): ?>
						<?php if( $item->getSeparatorBefore() ): ?>
							<li role="separator" class="divider"></li><?php endif; ?>
						<li>
							<a href="<?=$item->getUrl()?>"><?=UI::icon( $item->getIcon() )->setWidth( 20 )?> <?=$item->getLabel()?></a>
						</li>
						<?php if( $item->getSeparatorAfter() ): ?>
							<li role="separator" class="divider"></li><?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</li>
		<?php endforeach; ?>
	</ul>

	<ul class="nav navbar-nav navbar-right">

		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
			   aria-expanded="false">
				<span><?=UI::flag( Locale::getCurrentLocale() )?></span>
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
				<?php foreach( Mvc::getCurrentSite()->getLocales() as $locale ):
					if( !( $page = Mvc_Page::get( Mvc::getCurrentPage()->getId(), $locale ) ) ) {
						continue;
					}
					?>
					<li>
						<a href="<?=$page->getURL()?>">
							<?=UI::flag( $locale )?>
							<?=$locale->getName( $locale )?>
						</a>
					</li>
				<?php endforeach; ?>
			</ul>
		</li>

		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
			   aria-expanded="false">
				<?=UI::icon( 'user' )?>
				<?=Auth::getCurrentUser()->getUsername()?>
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">

				<?php if(
						Mvc_Page::get( 'change_password' ) &&
						Mvc_Page::get( 'change_password' )->accessAllowed()
				): ?>
				<li><a href="<?=Mvc_Page::get( 'change_password' )->getURL()?>">
						<?=UI::icon( 'cog' )?>
						<?=Tr::_( 'Change password' )?>
					</a></li>
				<li role="separator" class="divider"></li>
				<?php endif; ?>

				<li><a href="<?=Mvc_Page::get( Mvc_Page::HOMEPAGE_ID )->getURL( [], [ 'logout' => 'logout' ] )?>">
						<?=UI::icon( 'sign-out' )?>
						<?=Tr::_( 'Logout' )?>
					</a></li>
			</ul>
		</li>

	</ul>
</div>
