<?php
namespace JetApplicationModule\JetExample\AdminUI;
use Jet;
use Jet\Mvc_Page;
use Jet\Tr;
?>

<div style="width: 100%; text-align: center;">
	<a href="<?=Mvc_Page::get('admin/ria')->getURL(); ?>" class="btn btn-default" style="width: 250px;">
		<jetml_icon icon="module/JetExample.AdminUI/ria" size="large"></jetml_icon>
		<?=Tr::_('RIA User Interface');?>
	</a>

	<a href="<?=Mvc_Page::get('admin/classic')->getURL(); ?>" class="btn btn-default" style="width: 250px;">
		<jetml_icon icon="module/JetExample.AdminUI/classic" size="large"></jetml_icon>
		<?=Tr::_('Classic User Interface');?>
	</a>
</div>