<?php
namespace JetApplicationModule\JetExample\AdminUI;
use Jet;
?>

<div style="width: 100%; text-align: center;">
	<a href="<?=Jet\Mvc_Page::get('admin/ria')->getURL(); ?>" class="btn btn-default" style="width: 250px;">
		<jetml_icon icon="module/JetExample\AdminUI/ria" size="large"></jetml_icon>
		<?=Jet\Tr::_('RIA User Interface');?>
	</a>

	<a href="<?=Jet\Mvc_Page::get('admin/classic')->getURL(); ?>" class="btn btn-default" style="width: 250px;">
		<jetml_icon icon="module/JetExample\AdminUI/classic" size="large"></jetml_icon>
		<?=Jet\Tr::_('Classic User Interface');?>
	</a>
</div>