<?php
namespace JetApplicationModule\Content\Articles\Admin;

use Jet\MVC;
use Jet\MVC_View;
use Jet\Form;

use Jet\UI;
use JetApplication\Application_Admin;
use JetApplication\Content_Article;

/**
 * @var MVC_View $this
 * @var Form $form
 */

$form = $this->getRaw( 'form' );

$form->setDefaultLabelWidth( [Form::LJ_SIZE_MEDIUM => 2] );
$form->setDefaultFieldWidth( [Form::LJ_SIZE_MEDIUM => 9] );

//$form->field( 'text' )->input()->addCustomCssStyle( 'height:400px' );


?>

<?= Application_Admin::requireDialog( 'select-image' ); ?>

<script type="text/javascript">

</script>

<?= $form->start(); ?>

<div class="row toolbar" id="main-toolbar">
	<div class="col-md-12">
		<?= UI::button_goBack()->setUrl( MVC::getPage()->getURLPath() ) ?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?= UI::button_save() ?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?= $form->field( 'date_time' ) ?>

		<?php foreach( Content_Article::getLocales() as $locale ):

			$form->field( '/localized/' . $locale . '/text' )->input()->addCustomCssStyle( 'height:400px' );
			?>
			<legend><?= UI::flag( $locale ) ?>&nbsp;<?= $locale->getName() ?></legend>
			<?= $form->field( '/localized/' . $locale . '/title' ) ?>
			<?= $form->field( '/localized/' . $locale . '/annotation' ) ?>
			<?= $form->field( '/localized/' . $locale . '/text' ) ?>

		<?php endforeach; ?>
	</div>
</div>
<?= $form->end(); ?>
