<?php
namespace JetApplicationModule\Content\Articles\Admin;

use JetApplication\Content_Article;

use Jet\Form;
use Jet\UI_button;
use Jet\UI_dataGrid;
use Jet\UI;

use Jet\Tr;
use Jet\Locale;
use Jet\Mvc_View;
use JetApplication\Application_Web;

/**
 * @var Mvc_View $this
 * @var UI_dataGrid $grid
 * @var Form $filter_form
 */
$router = $this->getController()->getControllerRouter();
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );

$delete_uri = $router->action( 'delete' )->URI();

$grid->getColumn( '_edit_' )
	->setAllowSort( false )
	->setCssStyle( 'width:30px;' )
	->setRenderer(
		function( Content_Article $item ) use ( $delete_uri ) {
			if( $delete_uri ):
				?>
				<input type="checkbox" name="selected[]" value="<?= $item->getId() ?>"/>
			<?php
			endif;
		}
	);


$grid->getColumn( 'title' )
	->setRenderer(
		function( Content_Article $item ) use ( $router ) {
			foreach( Application_Web::getBase()->getLocales() as $locale ):
				$URI = $router->action( 'edit' )->URI( $item->getId() );
				$title = $item->getLocalized( $locale )->getTitle();

				echo UI::flag( $locale ) . '&nbsp;<a href="' . $URI . '">' . $title . '</a><br/>';
			endforeach;
		}
	);

$grid->getColumn( 'date_time' )
	->setCssStyle( 'width:200px;' )
	->setRenderer(
		function( Content_Article $item ) {
			echo Locale::dateAndTime( $item->getDateTime() );
		}
	);

if( $delete_uri && count( $grid->getData() ) ) {
	$grid->setCustomFooter( '
		<tr>
			<td colspan="' . count( $grid->getColumns() ) . '" class="toolbar">
				' . UI::button_delete()->setType( 'submit' )->setSize( UI_button::SIZE_EXTRA_SMALL ) . '
			</td>
		</tr>
	' );
}

?>
<?= $filter_form->start() ?>
<div class="row toolbar" id="main-toolbar">
	<div class="col-xs-5 col-md-2">
		<?php if( ($add_uri = $router->action( 'add' )->URI()) ): ?>
			<?= UI::button_create( Tr::_( 'Create a new Article' ) )->setUrl( $add_uri ) ?>
		<?php endif; ?>
	</div>

	<div class="col-xs-7 col-md-3">
		<?= UI::searchField( 'search', $filter_form->field( 'search' )->getValue() ) ?>
	</div>
</div>
<?= $filter_form->end() ?>


<div class="row main-row">
	<div class="col-md-12 main-col">
		<form action="<?= $delete_uri ?>" method="post">
			<?= $grid->render() ?>
		</form>
	</div>
</div>
