<?php
namespace JetApplicationModule\Admin\Auth\Entity;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Administrator $user
 */

$user = $this->getRaw( 'user' );
?>
Vaše administrátorské heslo bylo vyresetováno

Zde jsou vaše přihlašovací údaje:

Uživatelské jméno: <?= $user->getUsername() ?>

Heslo: <?= $this->getString( 'password' ) ?>


Po přihlášení si prosím změňte heslo

Přejeme příjemný den