<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

$base = Bases::getCurrentBase();

if( $base ) {
	return;
}
?>
<div class="row" id="main-toolbar">
	<div class="col-md-12 toolbar">
		<?= UI::button_create( Tr::_( 'Create a new base' ) )->setOnClick( 'Bases.createBase.openDialog()' ) ?>
	</div>
</div>
<div class="row" id="main-col">
	<div class="col-md-12">
		<?= Application_UI::messages(); ?>
		<?= Application::getView()->render( 'bases_list' ); ?>
	</div>
</div>
