<?php
namespace JetStudio;

use Jet\Locale;
use Jet\Tr;
use Jet\UI;
use Jet\Form_Renderer;
use Jet\UI_dialog;

$base = Bases::getCurrentBase();

if( !$base ) {
	return;
}

$form = $base->getEditForm();

$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 1
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 8
] );


$add_locale_form = $base->getAddLocaleForm();
$sort_locales_form = $base->getSortLocalesForm();

$sort_dialog = UI::dialog( 'locales_sort_dialog', Tr::_( 'Sort locales' ), UI_dialog::SIZE_LARGE );
?>
<?= $form->start() ?>

<script>
	function copyBaseIDtoClipboard()
	{
		const id_input = document.getElementById("base_id_to_cb");
		id_input.select();
		document.execCommand("copy");
	}
</script>



<div class="container-fluid" id="main-edit-area">

	<legend style="margin-top: 10px"><?= Tr::_( 'Base' ) ?>
		<span style="font-weight: bolder"><?= $base->getName() ?></span>
		
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="#" onclick="copyBaseIDtoClipboard();" class="entity-id">
			ID: <?=UI::icon('clipboard')?>
			<input id="base_id_to_cb" readonly value="<?= $base->getId() ?>"/>
		</a>
		
	</legend>
	
	
	<?= Application_UI::messages(); ?>

	<fieldset style="margin-bottom: 40px;">
		<?= $form->field( 'name' ) ?>
		<?= $form->field( 'is_default' ) ?>
		<?= $form->field( 'is_secret' ) ?>
		<?= $form->field( 'is_active' ) ?>
		<?= $form->field( 'SSL_required' ) ?>
		<?= $form->field( 'initializer' ) ?>
	</fieldset>

	<?php foreach( $base->getLocales() as $locale ): ?>
		<fieldset style="margin-bottom: 40px;">
			<legend>

				<span style="padding-left: 30px;"><?= UI::flag( $locale ) ?></span>
				<span style="padding-left: 10px;"><?= $locale->getName( Locale::getCurrentLocale() ) ?></span>
				<span style="padding-left: 10px;font-size: 12px;"><?= $locale ?></span>
				<span style="padding-left: 10px;font-size: 12px;"><?= $locale->getName( $locale ) ?></span>

			</legend>

			<?= $form->field( '/' . $locale . '/is_active' ) ?>
			<?= $form->field( '/' . $locale . '/SSL_required' ) ?>
			<?= $form->field( '/' . $locale . '/title' ) ?>
			
			<div class="form-group row">
				<label class="control-label col-md-1"><?= Tr::_( 'URLs:' ); ?></label>
				<div class="col-md-5">
					<div class="container">
					
					
					<?php for( $u = 0; $u < 100; $u++ ):
						if( !$form->fieldExists( '/' . $locale . '/URLs/' . $u ) ) {
							break;
						}
						
						$field = $form->field( '/' . $locale . '/URLs/' . $u );
						$field->input()->addCustomCssStyle( 'width: 400px' );
						?>
							<?= $field->row()->start() ?>
							<?= $field->error() ?>
							<div class="input-group">
											<span class="input-group-prepend">
												<span class="input-group-text"><?= $base->getSSLRequired() ? 'https://' : 'http://' ?></span>
											</span>
								<?= $field->input() ?>
							</div>
							<?= $field->row()->end() ?>
					<?php endfor; ?>
					</div>
					
				</div>
			</div>



			<div class="form-group row">
				<label class="control-label col-md-1"><?= Tr::_( 'Default Meta Tags:' ); ?></label>
				<div class="col-md-10">
					<?=$form->field('/' . $locale . '/meta_tags')->input()?>
				</div>
			</div>


			<br>
			<div class="form-group row">
				<label class="control-label col-md-1"><?= Tr::_( 'Parameters:' ); ?></label>
				<div class="col-md-10">
					<?=$form->field('/' . $locale . '/params')->input()?>
				</div>
			</div>
			
			

		</fieldset>

	<?php endforeach; ?>

</div>
<?= $form->end() ?>


<?= $add_locale_form->start() ?>
<?= $add_locale_form->field( 'locale' ) ?>
<?= $add_locale_form->end() ?>


<?= $sort_dialog->start() ?>

<div id="locales_sort_area">
	<?php foreach( $base->getLocales() as $l ): ?>
		<div class="list-group-item locale-sort-item" data-locale="<?= $l ?>"
		     style="display: grid;grid-template-columns: 20px 40px 80px 1fr 1fr;align-items: center;gap: 5px;"
		>
			<div><span class="fa fa-arrows-v" style="font-size:16px;"></span></div>
			<div style="font-size: 30px;"><?= UI::flag( $l ) ?></div>

			<div><?= $l ?></div>
			<div><?= $l->getName( Locale::getCurrentLocale() ) ?></div>
			<div><?= $l->getName( $l ) ?></div>
		</div>
	<?php endforeach; ?>
</div>
<?= $sort_dialog->footer() ?>

<?= $sort_locales_form->start() ?>
<?= $sort_locales_form->field( 'locales' ) ?>
<?= UI::button_save() ?>
<?= $sort_locales_form->end() ?>

<?= $sort_dialog->end(); ?>

