<?php

namespace JetStudio;

use Jet\DataModel;use Jet\UI;
use Jet\Tr;
use Jet\UI_dialog;

$dialog = UI::dialog( 'dialog_create_new_data_model_'.DataModel::MODEL_TYPE_MAIN, Tr::_( 'Create a new DataModel - Main' ), UI_dialog::SIZE_EXTRA_LARGE );

echo $dialog->start();
?>
	<div id="create_model_form_area_<?=DataModel::MODEL_TYPE_MAIN?>">
		<?php require 'form.phtml'; ?>
	</div>
	<?php
echo $dialog->footer();
echo UI::button_save( Tr::_( 'Create' ) )->setOnClick( "DataModel.create.createSend('".DataModel::MODEL_TYPE_MAIN."')" );
echo $dialog->end();

