<?php
namespace JetApplicationModule\JetExample\AdminUsers;
use Jet;

/**
 * @var Jet\Auth_User_Abstract[] $users
 */
$users = $this->users;

/**
 * @var Jet\Data_Paginator $paginator
 */
$paginator = $this->paginator;

/**
 * @var \JetApplicationModule\JetExample\AdminUIManager\Main $UI_manager
 */
$UI_manager = Jet\Mvc::getCurrentUIManagerModuleInstance();
?>

<div style="padding: 10px;">

<a href="?new" class="btn btn-primary"><?=Jet\Tr::_('Add new user');?></a>

<table class="table table-striped">
	<thead>
		<tr>
			<th style="width: 40px;"></th>
			<th><?=Jet\Tr::_('Login');?></th>
			<th><?=Jet\Tr::_('ID');?></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach( $users as $user ): ?>
	<tr>
		<td>
			<a href="?ID=<?php echo rawurlencode( $user->getID() ); ?>" class="btn btn-info">EDIT</a>
		</td>
		<td><?=$user->getLogin(); ?></td>
		<td><?=$user->getID(); ?></td>
	</tr>
	<?php endforeach; ?>
	</tbody>
	<tfoot>
	<tr>
		<td colspan="4">
			<?=$UI_manager->renderPaginator( $paginator );?>
		</td>
	</tr>
	</tfoot>
</table>

</div>