<?php
namespace JetApplicationModule\JetExample\AdminUsers;
use Jet;
use JetApplicationModule\JetExample\UIElements;


/**
 * @var UIElements\DataGrid $grid
 */
$grid = $this->grid;

$c_edit = $grid->getColumn('_edit_');
$c_edit->setDisplayCallback( function( Jet\Auth_User_Abstract $item ) {
	$ID = rawurlencode($item->getID());
	?>
	<a href="?ID=<?=$ID;?>" class="btn btn-default btn-xs"><?=Jet\Tr::_('Edit');?></a>
	&nbsp;
	<a href="?delete=<?=$ID;?>" class="btn btn-danger btn-xs"><?=Jet\Tr::_('Delete');?></a>
<?php
} );
$c_edit->setCssStyle( 'width:120px;' );

$grid->getColumn('login')->setDisplayCallback( function( Jet\Auth_User_Abstract $item ) {
	$ID = rawurlencode($item->getID());
	?>
	<a href="?ID=<?=$ID;?>"><?=$item->getLogin();?></a>
	<?php
} );
$grid->getColumn('ID')->setDisplayCallback( function( Jet\Auth_User_Abstract $item ) {
	echo $item->getID();
} );


?>

<div style="padding: 10px;">

<a href="?new" class="btn btn-primary"><?=Jet\Tr::_('Add new user');?></a>

<?=$grid->render();?>

</div>