<?php
namespace JetApplicationModule\JetExample\Articles;
use Jet;

/**
 * @var Jet\Auth_User_Abstract $user
 */
$user = $this->user;

/**
 * @var Jet\Mvc_MicroRouter $router
 */
$router = $this->router;

?>

<div style="padding: 10px;">

	<a href="<?=Jet\Mvc::getCurrentURI();?>" class="btn btn-default"><?=Jet\Tr::_('&lt Back');?></a>

	<p>
	<?=Jet\Tr::_('Do you really want to delete this user?');?>
	<br/>
	<a href="<?=$router->getActionURI('edit', $user);?>" style="font-weight: bolder;font-size: 20px;"><?=$user->getName();?> (<?=$user->getLogin();?>)</a>
	</p>

	<form action="?delete=<?=rawurlencode($user->getID());?>" method="post">
		<input type="hidden" name="delete" value="yes">
		<input type="submit" value="<?=Jet\Tr::_('YES! Delete it!');?>" class="btn btn-danger"/>
	</form>
</div>