<?php
use Jet\Auth_User_Interface;
use Jet\Mvc_Controller_Router;
use Jet\Mvc;
use Jet\Tr;

/**
 * @var Auth_User_Interface $user
 */
$user = $this->user;

/**
 * @var Mvc_Controller_Router $router
 */
$router = $this->router;

?>

<div style="padding: 10px;">

	<a href="<?=Mvc::getCurrentPageURI();?>" class="btn btn-default"><?=Tr::_('&lt Back');?></a>

	<p>
	<?=Tr::_('Do you really want to delete this user?');?>
	<br/>
	<a href="<?=$router->getActionURI('edit', $user);?>" style="font-weight: bolder;font-size: 20px;"><?=$user->getName();?> (<?=$user->getLogin();?>)</a>
	</p>

	<form action="?delete=<?=rawurlencode($user->getID());?>" method="post">
		<input type="hidden" name="delete" value="yes">
		<input type="submit" value="<?=Tr::_('YES! Delete it!');?>" class="btn btn-danger"/>
	</form>
</div>