<?php
namespace JetApplication\Installer;

use Jet\Mvc_View;
use Jet\Mvc_Site;
use Jet\Form;
use Jet\UI;
use Jet\Tr;

use JetApplication\Application_Admin;
use JetApplication\Application_Web;
use JetApplication\Application_REST;

/**
 * @var Mvc_View $this
 * @var Mvc_Site[] $sites
 * @var Form $main_form
 */

$main_form = $this->getRaw( 'main_form' );

$main_form->setDefaultLabelWidth( [Form::LJ_SIZE_MEDIUM => 2] );

$sites = $this->getRaw( 'sites' );

$titles = [
	Application_Web::getSiteId()   => Tr::_( 'Web' ),
	Application_Admin::getSiteId() => Tr::_( 'Administration' ),
	Application_REST::getSiteId()  => Tr::_( 'REST API' ),
];

?>

<?= $main_form->start() ?>
<?= $main_form->message() ?>
<?php foreach( $sites as $site ): ?>
	<fieldset>
		<legend><?= $titles[$site->getId()] ?></legend>

		<?php foreach( $site->getLocales() as $locale ):
			$field = $main_form->field( '/' . $site->getId() . '/' . $locale . '/URL' );
			?>


			<?= $field->error() ?>
			<div style="margin-bottom: 25px" class="input-group">
				<span class="input-group-addon"><span
							style="display: inline-block;width: 150px"><?= UI::locale( $locale ); ?></span> http://</span>
				<?= $field->input() ?>
				<span class="input-group-addon">/</span>
			</div>

		<?php endforeach; ?>

	</fieldset>
<?php endforeach; ?>

<?= Installer::buttonNext() ?>

<?= $main_form->end() ?>

