<?php
namespace JetApplication;

use Jet\Mvc_View;
use Jet\Mvc_Site;
use Jet\Form;

/**
 * @var Mvc_View $this
 * @var Mvc_Site $site
 * @var Form     $main_form
 */

$main_form = $this->getRaw( 'main_form' );

$main_form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );

$site = $this->getRaw( 'site' );

?>

<?=$main_form->start()?>
<?=$main_form->message()?>
<fieldset>
	<?php foreach( $site->getLocales() as $locale ):
		$field = $main_form->field( '/'.$locale.'/URL' );
		?>

		<legend><?=$locale->getName();?></legend>


		<?=$field->error()?>
		<div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon">http://</span>
			<?=$field->input()?>
			<span class="input-group-addon">/</span>
		</div>

	<?php endforeach; ?>

	<?php Installer::buttonNext() ?>
</fieldset>
<?=$main_form->end()?>

