<?php
namespace JetApplicationModule\JetExample\AdminUIManager;
use Jet;
?>

<jetml_layout_container id="_jet_main_border_" gutters="false" style="width:100%;height:100%;">

	<jetml_layout_tabs region="center" tabPosition="top" id="_jet_modules_tabs_">
	</jetml_layout_tabs>

	<jetml_layout_toolbar region="bottom">
		<jetml_form_button title="Articles" icon="module/JetExample\Articles/module" onClick="Jet.modules.CURRENT_MODULE.openModule('JetExample\\Articles');" />
		<jetml_form_button title="Images" icon="module/JetExample\Images/module" onClick="Jet.modules.CURRENT_MODULE.openModule('JetExample\\Images');" />
		<jetml_form_button title="Roles" icon="module/JetExample\AdminRoles/module" onClick="Jet.modules.CURRENT_MODULE.openModule('JetExample\\AdminRoles');" />
		<jetml_form_button title="Users" icon="module/JetExample\AdminUsers/module" onClick="Jet.modules.CURRENT_MODULE.openModule('JetExample\\AdminUsers');" />
		<jetml_form_button title="Form test" icon="module/JetExample\TestModule/module" onClick="Jet.modules.CURRENT_MODULE.openModule('JetExample\\TestModule');" />

		<jetml_form_button title="test Jet.alert" onClick="Jet.alert('Alert text!', 'Alert title', function() {alert('onOk');});" />
		<jetml_form_button title="test Jet.confirm" onClick="Jet.confirm('Confirm text!', 'Confirm title', function() {alert('onYes');}, function() {alert('onNo');});" />
	</jetml_layout_toolbar>
</jetml_layout_container>
