<?php
use Jet\Tr;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 */
?>
<h1><?=Tr::_('Done!');?></h1>

<div style="border: 5px solid red;padding: 10px;margin: 5px;">
	<?=Tr::_('Please copy <b>%SRC%</b> to <b>%TG%</b>', ['SRC'=>$this->getString('source'), 'TG'=>$this->getString('target')]);?>
	<p>
		<?=Tr::_('I can\'t do that, because ...'); ?>
	</p>
	<p>
		<span style="color:red;"><?=$this->getString('message');?></span>
	</p>

</div>

<p>
	<?=Tr::_('Please remove this line from application/bootstrap.php:');?>
</p>

<code>
	require( JET_APPLICATION_PATH . '_install/_installer/install.php' );
</code>

<p>
	<?=Tr::_('It is possible (and recommended) to delete _installer directory.');?>
</p>

<p>
	<?=Tr::_('Enjoy!! :-)');?>
</p>