<?php
namespace JetApplicationModule\Admin\ManageAccess\RESTClients\Roles;

use JetApplication\Auth_RESTClient_Role as Role;

use Jet\UI;
use Jet\UI_button;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Role $item
 */

$item = $this->getRaw('item');
$router = $this->getController()->getControllerRouter();

if( ($delete_uri = $router->action( 'delete' )->URI( $item->getId() )) ):
	echo UI::button_delete(' ')->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL );
	echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
endif;

if( ($edit_uri = $router->action( 'edit' )->URI( $item->getId() )) ):
	echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL );
endif;
