<?php
namespace JetApplicationModule\JetExample\System\Visitors\Users;

use Jet\UI;
use JetApplication\Auth_Visitor_User;
use Jet\Mvc;
use Jet\Tr;
use Jet\Mvc_View;

/**
 * @var Mvc_View               $this
 * @var Auth_Visitor_User      $user
 * @var Controller_Main_Router $router
 */
$user = $this->getRaw( 'user' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12 main-col">

		<?=UI::button_goBack()->setUrl( Mvc::getCurrentPage()->getURI() )?>

		<p>
			<?=Tr::_( 'Do you really want to delete this user?' );?>
			<br/>
			<a href="<?=$router->getViewURI( $user->getId() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$user->getName();?> (<?=$user->getUsername();?>)</a>
		</p>

		<form action="?delete=<?=rawurlencode( $user->getId() );?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>