<?php

namespace JetStudioModule\Menus;

$form = Menu::getCreateForm();

$form->getField( 'label' )->input()->addJsAction( 'onkeyup', 'Menus.createMenu.generateId(this.value);' );


echo $form->start();
echo $form->getCommonMessage();
?>
	<div class="form-fields" style="grid-template-columns: 0.6fr 2fr;">
		<?php
		echo $form->field( 'label' );
		echo $form->field( 'id' );
		echo $form->field( 'icon' );
		echo $form->field( 'index' );
		?>
	</div>
<?php
echo $form->end();

