<?php
use JetUI\dialog;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var dialog $d
 */
$d = $this->getRaw( 'element' );
?>
<div class="modal fade" id="<?=$d->getId()?>" role="dialog">
	<div class="modal-dialog" style="width: <?=$d->getWidth()?>px;">

		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title"><?=$d->getTitle()?></h4>
			</div>
			<div class="modal-body">

