<?php
namespace Jet;

/**
 * @var Form $form
 */
$form = $this->form;


?>
<jet_form name="<?=$form->getName();?>">
	<jet_form_common_error_message class="formError"/>
	<table>
		<tr>
			<td valign="top"><jet_form_field_label name="backend_type"/></td>
			<td><jet_form_field_error_msg name="backend_type" class="error"/><jet_form_field name="backend_type"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="backend_options"/></td>
			<td><jet_form_field_error_msg name="backend_options" class="error"/><jet_form_field name="backend_options"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="history_enabled"/></td>
			<td><jet_form_field_error_msg name="history_enabled" class="error"/><jet_form_field name="history_enabled"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="history_backend_type"/></td>
			<td><jet_form_field_error_msg name="history_backend_type" class="error"/><jet_form_field name="history_backend_type"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="history_backend_options"/></td>
			<td><jet_form_field_error_msg name="history_backend_options" class="error"/><jet_form_field name="history_backend_options"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="cache_enabled"/></td>
			<td><jet_form_field_error_msg name="cache_enabled" class="error"/><jet_form_field name="cache_enabled"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="cache_backend_type"/></td>
			<td><jet_form_field_error_msg name="cache_backend_type" class="error"/><jet_form_field name="cache_backend_type"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="cache_backend_options"/></td>
			<td><jet_form_field_error_msg name="cache_backend_options" class="error"/><jet_form_field name="cache_backend_options"/></td>
		</tr>
	</table>

	<input type="submit" value="<?=Tr::_("Next", array(), Translator::COMMON_NAMESPACE);?>"/>
</jet_form>