<?php
namespace JetStudio;
?>
<?php use Jet\Http_Request;

if( Forms::getCurrentWhatToEdit() == 'form' ): ?>
	<b class="badge badge-info" style="font-size: 20px;"><?= Forms::getCurrentClass()->getFullClassName() ?></b>
<?php else: ?>
	<a href="<?= Http_Request::currentURI( [], [
		'property',
	] ) ?>" style="font-weight: bolder;font-size: 20px;"><?= Forms::getCurrentClass()->getFullClassName() ?></a>
<?php endif; ?>
<br/>
<table style="width: 100%;margin-top: 5px;">
	<tr style="background: transparent">
		<td style="border:none">
			<?php require 'item/properties.phtml' ?>
		</td>
	</tr>
</table>


