<?php
/**
 * @var Jet\Form $form
 */
$form = $this->form;

/**
 * @var Jet\Config $config
 */
$config = $this->config;

/**
 * @var Jet\Config_Definition_Property_Abstract[] $config_props
 */
$config_props = $config->getPropertiesDefinition();

?>
<jet_form name="<?=$form->getName();?>">
	<jet_form_common_error_message class="formError"/>

    <?php foreach( $form->getFields() as $field ): ?>
        <div class="form-group">
            <jet_form_field_label name="<?=$field->getName()?>"/>
            <jet_form_field_error_msg name="<?=$field->getName()?>" class="form-error"/>
            <jet_form_field name="<?=$field->getName()?>" class="form-control"/>
        </div>
    <?php endforeach; ?>

	<input type="submit" class="btn btn-primary" value="<?=Jet\Tr::_('Next', [], Jet\Translator::COMMON_NAMESPACE);?>"/>

</jet_form>