<?php

namespace JetStudio;

use Jet\MVC_View;
use Jet\UI;
use Jet\Tr;
use Jet\UI_dialog;

/**
 * @var MVC_View $this
 * @var DataModel_Definition_Key $key
 */

if( !DataModels::getCurrentModel() ) {
	return;
}

$dialog = UI::dialog( 'delete_key', Tr::_( 'Delete key' ), UI_dialog::SIZE_LARGE );

echo $dialog->start();
?>
<?= Tr::_( 'Do You really want to delete key?', [] ); ?>
	<?php
echo $dialog->footer();
echo UI::button_delete()->setUrl( DataModels::getActionUrl( 'key/delete' ) );
echo $dialog->end();

