<?php
namespace Jet;
/**
 * @var Mvc_View $this
 */

$locales = $this->getRaw('locales');
?>
<jet_form name="locale_add">
	<jet_form_common_error_message class="formError"/>
	<table>
		<tr>
			<td valign="top"><jet_form_field_label name="locale"/></td>
			<td><jet_form_field_error_msg name="locale" class="error"/><jet_form_field name="locale"/></td>
		</tr>
		<tr><td colspan="2" align="center"><input type="submit" value="<?=Tr::_('Add locale');?>"/></td></tr>
	</table>
</jet_form>


<jet_form name="main">
	<jet_form_common_error_message class="formError"/>
	<table>
		<tr>
			<td valign="top"><jet_form_field_label name="name"/></td>
			<td><jet_form_field_error_msg name="name" class="error"/><jet_form_field name="name"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="ID"/></td>
			<td><jet_form_field_error_msg name="ID" class="error"/><jet_form_field name="ID"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="template"/></td>
			<td><jet_form_field_error_msg name="template" class="error"/><jet_form_field name="template"/></td>
		</tr>
	</table>
	<table>
		<?php foreach($locales as $locale=>$data): ?>
		<tr>
			<td rowspan="2">
				<?=$data['locale'];?>
				<br/>
				[<a href="?remove_locale=<?=$locale;?>"><?=Tr::_('remove');?></a>]
			</td>
			<td valign="top"><jet_form_field_label name="/<?=$locale;?>/nonSSL"/></td>
			<td><jet_form_field_error_msg name="/<?=$locale;?>/nonSSL" class="error"/><jet_form_field name="/<?=$locale;?>/nonSSL"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="/<?=$locale;?>/SSL"/></td>
			<td><jet_form_field_error_msg name="/<?=$locale;?>/SSL" class="error"/><jet_form_field name="/<?=$locale;?>/SSL"/></td>
		</tr>
		<?php endforeach; ?>
	</table>

	<?php if($locales): ?>
	<input type="submit" value="<?=Tr::_('Next', array(), Translator::COMMON_NAMESPACE);?>"/>
	<?php else: ?>
	<?=Tr::_('Please add at least one locale');?>
	<?php endif; ?>
</jet_form>