<?php
use Jet\Mvc_View;
use Jet\Tr;
use Jet\Application_Modules_Module_Manifest;
/**
 * @var Mvc_View $this
 */

/**
 * @var Application_Modules_Module_Manifest[] $modules
 */
$modules = $this->getRaw('modules');
?>
<jet_form name="modules_select_form">
<jet_form_common_error_message class="formError"/>

<table class="table table-striped">
	<thead>
	<tr>
		<th></th>
		<th><?=Tr::_('Vendor');?></th>
		<th><?=Tr::_('Module');?></th>
		<th><?=Tr::_('Installed?');?></th>
		<th><?=Tr::_('Activated?');?></th>
	</tr>
	</thead>
	<?php foreach( $modules as $info ): ?>
	<tr>
		<td>
			<?php if(!$info->getIsActivated()): ?>
			<input type="checkbox" value="<?=$info->getName();?>" name="modules[]" id="module_<?=$info->getName();?>" checked="checked"/>
			<?php endif; ?>
		</td>
		<td><?=$info->getVendor();?></td>
		<td>
			<label for="module_<?=$info->getName();?>"><?=$info->getLabel();?> </label>
			<br/>
			<div style="font-size: 11px;"><?=$info->getName();?></div>
			<br/>
			<?=$info->getDescription();?>
		</td>
		<td><?=Tr::_($info->getIsInstalled()?'Yes':'NO');?></td>
		<td><?=Tr::_($info->getIsActivated()?'Yes':'NO');?></td>
	</tr>
	<?php endforeach; ?>
</table>

	<input type="submit" value="<?=Tr::_('Install and activate selected modules');?>" class="btn btn-primary">
</jet_form>