<?php
use Jet\Mvc_View;
use Jet\Tr;
use Jet\Form;
use Jet\Application_Modules_Module_Manifest;
use JetExampleApp\Installer;
/**
 * @var Mvc_View $this
 * @var Form $form
 * @var Application_Modules_Module_Manifest[] $modules
 */

$modules = $this->getRaw('modules');

$form = $this->getRaw('form');

?>
<?=$form->start()?>

<table class="table table-striped">
	<thead>
	<tr>
		<th></th>
		<th><?=Tr::_('Vendor');?></th>
		<th><?=Tr::_('Module');?></th>
		<th><?=Tr::_('Installed?');?></th>
		<th><?=Tr::_('Activated?');?></th>
	</tr>
	</thead>
	<?php foreach( $modules as $info ): ?>
	<tr>
		<td>
			<?php if(!$info->getIsActivated()):

				if( $info->getIsAuthController() ):
					?>
					<input type="checkbox" value="<?=$info->getName();?>" name="modules[]" id="module_<?=$info->getName();?>" checked="checked" disabled="disabled"/>
					<?php
				else:
					?>
					<input type="checkbox" value="<?=$info->getName();?>" name="modules[]" id="module_<?=$info->getName();?>" checked="checked"/>
					<?php
				endif;
			endif; ?>
		</td>
		<td><?=$info->getVendor();?></td>
		<td>
			<label for="module_<?=$info->getName();?>"><?=$info->getLabel();?> </label>
			<br/>
			<div style="font-size: 11px;"><?=$info->getName();?></div>
			<br/>
			<?=$info->getDescription();?>
		</td>
		<td><?=Tr::_($info->getIsInstalled()?'Yes':'NO');?></td>
		<td><?=Tr::_($info->getIsActivated()?'Yes':'NO');?></td>
	</tr>
	<?php endforeach; ?>
</table>

	<?=Installer::buttonNext();?>
<?=$form->end()?>