<?php

namespace JetStudio;

use Jet\Tr;
use Jet\UI;
use Jet\Locale;
use Jet\UI_dialog;

$dialog = UI::dialog( 'dialog_create_new_base', Tr::_( 'Create a new Base' ), UI_dialog::SIZE_LARGE );

echo $dialog->start();
?>
	<div id="<?= Bases::getCreateForm()->getId() ?>_form_area">
		<?php
		require 'form.phtml';
		?>
	</div>

	<legend><?= Tr::_( 'Locales' ) ?></legend>
	<div id="selected_locales_area">
		<table style="width: 100%">
			<?php
			$current_locale = Locale::getCurrentLocale();
			$default_locales = Project::getDefaultLocales( true );

			foreach( Locale::getAllLocalesList() as $l => $name ):
				$l = new Locale( $l );

				$display = 'none';

				if( in_array( $l->toString(), $default_locales ) ) {
					$display = '';
				}
				?>
				<tr
						class="selected-locale-row"
						data-locale="<?= $l ?>"
						id="selected_locale_<?= $l ?>"
						style="cursor: pointer;display: <?= $display; ?>"
						onclick="Bases.createBase.addLocale.unSelect('<?= $l ?>');"
				>
					<td style="padding: 5px;"><?= UI::flag( $l ) ?></td>

					<td><?= $l ?></td>
					<td><?= $l->getName( $current_locale ) ?></td>
					<td><?= $l->getName( $l ) ?></td>

				</tr>
			<?php endforeach; ?>
		</table>

	</div>
<?= UI::button_create( Tr::_( 'Add locale' ) )->setOnClick( 'Bases.createBase.addLocale.openDialog()' ); ?>

	<?php
echo $dialog->footer();
echo UI::button_save( Tr::_( 'Create' ) )->setOnClick( 'Bases.createBase.createSend()' );
echo $dialog->end();

