<?php

namespace JetStudio;

use Jet\Form_Renderer;

$form = Bases::getCreateForm();

$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 10
] );


$form->getField( 'name' )->input()->addJsAction( 'onkeyup', 'Bases.createBase.generateId(this.value);' );

echo $form->start();

echo $form->getCommonMessage();

echo $form->field( 'name' );
echo $form->field( 'id' );

$base_url = $form->field( 'base_url' );
?>
<?= $base_url->row()->start() ?>
<?= $base_url->label() ?>

<?= $base_url->container()->start() ?>
	<div class="input-group">
		<span class="input-group-prepend" style="font-weight: bolder"><span class="input-group-text">https://</span></span><?php
		echo $base_url->input();
		echo $base_url->error();
	?></div>
<?= $base_url->container()->end() ?>

<?= $base_url->row()->end() ?>
	<?php

echo $form->field( 'locales' );

echo $form->end();
