<?php

use Jet\UI;
use Jet\Navigation_MenuSet;
use Jet\Auth;
use Jet\Tr;
use Jet\Locale;
use Jet\MVC;

?>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="<?= MVC::getHomePage()->getURLPath() ?>">JetApplication</a>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavBar"
	        aria-controls="mainNavBar" aria-expanded="false" aria-label="">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="mainNavBar">
		<ul class="nav navbar-nav">
			<?php foreach( Navigation_MenuSet::get( 'admin' )->getMenus() as $menu ): ?>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
					   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<?= $menu->getLabel() ?> <span class="caret"></span>
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<?php foreach( $menu->getItems() as $item ): ?>
							<?php if( $item->getSeparatorBefore() ): ?>
								<div class="dropdown-divider"></div>
							<?php endif; ?>
							<a class="dropdown-item"
							   href="<?= $item->getUrl() ?>"><?= UI::icon( $item->getIcon() ) ?> <?= $item->getLabel() ?></a>
							<?php if( $item->getSeparatorAfter() ): ?>
								<div class="dropdown-divider"></div>
							<?php endif; ?>
						<?php endforeach; ?>
					</div>

				</li>
			<?php endforeach; ?>
		</ul>

		<ul class="navbar-nav ml-auto">

			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
				   aria-haspopup="true" aria-expanded="false">
					<span><?= UI::flag( Locale::getCurrentLocale() ) ?></span>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
					<?php foreach( MVC::getBase()->getLocales() as $locale ): ?>
						<a class="dropdown-item"
						   href="<?= MVC::getBase()->getHomepage($locale)->getURLPath() ?>">
							<?= UI::flag( $locale ) ?>
							<?= $locale->getName( $locale ) ?>
						</a>
					<?php endforeach; ?>
				</div>
			</li>

			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
				   aria-haspopup="true" aria-expanded="false">
					<?= UI::icon( 'user' ) ?>
					<?= Auth::getCurrentUser()->getUsername() ?>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

					<?php if(
						MVC::getPage( 'change_password' ) &&
						MVC::getPage( 'change_password' )->accessAllowed()
					): ?>
						<a class="dropdown-item" href="<?= MVC::getPage( 'change_password' )->getURL() ?>">
							<?= UI::icon( 'cog' ) ?>
							<?= Tr::_( 'Change password' ) ?>
						</a>
						<div class="dropdown-divider"></div>
					<?php endif; ?>

					<a class="dropdown-item"
					   href="<?= MVC::getHomePage()->getURL( [], ['logout' => 'logout'] ) ?>">
						<?= UI::icon( 'sign-out-alt' ) ?>
						<?= Tr::_( 'Logout' ) ?>
					</a>
				</div>
			</li>

		</ul>
	</div>
</nav>




