<?php
use Jet\Mvc_Page;
use Jet\UI;
use Jet\Navigation_Menu;
use Jet\Auth;
use Jet\Tr;
use Jet\Locale;
use Jet\Mvc;

?>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="<?=Mvc_Page::get( Mvc_Page::HOMEPAGE_ID )->getURI()?>">JetApplication</a>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavBar" aria-controls="mainNavBar" aria-expanded="false" aria-label="">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="mainNavBar">
		<ul class="nav navbar-nav">
			<?php foreach( Navigation_Menu::getRootMenus() as $menu ): ?>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<?=$menu->getLabel()?> <span class="caret"></span>
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<?php foreach( $menu->getItems() as $item ): ?>
							<?php if( $item->getSeparatorBefore() ): ?>
								<div class="dropdown-divider"></div>
							<?php endif; ?>
							<a class="dropdown-item" href="<?=$item->getUrl()?>"><?=UI::icon( $item->getIcon() )->setWidth( 20 )?> <?=$item->getLabel()?></a>
							<?php if( $item->getSeparatorAfter() ): ?>
								<div class="dropdown-divider"></div>
							<?php endif; ?>
						<?php endforeach; ?>
					</div>

				</li>
			<?php endforeach; ?>
		</ul>

		<ul class="navbar-nav ml-auto">

			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<span><?=UI::flag( Locale::getCurrentLocale() )?></span>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
					<?php foreach( Mvc::getCurrentSite()->getLocales() as $locale ): ?>
						<a class="dropdown-item" href="<?=Mvc::getCurrentSite()->getHomepage()->getURI([], ['locale'=>$locale->toString()])?>">
							<?=UI::flag( $locale )?>
							<?=$locale->getName( $locale )?>
						</a>
					<?php endforeach; ?>
				</div>
			</li>

			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<?=UI::icon( 'user' )?>
					<?=Auth::getCurrentUser()->getUsername()?>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

					<?php if(
						Mvc_Page::get( 'change_password' ) &&
						Mvc_Page::get( 'change_password' )->accessAllowed()
					): ?>
						<a class="dropdown-item"  href="<?=Mvc_Page::get( 'change_password' )->getURL()?>">
								<?=UI::icon( 'cog' )?>
								<?=Tr::_( 'Change password' )?>
							</a>
						<div class="dropdown-divider"></div>
					<?php endif; ?>

					<a class="dropdown-item"  href="<?=Mvc_Page::get( Mvc_Page::HOMEPAGE_ID )->getURL( [], [ 'logout' => 'logout' ] )?>">
							<?=UI::icon( 'sign-out-alt' )?>
							<?=Tr::_( 'Logout' )?>
					</a>
				</ul>
			</li>

		</ul>
	</div>
</nav>




