<?php
namespace JetApplication;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Auth_RESTClient_User $user
 */

$user = $this->getRaw( 'user' );
?>
<h1>Vaše heslo k REST API bylo vyresetováno</h1>

<p>Zde jsou vaše přihlašovací údaje:</p>

<table>
	<tr>
		<td>Uživatelské jméno:</td>
		<td><?= $user->getUsername() ?></td>
	</tr>
	<tr>
		<td>Heslo:</td>
		<td><?= $this->getString( 'password' ) ?></td>
	</tr>
</table>

<p>Přejeme příjemný den</p>