<?php

use Jet\Mvc_View;
use Jet\Form_Renderer;

/**
 * @var Mvc_View $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

$field = $r->getField();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}
?>
<input type="hidden" name="<?= $field->getTagNameValue() ?>" id="<?= $field->getId() ?>"
       value="<?= $field->getValue() ?>" <?php if( $r->getJsActions() ) echo $r->getJsActions() ?>/>
