<?php

use Jet\Mvc_View;
use Jet\Form_Renderer;
use Jet\Form_Field_Int;

/**
 * @var Mvc_View $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

/**
 * @var Form_Field_Int $field
 */
$field = $r->getField();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$attrs = $r->getStdInputFieldAttributes('number');

if( $field->getMinValue() !== null ) {
	$attrs['min'] = $field->getMinValue();
}

if( $field->getMaxValue() !== null ) {
	$attrs['max'] = $field->getMaxValue();
}

if($field->getStep()!==null) {
	$attrs['step'] = $field->getStep();
}
?>
<input <?=$r->renderAttributes( $attrs )?>/>