<?php
use Jet\Mvc_View;
use Jet\Form_Renderer;
use Jet\Form_Field_Select;
use Jet\Form_Field_Select_Option_Interface;
use Jet\Data_Text;

/**
 * @var Mvc_View          $this
 * @var Form_Renderer     $r
 * @var Form_Field_Select $field
 */
$r = $this->getRaw( 'element' );


if(!$r->getBaseCssClasses()) {
	$r->setBaseCssClass('form-control');
}

$field = $r->getField();
$value = $field->getValue();
if($field->getLastErrorCode()) {
	$r->addCustomCssClass('is-invalid');
}
?>
	<select name="<?=$field->getTagNameValue()?>" id="<?=$field->getId()?>" <?php

	if( $r->getCssClasses() ) echo ' class ="'.$r->getCssClasses().'"';
	if( $r->getCssStyles() ) echo ' style ="'.$r->getCssStyles().'"';
	if( $r->getJsActions() ) echo $r->getJsActions();

	if( $field->getIsRequired() ) echo ' required="required"';
	if( $field->getIsReadonly() ) echo ' disabled="disabled"';
	?>>
		<?php foreach( $field->getSelectOptions() as $val => $label ):

			$css = '';
			if( $label instanceof Form_Field_Select_Option_Interface ) {
				if( ( $class = $label->getSelectOptionCssClass() ) ) {
					$css .= ' class="'.$class.'"';
				}
				if( ( $style = $label->getSelectOptionCssStyle() ) ) {
					$css .= ' style="'.$style.'"';
				}
			}

			if( ( (string)$val )==( (string)$value ) ) {
				echo '<option value="'.Data_Text::htmlSpecialChars( $val ).'" '.$css.' selected="selected">'.Data_Text::htmlSpecialChars( $label ).'</option>'.PHP_EOL;
			} else {
				echo '<option value="'.Data_Text::htmlSpecialChars( $val ).'" '.$css.'>'.Data_Text::htmlSpecialChars( $label ).'</option>'.PHP_EOL;
			}
		endforeach; ?>
	</select>