<?php

use Jet\Mvc_View;
use Jet\Form_Renderer;
use Jet\Data_Text;

/**
 * @var Mvc_View $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

$field = $r->getField();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$attrs = [
	'name' => $field->getTagNameValue(),
	'id' => $field->getId(),
];

if( $field->getPlaceholder() ) {
	$attrs['placeholder'] = Data_Text::htmlSpecialChars( $field->getPlaceholder() );
}
if( $field->getIsReadonly() ) {
	$attrs['readonly'] = 'readonly';
}
if( $field->getIsRequired() ) {
	$attrs['required'] = 'required';
}
?>
<textarea <?=$r->renderAttributes($attrs)?>><?= $field->getValueRaw() ?></textarea>
