<p><?=Jet\Tr::_('Please change your password');?></p>

<p>
	<jet_form name="login">
		<div class="form_cell">
			<jet_form_field_label name="password"/>
			<jet_form_field_error_msg name="password"/>
			<jet_form_field name="password"/>
		</div>
		<div class="form_cell">
			<jet_form_field_check_label name="password"/>
			<jet_form_field_check name="password"/>
		</div>
		<input type="submit"/>
	</jet_form>
</p>

[<a href="?logout"><?=Jet\Tr::_('LOGOUT');?></a>]