<?php
use JetExampleApp\Installer;
use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form $form
 */
$form = $this->getRaw('form');

$form->setDefaultLabelWidth(2);
$form->setDefaultFieldWidth(4);
?>
<?=$form->start()?>
	<?=$form->message()?>

    <?php foreach( $form->getFields() as $field ):
        echo $field;
    endforeach; ?>

    <?=Installer::buttonNext();?>

<?=$form->end()?>