<?php
use Jet\Mvc_View;
use Jet\Form_Renderer;

/**
 * @var Mvc_View      $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if(!$r->getBaseCssClasses()) {
	$r->setBaseCssClass('checkbox');
}

$field = $r->getField();
?>
	<div class="<?=$r->getCssClasses()?>">
		<label><input type="checkbox" name="<?=$field->getTagNameValue()?>" id="<?=$field->getId()?>" value="1" <?php

			if( $r->getCssStyles() ) echo ' style ="'.$r->getCssStyles().'"';
			if( $r->getJsActions() ) echo $r->getJsActions();

			if( $field->getIsReadonly() ) echo ' disabled="disabled"';
			if( $field->getValue() ) echo ' checked="checked"';

			?>/><?=$r->getField()->getLabel()?></label>
	</div>