<?php
/**
 *
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license http://www.php-jet.net/license/license.txt
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

$event = $this->getRaw('event');
$event_data = $this->getRaw('event_data');

if($event_data):
?>

<script>gtag('event', '<?=$event?>', <?=json_encode($event_data)?>);</script>

<?php else: ?>

<script>gtag('event', '<?=$event?>');</script>

<?php endif;
