<?php

use Jet\Tr;
use Jet\UI;
use Jet\MVC_View;
use Jet\Form;
use Jet\UI_icon;

/**
 * @var MVC_View $this
 * @var Form $form
 */
$form = $this->getRaw( 'form' );
?>
<div class="col-md-6 offset-md-3 col-sm-8 offset-sm-2">
	<div class="card">
		<h5 class="card-header">
			<?= Tr::_( 'Please change your password' ) ?>
			<?php require '_language_select.phtml'; ?>
		</h5>
		<?= $form->start() ?>
		<div class="card-body">

			<table>
				<tr>
					<td style="padding: 5px;">
						<?= UI::icon( 'exclamation-circle' )->setSize( UI_icon::SIZE_EXTRA_LARGE ) ?>
					</td>
					<td>
						<?= Tr::_( '<b>Your password expired.</b><br/>Please change your password.' ); ?>
					</td>
				</tr>
			</table>

			<div style="padding-top: 30px">
				<?= $form->field( 'password' ) ?>
				<?= $form->field( 'password_check' ) ?>
			</div>

			<div class="text-right">
				<a href="?logout" class="btn btn-light"><?= Tr::_( 'Logout' ); ?></a>
				<input type="submit" value="<?= Tr::_( 'Change password' ); ?>" class="btn btn-primary"/>
			</div>

		</div>
		<?= $form->end() ?>
	</div>
</div>

