<?php
use Jet\Mvc_View;
use Jet\Form_Renderer;
/**
 * @var Mvc_View $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );
$form = $r->getForm();


if(!$r->getBaseCssClasses()) {
	$r->setBaseCssClass('form-horizontal');
}

$attrs = [
	'name' => $form->getName(),
	'id' => $form->getId(),
	'method' => $form->getMethod(),
];

if($form->getAction()) {
	$attrs['action'] = $form->getAction();
}
if($form->getTarget()) {
	$attrs['target'] = $form->getTarget();
}
if($form->getEnctype()) {
	$attrs['enctype'] = $form->getEnctype();
	?> enctype="<?=$form->getEnctype()?>"<?php
}
if($form->getAcceptCharset()) {
	$attrs['accept-charset'] = $form->getAcceptCharset();
}
if($form->getNovalidate()) {
	$attrs['novalidate'] = 'novalidate';
}
if(!$form->getAutocomplete()) {
	$attrs['autocomplete'] = 'off';
}
?>
<form <?=$r->renderAttributes($attrs)?>>
<?php if( !$form->getIsReadonly() ): ?>
	<input type="hidden" name="<?=$form->getSentKey()?>" value="<?=$form->getName();?>">
<?php endif; ?>