<?php
namespace JetApplication\Installer;

use Jet\Form;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Form $form
 */
$form = $this->getRaw( 'form' );
?>

<?= $form->start() ?>
<div style="display: grid;grid-template-columns: 150px 400px;gap: 10px;align-items: center">
	<?= $form->field( 'type' )?>
	<div></div>
	<div>
		<?= Installer::buttonNextSubmit(); ?>
	</div>
	
</div>


<?= $form->end() ?>
