<?php
namespace JetStudio;

use Jet\UI;
use Jet\Mvc_View;
use Jet\UI_button;

/**
 * @var Mvc_View $this;
 * @var DataModels_OuterRelation $relation
 */

$relation = $this->getRaw('relation');

$form = $relation->getEditForm();

echo $form->start();

echo $form->field('join_type');

$form->setDoNotTranslateTexts(true);
foreach( $relation->getRelatedDataModel()->getProperties() as $property ) {
	if(!$property->getIsId()) {
		continue;
	}

	echo $form->field('glue_'.$property->getInternalId());
}
$form->setDoNotTranslateTexts(false);

echo '<div style="text-align: right">';
echo UI::button_save()->setType('button')->setOnclick('JetStudio.DataModel.relation.edit.save(\''.$relation->getInternalId().'\')');
echo '</div>';

echo $form->end();



echo UI::button_delete()
	->setOnclick('JetStudio.DataModel.relation.delete.openDialog(\''.$relation->getInternalId().'\')')
	->setSize(UI_button::SIZE_EXTRA_SMALL);
echo $this->render('data_model/delete_relation/dialog');
