<?php

namespace JetStudio;

$module = Modules::getCurrentModule();

$form = $module->getCreateMenuItemForm();

$form->getField( 'label' )->input()->addJsAction( 'onkeyup', 'Modules.editModule.addMenuItem.generateId(this.value);' );

echo $form->start();
echo $form->getCommonMessage();

echo $form->field( 'target_menu' );

echo $form->field( 'label' );
echo $form->field( 'id' );
echo $form->field( 'icon' );
echo $form->field( 'index' );

echo $form->end();

