<?php
namespace JetStudio;

use Jet\Tr;
use Jet\Form;
use Jet\Mvc_View;
use Jet\UI;

/**
 * @var Mvc_View $this
 */

$form = $this->getRaw('form');

if(!$form) {
	$form = Menus::getCurrentMenuItem()->getEditForm();
}

$field_prefix = $this->getRaw('form_field_prefix', '');

if($field_prefix) {
	$field_prefix_a = $field_prefix.'/';
} else {
	$field_prefix_a = '';
}

$tabs_prefix = $this->getRaw('tabs_prefix', '');

$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);
$form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 6
]);

$tabs = UI::tabsJS('create_menu_item_target_tabs', [
	$tabs_prefix.'tab_direct_mvc' => Tr::_('MVC link'),
	$tabs_prefix.'tab_direct_link' => Tr::_('Direct link'),
]);


?>
	<?=$form->getCommonMessage();?>
	<?=$form->field($field_prefix_a.'id')?>
	<?=$form->field($field_prefix_a.'label')?>
	<?=$form->field($field_prefix_a.'icon')?>
	<?=$form->field($field_prefix_a.'index')?>

	<?=$form->field($field_prefix_a.'separator_before')?>
	<?=$form->field($field_prefix_a.'separator_after')?>

	<?=$tabs?>

	<?=$tabs->contentStart()?>

		<?=$tabs->tab($tabs_prefix.'tab_direct_mvc')->contentStart()?>
			<?=$form->field($field_prefix_a.'page_id')?>
			<?=$form->field($field_prefix_a.'site_id')?>
			<?=$form->field($field_prefix_a.'locale')?>

			<div class="form-group row">
				<label class="col-md-2 control-label"><?=Tr::_('Custom URL parts:')?></label>
				<div class="col-md-6">
					<?php for( $c=0; $c<Menus_Menu_Item::URL_PARTS_COUNT; $c++):
						$field = $form->getField($field_prefix.'/URL_parts/'.$c);
						?>
						<div class="input-group">
							<span class="input-group-prepend" style="font-weight: bolder"><span class="input-group-text">/</span></span>
							<?=$field->input()?>
							<span class="input-group-append" style="font-weight: bolder"><span class="input-group-text">/</span></span>
						</div>
					<?php endfor; ?>
				</div>
			</div>

			<div class="form-group row">
				<label class="col-md-2 control-label"><?=Tr::_('GET parameter:')?></label>
				<div class="col-md-6">
					<?php for( $c=0; $c<Menus_Menu_Item::GET_PARAMS_COUNT; $c++):
						$field_key = $form->getField($field_prefix.'/GET_params/'.$c.'/key');
						$field_value = $form->getField($field_prefix.'/GET_params/'.$c.'/value');
						?>
						<div class="input-group">
							<span class="input-group-prepend" style="font-weight: bolder"><span class="input-group-text"> </span></span>
							<?=$field_key->input()?>
							<span class="input-group-prepend" style="font-weight: bolder"><span class="input-group-text">=</span></span>
							<?=$field_value->input()?>
							<span class="input-group-append" style="font-weight: bolder"><span class="input-group-text"> </span></span>
						</div>
					<?php endfor; ?>
				</div>
			</div>

		<?=$tabs->tab($tabs_prefix.'tab_direct_mvc')->contentEnd()?>
		<?=$tabs->tab($tabs_prefix.'tab_direct_link')->contentStart()?>
			<?=$form->field($field_prefix_a.'URL')?>
		<?=$tabs->tab($tabs_prefix.'tab_direct_link')->contentEnd()?>
	<?=$tabs->contentEnd()?>

