<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

$dialog = UI::dialog('dialog_create_new_module', Tr::_('Create a new Module'), 600);

echo $dialog->start();
	?>
	<div id="<?=Modules_Manifest::getCreateForm()->getId()?>_form_area">
		<?php require 'form.phtml'; ?>
	</div>
	<?php
echo $dialog->footer();
	echo UI::button_save(Tr::_('Create'))->setOnclick('Modules.createModule.createSend()');
echo $dialog->end();

