<?php
namespace JetApplicationModule\JetExample\AdminRoles;
use Jet;

/**
 * @var Jet\Auth_Role_Privilege_AvailablePrivilegesListItem[] $available_privileges_list
 */
$available_privileges_list = $this->available_privileges_list;

/**
 * @var Jet\Form $form
 */
$form = $this->form;
?>
<jetml_editarea id="role_edit" title="Roles" icon="module/%JET_CURRENT_MODULE_NAME%/module" onClose="Jet.modules.CURRENT_MODULE.close();">
	<jetml_editarea_dialog id="role_edit">
		<jetml_layout_toolbar region="top">
			<jetml_form_button_save id="role_save" onClick="Jet.modules.CURRENT_MODULE.save();"/>
			<jetml_form_button_cancel onClick="Jet.modules.CURRENT_MODULE.close();"/>
		</jetml_layout_toolbar>
		<jetml_layout_tabs region="center">
			<jetml_layout_pane title="Basic info">
				<jetml_data id="role_form_fields_definition"><?=json_encode( $form->getFields() ); ?></jetml_data>
				<jetml_data id="role_privileges_scope"><?=json_encode($available_privileges_list);?></jetml_data>

				<jet_form name="<?=$form->getName();?>">
					<jet_form_field name="ID"/>
					<table>
						<tr>
							<td valign="top"><jet_form_field_label name="name"/></td>
							<td><jet_form_field name="name" style="width:400px;"/></td>
						</tr>
						<tr>
							<td valign="top"><jet_form_field_label name="description"/></td>
							<td><jet_form_field name="description" style="width:400px;height:300px;"/></td>
						</tr>
					</table>
				</jet_form>
			</jetml_layout_pane>
			<?php foreach($available_privileges_list as $privilege=>$pd ): ?>
			<jetml_layout_pane title="<?=$pd->getLabel();?>" id="role_access_<?=$privilege;?>_pane">
			</jetml_layout_pane>
			<?php endforeach; ?>
		</jetml_layout_tabs>
	</jetml_editarea_dialog>
	<jetml_editarea_list id="role_edit">
		<jetml_layout_toolbar region="top">
			<jetml_form_button icon="reload" onclick="Jet.modules.CURRENT_MODULE.reloadGrid();"/>
			<jetml_form_button icon="add" title="Add new" onclick="Jet.modules.CURRENT_MODULE.add();"/>
			<jetml_trash_button id="role_trash"/>
		</jetml_layout_toolbar>

		<jetml_layout_pane region="center" gutters="false" style="padding:0px;">
			<jetml_datagrid id="roles_grid">
				<jetml_datagrid_column field="name" title="Name" width="20%"/>
				<jetml_datagrid_column field="description" title="Description" width="60%"/>
				<jetml_datagrid_column field="ID" title="" width="20%"/>
			</jetml_datagrid>
		</jetml_layout_pane>
	</jetml_editarea_list>
</jetml_editarea>

<jetml_trash_dialog id="role_trash"/>
