<?php
use JetUI\UI;
use JetExampleApp\Auth_Administrator_User;
use JetExampleApp\Auth_Administrator_Role;
use Jet\Form;
use Jet\Auth_Role_Privilege_AvailablePrivilegesListItem;
use Jet\Tr;
use Jet\Mvc;
use Jet\Mvc_View;
use Jet\Application_Modules;
use JetApplicationModule\JetExample\Admin\Administrators\Users\Main as UsersModule;

/**
 * @var Mvc_View                                          $this
 * @var Auth_Administrator_Role                           $role
 * @var Form                                              $form
 * @var Auth_Role_Privilege_AvailablePrivilegesListItem[] $available_privileges_list
 * @var UsersModule                                       $users_module
 */
$role = $this->getRaw( 'role' );
$form = $this->getRaw( 'form' );
$available_privileges_list = $this->getRaw( 'available_privileges_list' );
$users_module = Application_Modules::getModuleInstance( 'JetExample.Admin.Administrators.Users' );

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 4 ] );


?>

<div class="col-md-12 main-col" style="padding-top: 5px;">

	<?=$form->start()?>

	<div class="toolbar" id="main-toolbar">
		<?=UI::button_goBack()->setUrl( Mvc::getCurrentPage()->getURI() )?>

		<?php if( !$form->getIsReadonly() ): ?>
			<?=UI::button_save()?>
		<?php endif; ?>
	</div>

	<?=$form->field( 'name' )?>
	<?=$form->field( 'description' )?>

	<fieldset>
		<legend><?=Tr::_( 'Privileges' );?></legend>
		<?php foreach( $available_privileges_list as $privilege => $pd ):
			$fl = $form->field( '/privileges/'.$privilege.'/values' );

			$fl->input()->addCustomCssStyle( 'height:300px' );
			?>
			<?=$fl?>
		<?php endforeach; ?>
	</fieldset>

	<?=$form->end()?>


	<?php if( $role&&count( $role->getUsers() ) ): ?>
		<fieldset style="margin-top: 30px">
			<legend><?=Tr::_( 'Users' );?></legend>
			<table class="table table-striped">
				<thead>
				<tr>
					<th><?=Tr::_( 'Username' );?></th>
				</tr>
				</thead>
				<tbody>
				<?php foreach( $role->getUsers() as $user ):
					/**
					 * @var Auth_Administrator_User $user
					 */
					?>
					<tr>
						<td>
							<a href="<?=$users_module->getAdminControllerRouter()->getEditURI(
								$user->getId()
							);?>"><?=$user->getUsername();?></a>
						</td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</fieldset>
	<?php endif; ?>

</div>