<?php
namespace JetApplicationModule\ManageAccess\RESTClients\Roles;

use JetApplication\Auth_RESTClient_Role as Role;

use Jet\Http_Request;
use Jet\UI;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View $this
 * @var Role     $role
 */
$router = $this->getController()->getControllerRouter();
$role = $this->getRaw( 'role' );
?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>

		<p>
			<?=Tr::_( 'Do you really want to delete this role?' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $role->getId() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$role->getName();?> (<?=$role->getId();?>)</a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>