<?php

use Jet\UI;
use JetApplication\Auth_RESTClient_User;
use JetApplication\Auth_RESTClient_Role;
use Jet\Form;
use Jet\Tr;
use Jet\Mvc;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Auth_RESTClient_Role $role
 * @var Form $form
 * @var array $available_privileges_list
 */
$role = $this->getRaw( 'role' );
$form = $this->getRaw( 'form' );
$available_privileges_list = $this->getRaw( 'available_privileges_list' );

$form->setDefaultLabelWidth( [Form::LJ_SIZE_MEDIUM => 2] );
$form->setDefaultFieldWidth( [Form::LJ_SIZE_MEDIUM => 4] );

?>
<?= $form->start() ?>
<div class="row">
	<div class="col-md-12" style="padding: 0px">
		<div class="toolbar" id="main-toolbar">
			<?= UI::button_goBack()->setUrl( Mvc::getPage()->getURLPath() ) ?>

			<?php if( !$form->getIsReadonly() ): ?>
				<?= UI::button_save() ?>
			<?php endif; ?>
		</div>

		<div class="container-fluid">
			<div class="row main-row">
				<div class="col-md-12 main-col">
					<?= $form->field( 'name' ) ?>
					<?= $form->field( 'description' ) ?>

					<fieldset>
						<legend><?= Tr::_( 'Privileges' ); ?></legend>
						<?php foreach( $available_privileges_list as $privilege ):
							$fl = $form->field( '/privileges/' . $privilege . '/values' );

							$fl->input()->addCustomCssStyle( 'height:300px' );
							?>
							<?= $fl ?>
						<?php endforeach; ?>
					</fieldset>


					<?php if( $role && count( $role->getUsers() ) ): ?>
						<fieldset style="margin-top: 30px">
							<legend><?= Tr::_( 'Users' ); ?></legend>
							<table class="table table-striped">
								<thead>
								<tr>
									<th><?= Tr::_( 'Username' ); ?></th>
								</tr>
								</thead>
								<tbody>
								<?php foreach( $role->getUsers() as $user ):
									/**
									 * @var Auth_RESTClient_User $user
									 */
									?>
									<tr>
										<td>
											<?= $user->getUsername(); ?>
										</td>
									</tr>
								<?php endforeach; ?>
								</tbody>
							</table>
						</fieldset>
					<?php endif; ?>

				</div>
			</div>
		</div>
	</div>
</div>
<?= $form->end() ?>
