<?php
use Jet\Mvc_NavigationData_Breadcrumb_Abstract;

/**
 * @var Mvc_NavigationData_Breadcrumb_Abstract[] $data
 */
$data = $this->data;
?>
<ol class="breadcrumb">
	<?php foreach( $data as $d ): ?>
		<?php if(!$d->getIsLast()): ?>
			<li><a href="<?=$d->getURI(); ?>"><?=$d->getTitle(); ?></a></li>
		<?php else: ?>
			<li class="active"><?=$d->getTitle(); ?></li>
		<?php endif; ?>
	<?php endforeach; ?>
</ol>
