<?php
namespace JetApplicationModule\JetExample\Admin\Administrators\Users;

use JetUI\UI;
use JetExampleApp\Auth_Administrator_User;
use Jet\Mvc;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View $this
 * @var Auth_Administrator_User $user
 */
$user = $this->getRaw('user');

/**
 * @var Controller_Main_Router $router
 */
$router = Mvc::getCurrentContent()->getControllerInstance()->getControllerRouter();

?>

<div class="col-md-12 main-col" style="padding-top: 5px;">

	<?=UI::button_goBack()->setUrl(Mvc::getCurrentPageURI())?>

	<p>
	<?=Tr::_('Do you really want to delete this user?');?>
	<br/>
	<a href="<?=$router->getViewURI($user->getId());?>" style="font-weight: bolder;font-size: 20px;"><?=$user->getName();?> (<?=$user->getLogin();?>)</a>
	</p>

	<form action="?delete=<?=rawurlencode($user->getId());?>" method="post">
		<input type="hidden" name="delete" value="yes">
		<?=UI::button_delete()->setType('submit')?>
	</form>
</div>