<?php
namespace JetApplicationModule\JetExample\Admin\Administrators\Users;

use JetApplication\Auth_Administrator_User;

use Jet\UI_dataGrid;
use Jet\UI;
use Jet\UI_button;

use Jet\Tr;
use Jet\Mvc;
use Jet\Mvc_View;

/**
 * @var Mvc_View               $this
 * @var UI_dataGrid            $grid
 * @var Controller_Main_Router $router
 */
$grid = $this->getRaw( 'grid' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Auth_Administrator_User $item ) use ( $router ) {
		if( ( $edit_uri = $router->getEditURI( $item->getId() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
		echo '&nbsp;';
		if( ( $delete_uri = $router->getDeleteURI( $item->getId() ) ) ):
			echo UI::button_delete()->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;

	}
);
$c_edit->setCssStyle( 'width:180px;' );

$grid->getColumn( 'id' )->setCssStyle( 'width:120px;' );

$grid->getColumn( 'username' )->setRenderer(
	function( Auth_Administrator_User $item ) use ( $router ) {
		$edit_uri = $router->getEditOrViewURI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getUsername();?></a>
		<?php
	}
);

$grid->getColumn( 'id' )->setRenderer(
	function( Auth_Administrator_User $item ) use ( $router ) {
		$edit_uri = $router->getEditOrViewURI( $item->getId() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->getId();?></a>
		<?php
	}
);

$grid->getColumn( 'first_name' )->setRenderer(
	function( Auth_Administrator_User $item ) {
		echo $item->getFirstName();
	}
);

$grid->getColumn( 'surname' )->setRenderer(
	function( Auth_Administrator_User $item ) {
		echo $item->getSurname();
	}
);


?>

<div class="row toolbar">
	<div class="col-xs-7 col-md-3">
		<?=$this->getRaw( 'search_form' ) ?>
	</div>
	<div class="col-xs-5 col-md-3">
		<?php if( ( $add_uri = $router->getAddURI() ) ): ?>
			<?=UI::button_create( Tr::_( 'Create a new User' ) )->setUrl( $add_uri )?>
		<?php endif; ?>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
