<?php
namespace JetApplicationModule\JetExample\Articles;

use Jet\UI_button;
use Jet\UI_dataGrid;
use Jet\UI;

use Jet\Tr;
use Jet\Locale;
use Jet\Mvc;
use Jet\Mvc_View;

/**
 * @var Mvc_View    $this
 * @var UI_dataGrid $grid
 */
$grid = $this->getRaw( 'grid' );

/**
 * @var Controller_Admin_Main_Router $router
 */
$router = $this->getController()->getControllerRouter();

$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setDisplayCallback(
	function( Article $item ) use ( $router ) {

		if( ( $edit_uri = $router->getEditURI( $item->getId() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
		echo '&nbsp;';

		if( ( $delete_uri = $router->getDeleteURI( $item->getId() ) ) ):
			echo UI::button_delete()->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;
	}
);

$c_edit->setAllowSort( false );
$c_edit->setCssStyle( 'width:180px;' );

$grid->getColumn( 'title' )->setDisplayCallback(
	function( Article $item ) use ( $router ) {
		?>
		<a href="<?=$router->getEditOrViewURI( $item->getId() );?>"><?=$item->getTitle();?></a>
		<?php
	}
);

$c_date_time = $grid->getColumn( 'date_time' );
$c_date_time->setDisplayCallback(
	function( Article $item ) {
		echo Locale::dateAndTime( $item->getDateTime() );
	}
);

$c_date_time->setCssStyle( 'width:200px;' );

?>

<div class="col-md-12 main-col" style="padding-top: 5px;">

	<div class="toolbar">
		<?php if( ( $add_uri = $router->getAddURI() ) ): ?>
			<?=UI::button_create( Tr::_( 'Create a new Article' ) )->setUrl( $add_uri )?>
		<?php endif; ?>

	</div>

	<?=$grid->render();?>

</div>
