<?php
use JetApplicationModule\JetExample\Articles\Article;
use JetUI\dataGrid;
use Jet\Mvc_Controller_Router;
use Jet\Tr;
use Jet\Locale;
use JetUI\UI;

/**
 * @var dataGrid $grid
 */
$grid = $this->grid;


/**
 * @var Mvc_Controller_Router $router
 */
$router = $this->router;

$c_edit = $grid->getColumn('_edit_');
$c_edit->setDisplayCallback( function( Article $item ) use ( $router) {

	if( ($edit_uri=$router->getActionURI('edit', $item)) ):
		echo UI::button_edit()->setUrl($edit_uri);
	endif;
	echo '&nbsp;';

	if( ($delete_uri=$router->getActionURI('delete', $item)) ):
		echo UI::button_delete()->setUrl($delete_uri);
	endif;
} );

$c_edit->setAllowSort(false);
$c_edit->setCssStyle( 'width:180px;' );

$grid->getColumn('title')->setDisplayCallback( function( Article $item ) use ( $router) {
	?>
	<?php if($router->getActionAllowed('edit')): ?>
	<a href="<?=$router->getActionURI('edit', $item);?>"><?=$item->getTitle();?></a>
	<?php else: ?>
	<a href="<?=$router->getActionURI('view', $item);?>"><?=$item->getTitle();?></a>
	<?php endif; ?>
	<?php
} );

$c_date_time = $grid->getColumn('date_time');
$c_date_time->setDisplayCallback( function( Article $item ) {
	echo Locale::dateAndTime( $item->getDateTime() );
} );

$c_date_time->setCssStyle( 'width:200px;' );

?>

<div class="col-md-12 main-col" style="padding-top: 5px;">

	<div class="toolbar">
		<?php if( ($add_uri=$router->getActionURI('add')) ): ?>
			<?=UI::button_create(Tr::_('Create a new Article'))->setUrl($add_uri)?>
		<?php endif; ?>

	</div>

	<?=$grid->render(); ?>

</div>
