<?php
namespace JetApplicationModule\JetExample\Articles;

use Jet\Mvc_View;
use Jet\UI;
use Jet\Tr;
use Jet\Mvc;

/**
 * @var Article  $article
 * @var Mvc_View $this
 */
$article = $this->getRaw( 'article' );

/**
 * @var Controller_Admin_Main_Router $router
 */
$router = $this->getController()->getControllerRouter();

?>

<div class="col-md-12 main-col" style="padding-top: 5px;">

	<?=UI::button_goBack()->setUrl( Mvc::getCurrentPage()->getURI() )?>

	<p>
		<?=Tr::_( 'Do you really want to delete this article?' );?>
		<br/>
		<a href="<?=$router->getViewURI( $article->getId() );?>"
		   style="font-weight: bolder;font-size: 20px;"><?=$article->getTitle();?></a>
	</p>

	<form action="?delete=<?=rawurlencode( $article->getIdObject() );?>" method="post">
		<input type="hidden" name="delete" value="yes">
		<?=UI::button_delete()->setType( 'submit' )?>
	</form>
</div>