<?php

namespace JetStudio;

use Jet\MVC_View;
use Jet\UI;
use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Pages_Page $page
 */

$page = $this->getRaw( 'page' );

$dialog = UI::dialog( 'delete_content', Tr::_( 'Delete this content' ), 600 );

echo $dialog->start();
?>
<?= Tr::_( 'Do You really want to delete this content item ?' ); ?>
	<?php
echo $dialog->footer();
echo UI::button_delete()->setOnclick( "Pages.editPage.content.deleteContentSend();" );
echo $dialog->end();

$form = $page->getDeleteContentForm();

echo $form->start();
echo $form->field( 'index' );
echo $form->end();
