<?php
namespace JetApplicationModule\Content\Images;

use Jet\Form_Field_FileImage;
use Jet\UI;
use Jet\Tr;
use Jet\Mvc_View;
use Jet\UI_messages;
use Jet\Locale;
use Jet\IO_File;

/**
 * @var Mvc_View                     $this
 * @var Gallery                      $gallery
 * @var Controller_Admin_Router $router
 * @var Form_Field_FileImage $files_field
 */
$gallery = $this->getRaw( 'gallery' );
$images = $gallery->getImages();

$router = $this->getController()->getControllerRouter();

$delete_uri = $router->getDeleteImagesURI($gallery->getId());

$files_field = $gallery->getImageUploadForm()->field('file');

foreach( $files_field->getMultipleUploadErrors() as $file_name=>$errors ):

	foreach( $errors as $code=>$message ):

		$message = Tr::_(
			'File <b>%file_name%</b>: %error_message%',
			[
				'file_name'=>$file_name,
				'error_message'=>$message
			]
		);

		if( $code==Form_Field_FileImage::ERROR_CODE_FILE_IS_TOO_LARGE ) {

			$message .= Tr::_(
				'<br/>The maximum size of one uploaded file is: <b>%max_upload_size%</b>',
				['max_upload_size'=>Locale::getCurrentLocale()->formatSize(IO_File::getMaxUploadSize())]
			);

		}

		echo UI_messages::createDanger($message);
	endforeach;
endforeach;


if( count( $images ) ): ?>
	<form action="<?=$delete_uri?>" method="post">
		<div class="row">
			<?php foreach( $images as $image ): ?>
				<div style="float:left;margin: 10px;overflow: hidden;">
					<div class="thumbnail" style="height: 200px;width: 200px;padding:10px;overflow: hidden">
						<a href="<?=$image->getURI();?>" target="_blank">
							<div
								style="width:180px;height:135px;background-position:center;background-repeat:no-repeat;background-image: url('<?=$image->getThumbnail( 180, 135 )->getURI();?>');"
							></div>
						</a>

						<div class="caption">
							<p>
								<?php if( $delete_uri ): ?>
									<input type="checkbox" name="images[]"
									       value="<?=$image->getId();?>"
									       id="image_<?=$image->getId();?>">
								<?php endif; ?>
								<?=$image->getFileName();?>
							</p>
						</div>
					</div>
				</div>
			<?php endforeach; ?>
		</div>

		<?php if( $delete_uri ): ?>
			<?=UI::button_delete( Tr::_( 'Delete selected images' ) )->setType( 'submit' )?>
		<?php endif; ?>
	</form>
<?php endif;
