<?php
namespace JetApplicationModule\Content\Images;

use Jet\Mvc_Layout;
use Jet\UI;


use Jet\Form;
use Jet\Mvc_View;

Mvc_Layout::getCurrentLayout()->requireJavascriptFile(JET_AJAX_FORM_JS_URL);

/**
 * @var Mvc_View  $this
 * @var Form      $upload_form
 * @var Gallery   $gallery
 */
$upload_form = $this->getRaw( 'upload_form' );
$gallery = $this->getRaw( 'gallery' );

if(!$upload_form || $upload_form->getIsReadonly()) {
	return;
}

$router = $this->getController()->getControllerRouter();

$upload_form->setAction( $router->action('image_upload')->URI( $gallery->getId() ) );

$file_field = $upload_form->field( 'file' );

$file_field->input()
	->addJsAction('onchange', 'imageGallery.uploadImage(this.form.id)')
	->addCustomCssStyle(' position: absolute;top: 0;right: 0;margin: 0;padding: 0;font-size: 20px;cursor: pointer;opacity: 0;filter: alpha(opacity=0);')
?>


<?=$upload_form->start()?>

<?=$file_field->row()->start()?>
	<div class="btn btn-primary" style=" position: relative;overflow: hidden;margin: 10px;">
		<?=UI::icon('upload')?>&nbsp;<span><?=$file_field->getLabel()?></span>
		<?=$file_field->input()?>
	</div>
<?=$file_field->row()->end()?>

<?=$upload_form->end()?>

<?=$upload_form->getCommonMessage();?>