<?php

namespace JetStudio;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

$menu_item = Modules::getCurrentMenuItem();
$menu_item->getEditForm()->setAction( Modules::getActionUrl( 'menu_item/edit' ) );

$app_part = Application::getCurrentPart();
Application::setCurrentPart( 'menus' );

$view = Application::getView();

$view->setVar( 'item', $menu_item );

echo Application_UI::messages();
echo $view->render( 'item/edit/form' );

echo $this->render( 'menu_item/delete/dialog' );

Application::setCurrentPart( $app_part );

