<?php
namespace JetStudioModule\ApplicationModules;

$module = Main::getCurrentModule();

$form = $module->getMenuItems()->getCreateMenuItemForm();

$form->getField( 'label' )->input()->addJsAction( 'onkeyup', 'Modules.editModule.addMenuItem.generateId(this.value);' );

echo $form->start();
echo $form->getCommonMessage();
?>
<div class="form-fields" style="grid-template-columns: 20% 1fr;">
<?php
echo $form->field( 'target_menu' );

echo $form->field( 'label' );
echo $form->field( 'id' );
echo $form->field( 'icon' );
echo $form->field( 'index' );


echo $form->field( 'separator_before' );
echo $form->field( 'separator_after' );

echo $form->field( 'URL' );

echo $form->field( 'base_id' );
echo $form->field( 'page_id' );
echo $form->field( 'locale' );
?>
</div>
<?php
echo $form->end();

