<title>Jet Example Application</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style type="text/css">
	html, body, #main{
		font: 12pt Arial,Myriad,Tahoma,Verdana,sans-serif;
		width: 100%;
		height: 100%;
	}

	.formFieldError {
		clear: none;
		background-color: #ff0000;
		color: #ffffff;
		padding: 3px;
	}
	.buttonCancel {
		margin-left: 20px;
	}
	.editAreaBn {
		padding: 5px;
	}
	.editAreaBn a {
		color: black;
	}

	.editAreaBn img {
		padding: 0px;
	}
	.editAreaBnSeparator {
	}
	.editAreaBnActiveTitle {
		font-weight: bolder;
		font-size: 15px;
	}

	.Jet_Uploader_FileItem {
		margin: 5px;
	}

	.Jet_Uploader_FileItem_inProgress {
		background-color: #c9c9c9;
	}

	.Jet_Uploader_FileItem_uploaded {
		background-color: #aaffaa;
	}

	.Jet_Uploader_FileItem_error {
		background-color: #ffbbbb;
	}

	.Jet_Uploader_FileItem .fileName {
		padding-top: 20px;
		font-weight: bolder;
	}

	.Jet_Uploader_FileItem .fileSize {
		font-size: 11px;
	}

	.Jet_Uploader_FileItem .fileIcon {
		max-width:100px;
		max-height:100px;
	}

	.Jet_Uploader_FileItem .fileIconBox {
		width: 104px;
		height: 104px;
		vertical-align: middle;
		text-align: center;

	}
</style>


<jet_layout_meta_tags/>
<jet_layout_javascripts/>
<jet_layout_header_suffix/>