<?php

namespace JetApplicationModule\Content\Images\Admin;

use Jet\UI;
use Jet\Form;
use Jet\MVC_View;

use JetApplication\Application_Web;

/**
 * @var MVC_View $this
 * @var Form $edit_form
 */

$edit_form = $this->getRaw( 'edit_form' );

$edit_form->setDefaultLabelWidth( [Form::LJ_SIZE_MEDIUM => 1] );
$edit_form->setDefaultFieldWidth( [Form::LJ_SIZE_MEDIUM => 5] );

echo $edit_form->start();

foreach( Application_Web::getBase()->getLocales() as $locale ):
	$field = $edit_form->field( '/localized/' . $locale . '/title' );

	echo $field->row()->start();
	?>
	<label for="<?= $field->getId() ?>"
	       class="col-md-1 col-form-label"><?= UI::flag( $locale ) ?> <?= $locale->getLanguageName() ?></label>
	<?php

	echo $field->container()->start();
	echo $field->input();
	echo $field->error();
	echo $field->container()->end();

	echo $field->row()->end();

endforeach;

echo $edit_form->end();
