<?php
namespace Jet;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-07 at 15:02:54.
 */
class Console_OptionsParserTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var Console_OptionsParser
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Console_OptionsParser;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Jet\Console_OptionsParser::addOption
	 * @todo   Implement testAddOption().
	 */
	public function testAddOption() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Console_OptionsParser::setHelpFooter
	 * @todo   Implement testSetHelpFooter().
	 */
	public function testSetHelpFooter() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Console_OptionsParser::getHelpFooter
	 * @todo   Implement testGetHelpFooter().
	 */
	public function testGetHelpFooter() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Console_OptionsParser::setHelpHeader
	 * @todo   Implement testSetHelpHeader().
	 */
	public function testSetHelpHeader() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Console_OptionsParser::getHelpHeader
	 * @todo   Implement testGetHelpHeader().
	 */
	public function testGetHelpHeader() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Console_OptionsParser::parse
	 * @todo   Implement testParse().
	 */
	public function testParse() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Console_OptionsParser::showHelp
	 * @todo   Implement testShowHelp().
	 */
	public function testShowHelp() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Console_OptionsParser::getOptions
	 * @todo   Implement testGetOptions().
	 */
	public function testGetOptions() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
