<?php

namespace JetStudio;

use Jet\Http_Request;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_badge;

/**
 * @var MVC_View $this
 */

$current = Modules::getCurrentModule();

if(
	!$current
) {
	return;
}

$pages = $current->getPages();
$bases = Bases::getBases();
$pages = $pages->getList();

$current_page = Modules::getCurrentPage();
?>
	<table class="table table-striped">
		<tr>
			<td><b><?= Tr::_( 'Pages' ) ?></b></td>
		</tr>
		<?php foreach( $bases as $base_id => $base ):

			if( empty( $pages[$base_id] ) ) {
				continue;
			}
			?>
			<tr>
				<td style="font-size: 10px;padding-left: 20px;"><b><?= Bases::getBase( $base_id )->getName() ?></b></td>
			</tr>
			<?php foreach( $pages[$base_id] as $page ): ?>
			<tr>
				<td style="padding-left: 50px;">
					<?php if( $current_page && $current_page->getFullId() == $page->getFullId() ):
						echo UI::badge(UI_badge::INFO, $page->getName());
					else: ?>
						<a href="<?= Http_Request::currentURI( ['page' => $page->getFullId()], [
							'menu_item',
							'action'
						] ) ?>"><?= $page->getName() ?></a>
					<?php endif; ?>
				</td>
			</tr>
		<?php endforeach; ?>
		<?php endforeach; ?>
	</table>
