<?php
namespace Jet;
/**
 * @var Installer_Step_Controller[] $steps
 * @var Mvc_Layout $this
 */
$steps = $this->getRaw("steps");
?>
<html>
<head>
	<title><?=Tr::_("PHP Jet Project Installer");?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" type="text/css" href="<?=JET_INSTALLER_URI;?>public/styles/main.css">
	<jet_layout_meta_tags/>
	<jet_layout_javascripts/>
	<jet_layout_header_suffix/>
</head>
<body>

<table cellpadding="0" cellspacing="0" width="100%" height="100%">
	<tr><td colspan="2" id="header" height="40" valign="middle">
		<?=Tr::_("PHP Jet Project Installer");?>
	</td></tr>
	<tr>
		<td valign="top" id="statusBar">

				<?php foreach( $steps as $step ):
					$class = "";
					if($step->getIsSubstep()) {
						$class = " stepSub";
					}
					?>
					<?php if($step->getIsPrev()): ?>
					<div class="stepPrev<?=$class;?>"><a href="<?=$step->getURL();?>"><?=$step->getLabel();?></a></div>
					<?php endif; ?>
					<?php if($step->getIsCurrent()): ?>
					<div class="stepCurrent<?=$class;?>"><?=$step->getLabel();?></div>
					<?php endif; ?>
					<?php if($step->getIsNext()): ?>
					<div class="stepNext<?=$class;?>"><?=$step->getLabel();?></div>
					<?php endif; ?>
				<?php endforeach; ?>

		</td>
		<td valign="top" style="padding: 10px;"><jet_layout_main_position/></td>
	</tr>
</table>


</body>
</html>