<?php

use Jet\Mvc;
use Jet\Tr;

?>
<div class="card bg-light text-dark">
	<div class="card-body">

		<table class="table">
			<tr>
				<td><?= Tr::_( 'Current base id:' ) ?></td>
				<td><?= Mvc::base()->getId(); ?></td>
			</tr>
			<tr>
				<td><?= Tr::_( 'Current locale:' ) ?></td>
				<td><?= Mvc::locale(); ?></td>
			</tr>
			<tr>
				<td><?= Tr::_( 'Current page id:' ) ?></td>
				<td><?= Mvc::page()->getId(); ?></td>
			</tr>
		</table>

	</div>
</div>