<?php
namespace JetStudioModule\DataModel;

use Jet\Tr;
use Jet\UI_messages;

$problems = DataModels::getProblems();
?>

<div style="padding: 20px;">
	<h1><?= Tr::_( 'Upsss .... ' ); ?></h1>
	<p><?= Tr::_( 'I am sorry, but there are some troubles ...' ) ?></p>

	<?php foreach( $problems as $context=>$error_message ): ?>
		<b><?= $context ?></b><br/>
		<?= UI_messages::createDanger( $error_message ) ?>
	<?php endforeach; ?>

</div>
