<jetml_dialog id="jet_alert_dialog" title="">
	<div id="jet_alert_dialog_msg_area" style="min-width: 200px; max-width: 400px;"></div>
	<jetml_dialog_buttons>
		<jetml_form_button id="jet_alert_dialog_ok_button" title="OK"/>
	</jetml_dialog_buttons>
</jetml_dialog>

<jetml_dialog id="jet_confirm_dialog" title="">
	<div id="jet_confirm_dialog_msg_area" style="min-width: 200px; max-width: 400px;"></div>
	<jetml_dialog_buttons>
		<jetml_form_button id="jet_confirm_dialog_yes_button" title="Yes"/>
		<jetml_form_button id="jet_confirm_dialog_no_button" title="NO"/>
	</jetml_dialog_buttons>
</jetml_dialog>