<?php
use Jet\Mvc_Layout;

/**
 * @var Mvc_Layout $this
 */

$this->requireCssFile( 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' );
$this->requireCssFile( 'https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' );
$this->requireCssFile( 'styles/flags.css' );

$this->requireJavascriptFile( 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js' );
$this->requireJavascriptFile( 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' );


?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title></title>

<jet_layout_meta_tags/>
<jet_layout_css/>
<jet_layout_javascripts/>

<style type="text/css">
	html, body {
		width: 100%;
		height: 100%;
		overflow: hidden;
		padding: 0 0 0 0;
		margin: 0 0 0 0;

		background: #c9c9c9;
		background: linear-gradient(#aaaaaa, #ffffff);
	}

	.container-table {
		height: 100%;
		display: table;
	}

	.vertical-center-row {
		display: table-cell;
		vertical-align: middle;
	}
</style>
