<?php

use Jet\MVC_View;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'col-form-label' );
}

$r->setWidthCssClassesCreator(function( $size, $width ) {
	return 'col-' . $size . '-' . $width;
});

$attrs = [
	'for' => $r->getField()->getId()
]
?>
<label <?=$r->renderAttributes($attrs)?>><?php
	if( $r->getField()->getIsRequired() ) echo '<em class="form-required">*</em> ';
	echo $r->getField()->getLabel();
?></label>