<?php
namespace JetApplication;

use Jet\Mvc_View;
use Jet\URI;

/**
 * @var Mvc_View $this
 * @var Auth_Administrator_User $user
 */

$user = $this->getRaw('user');
?>
<img src="<?=URI::PUBLIC()?>email_imges/email_header.jpg"/>

<h1>Vaše administrátorské heslo bylo vyresetováno</h1>

<p>Zde jsou vaše přihlašovací údaje:</p>

<table>
	<tr>
		<td>Uživatelské jméno:</td>
		<td><?=$user->getUsername()?></td>
	</tr>
	<tr>
		<td>Heslo:</td>
		<td><?=$this->getString('password')?></td>
	</tr>
</table>

<p>Po přihlášení si prosím změňte heslo</p>

<p>Přejeme příjemný den</p>