<?php
require_once 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html>
<head>
	<title><?=$this->getString( 'page_title', 'JetApplication admin' )?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>

	<style type="text/css">
		html, body {
			width: 100%;
			height: 100%;
			overflow: hidden;
			padding: 0 0 0 0;
			margin: 0 0 0 0;

			background: #c9c9c9;
			background: linear-gradient(#aaaaaa, #ffffff);
		}

		.container-table {
			height: 100%;
			display: table;
		}

		.vertical-center-row {
			display: table-cell;
			vertical-align: middle;
		}
	</style>

</head>
<body>
	<div class="container container-table">
		<div class="row vertical-center-row">
			<jet_layout_main_position/>
		</div>
	</div>

</body>
</html>