<?php
use Jet\Form;
use Jet\Tr;

/**
 * @var Form $form
 */
$form = $this->form;

/**
 * @var Form $upload_form
 */
//$upload_form = $this->upload_form;
?>
<jetml_dojo_layout_container gutters="true">
	<jetml_dojo_layout_container region="left" splitter="true" style="width:200px">
		<jetml_dojo_layout_toolbar region="top">

			<jetml_dojo_form_button onClick="Jet.modules.CURRENT_MODULE.add();" title="New gallery" icon="add"/>
			<jetml_dojo_trash_button trash_id="gellery_trash"/>

			<jetml_dojo_trash_dialog trash_id="gellery_trash">
			</jetml_dojo_trash_dialog>
		</jetml_dojo_layout_toolbar>
		<jetml_dojo_layout_pane region="center" id="galleries_tree_area" style="padding:0;">
		</jetml_dojo_layout_pane>
		<jetml_dojo_layout_toolbar region="bottom">
			<jetml_dojo_form_button onClick="Jet.modules.CURRENT_MODULE.treereload();" icon="reload"/>
			<jetml_dojo_form_button onClick="Jet.modules.CURRENT_MODULE.treeExpand();" icon="expand"/>
			<jetml_dojo_form_button onClick="Jet.modules.CURRENT_MODULE.treeCollapse();" icon="collapse"/>
		</jetml_dojo_layout_toolbar>
	</jetml_dojo_layout_container>

	<jetml_dojo_layout_container region="center" gutters="false" id="edit_area" style="visibility: hidden;">
		<jetml_dojo_layout_toolbar region="top">
			<table><tr>
					<td>
						<jetml_data id="gallery_form_fields_definition"><?=json_encode($form->getFields());?></jetml_data>
						<jetml_dojo_form_button_save onClick="Jet.modules.CURRENT_MODULE.save();" id="gallery_save"/>

					</td>
					<td>
						<jet_form name="<?=$form->getName();?>">
							<jet_form_common_error_message class="formError"/>
							<table>
								<jet_form_field name="parent_ID"/>
								<jet_form_field name="ID"/>
								<tr>
									<td><jet_form_field_label name="title"/></td>
									<td><jet_form_field_error_msg name="title" class="error"/><jet_form_field name="title"/></td>
								</tr>
							</table>
						</jet_form>

					</td>
					<td>
						<jetml_dojo_form_button title="Upload new image" icon="add" onClick="Jet.modules.CURRENT_MODULE.openUploadDialog();" id="upload_images_button"/>
					</td>

					<td>
						<jetml_dojo_trash_button trash_id="images_trash"/>
					</td>
			</tr></table>

		</jetml_dojo_layout_toolbar>

		<jetml_dojo_datagrid id="images_grid" region="center" plugins="{'dnd':{'copyOnly': true},'pagination':{'pageSizes':['25','50','100'],'description':true,'sizeSwitch':true,'pageStepper':true,'gotoButton':true,'maxPageStep':10,'position':'bottom'},'indirectSelection':{'headerSelector':true,'name':'Selection','width':'20px','styles':'text-align: center;'}}">
			<jetml_dojo_datagrid_column field="thumbnail_URI" title="Image" width="110" formatter="formatImage" />
			<jetml_dojo_datagrid_column field="file_name" title="File name" width="70%"/>
			<jetml_dojo_datagrid_column field="file_size" title="File size" width="110" formatter="Jet.Formatter.FileSize" />
		</jetml_dojo_datagrid>
	</jetml_dojo_layout_container>

</jetml_dojo_layout_container>

<jetml_dojo_trash_dialog trash_id="images_trash"/>

<jetml_dojo_dialog id="copy_image_dialog" align="center" title="Copy images">
	<jetml_div id="copy_images_thb_area" style="width:300px;height: 300px;overflow: auto; border: 1px solid #c9c9c9">

	</jetml_div>

	<jetml_dojo_dialog_buttons>
        <label>
            <jetml_dojo_form_checkbox id="copy_overwrite_if_exists"/>
            <?=Tr::_('Overwrite if exists');?>
        </label>

		<jetml_dojo_form_button_busy title="Copy selected images" onClick="Jet.modules.CURRENT_MODULE.copyImages();" id="copy_image_button"></jetml_dojo_form_button_busy>
	</jetml_dojo_dialog_buttons>
</jetml_dojo_dialog>

<?php


?>

<jetml_dojo_dialog id="upload_image" align="center">
	<jetml_dojo_form_button id="upload_images_select_files_button" title="Select files"/>

	<div style="display: none;">
		<form method="post" action="" enctype="multipart/form-data">
			<input name="files[]" id="%JET_UI_CONTAINER_ID_PREFIX%upload_images_files" type="file" multiple="multiple" />
		</form>
	</div>

	<jetml_div id="upload_images_selected_files_area" style="border: 1px solid #c9c9c9; width: 400px;height: 400px;overflow: auto;" align="left">
	</jetml_div>

	<table style="width: 100%;"><tr>
			<td style="vertical-align: bottom;text-align: left">
				<jetml_dojo_form_button icon="cancel" title="Cancel files selection" disabled="true" id="upload_images_reset_button"/>

			</td>

			<td style="vertical-align: bottom;text-align: right">
				<jet_form name="upload_form">
					<jet_form_field_label name="overwrite_if_exists"/>
					<jet_form_field_error_msg name="overwrite_if_exists" class="error"/><jet_form_field name="overwrite_if_exists"/>
				</jet_form>
				<jetml_dojo_form_button icon="add" title="Upload images" disabled="true" id="upload_images_upload_button"/>

			</td>
	</tr></table>

</jetml_dojo_dialog>

