<?php
use Jet\Mvc_Layout;
use Jet\Tr;
use Jet\UI;

/**
 * @var Mvc_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html>
<head>
	<title><?=Tr::_('PHP Jet Example Application')?> : %JET_SITE_TITLE% - %JET_PAGE_TITLE%</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="%JET_LANGUAGE%" />

	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>
</head>
<body>
<div class="container" style="width: 100%;height: 100%">
	<div class="page-header">
		<h1><?=UI::icon('user-secret')->setSize(40).Tr::_('Secret area!')?></h1>
		<small><?=Tr::_("PHP Jet Example Application");?></small>
	</div>

	<div class="row">
		<jet_module module="JetExample.BreadcrumbNavigation" view="default" />
	</div>

	<div class="row">
		<div class="col-md-3" style="background-color: #eeeeee">
			<jet_module module="JetExample.TestModule" action="secret_area_menu"/>
			<jet_layout_position name="left"/>
		</div>
		<div class="col-md-9" style="padding-top: 10px;padding-bottom: 20px;">
			<jet_layout_main_position/>
		</div>
	</div>
</div>

</body>
</html>