<?php
use Jet\Mvc_Layout;
use Jet\Tr;

/**
 * @var Mvc_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html>
<head>
	<title><?=Tr::_('PHP Jet Example Application')?> : %JET_SITE_TITLE% - %JET_PAGE_TITLE%</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="%JET_LANGUAGE%" />

	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>

	<jet_layout_header_suffix/>
</head>
<body>
<div style="display: none;">
	<jet_layout_body_prefix/>
</div>

<div class="container" style="width: 100%">
	<div class="page-header">
		<h1><?=Tr::_('Hello WORLD!')?></h1>
		<small><?=Tr::_("PHP Jet Example Application");?></small>
	</div>

	<div class="row">
		<jet_module module="JetExample.BreadcrumbNavigation" view="default" />
	</div>

	<div class="row" style="background-color: #e9e9e9;">
		<div class="clear"></div>

		<div class="col-md-3">
			<jet_module module="JetExample.TestModule" action="main_menu"/>
			<jet_layout_position name="left"/>
		</div>
		<div class="col-md-7" style="background-color: #ffffff;padding-top: 10px;padding-bottom: 20px;">
			<jet_layout_main_position/>
		</div>
		<div class="col-md-2">
			<jet_layout_position name="right"/>
		</div>
	</div>
</div>

<div style="display: none;">
	<jet_layout_body_suffix/>
</div>
</body>
</html>