<?php
namespace JetStudio;

use Jet\Mvc_Layout;
use Jet\Tr;
use Jet\UI;
use Jet\Form;
use Jet\UI_button;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 */

$page = $this->getRaw('page');

if(!$page) {
	$page = Pages::getCurrentPage();
}

if(!$page) {
	return;
}

$p_f_prefix = $this->getString('form_field_prefix', '');
$p_f_prefix_a = '';
if($p_f_prefix) {
	$p_f_prefix_a = substr($p_f_prefix, 0, -1);
}


$form = $this->getRaw('form', null);

if(!$form) {
	$form = $page->getEditForm();
}
$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 3
]);
$form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 7
]);

$site = $this->getRaw('site');

if(!$site) {
	$site = Sites::getCurrentSite();
}


$positions = [];
$known_positions = $site->getLayoutOutputPositions( $page->getLayoutScriptName() );

$i = 0;
foreach( $page->getContent() as $content ) {

	$position = $content->getOutputPosition();
	if(!$position) {
		$position = Mvc_Layout::DEFAULT_OUTPUT_POSITION;
	}
	if( !isset( $positions[$position] ) ) {
		if(isset($known_positions[$position])) {
			$known = true;
			$label = $known_positions[$position];
		} else {
			$known = false;
			$label = $position;
		}

		$positions[$position] = [
					'known'   => $known,
					'label'   => $label,
					'content' => []
				];
	}

	$positions[$position]['content'][$i] = $content;

	$i++;
}

foreach( $positions as $position=>$pd ) {
	uasort(
		$positions[$position]['content'],
		function( Pages_Page_Content $a, Pages_Page_Content $b ) {
			$a_p = $a->getOutputPositionOrder();
			$b_p = $b->getOutputPositionOrder();

			if($a_p==$b_p) {
				return 0;
			}

			if($a_p>$b_p) {
				return 1;
			}

			return -1;
		}
	);
}

$modules = [];

foreach( Modules::getModules() as $module )
{
	$modules[ $module->getName() ] = $module->getLabel().' ('.$module->getName().')';
}


$site_id = $page->getSiteId();
$page_id = $page->getId();

$delete_content_action_creator = $this->getRaw('delete_content_action_creator');

if(!$delete_content_action_creator) {
	$delete_content_action_creator = function( $i ) {
		return "JetStudio.Pages.editPage.content.deleteContent($i);";
	};
}

$save_button = $this->getRaw('save_button');
$showSaveButton_c = function() use ($save_button) {
	if(!$save_button) {
		return;
	}
	?>
	<div class="row" style="margin-bottom: 20px;">
		<div class="col-md-2">
		</div>
		<div class="col-md-6" align="right">
			<?=$this->getRaw('save_button')?>
		</div>
	</div>
	<?php
}


?>

<?php foreach( $positions as $position=>$pd ): ?>


<?php if($pd['known']): ?>
	<h4><?=Tr::_('Position: %position%', ['position'=>$pd['label']])?></h4>
<?php else: ?>
	<h4 style="color: #ff0000"><?=Tr::_('! Unknown position: %position%', ['position' => $pd['label']])?></h4>
<?php endif; ?>

	<?php foreach( $pd['content'] as $i=>$content ):
		/**
		 * @var Pages_Page_Content $content
		 */


		$f_prefix = '/content/'.$i.'/';

		?>
		<div>
			<div class="card">
				<div class="card-header" data-toggle="collapse" data-target="#content_<?=$site_id?>_<?=$page_id?>_<?=$i?>">
					<table width="100%">
						<tr>
							<td style="width: 100px"><?=$content->getOutputPositionOrder()?>.</td>

							<?php switch($content->getContentKind()) {
								case Pages_Page_Content::CONTENT_KIND_MODULE:
									$known = isset( $modules[$content->getModuleName()] );

									if($known) {
										$label = $modules[$content->getModuleName()];
									} else {
										$label = $content->getModuleName();
									}

									?>
									<td style="width: 200px;">
										<?php if( $known ): ?>
											<b><?=Tr::_('Module: ')?></b>
										<?php else: ?>
											<b style="color: #ff0000"><?=Tr::_('Unknown Module: ')?></b>
										<?php endif; ?>
									</td>
									<td>
										<table border="0">
											<tr>
												<td><?=$label?></td>
												<td>&nbsp;&nbsp;->&nbsp;&nbsp;</td>
												<td><?=$content->getControllerName()?></td>
												<td>&nbsp;&nbsp;->&nbsp;&nbsp;</td>
												<td><?=$content->getControllerAction()?></td>
											</tr>
										</table>
									</td>

									<?php
									break;
								case Pages_Page_Content::CONTENT_KIND_CLASS:
									?>
									<td style="width: 200px;"><b><?=Tr::_('Controller class: ')?></b></td>
									<td>
										<table border="0">
											<tr>
												<td><?=$content->getControllerClass()?></td>
												<td>&nbsp;&nbsp;->&nbsp;&nbsp;</td>
												<td><?=$content->getControllerAction()?></td>
											</tr>
										</table>
									</td>
									<?php
									break;
								case Pages_Page_Content::CONTENT_KIND_STATIC:
									?>
									<td style="width: 200px;"><b><?=Tr::_('Static:')?></b></td>
									<td>
										<?=substr(strip_tags($content->getOutput()), 0, 100).' ...'?>
									</td>
									<?php
									break;
								case Pages_Page_Content::CONTENT_KIND_CALLBACK:
									$callback = $content->getOutput();
									?>
									<td style="width: 200px;"><b><?=Tr::_('Callback:')?></b></td>
									<td>
										<?=$callback[0]?>::<?=$callback[1]?><span style="color: #c9c9c9">( Jet\Mvc_Page $page, Jet\Mvc_Page_Content $content )</span>
									</td>
									<?php
									break;

							}?>
							<td align="right">
								<?=UI::button_delete(Tr::_('Delete this content'))->setOnclick($delete_content_action_creator($i))->setSize(UI_button::SIZE_EXTRA_SMALL)?>
							</td>
						</tr>
					</table>



				</div>

				<div class="card-body collapse" id="content_<?=$site_id?>_<?=$page_id?>_<?=$i?>">
					<?php
					echo $form->field($p_f_prefix_a.$f_prefix.'output_position');
					echo $form->field($p_f_prefix_a.$f_prefix.'output_position_order');
					?>
					<hr/>
					<div class="form-group row">
						<label class="col-md-3 control-label"><?=Tr::_('Parameters:')?></label>
						<div class="col-md-7">
							<?php
							$i = 0;
							while( $form->fieldExists($p_f_prefix_a.$f_prefix.'params/'.$i.'/key') ):
								$field_key = $form->getField($p_f_prefix_a.$f_prefix.'params/'.$i.'/key');
								$field_value = $form->getField($p_f_prefix_a.$f_prefix.'params/'.$i.'/value');
								?>
								<div class="input-group">
									<span class="input-group-addon" style="font-weight: bolder"> </span>
									<?=$field_key->input()?>
									<span class="input-group-addon" style="font-weight: bolder">=</span>
									<?=$field_value->input()?>
									<span class="input-group-addon" style="font-weight: bolder"> </span>
								</div>
								<?php
								$i++;
							endwhile; ?>
						</div>
					</div>
					<hr/>


					<?php switch($content->getContentKind()) {
						case Pages_Page_Content::CONTENT_KIND_MODULE:
							echo $form->field($p_f_prefix_a.$f_prefix.'module_name');
							echo $form->field($p_f_prefix_a.$f_prefix.'controller_name');
							echo $form->field($p_f_prefix_a.$f_prefix.'controller_action');

							break;
						case Pages_Page_Content::CONTENT_KIND_CLASS:
							echo $form->field($p_f_prefix_a.$f_prefix.'controller_class');
							echo $form->field($p_f_prefix_a.$f_prefix.'controller_class_action');

							break;
						case Pages_Page_Content::CONTENT_KIND_STATIC:
							$form->field($p_f_prefix_a.$f_prefix.'output')->input()->addCustomCssStyle('height: 400px');

							echo $form->field($p_f_prefix_a.$f_prefix.'output')->input();

							break;
						case Pages_Page_Content::CONTENT_KIND_CALLBACK:
							$class_field = $form->field($p_f_prefix_a.$f_prefix.'output_callback_class');
							$method_field = $form->field($p_f_prefix_a.$f_prefix.'output_callback_method');
							?>
							<div style="width: 1000px;margin: 10px;">
								<?=$class_field->row()->start()?>
									<?=$class_field->error()?>
									<?=$method_field->error()?>
									<div class="input-group">
									<span class="input-group-prepend">
									</span>
										<?=$class_field->input()?>
										<span class="input-group-prepend"><span class="input-group-text">::</span></span>
										<?=$method_field->input()?>
										<span class="input-group-append"><span class="input-group-text">( Jet\Mvc_Page $page, Jet\Mvc_Page_Content $content )</span></span>
									</div>
									<?=$class_field->row()->end()?>
							</div>
							<?php
							break;

					}?>

					<?php $showSaveButton_c()?>
				</div>
			</div>

		</div>

	<?php endforeach; ?>

<?php endforeach; ?>

<?php
$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);
$form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 6
]);
