<?php
namespace JetStudio;

use Jet\Tr;
use Jet\UI;

if( Pages::getCurrentLocale() ) {
	return;
}

$sites = Sites::getSites();
?>


<div style="padding-top: 10px;">
<?php foreach( $sites as $site ): ?>
	<h5><?=$site->getName()?></h5>
	<table class="table table-striped">
		<?php foreach( $site->getLocales() as $locale ):
			$link = Pages::getActionUrl('', [], Pages_Page::HOMEPAGE_ID, $locale, $site->getId());
			?>
		<tr>
			<td style="width: 30px"><a href="<?=$link?>"><?=UI::flag($locale)?></a></td>
			<td style="width: 250px;"><a href="<?=$link?>"><?=$locale->getName()?></a></td>
			<td><a href="<?=$link?>"><?=$locale->getName($locale)?></a></td>
			<td></td>
		</tr>
		<?php endforeach; ?>
	</table>
<?php endforeach; ?>
</div>