<?php
namespace JetStudio;

use Jet\Http_Request;
use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var Mvc_View $this
 */

$page = Pages::getCurrentPage();

if(!$page) {
	return;
}

$this->setVar('page', $page);
$what = Pages::whatToEdit();

$tabs = UI::tabs(
	[
		'main' => Tr::_('Main settings'),
		'content' => Tr::_('Content'),
		'static_content' => Tr::_('Static content'),
		'callback' => Tr::_('Callback')
	],
	function( $tab_id ) {
		return Http_Request::currentURI(['what'=>$tab_id]);
	},
	$what
);

?>
<div style="padding: 5px;">
	<?=Application::getGeneralView()->render('messages');?>
</div>

<div class="container-fluid main-col">

	<?=$tabs?>

	<div style="padding: 10px;">
		<?php require 'edit/'.$what.'.phtml'; ?>
	</div>
</div>


<?php if($what=='content'): ?>
<?=Application::getView()->render('add_content/dialog');?>
<?=Application::getView()->render('delete_content/dialog');?>
<?php endif; ?>