<?php
namespace JetApplicationModule\JetExample\AdminUI;
use Jet;
use Jet\Tr;
use Jet\Mvc_Page;
use Jet\Auth;
?>

<jetml_dojo_layout_container id="_jet_main_border_" gutters="false" style="width:100%;height:100%;">
	<jetml_dojo_layout_toolbar region="top">
		<jetml_dojo_form_button title="Articles" icon="module/JetExample.Articles/module" icon_size="large" onClick="Jet.modules.CURRENT_MODULE.openModule('JetExample.Articles');" />
		<jetml_dojo_form_button title="Images" icon="module/JetExample.Images/module" icon_size="large" onClick="Jet.modules.CURRENT_MODULE.openModule('JetExample.Images');" />
		<jetml_dojo_form_button title="Roles" icon="module/JetExample.AdminRoles/module" icon_size="large" onClick="Jet.modules.CURRENT_MODULE.openModule('JetExample.AdminRoles');" />
		<jetml_dojo_form_button title="Users" icon="module/JetExample.AdminUsers/module" icon_size="large" onClick="Jet.modules.CURRENT_MODULE.openModule('JetExample.AdminUsers');" />
		<jetml_dojo_form_button title="Test module" icon="module/JetExample.TestModule/module" icon_size="large" onClick="Jet.modules.CURRENT_MODULE.openModule('JetExample.TestModule');" />

        <div style="position: absolute;top:5px; right: 10px;">
            <?=Tr::_('Current user: %USERNAME%', array('USERNAME' => Auth::getCurrentUser()->getLogin()));?>
            <a href="<?=Mvc_Page::get('admin/logout')->getURL(); ?>" class="btn btn-default"><?=Tr::_('LOGOUT');?></a>
        </div>

	</jetml_dojo_layout_toolbar>

	<jetml_dojo_layout_tabs region="center" tabPosition="top" id="_jet_modules_tabs_">
	</jetml_dojo_layout_tabs>

</jetml_dojo_layout_container>
