<?php
namespace JetStudio;

use Jet\Tr;
use Jet\UI;


$menu = Menus::getCurrentMenu();
$form = $menu->getEditForm();

?>
<?= UI::button_save()->setOnClick( "$('#" . $form->getId() . "').submit()" ) ?>

<?= UI::button_create( Tr::_( 'Create a new menu item' ) )->setOnClick( 'Menus.createMenuItem.openDialog();' ) ?>

<?= UI::button_delete( Tr::_( 'Delete this menu' ) )->setOnClick( "$('#delete_menu_dialog').modal('show')" ) ?>
