<?php
use Jet\Form;
use Jet\Config;
use Jet\Config_Definition_Property_Abstract;
/**
 * @var Form $form
 */
$form = $this->form;

/**
 * @var Config $config
 */
$config = $this->config;

/**
 * @var Config_Definition_Property_Abstract[] $config_props
 */
$config_props = $config->getPropertiesDefinition();


$form->helper_getBasicHTML('div');

?>
<jet_form name="<?=$form->getName();?>">
	<jet_form_common_error_message class="formError"/>

    <?php foreach( $form->getFields() as $field ): ?>
        <div class="form-group">
            <jet_form_field_label name="<?=$field->getName()?>"/>
            <jet_form_field_error_msg name="<?=$field->getName()?>" class="form-error"/>
            <jet_form_field name="<?=$field->getName()?>" class="form-control"/>
        </div>
    <?php endforeach; ?>


    <?=\Jet\Installer::buttonNext();?>

</jet_form>