<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

?>
<table class="table table-striped">
	<tbody>
	<?php

	foreach( Sites::getSites() as $site ): ?>
		<tr>
			<td nowrap="" class="<?= ($site->getId() == Sites::getCurrentSiteId()) ? 'bg-info' : '' ?>">
				<div>
					<?php if( $site->getId() == Sites::getCurrentSiteId() ): ?>
						<strong><?= $site->getName() ?></strong>
					<?php else: ?>
						<a href="<?= Sites::getActionUrl( '', [], $site->getId() ) ?>"><?= $site->getName() ?></a>
					<?php endif; ?>
				</div>
				<div style="font-weight: bolder;font-size: 14px;" width="100%" nowrap="">
					<?php
					if( !$site->getIsActive() ):
						echo '<span class="badge badge-danger">';
						echo UI::icon( 'times' )->setTitle( Tr::_( 'Is not active' ) );
						echo '</span>';
					else:
						echo '<span class="badge badge-success">';
						echo UI::icon( 'check' )->setTitle( Tr::_( 'Is active' ) );
						echo '</span>';
					endif;
					if( $site->getIsDefault() ): echo '&nbsp;&nbsp;' . Tr::_( 'default' ); endif;
					if( $site->getIsSecret() ): echo '&nbsp;&nbsp;' . UI::icon( 'user-secret' )->setTitle( Tr::_( 'Is secret' ) ); endif;
					if( $site->getSSLRequired() ): echo '&nbsp;&nbsp;' . UI::icon( 'lock' )->setTitle( Tr::_( 'SSL required' ) ); endif;

					foreach( $site->getLocales() as $locale ) {
						$ld_data = $site->getLocalizedData( $locale );

						echo '&nbsp;&nbsp;&nbsp;&nbsp;';

						if( !$ld_data->getIsActive() ):
							echo '<span class="badge badge-danger">';
							echo UI::icon( 'times' )->setTitle( Tr::_( 'Locale is not active' ) );
							echo '&nbsp;&nbsp;';
							echo UI::flag( $locale );
						else:
							echo '<span class="badge badge-success">';
							echo UI::icon( 'check' )->setTitle( Tr::_( 'Locale is active' ) );
							echo '&nbsp;&nbsp;';
							echo UI::flag( $locale );
						endif;
						if( !$site->getSSLRequired() ):
							if( $ld_data->getSSLRequired() ): echo '&nbsp;&nbsp;' . UI::icon( 'lock' )->setTitle( Tr::_( 'Locale requires SSL' ) ); endif;
						endif;
						echo '</span>';


					}
					?>
				</div>
			</td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>

