<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

?>
<table class="table table-striped">
	<tbody>
		<?php

		foreach( Sites::getSites() as $site ): ?>
			<tr>
				<td nowrap="">
				<?php if($site->getId()==Sites::getCurrentSiteId()): ?>
					<strong><?=$site->getName()?></strong>
				<?php else: ?>
					<a href="<?=Sites::getActionUrl('', [], $site->getId())?>"><?=$site->getName()?></a>
				<?php endif; ?>
				</td>
				<td style="font-weight: bolder;font-size: 14px;" width="100%" nowrap="">
					<?php
					if(!$site->getIsActive()): echo '&nbsp;&nbsp;'.UI::icon('times')->setTitle(Tr::_('Is not active')); endif;
					if($site->getIsActive()): echo '&nbsp;&nbsp;'.UI::icon('check')->setTitle(Tr::_('Is active')); endif;
					if($site->getIsDefault()): echo '&nbsp;&nbsp;'.Tr::_('default'); endif;
					if($site->getIsSecret()): echo '&nbsp;&nbsp;'.UI::icon('user-secret')->setTitle(Tr::_('Is secret')); endif;
					if($site->getSSLRequired()): echo '&nbsp;&nbsp;'.UI::icon('lock')->setTitle(Tr::_('SSL required')); endif;

					foreach($site->getLocales() as $locale) {
						echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.UI::flag($locale);
						$ld_data = $site->getLocalizedData( $locale );

						if( $site->getIsActive() ) {
							if(!$ld_data->getIsActive()): echo '&nbsp;&nbsp;'.UI::icon('times')->setTitle(Tr::_('Locale is not active')); endif;
							if($ld_data->getIsActive()): echo '&nbsp;&nbsp;'.UI::icon('check')->setTitle(Tr::_('Locale is active')); endif;
						}

						if(!$site->getSSLRequired()) {
							if($ld_data->getSSLRequired()): echo '&nbsp;&nbsp;'.UI::icon('lock')->setTitle(Tr::_('Locale requires SSL')); endif;
						}

					}
					?>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

