<?php
namespace JetApplicationModule\JetExample\Content\Images;

use Jet\UI;
use Jet\Mvc_View;

/**
 * @var Mvc_View  $this
 * @var Gallery[] $galleries
 */

$galleries = $this->getRaw( 'galleries' );

?>

<div class="row">
	<?php foreach( $galleries as $gallery ): ?>
		<a href="<?=$gallery->getLocalized()->getURL()?>" class="img-thumbnail"
		   style="width: 120px;height: 120px;text-align: center;overflow: hidden;margin: 3px;border:none">
			<?=UI::icon( 'folder-o' )->setSize( 80 )?>
			<br/>
			<?=$gallery->getTitle();?>
		</a>
	<?php endforeach; ?>
</div>
