<?php
namespace JetApplicationModule\JetExample\Images;

use Jet\DataModel_Fetch_Object_Assoc;
use Jet\UI;
use Jet\Mvc_Layout;
use Jet\Mvc_View;
use Jet\Mvc;

/**
 * @var Mvc_View                               $this
 * @var DataModel_Fetch_Object_Assoc|Gallery[] $children
 * @var Gallery                                $gallery
 */
$children = $this->getRaw( 'children' );
$gallery = $this->getRaw( 'gallery' );

$images = [];
if( $gallery ) {
	$images = $gallery->getImages();
}

Mvc_Layout::getCurrentLayout()->requireCssFile(
	'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
);

?>

<div class="row">
	<?php foreach( $children as $gallery ): ?>
		<a href="<?=Mvc::getCurrentPage()->getURI( [ $gallery->getTitle() ] );?>" class="img-thumbnail"
		   style="width: 120px;height: 120px;text-align: center;overflow: hidden;margin: 3px;">
			<?=UI::icon( 'folder-o' )->setSize( 80 )?>
			<br/>
			<?=$gallery->getTitle();?>
		</a>
	<?php endforeach; ?>
</div>

<div class="row">
	<?php foreach( $images as $image ):
		/**
		 * @var Gallery_Image $image
		 */
		$thumbnail = $image->getThumbnail( 120, 120 );
		?>
		<div style="float:left;margin: 10px;overflow: hidden;">
			<div class="thumbnail" style="height: 155px;width: 200px;padding:10px;overflow: hidden">
				<a href="<?=$image->getURI();?>">
					<div
							style="width:180px;height:135px;background-position:center;background-repeat:no-repeat;background-image: url('<?=$image->getThumbnail( 180, 135 )->getURI();?>');"
					></div>
				</a>
			</div>
		</div>
	<?php endforeach; ?>
</div>