<jet_form name="Application_Config">
	<jet_form_common_error_message class="formError"/>
	<table>
		<tr>
			<td valign="top"><jet_form_field_label name="IO_dirs_chmod"/></td>
			<td><jet_form_field_error_msg name="IO_dirs_chmod" class="error"/><jet_form_field name="IO_dirs_chmod"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="IO_files_chmod"/></td>
			<td><jet_form_field_error_msg name="IO_files_chmod" class="error"/><jet_form_field name="IO_files_chmod"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="default_time_zone"/></td>
			<td><jet_form_field_error_msg name="default_time_zone" class="error"/><jet_form_field name="default_time_zone"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="request_hide_super_globals"/></td>
			<td><jet_form_field_error_msg name="request_hide_super_globals" class="error"/><jet_form_field name="request_hide_super_globals"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="project_name"/></td>
			<td><jet_form_field_error_msg name="project_name" class="error"/><jet_form_field name="project_name"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="project_identifier"/></td>
			<td><jet_form_field_error_msg name="project_identifier" class="error"/><jet_form_field name="project_identifier"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="project_contact_name"/></td>
			<td><jet_form_field_error_msg name="project_contact_name" class="error"/><jet_form_field name="project_contact_name"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="project_description"/></td>
			<td><jet_form_field_error_msg name="project_description" class="error"/><jet_form_field name="project_description"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="project_contact_email"/></td>
			<td><jet_form_field_error_msg name="project_contact_email" class="error"/><jet_form_field name="project_contact_email"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="project_contact_phone"/></td>
			<td><jet_form_field_error_msg name="project_contact_phone" class="error"/><jet_form_field name="project_contact_phone"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="error_handlers"/></td>
			<td><jet_form_field_error_msg name="error_handlers" class="error"/><jet_form_field name="error_handlers"/></td>
		</tr>
	</table>
	<input type="submit" value="<?=Jet\Tr::_("Next", array(), Jet\Translator::COMMON_NAMESPACE);?>"/>
</jet_form>