<?php
namespace JetStudio;
?>
<?php use Jet\Http_Request;use Jet\UI;use Jet\UI_badge;

if( DataModels::getCurrentWhatToEdit() == 'model' ):
	echo UI::badge(UI_badge::INFO,DataModels::getCurrentClass()->getFullClassName() )->addCustomCssStyle('font-size: 20px;');
else: ?>
	<a href="<?= Http_Request::currentURI( [], [
		'key',
		'property',
		'relation'
	] ) ?>" style="font-weight: bolder;font-size: 20px;"><?= DataModels::getCurrentClass()->getFullClassName() ?></a>
<?php endif; ?>
<br/>
<?php require 'item/properties.phtml' ?>
<?php require 'item/relations.phtml' ?>
<?php require 'item/keys.phtml' ?>
