<?php
namespace JetStudio;
?>
<?php use Jet\Http_Request;

if( DataModels::getCurrentWhatToEdit() == 'model' ): ?>
	<b class="badge badge-info" style="font-size: 20px;"><?= DataModels::getCurrentClass()->getFullClassName() ?></b>
<?php else: ?>
	<a href="<?= Http_Request::currentURI( [], [
		'key',
		'property',
		'relation'
	] ) ?>" style="font-weight: bolder;font-size: 20px;"><?= DataModels::getCurrentClass()->getFullClassName() ?></a>
<?php endif; ?>
<br/>
<table style="width: 100%;margin-top: 5px;">
	<tr style="background: transparent">
		<td style="border:none">
			<?php require 'item/properties.phtml' ?>
		</td>
	</tr>
	<tr style="background: transparent">
		<td style="border:none">
			<?php require 'item/relations.phtml' ?>
		</td>
	</tr>
	<tr style="background: transparent">
		<td style="border:none">
			<?php require 'item/keys.phtml' ?>
		</td>
	</tr>
</table>


