<?php
namespace JetApplication;

use Jet\MVC_View;
use Jet\SysConf_URI;

/**
 * @var MVC_View $this
 * @var Auth_Administrator_User $user
 */

$user = $this->getRaw( 'user' );
?>
<img src="<?= SysConf_URI::getImages() ?>email_images/email_header.jpg"/>

<h1>Welcome to the system, Administrator!</h1>

<p>This is your user account details:</p>

<table>
	<tr>
		<td>Username:</td>
		<td><?= $user->getUsername() ?></td>
	</tr>
	<tr>
		<td>Password:</td>
		<td><?= $this->getString( 'password' ) ?></td>
	</tr>
	<tr>
		<td>Your name:</td>
		<td><?= $user->getName() ?></td>
	</tr>
	<tr>
		<td>Your e-mail:</td>
		<td><?= $user->getEmail() ?></td>
	</tr>
</table>

<p>Please change your password after sign in</p>

<p>We wish you a nice day</p>