<?php
/**
 * @var Jet\Form $form
 */
$form = $this->form;

?>
<jet_form name="<?=$form->getName();?>">
	<jet_form_common_error_message class="formError"/>

	<div class="form-group checkbox">
		<jet_form_field_label name="cache_enabled"/>
		<jet_form_field_error_msg name="cache_enabled" class="form-error"/>
		<jet_form_field name="cache_enabled"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="cache_backend_type"/>
		<jet_form_field_error_msg name="cache_backend_type" class="form-error"/>
		<jet_form_field name="cache_backend_type" class="form-control"/>
	</div>

	<input type="submit" value="<?=Jet\Tr::_('Next', [], Jet\Translator::COMMON_NAMESPACE);?>" class="btn btn-primary"/>
</jet_form>