<?php

namespace JetApplicationModule\Content\Images;

use Jet\Mvc_View;
use Jet\UI;
use Jet\Tr;
use Jet\Mvc_Page;

/**
 * @var Mvc_View $this
 */

$dialog = UI::dialog( 'dialog_select_image', Tr::_( 'Select image' ), 1100 );
?>
	<script type="text/javascript">
		const dialog_select_image = {
			open: function (on_response) {
				dialog_select_image.on_response = on_response;
			},

			close: function () {
				$('#dialog_select_image').modal('hide');
			},

			response: function () {
				dialog_select_image.on_response();
				dialog_select_image.close();
			}
		};
	</script>


<?= $dialog->start() ?>
	<div style="display: inline-block;height: 500px">
		<iframe
				src="<?= Mvc_Page::get( 'dialog-select-image' )->getURLPath() ?>"
				id="dialog_select_image_frame"
				frameborder="none"
				style="width: 750px;height: 500px;"
		></iframe>
	</div>
	<div style="display: inline-block;overflow: auto;width: 300px;height: 500px" id="dialog_select_image_selected_area">
	</div>
<?= $dialog->footer() ?>

	<button type="button"
	        id="dialog_select_image_select_button"
	        class="btn btn-primary btn-sm"
	        onclick="dialog_select_image.response()"
	><?= Tr::_( 'Select image' ) ?></button>

<?= $dialog->end() ?>