<?php
namespace JetApplicationModule\JetExample\UIElements;
use Jet;

/**
 * @var Tree $tree
 */
$tree = $this->tree;

$selected_ID = $tree->getSelectedID();

$path = ($selected_ID) ? $tree->getData()->getPath( $selected_ID ) : array('_root_');

$images_URI = $this->images_uri;
?>

<table>
	<?php foreach( $tree->getData() as $node ):

		/**
		 * @var Jet\Data_Tree_Node $node
		 */
		if(
			!$tree->getShowAll() &&
			!(
				in_array($node->getParentID(), $path) ||
				in_array($node->getID(), $path)
			)
		) {
				continue;
		}

		$opened = in_array($node->getID(), $path);
		$selected = ($selected_ID==$node->getID());

		$callback = $tree->getNormalDisplayCallback();
		if($selected) {
			$callback = $tree->getSelectedDisplayCallback();
		} else if( $opened ) {
			$callback = $tree->getOpenedDisplayCallback();
		}

		?>
		<tr><td>
				<table>
					<tr>
					<?php if($node->getHasChildren()): ?>
						<?php if($opened): ?>
							<td style="padding-left: <?=$node->getDepth()*22;?>px;padding-right: 5px;padding-top: 2px;padding-bottom: 2px;"><img src="<?=$images_URI;?>folder_open.png"></td>
						<?php else: ?>
							<td style="padding-left: <?=$node->getDepth()*22;?>px;padding-right: 5px;padding-top: 2px;padding-bottom: 2px;"><img src="<?=$images_URI;?>folder.png"></td>
						<?php endif;?>
					<?php else: ?>
							<?php if($opened): ?>
								<td style="padding-left: <?=$node->getDepth()*22;?>px;padding-right: 5px;padding-top: 2px;padding-bottom: 2px;"><img src="<?=$images_URI;?>file.png"></td>
							<?php else: ?>
								<td style="padding-left: <?=$node->getDepth()*22;?>px;padding-right: 5px;padding-top: 2px;padding-bottom: 2px;"><img src="<?=$images_URI;?>file.png"></td>
							<?php endif;?>
					<?php endif; ?>
						<td>
							<?=$callback($node, $node->getData());?>
						</td>
					</tr>

				</table>
			</td></tr>

	<?php endforeach; ?>
</table>

