<?php
namespace JetApplication;

use Jet\Mvc_View;
use Jet\Form;

/**
 * @var Mvc_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );
$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );

?>
<?=$form->start()?>
<?=$form->message()?>

<?=$form->field( 'username' )?>
<?=$form->field( 'password' )?>
<?=$form->field( 'dbname' )?>
<?=$form->field( 'host' )?>
<?=$form->field( 'port' )?>
<?=$form->field( 'unix_socket' )?>


<?=Installer::buttonNext();?>

<?=$form->end()?>

