<?php
namespace JetApplicationModule\JetExample\TestModule;
use Jet;

/**
 * @var Jet\Form $form
 */
$form = $this->form;
?>
<jetml_layout_container gutters="true">
	<jetml_layout_container region="left" splitter="true" style="width:200px">
		<jetml_layout_toolbar region="top">

			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.treeTest_openByID();" title="Open by ID"/>
			<jetml_trash_button trash_id="tree_trash"/>

			<jetml_trash_dialog trash_id="tree_trash">
			</jetml_trash_dialog>
		</jetml_layout_toolbar>
		<jetml_layout_pane region="center" id="test_tree_area" style="padding:0px;">
		</jetml_layout_pane>
		<jetml_layout_toolbar region="bottom">
			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.treeTest_reload();" icon="reload"/>
			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.treeTest_expand();" icon="expand"/>
			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.treeTest_collapse();" icon="collapse"/>
		</jetml_layout_toolbar>
	</jetml_layout_container>

	<jetml_layout_pane Id = "testpane" region="center">
		<div dojoType="dijit.ColorPalette" onChange="alert(this.value);" palette="3x4">
		</div>

			<table>
				<tr>
					<td>
						<jetml_data id="test_form_fields_definition"><?=json_encode($form->getFields());?></jetml_data>
						<?=$form->helper_getBasicHTML(); ?>
					</td>
					<td>
						<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.formTest_getData();" title="Get form data"/>
						<br/>
						<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.formTest_showErrors();" title="Show form errors"/>
						<br/>
						<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.formTest_hideErrors();" title="Hide form errors"/>
						<br/>
						<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.formTest_disable();" title="Disable form"/>
						<br/>
						<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.formTest_enable();" title="Enable form"/>
					</td>
				</tr>
			</table>

	</jetml_layout_pane>
</jetml_layout_container>