<?php
namespace Jet;
/**
 * @var Mvc_View $this
 * @var Mvc_Page[] $pages
 */
$pages = $this->getRaw('site_tree_current');


$show_menu = function( $pages ) use (&$show_menu) {
	/**
	 * @var Mvc_Page_Interface[] $pages
	 */

	if(!$pages) return;

	$current_page_key = Mvc::getCurrentPage()->getPageKey();
	?>
	<ul>
		<?php foreach($pages as $page):
			if($page->getIsAdminUI()) {
				continue;
			}
			?>
			<li>
				<?php if($current_page_key==$page->getPageKey() ): ?>
					<i><?=$page->getMenuTitle(); ?></i>
				<?php else: ?>
					<a href="<?=$page->getURL(); ?>"><?=$page->getMenuTitle(); ?></a>
				<?php endif; ?>
				<?php $show_menu($page->getChildren()); ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php

};
?>

<div style="background-color: #c9c9c9">
<?php foreach( Mvc::getCurrentLocalesList() as $locale ): ?>
	<div style="display: inline-block;padding: 3px;">
		<?php if($locale->toString()==Mvc::getCurrentLocale()->toString()): ?>
			<strong class="btn btn-primary btn-xs">
				<img src="//lipis.github.io/flag-icon-css/flags/4x3/<?=strtolower($locale->getRegion())?>.svg" style="width: 20px;height: auto"/>
				<?=$locale->getLanguageName( $locale )?>
			</strong>
		<?php else:
			$equal_page = Mvc_Page::get(null, $locale);
			if(!$equal_page) {
				$equal_page = Mvc_Page::get( Mvc_Page::HOMEPAGE_ID, $locale );
			}
			?>
			<a href="<?=$equal_page->getURL()?>" class="btn btn-default btn-xs">
				<img src="//lipis.github.io/flag-icon-css/flags/4x3/<?=strtolower($locale->getRegion())?>.svg" style="width: 20px;height: auto"/>
				<?=$locale->getLanguageName( $locale )?>
			</a>
		<?php endif; ?>
	</div>
<?php endforeach; ?>
</div>


<?php $show_menu($pages); ?>

