<?php
namespace Jet;


$show_menu = function( $pages ) use (&$show_menu) {
	/**
	 * @var Mvc_Page_Interface[] $pages
	 */

	if(!$pages) return;

	$current_page_ID = Mvc::getCurrentPage()->getID()->toString();
	?>
	<ul>
		<?php foreach($pages as $page):
			if($page->getIsAdminUI()) {
				continue;
			}
			?>
			<li>
				<?php if($current_page_ID==$page->getID()->toString() ): ?>
					<i><?=$page->getMenuTitle(); ?></i>
				<?php else: ?>
					<a href="<?=$page->getURL(); ?>"><?=$page->getMenuTitle(); ?></a>
				<?php endif; ?>
				<?php $show_menu($page->getChildren()); ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php

};
?>

<div style="margin:5px;border-top: 1px solid black;">
	<strong>Site map [current locale: <?=Mvc::getCurrentLocale();?>]:</strong>
	<?php $show_menu( $this->site_tree_current ); ?>
</div>


<?php foreach( Mvc::getCurrentLocalesList() as $locale ):
    if($locale==Mvc::getCurrentLocale()) {
        continue;
    }
    $home_page = Mvc_Page::get( Mvc_Page::HOMEPAGE_ID, $locale );
	?>
<div style="margin:5px;border-top: 1px solid black;">
	<strong>Site map [<?php echo $locale;?>]:</strong>
	<?php $show_menu( [$home_page] ); ?>
</div>
<?php endforeach; ?>
