<?php
if(!function_exists('showMenu')) {
	function showMenu( $pages ){
		if(!$pages) return;
		if($pages instanceof Jet\Data_Tree) {
			$pages = array( $pages->getRootNode() );
		}

		$current_page_ID = (string)Jet\Mvc::getCurrentPage()->getID();
		?>
	<ul>
		<?php foreach($pages as $page):
		/**
		 * @var Jet\Data_Tree_Node $page
		 */
		$d = $page->getData();

		if($d['is_admin_UI']) {
			continue;
		}
		?>
		<li>
			<?php if($current_page_ID==$d['ID'].':'.$d['site_ID'].':'.$d['locale']): ?>
			<i><?=$d['menu_title']; ?></i>
			<?php else: ?>
			<a href="<?=Jet\Mvc_Pages::getURI($d['ID'], $d['locale'], $d['site_ID']); ?>"><?=$d['menu_title']; ?></a>
			<?php endif; ?>
			<?php showMenu($page->getChildren()); ?>
		</li>
		<?php endforeach; ?>
	</ul>
	<?php
	}
}
?>

<div style="margin:5px;padding:5px;border-top: 1px solid black;">
	<strong>Site map [current locale: <?=Jet\Mvc::getCurrentLocale();?>]:</strong>
	<?php showMenu( $this->site_tree_current ); ?>
</div>


<?php foreach( Jet\Mvc::getCurrentLocalesList() as $locale ):
	$key = 'site_tree_'.$locale;
	?>
<div style="margin:5px;padding:5px;border-top: 1px solid black;">
	<strong>Site map [<?php echo $locale;?>]:</strong>
	<?php showMenu( $this->{$key} ); ?>
</div>
<?php endforeach; ?>
