<?php
use Jet\Mvc;
use Jet\Mvc_View;
use Jet\Mvc_Page;
use Jet\UI;

/**
 * @var Mvc_View   $this
 * @var Mvc_Page[] $pages
 */
$pages = $this->getRaw( 'site_tree_current' );


$show_menu = function( $pages ) use ( &$show_menu ) {
	/**
	 * @var Mvc_Page[] $pages
	 */

	if( !$pages ) return;

	$current_page_key = Mvc::getCurrentPage()->getKey();
	?>
	<ul>
		<?php foreach( $pages as $page ):
			if( 
				!$page->getIsActive() ||
				$page->getIsAdminUI() ||
				!$page->getIsSecretPage() ||
				!$page->getAccessAllowed()
			) {
				continue;
			}
			?>
			<li>
				<?php if( $current_page_key==$page->getKey() ): ?>
					<i><?=$page->getMenuTitle();?></i>
				<?php else: ?>
					<a href="<?=$page->getURL();?>"><?=$page->getMenuTitle();?></a>
				<?php endif; ?>
				<?php $show_menu( $page->getChildren() ); ?>
			</li>
		<?php endforeach; ?>
	</ul>
	<?php

};


$tabs = [];
foreach( Mvc::getCurrentSite()->getLocales() as $locale ) {
	$tabs[$locale->toString()] = UI::flag( $locale ).'&nbsp;'.$locale->getLanguageName( $locale );
}

$tabs = UI::tabs(
	$tabs,
	function( $locale ) {
		$equal_page = Mvc_Page::get( null, $locale );

		if( !$equal_page ) {
			$equal_page = Mvc_Page::get( Mvc_Page::HOMEPAGE_ID, $locale );
		}

		return $equal_page->getURL();

	},
	function() {
		return Mvc::getCurrentLocale()->toString();
	}
);
?>

<?=$tabs?>



<?php $show_menu( $pages ); ?>
