<?php
namespace JetApplicationModule\JetExample\TestModule;
use Jet;

/**
 * @var Jet\Form $form
 */
$form = $this->form;

/**
 * @var Jet\Mvc_View $view
 */
$view = $this;
?>
<p>
	M1: Test Action 2<br>
	<b>Parameter 1:</b> <?php echo $this->parameter_1; ?><br>
	<b>Parameter 2:</b> <?php echo $this->parameter_2; ?>
</p>

<p>
	<?=$form->helper_getBasicHTML(); ?>
	<?php if($view->varExists('form_data')): ?>
		<table>
			<?php foreach($form->getValues() as $k=>$v): ?>
			<tr>
				<td><?=$k;?>:</td>
				<td><?=is_array($v) ? implode(',', $v): $v;?></td>
			</tr>
			<?php endforeach; ?>
		</table>
	<?php endif; ?>
</p>
