<?php
use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form $form
 */
$form = $this->getRaw('form');
?>
<p>
	M1: Test Action 2<br>
	<b>Parameter 1:</b> <?=$this->getString('parameter_1'); ?><br>
	<b>Parameter 2:</b> <?=$this->getString('parameter_2'); ?>
</p>

<p>
	<?php
	echo $form->start();
	foreach($form->getFields() as $field) {
		echo $field;
	}
	echo $form->end();
	?>

	<?php if($this->varExists('form_data')): ?>
		<table>
			<?php foreach($form->getValues() as $k=>$v): ?>
			<tr>
				<td><?=$k;?>:</td>
				<td><?=is_array($v) ? implode(',', $v): $v;?></td>
			</tr>
			<?php endforeach; ?>
		</table>
	<?php endif; ?>

</p>
