<?php
namespace JetApplicationModule\Jet\AdminPages;
use Jet;

/**
 * @var Jet\Form $form
 */
$form = $this->form;
?>
<jetml_layout_container gutters="true">
	<jetml_layout_container region="left" splitter="true" style="width:200px">
		<jetml_layout_toolbar region="top">

			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.add();" title="New page" icon="add"/>
			<jetml_trash_button id="pages_trash"/>

			<jetml_trash_dialog id="pages_trash">
			</jetml_trash_dialog>
		</jetml_layout_toolbar>
		<jetml_layout_pane region="center" id="pages_tree_area" style="padding:0px;">
		</jetml_layout_pane>
		<jetml_layout_toolbar region="bottom">
			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.treereload();" icon="reload"/>
			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.treeExpand();" icon="expand"/>
			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.treeCollapse();" icon="collapse"/>
		</jetml_layout_toolbar>
	</jetml_layout_container>
	<jetml_layout_container region="center" gutters="false">
		<jetml_layout_toolbar region="top">
		</jetml_layout_toolbar>
		<jetml_layout_tabs region="center" id="pages_edit_area" style="visibility:hidden">
			<jetml_layout_tabs_tab region="center" title="Parameters" gutters="false">
				<jetml_layout_toolbar region="top">
					<jetml_form_button_save onClick="Jet.modules.CURRENT_MODULE.save();" id="page_save"/>
				</jetml_layout_toolbar>
				<jetml_layout_pane region="center">
					<jetml_data id="page_form_fields_definition"><?=json_encode($form->getFields());?></jetml_data>

					<jet_form name="<?=$form->getName();?>">
						<jet_form_common_error_message class="formError"/>
						<table>
							<jet_form_field name="ID"/>
							<jet_form_field name="site_ID"/>
							<jet_form_field name="locale"/>
							<jet_form_field name="parent_ID" style="display:none"/>
							<jet_form_field name="is_admin_UI" style="display:none"/>
							<jet_form_field name="force_UI_manager_module_name" style="display:none"/>

							<tr>
								<td valign="top"><jet_form_field_label name="name"/></td>
								<td><jet_form_field_error_msg name="name" class="error"/><jet_form_field name="name"/></td>
							</tr>
							<tr>
								<td valign="top"><jet_form_field_label name="authentication_required"/></td>
								<td><jet_form_field_error_msg name="authentication_required" class="error"/><jet_form_field name="authentication_required"/></td>
							</tr>
							<tr>
								<td valign="top"><jet_form_field_label name="SSL_required"/></td>
								<td><jet_form_field_error_msg name="SSL_required" class="error"/><jet_form_field name="SSL_required"/></td>
							</tr>

							<tr>
								<td valign="top"><jet_form_field_label name="title"/></td>
								<td><jet_form_field_error_msg name="title" class="error"/><jet_form_field name="title"/></td>
							</tr>
							<tr>
								<td valign="top"><jet_form_field_label name="menu_title"/></td>
								<td><jet_form_field_error_msg name="menu_title" class="error"/><jet_form_field name="menu_title"/></td>
							</tr>
							<tr>
								<td valign="top"><jet_form_field_label name="breadcrumb_title"/></td>
								<td><jet_form_field_error_msg name="breadcrumb_title" class="error"/><jet_form_field name="breadcrumb_title"/></td>
							</tr>
							<tr>
								<td valign="top"><jet_form_field_label name="URL_fragment"/></td>
								<td><jet_form_field_error_msg name="URL_fragment" class="error"/><jet_form_field name="URL_fragment"/></td>
							</tr>
							<tr>
								<td valign="top"><jet_form_field_label name="layout"/></td>
								<td><jet_form_field_error_msg name="layout" class="error"/><jet_form_field name="layout"/></td>
							</tr>
							<tr>
								<td valign="top"><jet_form_field_label name="headers_suffix"/></td>
								<td><jet_form_field_error_msg name="headers_suffix" class="error"/><jet_form_field name="headers_suffix"/></td>
							</tr>
							<tr>
								<td valign="top"><jet_form_field_label name="body_prefix"/></td>
								<td><jet_form_field_error_msg name="body_prefix" class="error"/><jet_form_field name="body_prefix"/></td>
							</tr>
							<tr>
								<td valign="top"><jet_form_field_label name="body_suffix"/></td>
								<td><jet_form_field_error_msg name="body_suffix" class="error"/><jet_form_field name="body_suffix"/></td>
							</tr>
						</table>
					</jet_form>
				</jetml_layout_pane>
			</jetml_layout_tabs_tab>
			<jetml_layout_pane region="center" title="Contents">
				XXX
			</jetml_layout_pane>
			<jetml_layout_pane region="center" title="Preview">
				XXX
			</jetml_layout_pane>
		</jetml_layout_tabs>
	</jetml_layout_container>

</jetml_layout_container>