<?php
use Jet\UI;
use Jet\Locale;
use JetApplication\Application_Admin;
use Jet\Http_Request;
?>
<div style="position: absolute;top:15px; right: 15px;">
	<?php foreach( Application_Admin::getAvlLovales() as $locale ): ?>
		<?php if( $locale->toString() == Locale::getCurrentLocale()->toString() ): ?>
			<?= UI::flag( $locale ) ?>
		<?php else: ?>
			<a href="<?=Http_Request::currentURI(['set_locale'=>$locale->toString()])?>"><?= UI::flag( $locale ) ?></a>
		<?php endif; ?>
	<?php endforeach; ?>
</div>
