<?php

use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use Jet\MVC_View;
use Jet\Form;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form $form
 */
$form = $this->getRaw( 'form' );

$form->renderer()->setDefaultLabelWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 2] );
$form->renderer()->setDefaultFieldWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 10] );
?>

<div class="col-md-6 offset-md-3 col-sm-8 offset-sm-2">
	<div class="card" style="margin-top: 40px;">
		<h5 class="card-header"><?= Tr::_( 'Please change your password' ) ?></h5>
		<?= $form->start() ?>
		<div class="card-body">
	
			<?= $form->field( 'current_password' ) ?>
			<?= $form->field( 'password' ) ?>
			<?= $form->field( 'password_check' ) ?>
	
			<div class="text-right">
				<?= UI::button( Tr::_( 'Change password' ) )->setClass( UI_button::CLASS_PRIMARY )->setType(UI_button::TYPE_SUBMIT) ?>
			</div>
		</div>
		<?= $form->end() ?>
	</div>
</div>
