<?php

use Jet\Tr;
use Jet\UI;
use Jet\UI_icon;

?>

<div class="card">
	<h5 class="card-header">
		<?= Tr::_( 'Account is not activated' ) ?>
		<?php require '_language_select.phtml'; ?>
	</h5>
	<div class="card-body">
		<div style="display: flex; align-items: center;gap: 10px;">
			<div>
				<?= UI::icon( 'times-circle' )->setSize( UI_icon::SIZE_EXTRA_LARGE ) ?>
			</div>
			<div>
				<?= Tr::_( '<b>Your account is not activated!</b><br/>Please contact your system administrator.' ); ?>
			</div>
		</div>

		<div style="padding-top: 10px">
			<a href="?logout" class="btn btn-light"><?= Tr::_( 'Logout' ); ?></a>
		</div>
	</div>
</div>
