<?php

use Jet\Form;
use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Form $form
 */

$form = $this->getRaw( 'form' );

$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 3
] );
$form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 9
]);
//$form->setIsReadonly();
?>
<?= $form->start() ?>

<?php foreach( $form->getFields() as $field ) echo $field; ?>

<?php if( !$form->getIsReadonly() ): ?>
	<div class="row">
		<div class="offset-md-3">
			<input type="submit" class="btn btn-light" value="<?= Tr::_( 'Submit' ) ?>"/>

			<input type="button" class="btn btn-light" value="<?= Tr::_( 'Submit (AJAX)' ) ?>"
			       onclick="testSendForm.submit('<?= $form->getId() ?>')"/>
		</div>
	</div>
<?php endif; ?>

<?= $form->end() ?>