<?php
use Jet\Form;
use Jet\Tr;
use Jet\Form_Field_FileImage;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form   $form
 */

$form = $this->getRaw( 'form' );

//$form->setIsReadonly();
?>
<?=$form->start()?>

	<?=$form->message()?>

	<?php foreach( $form->getFields() as $field ) echo $field; ?>

	<?php if( $form->getIsValid() ): ?>
	<div class="row">
		<div class="col-md-offset-4">
			<hr>
			<?=Tr::_( 'Form sent:' )?>

			<?php if( $form->getName()=='upload_image_form' ):
				$image_field = $form->getField( 'upload_image' );
				/**
				 * @var Form_Field_FileImage $image_field
				 */
				?>
				<img src="<?=JET_URI_PUBLIC?>test_uploads/<?=$image_field->getFileName()?>">
			<?php else: ?>
				<table class="table table-bordered">
					<?php foreach( $form->getValues() as $k => $v ): ?>
						<tr>
							<td><?=$k?>:</td>
							<td><?=is_array( $v ) ? implode( ',', $v ) : $v?></td>
						</tr>
					<?php endforeach; ?>
				</table>
			<?php endif; ?>
		</div>
	</div>
	<?php endif; ?>


	<?php if( !$form->getIsReadonly() ):?>
		<div class="row">
			<div class="col-md-offset-4">
				<input type="submit" class="btn btn-light" value="<?=Tr::_( 'Submit' )?>"/>

				<input type="button" class="btn btn-light" value="<?=Tr::_( 'Submit (AJAX)' )?>" onclick="testSendForm.submit('<?=$form->getId()?>')"/>
			</div>
		</div>
	<?php endif; ?>


<?=$form->end()?>