<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<jet_layout_part name="header"/>
	<style type="text/css">
		html, body, #main{
			width: 100%;
			height: 100%;
			overflow: hidden;
			padding: 0 0 0 0;
			margin: 0 0 0 0;
		}
	</style>
</head>
<body class="%DOJO_THEME%">
	<jet_layout_body_prefix/>

	<jet_layout_part name="dialogs"/>


	<?php /*
	<div>
	User: <?=Jet\Auth::getCurrentUser()->getLogin(); ?>
		[<a href="?logout">LOGOUT</a>]
	</div>
 */ ?>

	<jet_layout_main_position/>
	<jet_layout_body_suffix/>
</body>
</html>