<?php
namespace JetApplicationModule\JetExample\Articles;
use Jet;
/**
 * @var Article[] $articles_list
 */
$articles_list = $this->articles_list;
/**
 * @var Jet\Data_Paginator $paginator
 */
$paginator = $this->paginator;
?>

<?php foreach( $articles_list as $article ): ?>
<div>
	<a href="<?=$article->getURIFragment();?>"><?=$article->getTitle();?></a>&nbsp;&nbsp;<?=Jet\Locale::dateAndTime($article->getDateTime());?>
	<p><?=$article->getAnnotation();?></p>
</div>
<hr/>
<?php endforeach; ?>

<table>
	<tr>
		<?php if( ($p_URL=$paginator->getPrevPageURL()) ): ?>
		<td><a href="<?=$p_URL; ?>">&lt;</a></td>
		<?php endif ?>
		<td width="100%" align="center">
			<?php foreach($paginator->getPagesURL() as $p_no => $p_URL): ?>
			<?php if($p_no==$paginator->getCurrentPageNo()): ?>
				<strong><?php echo $p_no; ?></strong>
				<?php else: ?>
				<a href="<?=$p_URL; ?>"><?=$p_no; ?></a>
				<?php endif; ?>
			<?php endforeach; ?>
		</td>
		<?php if( ($p_URL=$paginator->getNextPageURL()) ): ?>
		<td><a href="<?=$p_URL; ?>">&gt;</a></td>
		<?php endif ?>

		<td nowrap>[<?=$paginator->getShowFrom();?>-<?=$paginator->getShowTo();?>/<?=$paginator->getDataItemsCount();?>]</td>
	</tr>
</table>
