<?php

use Jet\Mvc_View;
use Jet\Form_Field_RegistrationPassword;

/**
 * @var Mvc_View $this
 * @var Form_Field_RegistrationPassword $f
 */
$f = $this->getRaw( 'field' );

echo $f->row()->start()
	. $f->label()
	. $f->container()->start()
		. $f->input()
		. $f->error()
	. $f->container()->end()
. $f->row()->end()
. $f->row()->start()
	. $f->label_confirmation()
	. $f->container()->start()
		. $f->input_confirmation()
	. $f->container()->end()
. $f->row()->end();