<?php
namespace JetStudioModule\ApplicationModules;

$form = Main::getCurrentModule()->getPages()->getPageCreateForm();


$form->field( 'page_name' )->input()->addJsAction( 'onkeyup', 'Modules.editModule.addPage.generateId(this.value);' );
$form->field( 'base_id' )->input()->addJsAction( 'onchange', 'Modules.editModule.addPage.toggleFields(this.options[this.selectedIndex].value);' );

echo $form->start();

echo $form->getCommonMessage();
?>
<div class="form-fields" style="grid-template-columns: 20% 1fr;">
<?php
echo $form->field( 'base_id' );
echo $form->field( 'page_name' );
echo $form->field( 'page_id' );
?>
</div>
<?php
echo $form->end();
