<?php
namespace JetStudio;

use Jet\Tr;
use Jet\UI;
use Jet\Mvc_View;
use Jet\UI_button;

/**
 * @var Mvc_View $this
 * @var Modules_Module_Controller $controller
 */

$current = Modules::getCurrentModule();

if(
	!$current ||
	!$current->getControllers()
) {
	return;
}


$controller = $this->getRaw('controller');

?>
<table style="width: 100%">
	<tr>
		<td>
			<b style="font-size: 16px"><?=$controller->getName()?></b>
			<span style="font-size: 10px"> extends <?=$controller->getExtendsClass()?></span>
		</td>
		<td align="right">
			<?=UI::button_delete(Tr::_('Delete this controller'))->setOnclick("$('#delete_controller_dialog_{$controller->getInternalId()}').modal('show');")->setSize(UI_button::SIZE_EXTRA_SMALL)?>
		</td>
	</tr>
</table>
