<?php
namespace JetStudio;

use Jet\Application_Modules;
use Jet\Tr;
use Jet\UI;
use Jet\Form;
use Jet\Mvc_View;
use Jet\UI_button;

/**
 * @var Mvc_View $this
 * @var Modules_Module_Controller $controller
 */

$current = Modules::getCurrentModule();

if(
	!$current ||
	!$current->getControllers()
) {
	return;
}


$controller = $this->getRaw('controller');

$form = $controller->getEditForm( $current );

$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);
$form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 6
]);

$form->setAction( Modules::getActionUrl('controller/edit', [
	'controller' => $controller->getInternalId()
]) );

?>
<?=$form->start()?>
<?=$form->field('controller_name')?>
<?=$form->field('extends_class')?>

<div class="row">
	<div class="col-md-2">
	</div>
	<div class="col-md-6" align="right">
		<?=UI::button_save()->setOnclick("JetStudio.Modules.editModule.editController.send('".$form->getId()."')")->setType('button')?>
	</div>
</div>

<legend><?=Tr::_('Actions')?></legend>
<table>
	<thead>
	<tr>
		<th style="padding-left: 40px"><?=Tr::_('Controller action')?></th>
		<th style="padding-left: 40px"><?=Tr::_('ACL action')?></th>
	</tr>
	</thead>
	<tbody>
	<?php for( $m=0;$m<Modules_Module_Controller::MAX_ACTIONS_COUNT;$m++ ):
		$a_f_prefix = '/actions/'.$m;

		if(!$form->fieldExists( $a_f_prefix.'/controller_action')) {
			break;
		}
		$controller_action = $form->field( $a_f_prefix.'/controller_action' );
		$controller_action->input()->addCustomCssStyle('width:300px;');
		$ACL_action = $form->field( $a_f_prefix.'/ACL_action' );
		$ACL_action->input()->addCustomCssStyle('width:300px;');

		?>
		<tr>
			<td><?=$controller_action?></td>
			<td><?=$ACL_action?></td>
		</tr>
	<?php endfor; ?>
	<tr>
		<td>

		</td>
		<td align="right">
			<?=UI::button_save()->setOnclick("JetStudio.Modules.editModule.editController.send('".$form->getId()."')")->setType('button')?>
		</td>
	</tr>

	</tbody>
</table>
<?=$form->end()?>