<?php
/**
 *
 * @copyright Copyright (c) 2011-2021 Miroslav Marek <mirek.marek@web-jet.cz>
 * @license http://www.php-jet.net/license/license.txt
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */

use Jet\Debug_Profiler_Run;
use Jet\SysConf_Jet;


/**
 * @var Debug_Profiler_Run $run
 * @var string $URL
 */

$root_block = $run->getBlocks()[0];
$duration = round($root_block->getDuration()*1000, 2);
$memory = $root_block->getMemoryUsageDiff()/1024;

$show_cache_state = function( string $title, bool $state ) {
	?>
	<table>
		<tr>
			<td style="padding-right: 5px;padding-left: 5px;"><?=$title?></td>
			<?php if($state): ?>
				<td style="background-color: #009900; color: #0f0f0f;padding-left: 10px; padding-right: 10px;font-weight: bolder;">YES</td>
			<?php else: ?>
				<td style="background-color: #990000; color: #b9b9b9;padding-left: 10px; padding-right: 10px;font-weight: bolder;">NO</td>
			<?php endif; ?>
		</tr>
	</table>
	<?php
};

?>
<div id="__profiler__" style="position: fixed; bottom: 0px;left: 0px;background-color: #c9c9c9;padding: 5px;font-family: Helvetica, Arial, sans-serif;border: 1px inset #ffffff;font-size:14px;">
	<table>
		<tr>
			<td style="padding-right: 20px;">
				<span onclick="document.getElementById('__profiler__').style.display='none';">X</span>
			</td>
			<td style="padding-right: 20px;">
				<a href="<?=$URL?>" target="_blank" style="text-decoration: underline;font-weight: bolder;color: #000000;">PROFILER</a>
			</td>
			<td style="padding-right: 20px;">
				Duration: <b><?=$duration?> ms</b>
			</td>
			<td style="padding-right: 20px;">
				Memory: <b><?=round($memory, 3)?> KiB</b>
			</td>
			<td style="padding-right: 20px;">
				SQL queries count: <b><?=count($run->getSqlQueries())?></b>
			</td>
			<td><b>Cache state:</b></td>
			<td><?php $show_cache_state('Autoloader', SysConf_Jet::isCacheAutoloaderEnabled() ); ?></td>
			<td><?php $show_cache_state('MVC', SysConf_Jet::isCacheMvcEnabled() ); ?></td>
			<td style="padding-left: 20px"><b>Packager state:</b></td>
			<td><?php $show_cache_state('JS', SysConf_Jet::isJSPackagerEnabled() ); ?></td>
			<td><?php $show_cache_state('CSS', SysConf_Jet::isCSSPackagerEnabled() ); ?></td>
		</tr>
	</table>


</div>
