<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

$site = Sites::getCurrentSite();

if($site) {
	return;
}
?>
<div class="toolbar" id="main-toolbar">
	<?=UI::button_create(Tr::_('Create new site'))->setOnclick('JetStudio.Sites.createSite.openDialog()')?>
</div>
<div class="container-fluid" id="main-edit-area">
	<?=Application::getGeneralView()->render('messages');?>
	<?=Application::getView()->render('sites_list');?>
</div>
