<?php
namespace JetApplicationModule\Jet\Images;
use Jet;

/**
 * @var Jet\Form $form
 */
$form = $this->form;

?>
<jetml_layout_container gutters="true">
	<jetml_layout_container region="left" splitter="true" style="width:200px">
		<jetml_layout_toolbar region="top">

			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.add();" title="New gallery" icon="add"/>
			<jetml_trash_button id="gellery_trash"/>

			<jetml_trash_dialog id="gellery_trash">
			</jetml_trash_dialog>
		</jetml_layout_toolbar>
		<jetml_layout_pane region="center" id="galleries_tree_area" style="padding:0px;">
		</jetml_layout_pane>
		<jetml_layout_toolbar region="bottom">
			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.treereload();" icon="reload"/>
			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.treeExpand();" icon="expand"/>
			<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.treeCollapse();" icon="collapse"/>
		</jetml_layout_toolbar>
	</jetml_layout_container>

	<jetml_layout_container region="center" gutters="false" id="edit_area" style="visibility: hidden;">
		<jetml_layout_container region="top" gutters="false" style="height: 170px;">
			<jetml_layout_toolbar region="top">
				<jetml_data id="gallery_form_fields_definition"><?=json_encode($form->getFields());?></jetml_data>
				<jetml_form_button_save onClick="Jet.modules.CURRENT_MODULE.save();" id="gallery_save"/>
			</jetml_layout_toolbar>
			<jetml_layout_pane region="center">

				<jet_form name="Gallery">
					<jet_form_common_error_message class="formError"/>
					<table>
						<jet_form_field name="parent_ID"/>
						<jet_form_field name="ID"/>
						<tr>
							<td valign="top"><jet_form_field_label name="title"/></td>
							<td><jet_form_field_error_msg name="title" class="error"/><jet_form_field name="title"/></td>
						</tr>
					</table>
				</jet_form>

				<form method="post" action="UploadFile.php" id="myForm" enctype="multipart/form-data" >
					<jetml_div id="uploader_area" style="border: 2px solid red; width: 100px;height: 100px;">
					</jetml_div>
				</form>

				<jetml_form_button onClick="Jet.modules.CURRENT_MODULE.uploadImage();" icon="add" title="Upload image"/>

				<input name="uploadedfile" multiple="true" type="file" data-dojo-type="dojox.form.Uploader" label="Select Some Files" id="uploader" />
				<input type="submit" label="Submit" data-dojo-type="dijit.form.Button" />


			</jetml_layout_pane>
		</jetml_layout_container>

		<jetml_layout_container region="center" gutters="false">

			<jetml_layout_pane region="center">
				<jetml_datagrid id="images_grid">
					<!-- <jetml_datagrid_column field="ID" title="Image" width="30%" formatter="Jet.modules.CURRENT_MODULE.formatterImage" /> -->
					<jetml_datagrid_column field="thumbnail_URI" title="Image" width="110" formatter="Jet_module_Jet_Images_formatImage" />
					<jetml_datagrid_column field="file_name" title="File name" width="70%"/>
				</jetml_datagrid>


			</jetml_layout_pane>
		</jetml_layout_container>
	</jetml_layout_container>

</jetml_layout_container>