<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

$current_model = DataModels::getCurrentModel();
if(!$current_model) {
    return;
}

$dialog = UI::dialog('dialog_create_new_key', Tr::_('Create new Key'), 600);


echo $dialog->start();
    ?>
    <div id="<?=DataModel_Definition_Key::getCreateForm()->getId()?>_form_area">
		<?php require 'form.phtml'; ?>
    </div>
	<?php

echo $dialog->footer();
echo UI::button_save(Tr::_('Create'))->setOnclick('JetStudio.DataModel.key.create.createSend()');
echo $dialog->end();

