<jet_form name="connection_add">
	<jet_form_common_error_message class="formError"/>
	<table>
		<tr>
			<td valign="top"><jet_form_field_label name="name"/></td>
			<td><jet_form_field_error_msg name="name" class="error"/><jet_form_field name="name"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="type"/></td>
			<td><jet_form_field_error_msg name="type" class="error"/><jet_form_field name="type"/></td>
		</tr>
		<tr><td colspan="2" align="right"><input type="submit" value="<?=Jet\Tr::_("Add connection");?>"/></td></tr>
	</table>
</jet_form>