<?php
/**
 * @var Jet\Form $form
 */
$form = $this->form;

/**
 * @var Jet\Config $config
 */
$config = $this->config;

/**
 * @var Jet\Config_Definition_Property_Abstract[] $config_props
 */
$config_props = $config->getPropertiesDefinition();
?>

<a href="?" class="btn btn-default"><?=Jet\Tr::_('&lt Back');?></a> <h3><?=Jet\Tr::_('Delete connection \'%CONNECTION%\' ', array("CONNECTION"=>$this->connection_name));?></h3>

<jet_form name="<?=$form->getName();?>">
	<jet_form_common_error_message class="formError"/>

	<div class="form-group">
		<jet_form_field_label name="name"/>
		<jet_form_field_error_msg name="name" class="form-error"/>
		<jet_form_field name="name" class="form-control" readonly="readonly"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="driver"/>
		<jet_form_field_error_msg name="driver" class="form-error"/>
		<jet_form_field name="driver" class="form-control" readonly="readonly"/>
	</div>

	<div class="form-group">
		<jet_form_field_label name="DSN"/>
		<jet_form_field_error_msg name="DSN" class="form-error"/>
		<jet_form_field name="DSN" class="form-control" readonly="readonly"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="username"/>
		<jet_form_field_error_msg name="username" class="form-error"/>
		<jet_form_field name="username" class="form-control" readonly="readonly"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="password"/>
		<jet_form_field_error_msg name="password" class="form-error"/>
		<jet_form_field name="password" class="form-control" readonly="readonly"/>
	</div>

	<input type="submit" value="<?=Jet\Tr::_('YES! Delete it!');?>" class="btn btn-danger"/>
</jet_form>