<?php
use Jet\Mvc_View;
use Jet\Form_Renderer;
use Jet\Data_Text;

/**
 * @var Mvc_View      $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if(!$r->getBaseCssClasses()) {
	$r->setBaseCssClass('form-control');
}

$field = $r->getField();
if($field->getLastErrorCode()) {
	$r->addCustomCssClass('is-invalid');
}
?>
	<input type="url" name="<?=$field->getTagNameValue()?>" id="<?=$field->getId()?>" <?php

	if( $r->getCssClasses() ) echo ' class ="'.$r->getCssClasses().'"';
	if( $r->getCssStyles() ) echo ' style ="'.$r->getCssStyles().'"';
	if( $r->getJsActions() ) echo $r->getJsActions();

	if( $field->getPlaceholder() ) echo ' placeholder="'.Data_Text::htmlSpecialChars($field->getPlaceholder()).'"';
	if( $field->getIsReadonly() ) echo ' readonly="readonly"';
	if( $field->getIsRequired() ) echo ' required="required"';
	if( $field->getValidationRegexp() ) echo ' pattern="'.$field->getValidationRegexp().'"';

	?> value="<?=$field->getValue()?>"/>
