<?php
namespace JetApplication\Installer;

use Jet\Form;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Form $form
 */
$form = $this->getRaw( 'form' );
$form->setDefaultLabelWidth( [Form::LJ_SIZE_MEDIUM => 2] );

?>
<?= $form->start() ?>
<?= $form->message() ?>

<?php foreach( $form->getFields() as $field ):
	echo $field;
endforeach; ?>


<?= Installer::buttonNext(); ?>

<?= $form->end() ?>

