<?php
namespace JetApplication;

use Jet\Mvc_View;
use Jet\Form;
use Jet\Tr;

use Jet\UI_messages;

/**
 * @var Mvc_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );

$form->setIsReadonly();
$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
?>

<?=Installer::buttonBack()?>

<h3><?=Tr::_( 'Connection \'%CONNECTION%\' Test', [ 'CONNECTION' => $this->getString( 'connection_name' ) ] );?></h3>

<?php if( $this->getBool( 'OK' ) ): ?>
	<?=UI_messages::createSuccess( Tr::_( 'OK! Database connection works correctly.' ) )?>
<?php else: ?>
	<?=UI_messages::createDanger( Tr::_( 'Error connecting to database:' ).$this->getString( 'error_message' ) )?>
<?php endif; ?>


<?=$form->start()?>
<?=$form->message()?>

<?=$form->field( 'name' )?>
<?=$form->field( 'DSN' )?>
<?=$form->field( 'username' )?>

<?=$form->end()?>


<?php if( $this->getBool( 'OK' ) ):
	Installer::continueForm();
endif; ?>
