<?php

use Jet\Http_Request;
use Jet\UI;
use Jet\Locale;
use JetApplication\Application_Admin;


?>


<li class="nav-item dropdown">
	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
	   aria-haspopup="true" aria-expanded="false">
		<span><?= UI::flag( Locale::getCurrentLocale() ) ?></span>
	</a>
	<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
		<?php foreach( Application_Admin::getAvlLovales() as $locale ): ?>
			<a class="dropdown-item" href="<?=Http_Request::currentURI(['set_locale'=>$locale->toString()])?>">
				<?= UI::flag( $locale ) ?>
				<?= $locale->getName( $locale ) ?>
			</a>
		<?php endforeach; ?>
	</div>
</li>

