<?php
namespace JetExampleApp;

use Jet\Tr;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 */
?>
	<table class="table table-striped">
		<thead>
		<tr>
			<th><?=Tr::_( 'Class' );?></th>
			<th><?=Tr::_( 'Status' );?></th>
		</tr>
		</thead>
		<?php foreach( $this->getRaw( 'result' ) as $class => $state ): ?>
			<tr>
				<td><?=$class;?></td>
				<?php if( $state===true ): ?>
					<td>
						<div class="OK">OK</div>
					</td>
				<?php else: ?>
					<td>
						<div class="error"><?=$state;?></div>
					</td>
				<?php endif; ?>
			</tr>
		<?php endforeach; ?>
	</table>


<?php if( $this->getBool( 'OK' ) ): ?>
	<form method="post">
		<input type="hidden" name="go" value="1">
		<?=Installer::buttonNext();?>
	</form>
<?php endif; ?>