#!/usr/local/bin/php
<?php
require 'bootstrap.php';
/** @noinspection PhpIncludeInspection */
require 'SebastianBergmann/PHPUnit/SkeletonGenerator/autoload.php';

use SebastianBergmann\PHPUnit\SkeletonGenerator\Command;

$text_ui = new Command();
$text_ui->main();