<?php
namespace JetApplicationModule\Content\Images\Admin;

use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 */

?>
<?php require 'parts/js.phtml'; ?>

<?php require 'parts/toolbar.phtml' ?>

<div class="row" id="main-col">
	<div class="col-md-3">
		<?php require 'parts/galleries.phtml'; ?>
	</div>
	<div class="col-md-9">

		<div id="edit_form_area">
			<?php require 'parts/edit-form.phtml' ?>
		</div>

		<div class="card" style="margin-bottom: 20px;">
			<div class="card-body bg-light">

				<div id="images_area">
					<?php require 'parts/images.phtml'; ?>
				</div>

			</div>
		</div>
	</div>
</div>
