<?php
namespace JetApplicationModule\Jet\AdminUsers;
use Jet;

/**
 * @var Jet\Auth_User_Abstract[] $users
 */
$users = $this->users;
?>
<a href="?new">ADD USER</a>

<table border="1">
	<thead>
		<tr>
			<td></td>
			<td>ID</td>
			<td>Login</td>
		</tr>
	</thead>
	<?php foreach( $users as $user_ID=>$user ): ?>
	<tr>
		<td><a href="?ID=<?=rawurlencode( $user_ID ); ?>">EDIT</a></td>
		<td><?=$user->getID(); ?></td>
		<td><?=$user->getLogin(); ?></td>
	</tr>
<?php endforeach; ?>
</table>
