<?php
use Jet\Redis_Config;
use Jet\Form;
use JetExampleApp\Installer;
use Jet\Tr;

/**
 * @var Redis_Config $config
 */
$config = $this->config;

/**
 * @var Form $form
 */
$form = $this->form;

?>

<?php if($config->getConnections()): ?>
	<a href="?add_connection" class="btn btn-success"><?=Tr::_('Add new connection');?></a>

	<?=$form->start()?>

	<table class="table table-striped">
	<thead>
	<tr>
		<th></th>
		<th nowrap><?=Tr::_('Is default?');?></th>
		<th><?=Tr::_('Name');?></th>
		<th nowrap><?=Tr::_('Host or socket');?></th>
		<th><?=Tr::_('Port');?></th>
	</tr>
	</thead>
	<?php foreach( $config->getConnections() as $name => $connection ): ?>
	<tr>
		<td nowrap>
			<a href="?edit_connection=<?=rawurlencode($name);?>" class="btn btn-default btn-xs"><?=Tr::_('Edit');?></a>
			&nbsp;
			<a href="?delete_connection=<?=rawurlencode($name);?>" class="btn btn-danger btn-xs"><?=Tr::_('Delete');?></a>
			&nbsp;
			<a href="?test_connection=<?=rawurlencode($name);?>" class="btn btn-default btn-xs"><?=Tr::_('Test');?></a>
		</td>
		<td style="text-align: center;"><input type="radio" name="default_connection_name" value="<?=htmlspecialchars($name);?>" <?php if($name==$config->getDefaultConnectionName()): ?>checked="checked" <?php endif;?>/></td>
		<td nowrap style="padding-right: 20px;"><?=$connection->getName();?></td>
		<td nowrap style="padding-right: 20px;"><?=$connection->getHost();?></td>
		<td nowrap style="padding-right: 20px;width: 100%"><?=$connection->getPort();?></td>
	</tr>
	<?php endforeach; ?>
	</table>

		<?=Installer::buttonNext();?>
	<?=$form->end()?>

<?php else: ?>
	<form method="post">
		<input type="hidden" name="go" value="1">
		<?=Installer::buttonNextSkipIt()?>
	</form>
<?php endif; ?>
