<?php
use JetExampleApp\Installer;
use Jet\Tr;
use Jet\Form;

/**
 * @var Form $form
 */
$form = $this->form;

$form->setDefaultLabelWidth(2);
$form->setDefaultFieldWidth(4);

$form->field('name')->setIsReadonly(true);
$form->field('host')->setIsReadonly(true);
$form->field('port')->setIsReadonly(true);
?>

<?=Installer::buttonBack()?>

<h3><?=Tr::_('Delete connection \'%CONNECTION%\' ', ["CONNECTION"=>$this->connection_name]);?></h3>

<?=$form->start()?>
	<?=$form->message()?>

	<?=$form->field('name')?>
	<?=$form->field('host')?>
	<?=$form->field('port')?>

	<input type="submit" value="<?=Tr::_('YES! Delete it!');?>" class="btn btn-danger"/>
<?=$form->end()?>