<?php
use Jet\Form;
use Jet\Tr;
/**
 * @var Form $form
 */
$form = $this->form;

$form->setDefaultLabelWidth(2);
$form->setDefaultFieldWidth(4);
?>

<?=\Jet\Installer::buttonBack()?>

<h3><?=Jet\Tr::_('Edit connection \'%CONNECTION%\' ', ['CONNECTION'=>$this->connection_name]);?></h3>

<?=$form->start()?>
	<?=$form->message()?>

	<?=$form->field('name')?>
	<?=$form->field('host')?>
	<?=$form->field('port')?>

	<input type="submit" class="btn btn-primary" value="<?=Tr::_('Save');?>"/>

<?=$form->end()?>