<?php
use Jet\Form;
use Jet\Tr;
use Jet\Installer;
/**
 * @var Form $form
 */
$form = $this->form;

$form->setDefaultLabelWidth(2);
$form->setDefaultFieldWidth(4);

$form->field('name')->setIsReadonly(true);
$form->field('host')->setIsReadonly(true);
$form->field('port')->setIsReadonly(true);

if(!$this->OK) {
	$form->setIsReadonly();
}
?>

<?=Installer::buttonBack()?>

<h3><?=Tr::_('Connection \'%CONNECTION%\' Test', ['CONNECTION'=>$this->connection_name]);?></h3>

<?php if($this->OK): ?>
	<div class="OK" style="padding: 5px;margin: 5px;">OK</div>
<?php else: ?>
	<div class="error" style="padding: 5px;margin: 5px;">
		<strong><?=Jet\Tr::_('Error:');?></strong>
		<?=$this->error_message;?>
	</div>
<?php endif; ?>

<?=$form->start()?>
	<?=$form->message()?>

	<?=$form->field('name')?>
	<?=$form->field('host')?>
	<?=$form->field('port')?>

	<a href="?edit_connection=<?=$this->connection_name;?>" class="btn btn-default"><?=Tr::_('Edit connection');?></a>
<?php if($this->OK): ?>
	<input type="submit" value="<?=Tr::_('OK');?>" class="btn btn-primary"/>
<?php endif; ?>

<?=$form->end()?>
