<?php
namespace JetApplicationModule\Content\Articles\Admin;

use Jet\UI_button;
use Jet\UI;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Listing $listing
 */
$listing = $this->getRaw( 'listing' );
$grid = $listing->getGrid();
$filter_form = $listing->getFilterForm();

$router = $this->getController()->getControllerRouter();


$delete_uri = $router->action( 'delete' )->URI();

if( !$delete_uri || !$grid->getPaginator()->getPagesCount() ) {
	return;
}
?>
<tr>
	<td colspan="<?=count( $grid->getColumns() )?>" class="toolbar">
		<?=UI::button_delete()->setType( UI_button::TYPE_SUBMIT )->setSize( UI_button::SIZE_EXTRA_SMALL )?>
	</td>
</tr>

