<?php
namespace JetApplicationModule\Test\REST;

use Jet\Http_Request;
use Jet\Tr;
use Jet\MVC_View;

/**
 *
 * @var MVC_View $this
 * @var Test_Abstract $selected_test
 */


$tests = $this->getRaw( 'tests' );
$selected_test = $this->getRaw( 'selected_test' );

$session = Main::getSession();
?>
<style>
    h3 {
        background: #b9b9b9;
        padding: 4px;
        margin-top: 5px;
        margin-bottom: 5px;
    }

    h4 {
        background: #e9e9e9;
        padding: 4px;
        margin-top: 5px;
        margin-bottom: 5px;
    }
</style>
<div style="background: #0f0f0f;color: #c9c9c9;display: grid;align-items: center;grid-template-columns: 160px 1fr;">
	<div style="padding: 10px;"><img src="https://php-jet.net/images/logo-st.svg" style="width: 120px;height: auto"></div>
	<div><b><?= Tr::_( 'REST API tests' ) ?></b></div>
</div>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4" style="background: #eeeeee">
			<div style="padding: 5px;background: #aaaaaa;margin-bottom: 10px;margin-left: -15px;margin-right: -15px;">
				<table>
					<tr>
						<td><?= Tr::_( 'Current REST API client user: %USERNAME%', ['USERNAME' => $session->getValue( 'username' )] ) ?>
							<br/></td>
						<td style="padding-left: 10px"><a href="?logout"
						                                  class="btn btn-light btn-sm"><?= Tr::_( 'Logout' ) ?></a></td>
					</tr>
				</table>
			</div>


			<?php foreach( $tests as $tests_data ): ?>
				<h2><?= $tests_data['title'] ?></h2>
				<ul>
					<?php foreach( $tests_data['tests'] as $test ):
						/**
						 * @var Test_Abstract $test
						 */
						if( !$test->isEnabled() ) {
							continue;
						}

						if( $test->isSelected() ):
							?>
							<li><strong><?= $test->getTitle() ?></strong></li>
						<?php
						else:
							?>
							<li>
								<a href="<?= Http_Request::currentURL( ['test' => $test->getId()] ) ?>"><?= $test->getTitle() ?></a>
							</li>
						<?php
						endif;
					endforeach; ?>
				</ul>
			<?php endforeach; ?>
		</div>
		<div class="col-md-8">
			<?php $selected_test?->showResult(); ?>
		</div>
	</div>

</div>

