<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

if(!Pages::getCurrentPage()) {
	return;
}

$dialog = UI::dialog('delete_content', Tr::_('Delete this content'), 600);

echo $dialog->start();
?>
<?=Tr::_('Do You really want to delete this content item ?');?>
	<?php
echo $dialog->footer();
echo UI::button_delete()->setOnclick( "Pages.editPage.content.deleteContentSend();" );
echo $dialog->end();

$form = Pages::getCurrentPage()->getDeleteContentForm();

echo $form->start();
echo $form->field('index');
echo $form->end();
