<?php
namespace JetStudio;

use Jet\Form_Renderer;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Pages_Page $page
 */

$page = $this->getRaw( 'page' );

$form = $page->getEditForm_content();

$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 6
] );

?>
<?= $form->start() ?>
<div style="min-height: 600px;margin-bottom: 40px;">
	<div style="padding: 10px;">
		<?= $form->field( 'layout_script_name' ) ?>
	</div>
	<div id="content_list_area">
		<?= $this->render( 'page/content/edit/form/list' ); ?>
	</div>
</div>
<?= $form->end() ?>

<?= $this->render( 'page/content/delete/dialog' ); ?>
<?= $this->render( 'page/content/create/dialog' ); ?>
