<?php
namespace JetStudio;

use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View $this
 * @var Pages_Page $page
 */

$page = $this->getRaw( 'page' );

$form = $page->getEditForm_content();

$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 6
] );

?>
<div class="toolbar">
	<?= UI::button_create( Tr::_( 'Add content' ) )
		->setOnClick( 'Pages.editPage.content.addContent()' )?>
	
	<?= UI::button_save( Tr::_('Stave content settings') )->setOnClick( "$('#{$form->getId()}').submit()" ) ?>
</div>


<?= $form->start() ?>
<div style="min-height: 600px;margin-bottom: 40px;">
	<div id="content_list_area">
		<?= $this->render( 'page/content/edit/form/list' ); ?>
	</div>
</div>
<?= $form->end() ?>

<?= $this->render( 'page/content/delete/dialog' ); ?>
<?= $this->render( 'page/content/create/dialog' ); ?>
