<?php
/**
 * @var Jet\Form $form
 */
$form = $this->form;

/**
 * @var Jet\Config $config
 */
$config = $this->config;

/**
 * @var Jet\Config_Definition_Property_Abstract[] $config_props
 */
$config_props = $config->getPropertiesDefinition();
?>

<h3><?=Jet\Tr::_('Add new Memcache connection');?></h3>

<jet_form name="<?=$form->getName();?>">
	<jet_form_common_error_message class="formError"/>
	<div class="form-group">
		<jet_form_field_label name="name"/>
		<jet_form_field_error_msg name="name" class="form-error"/>
		<jet_form_field name="name" class="form-control"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="host"/>
		<jet_form_field_error_msg name="host" class="form-error"/>
		<jet_form_field name="host" class="form-control"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="port"/>
		<jet_form_field_error_msg name="port" class="form-error"/>
		<jet_form_field name="port" class="form-control"/>
	</div>
	<input type="submit" class="btn btn-primary" value="<?=Jet\Tr::_('Add');?>"/>


</jet_form>