<?php
require JET_EXAMPLE_APP_INSTALLER_PATH.'classes/CompatibilityTester.php';
require JET_EXAMPLE_APP_INSTALLER_PATH.'classes/CompatibilityTester/TestResult.php';

use JetExampleApp\Installer;
use JetExampleApp\CompatibilityTester;

$tester = new CompatibilityTester();

//TODO: ikony nahradit Bootstrap ikonami
?>

<style type="text/css">


	.isok {
		background-color: #aaaaaa;
	}

	.fail {
		background-color: #ff1111;
	}

	.warning {
		background-color: #ff9999;
	}

	table {
		padding: 0;
		margin: 0;
		border-collapse: collapse;
	}

	table td, table th {
		text-align: left;
		padding: 10px;
		vertical-align: top;
		border: 0 solid #c9c9c9;
		border-top-width: 1px;
		background-color: inherit;
	}

	.resicon {
	}

	.restitle {
	}

	.resresult {
	}

	.resultmsg {
		margin-top: 40px;
		margin-bottom: 40px;
		padding: 20px;
		border: 1px solid #000000;
	}

</style>


<?php if($tester->testSystem()) :?>
	<?php $tester->showResult(); ?>
<form method="post">
<input type="hidden" name="go" value="1">
	<?=Installer::buttonNext();?>
</form>
<?php else: ?>
	<?php $tester->showResult(); ?>
<?php endif; ?>