<?php
namespace JetStudio\ModuleWizard\Basic;

use Jet\Form_Renderer;
use Jet\UI_button;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View $this
 * @var Wizard $wizard
 */
$wizard = $this->getRaw( 'wizard' );


$setup_form = $wizard->getSetupForm();

$setup_form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 2
] );
$setup_form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 10
] );

?>
<?= $setup_form->start() ?>
<legend><?= Tr::_( 'Main module parameters' ) ?></legend>

<?= $setup_form->field( 'NAME' ) ?>

<?= $setup_form->field( 'LABEL' ) ?>
<?= $setup_form->field( 'DESCRIPTION' ) ?>
<?= $setup_form->field( 'AUTHOR' ) ?>
<?= $setup_form->field( 'LICENSE' ) ?>
<?= $setup_form->field( 'COPYRIGHT' ) ?>

<div style="text-align: right">
	<?= UI::button_save( Tr::_( 'Create' ) )->setClass( UI_button::CLASS_PRIMARY )->setIcon( 'magic' ) ?>
</div>
<?= $setup_form->end() ?>

