<?php
namespace JetApplicationModule\JetExample\Images;
use Jet;
use JetApplicationModule\JetExample\UIElements;

/**
 * @var Jet\Mvc_MicroRouter $router
 */
$router = $this->router;


/**
 * @var Jet\Data_Tree $galleries
 */
$galleries = $this->galleries;

/**
 * @var Gallery $gallery
 */
$gallery = $this->gallery;

/**
 * @var Jet\Form $upload_form
 */
$upload_form = $this->upload_form;

/**
 * @var Jet\Form $edit_form
 */
$edit_form = $this->edit_form;


/**
 * @var UIElements\Main $UI_m
 */
$UI_m = Jet\Application_Modules::getModuleInstance('JetExample\UIElements');
$tree = $UI_m->getTreeInstance();

$tree->setData( $galleries );
$tree->setSelectedID( $this->selected_ID );

$tree->setNormalDisplayCallback( function( Jet\Data_Tree_Node $node, array $data ) use ( $router)  {
	?>
	<?php if($router->getActionAllowed('edit')): ?>
		<a href="<?=$router->getActionURI('edit', $data['ID']);?>"><?=$data['title'];?></a>
	<?php else: ?>
		<a href="<?=$router->getActionURI('view', $data['ID']);?>"><?=$data['title'];?></a>
	<?php endif; ?>
	<?php
} );

$tree->setSelectedDisplayCallback( function( Jet\Data_Tree_Node $node, array $data ) {
	?>
	<strong><?=$data['title'];?></strong>
	<?php
});

$tree->setOpenedDisplayCallback( function( Jet\Data_Tree_Node $node, array $data ) use ( $router)  {
	if($node->getIsRoot()):
		?>
		<a href="<?=Jet\Mvc::getCurrentURI();?>" style="font-style: italic;"><?=$data['title'];?></a>
		<?php
		return;
	endif;
	?>
	<?php if($router->getActionAllowed('edit')): ?>
		<a href="<?=$router->getActionURI('edit', $data['ID']);?>" style="font-style: italic;"><?=$data['title'];?></a>
	<?php else: ?>
		<a href="<?=$router->getActionURI('view', $data['ID']);?>" style="font-style: italic;"><?=$data['title'];?></a>
	<?php endif; ?>
<?php
});

?>


<div class="row">
	<div class="col-md-2">
		<?php if(
			$router->getActionAllowed('add') &&
			(
				!$gallery ||
				!$gallery->getIsNew()
			)
		):
			$parent_ID = $gallery ? $gallery->getID(): '_root_';
			?>
		<div style="padding: 5px;">
			<a href="<?=$router->getActionURI('add', $parent_ID);?>" class="btn btn-default" style="width: 100%;">
				<jetml_icon icon="module/JetExample\Images/module" size="large"/>
				<?=Jet\Tr::_('Create new gallery');?>
			</a>
		</div>
		<?php endif; ?>

		<?=$tree->render();?>

	</div>
	<div class="col-md-9">

		<?php if($gallery): ?>

			<jet_form name="<?=$edit_form->getName();?>">
				<jet_form_common_error_message class="form-error"/>
				<fieldset>
					<jet_form_field name="parent_ID"/>
					<jet_form_field name="ID"/>
					<div class="form-group">
						<jet_form_field_label name="title"/>
						<jet_form_field_error_msg name="title" class="form-error"/>
						<jet_form_field name="title" class="form-control"/>
					</div>
					<?php if($this->has_access): ?>
					<input type="submit" class="btn btn-primary" value="<?=Jet\Tr::_('Save');?>"/>
					<?php endif; ?>
				</fieldset>
			</jet_form>

			<?php if($upload_form): ?>
			<div>
				<jet_form name="<?=$upload_form->getName();?>" action="" enctype="multipart/form-data">
					<jet_form_common_error_message class="form-error"/>

					<div class="form-group">
						<jet_form_field_label name="file"/>
						<jet_form_field_error_msg name="file" class="form-error"/>
						<jet_form_field name="file" class="form-control"/>
					</div>
					<div class="form-group">
						<jet_form_field_label name="overwrite_if_exists"/>
						<jet_form_field_error_msg name="overwrite_if_exists" class="form-error"/>
						<jet_form_field name="overwrite_if_exists"/>
					</div>
					<input type="submit" class="btn btn-primary" value="<?=Jet\Tr::_('Upload');?>"/>

				</jet_form>
			</div>
			<?php endif; ?>

			<?php if(
				$gallery &&
				$gallery->getIsSaved()
			): ?>

				<?php
				$images=$gallery->getImages();
				if( count($images) ): ?>
				<form action="?ID=<?=$gallery->getID();?>&amp;delete_images" method="post">
					<div style="padding: 10px;">
						<?php foreach( $images as $image ): ?>
						<div class="img-thumbnail">
							<div style="width: 150px;height: 150px;vertical-align: middle;text-align: center;">
								<a href="<?=$image->getURI();?>" target="_blank"><img src="<?=$image->getThumbnail(150, 150)->getURI();?>" /></a>
							</div>
							<div style="width: 150px;height: 40px;overflow: hidden;text-align: left;">
									<table><tr>
										<?php if($this->can_delete_image): ?>
										<td style="vertical-align: top; padding: 5px;"><input type="checkbox" name="images[]" value="<?=$image->getID();?>" id="image_<?=$image->getID();?>"></td>
										<?php endif; ?>
										<td><label for="image_<?=$image->getID();?>"><?=$image->getFileName();?></label></td>
									</tr></table>


							</div>
						</div>
						<?php endforeach; ?>
					</div>
					<?php if($this->can_delete_image): ?>
					<input type="submit" class="btn btn-danger" value="<?=Jet\Tr::_('Delete selected images');?>">
					<?php endif; ?>
				</form>
				<?php endif; ?>
			<?php endif; ?>

		<?php endif; ?>
	</div>
</div>