<?php

use Jet\UI_button;
use Jet\UI;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var UI_button $b
 */
$b = $this->getRaw( 'element' );

if( !$b->getLabel() ) {
	$b->setLabel( UI::_( 'Delete' ) );
}

if( !$b->getIcon() ) {
	$b->setIcon( 'trash' );
}

if( !$b->getClass() ) {
	$b->setClass( 'danger' );
}

$label = trim($b->getLabel());
$label = $label ? '&nbsp;'.$label : '';
$id = $b->getId() ? ' id="'.$b->getId().'"' : '';
$icon = $b->getIcon() ? UI::icon( $b->getIcon() ) : '';
$class = 'btn btn-'.$b->getClass().' btn-'.$b->getSize();

if( $b->getUrl() ):
	?><a href="<?= $b->getUrl() ?>"<?=$id?> class="<?=$class?>" <?= $b->getJsActions() ?>><?=$icon?><?=$label?></a><?php
else:
	?><button type="<?= $b->getType() ?>"<?=$id?> class="<?=$class?>" <?= $b->getJsActions() ?>><?=$icon?><?=$label?></button><?php
endif;
