<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

if(!Modules::getCurrentModule()) {
    return;
}

$dialog = UI::dialog('delete_module', Tr::_('Delete this Module'), 600);

echo $dialog->start();
	?>
    <?=Tr::_('Do You really want to delete module <strong>%name%</strong> ?', [
        'name' => Modules::getCurrentModule()->getName()
    ]);?>
	<?php
echo $dialog->footer();
	echo UI::button_delete()->setUrl( Modules::getActionUrl('delete') );
echo $dialog->end();

