<?php

use Jet\MVC_View;
use Jet\Form_Renderer_Field_Input;
use Jet\Form_Field_File;

/**
 * @var MVC_View $this
 * @var Form_Renderer_Field_Input $r
 * @var Form_Field_File $field
 */
$r = $this->getRaw( 'renderer' );
$field = $r->getField();

$r->setInputType('file');

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$attrs = [];

if( $field->getAllowMultipleUpload() ) {
	$attrs['multiple'] = 'multiple';
}
if( $field->getAllowedMimeTypes() ) {
	$attrs['accept'] = implode( '|', $field->getAllowedMimeTypes() );
}

$attrs['value'] = '';

$r->setCustomTagAttributes($attrs);
?>
<input <?=$r->renderTagAttributes()?>/>