<?php

use Jet\MVC_View;
use Jet\Form_Renderer_Field_Input_File;
use Jet\Form_Field_File;

/**
 * @var MVC_View $this
 * @var Form_Renderer_Field_Input_File $r
 * @var Form_Field_File $field
 */
$r = $this->getRaw( 'renderer' );
$field = $r->getField();

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}
?>
<input <?=$r->renderTagAttributes()?>/>