<?php

use Jet\MVC_View;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

$field = $r->getField();
/*
if($field->getForm()->getRawData()) {
	if($field->getLastErrorCode()) {
		$r->addCustomCssClass('is-invalid');
	} else {
		$r->addCustomCssClass('is-valid');
	}
}
*/
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}
?>
<input <?=$r->renderAttributes($r->getStdInputFieldAttributes('text'))?>/>
