<?php

use Jet\MVC_View;
use Jet\Form_Renderer;
use Jet\Form_Field_Select;
use Jet\Data_Text;

/**
 * @var MVC_View $this
 * @var Form_Renderer $r
 * @var Form_Field_Select $field
 */
$r = $this->getRaw( 'element' );


if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

$field = $r->getField();

if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$attrs = [
	'id' => $field->getId(),
	'multiple' => 'multiple',
];

if( $field->getIsReadonly() ) {
	$attrs['disabled'] = 'disabled';
}
if( $field->getIsRequired() ) {
	$attrs['required'] = 'required';
}

?>
<select name="<?= $field->getTagNameValue() ?>[]" <?=$r->renderAttributes($attrs)?>>
	<?php foreach( $field->getSelectOptions() as $val => $label ):
		
		$css = $label->getSelectOptionCss();
		$selected = $field->optionIsSelected($val) ? ' selected="selected"' : '';
		
		?><option value="<?=Data_Text::htmlSpecialChars( $val )?>" <?=$css?><?=$selected?>><?=Data_Text::htmlSpecialChars( $label )?></option><?php
	endforeach; ?>
</select>
