<?php

use Jet\MVC_View;
use Jet\Form_Renderer_Field_Input;
use Jet\Form_Field_Select;
use Jet\Data_Text;

/**
 * @var MVC_View $this
 * @var Form_Renderer_Field_Input $r
 * @var Form_Field_Select $field
 */
$r = $this->getRaw( 'renderer' );
$field = $r->getField();

$r->setInputType('radio');

$value = $field->getValue();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$container_class = 'radio';
if($field->getIsReadonly()) {
	$container_class = 'radio disabled';
}


$c = 0;
foreach( $field->getSelectOptions() as $key => $option ):
	$c++;
	
	
	$id = $field->getId().'__'.$c;
	
	$attrs = [];
	$attrs['id'] = $id;
	$attrs['value'] = Data_Text::htmlSpecialChars( $key );
	
	if($field->optionIsSelected($key)) {
		$attrs['checked'] = 'checked';
	}
	
	$r->setCustomTagAttributes($attrs);
	
	if(!$option->getSelectOptionCssClass()) {
		$option->setSelectOptionCssClass('form-check-label');
	}
	?>
	<div class="<?= $container_class ?>">
		<input <?=$r->renderTagAttributes()?>/>
		<label for="<?= $id ?>" <?=$option->getSelectOptionCss()?>><?= $option ?></label>
	</div>
<?php endforeach; ?>
