<?php

use Jet\MVC_View;
use Jet\Form_Renderer_Field_Input;
use Jet\Form_Field_Int;

/**
 * @var MVC_View $this
 * @var Form_Renderer_Field_Input $r
 * @var Form_Field_Int $field
 */
$r = $this->getRaw( 'renderer' );
$field = $r->getField();

$r->setFieldType('range');

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$attrs = [];

if( $field->getMinValue() !== null ) {
	$attrs['min'] = $field->getMinValue();
}

if( $field->getMaxValue() !== null ) {
	$attrs['max'] = $field->getMaxValue();
}

if($field->getStep()!==null) {
	$attrs['step'] = $field->getStep();
}

$r->setCustomTagAttributes($attrs);
?>
<input <?=$r->renderAttributes()?>/>