<?php

use Jet\MVC_View;
use Jet\Form_Renderer;
use Jet\Form_Field_Select;
use Jet\Form_Field_Select_Option_Interface;
use Jet\Data_Text;
use Jet\Data_Tree_Node;

/**
 * @var MVC_View $this
 * @var Form_Renderer $r
 * @var Form_Field_Select $field
 */
$r = $this->getRaw( 'element' );


if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

$field = $r->getField();
$value = $field->getValue();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}


$attrs = [
	'name' => $field->getTagNameValue(),
	'id' => $field->getId(),
];

if( $field->getIsReadonly() ) {
	$attrs['disabled'] = 'disabled';
}
if( $field->getIsRequired() ) {
	$attrs['required'] = 'required';
}

?>
<select  <?=$r->renderAttributes($attrs)?>>
	<?php foreach( $field->getSelectOptions() as $val => $label ):

		$css = '';
		if( $label instanceof Form_Field_Select_Option_Interface ) {
			if( ($class = $label->getSelectOptionCssClass()) ) {
				$css .= ' class="' . $class . '"';
			}
			if( ($style = $label->getSelectOptionCssStyle()) ) {
				$css .= ' style="' . $style . '"';
			}
		}

		$text = Data_Text::htmlSpecialChars( $label );
		if($label instanceof Data_Tree_Node) {
			$text = str_pad('', ($label->getDepth()*36), '&nbsp;', STR_PAD_LEFT).$text;
		}

		if( ((string)$val) == ((string)$value) ) {
			echo '<option value="' . Data_Text::htmlSpecialChars( $val ) . '" ' . $css . ' selected="selected">' . $text . '</option>' . PHP_EOL;
		} else {
			echo '<option value="' . Data_Text::htmlSpecialChars( $val ) . '" ' . $css . '>' . $text . '</option>' . PHP_EOL;
		}
	endforeach; ?>
</select>