<?php

use Jet\MVC_View;
use Jet\Form_Renderer_Field_Input_Textarea;

/**
 * @var MVC_View $this
 * @var Form_Renderer_Field_Input_Textarea $r
 */
$r = $this->getRaw( 'renderer' );

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

$field = $r->getField();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}
?>
<textarea <?=$r->renderTagAttributes()?>><?= $field->getValueRaw() ?></textarea>
