<?php
use Jet\Form;
use Jet\Config;
use Jet\Config_Definition_Property_Abstract;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View $this
 * @var Form $form
 * @var Config $config
 * @var Config_Definition_Property_Abstract[] $config_props
 */
$form = $this->getRaw('form');
$config = $this->getRaw('config');
$config_props = $config->getPropertiesDefinition();

$btn_label = 'Add';
?>


<h3><?=Tr::_('Add new DB (PDO) connection');?></h3>

<?php
require 'parts/connection.phtml';
?>