<?php
use JetExampleApp\Installer;
use Jet\Form;
use Jet\Db_Config;
use Jet\Tr;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form $form
 * @var Db_Config $config
 */
$form = $this->getRaw('form');
$config = $this->getRaw('config');
?>

<?php if($config->getConnections()): ?>

<a href="?add_connection" class="btn btn-success"><?=Tr::_('Add new connection');?></a>

<?=$form->start()?>
	<?=$form->message()?>
<table class="table table-striped">
	<thead>
	<tr>
		<th></th>
		<th nowrap><?=Tr::_('Is default?');?></th>
		<th><?=Tr::_('Name');?></th>
		<th><?=Tr::_('Type');?></th>
		<th style="width: 100%"><?=Tr::_('DSN');?></th>
	</tr>
	</thead>
	<?php foreach( $config->getConnections() as $name => $connection ): ?>
	<tr>
		<td nowrap>
			<a href="?edit_connection=<?=rawurlencode($name);?>" class="btn btn-default btn-xs"><?=Tr::_('Edit');?></a>
			&nbsp;
			<a href="?delete_connection=<?=rawurlencode($name);?>" class="btn btn-danger btn-xs"><?=Tr::_('Delete');?></a>
			&nbsp;
			<a href="?test_connection=<?=rawurlencode($name);?>" class="btn btn-default btn-xs"><?=Tr::_('Test');?></a>
		</td>
		<td style="text-align: center;"><input type="radio" name="default_connection_name" value="<?=htmlspecialchars($name);?>"
		           <?php if($name==$config->getDefaultConnectionName()): ?>checked="checked" <?php endif;?>
				/></td>
		<td nowrap style="padding-right: 20px;"><?=$connection->getName();?></td>
		<td nowrap style="padding-right: 20px;"><?=$connection->getDriver();?></td>
		<td nowrap><?=$connection->getDsn();?></td>
	</tr>
	<?php endforeach; ?>
</table>


	<?=Installer::buttonNext();?>
<?=$form->end()?>

<?php else: ?>
<form method="post">
	<input type="hidden" name="go" value="1">
	<?=Installer::buttonNextSkipIt()?>
</form>
<?php endif; ?>

