<?php
use JetExampleApp\Installer;
use Jet\Tr;
use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form $form
 */
$form = $this->getRaw('form');

$form->setDefaultLabelWidth(2);

$form->field('name')->setIsReadonly(true);
$form->field('driver')->setIsReadonly(true);


$form->field('DSN')->setIsReadonly(true);
$form->field('username')->setIsReadonly(true);
$form->field('username')->setIsReadonly(true);

?>

<?=Installer::buttonBack()?>

<h3><?=Tr::_('Delete connection \'%CONNECTION%\' ', ["CONNECTION"=>$this->getString('connection_name')]);?></h3>

<?=$form->start()?>
<?=$form->message()?>

<?=$form->field('name')?>
<?=$form->field('driver')?>


<?=$form->field('DSN')?>
<?=$form->field('username')?>

<input type="submit" value="<?=Jet\Tr::_('YES! Delete it!');?>" class="btn btn-danger"/>

<?=$form->end()?>
