<?php
/**
 * @var Jet\Form $form
 */
$form = $this->form;

/**
 * @var Jet\Config $config
 */
$config = $this->config;

/**
 * @var Jet\Config_Definition_Property_Abstract[] $config_props
 */
$config_props = $config->getPropertiesDefinition();

$btn_label = 'Save';

?>

<a href="?" class="btn btn-default"><?=Jet\Tr::_('&lt Back');?></a> <h3><?=Jet\Tr::_('Edit connection \'%CONNECTION%\' ', ['CONNECTION'=>$this->connection_name]);?></h3>

<?php
require 'parts/connection.phtml';
?>