<?php
use Jet\Form;
use Jet\Tr;
use JetExampleApp\Installer;

/**
 * @var Form $form
 */
$form = $this->form;

$form->setIsReadonly();
$form->setDefaultLabelWidth(2);
?>

<?=Installer::buttonBack()?>

<h3><?=Tr::_('Connection \'%CONNECTION%\' Test', ['CONNECTION'=>$this->connection_name]);?></h3>

<?php if($this->OK): ?>
	<div class="OK" style="padding: 5px;margin: 5px;">OK</div>
<?php else: ?>
	<div class="error" style="padding: 5px;margin: 5px;">
		<strong><?=Jet\Tr::_('Error:');?></strong>
		<?=$this->error_message;?>
	</div>
<?php endif; ?>


<?=$form->start()?>
<?=$form->message()?>

<?=$form->field('name')?>
<?=$form->field('driver')?>


<?=$form->field('DSN')?>
<?=$form->field('username')?>
<?=$form->field('password')?>

<a href="?edit_connection=<?=$this->connection_name;?>" class="btn btn-default"><?=Jet\Tr::_('Edit connection');?></a>

<?=$form->end()?>

