<?php
namespace JetStudio;

$form = Modules_Manifest::getPageCreateForm();


$form->field('page_name')->input()->addJsAction('onkeyup', 'JetStudio.Modules.editModule.addPage.generateId(this.value);');
$form->field('site_id')->input()->addJsAction('onchange', 'JetStudio.Modules.editModule.addPage.toggleFields(this.options[this.selectedIndex].value);');

echo $form->start();

echo $form->field('site_id');
echo $form->field('page_name');
echo $form->field('page_id');

echo $form->end();
