<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

$site = Sites::getCurrentSite();

if($site) {
	return;
}
?>
<div class="toolbar" id="main-toolbar">
	<?=UI::button_create(Tr::_('Create a new module'))->setOnclick('JetStudio.Modules.createModule.openDialog()')?>
</div>
<div class="container-fluid" id="main-edit-area">
	<?=Application::getGeneralView()->render('messages');?>
	<?=Application::getView()->render('models_list');?>
</div>
