<?php
namespace JetStudio;

use Jet\Application_Modules;
use Jet\Tr;
use Jet\UI;
use Jet\Form;
use Jet\Mvc_View;
use Jet\UI_button;

/**
 * @var Mvc_View $this
 */

$current = Modules::getCurrentModule();

if(!$current) {
	return;
}

$form = $current->getEditForm();

$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);
$form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 6
]);

$add_page_dialog = UI::dialog('add_page_dialog', Tr::_('Add page'), 600);

$add_controller_dialog = UI::dialog('add_controller_dialog', Tr::_('Add controller'), 600);

$add_menu_item_dialog = UI::dialog('add_menu_item_dialog', Tr::_('Add menu item'), 900);

$delete_content_dialog = UI::dialog('delete_content', Tr::_('Delete this content'), 600);

$delete_module_dialog = UI::dialog('delete_module', Tr::_('Delete this module'), 600);

$module_wizard_select_dialog = UI::dialog('module_wizard_select_dialog', Tr::_('Please select module wizard'), 800);

$module_wizard_setup_dialog = UI::dialog('module_wizard_setup_dialog', Tr::_('Setup module wizard'), 1040);


?>

<?=$form->start()?>
<input type="hidden" name="generate" value="0"/>

<div class="toolbar" id="main-toolbar">
	<?=UI::button_save()?>
	<?=UI::button_save(Tr::_('Save and generate'))->setOnclick("this.form.generate.value=1;this.form.submit()")?>
	<?=UI::button(Tr::_('Wizard'))->setOnclick("$('#module_wizard_select_dialog').modal('show');")->setClass('success')->setIcon('magic')?>

	<?php if($current->getIsInstalled()):
		if(!$current->isMandatory()):
			if($current->getIsActive()):
				?>
				<?=UI::button(Tr::_('Deactivate'))->setUrl(Modules::getActionUrl('deactivate'))->setClass('danger')?>
				<?php
			else:
				?>
				<?=UI::button(Tr::_('Activate'))->setUrl(Modules::getActionUrl('activate'))->setClass('success')?>
				<?php
			endif;
			?>
			<?=UI::button(Tr::_('Uninstall'))->setUrl(Modules::getActionUrl('uninstall'))->setClass('danger')?>
			<?php
		endif;
	else:
		?>
		<?=UI::button(Tr::_('Install'))->setUrl(Modules::getActionUrl('install'))->setClass('info')?>
		<?=UI::button(Tr::_('Install and activate'))->setUrl(Modules::getActionUrl('install_activate'))->setClass('success')?>
	<?php endif; ?>

	<?=UI::button_create(Tr::_('Add controller'))->setOnclick('JetStudio.Modules.editModule.addController.openDialog()')?>
	<?=UI::button_create(Tr::_('Add page'))->setOnclick('JetStudio.Modules.editModule.addPage.openDialog()')?>
	<?=UI::button_create(Tr::_('Add menu item'))->setOnclick('JetStudio.Modules.editModule.addMenuItem.openDialog()')?>
	<?=UI::button_delete(Tr::_('Delete this module'))->setOnclick('JetStudio.Modules.deleteModule.openDialog()')?>

</div>
<div class="container-fluid" id="main-edit-area">
	<?=Application::getGeneralView()->render('messages');?>

	<legend>
		<?=Tr::_('Module')?>
		<span style="font-weight: bolder"><?=$current->getLabel()?></span> <span style="color: #aaaaaa;font-size: 12px;"><?=$current->getName()?></span>
	</legend>


	<?=$form->field('module_name')?>
	<?=$form->field('module_label')?>
	<?=$form->field('vendor')?>
	<?=$form->field('version')?>
	<?=$form->field('description')?>
	<?=$form->field('is_mandatory')?>
	<?=$form->field('is_active')?>
	<?=$form->field('is_installed')?>

	<legend><?=Tr::_('ACL actions')?></legend>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-6">
			<fieldset style="margin-bottom: 40px;">
				<table>
					<thead>
					<tr>
						<th><?=Tr::_('Action')?></th>
						<th><?=Tr::_('Description')?></th>
					</tr>
					</thead>
					<tbody>
					<?php for( $m=0;$m<Modules_Manifest::MAX_ACL_ACTION_COUNT;$m++ ):
						$prefix = '/ACL_action/'.$m;

						if(!$form->fieldExists($prefix.'/action')) {
							break;
						}

						$action = $form->field($prefix.'/action');
						$action->input()->addCustomCssStyle('width:300px;');
						$description = $form->field($prefix.'/description');
						$description->input()->addCustomCssStyle('width:300px;');

						?>
						<tr>
							<td style="padding: 5px;"><?=$action->input()?></td>
							<td style="padding: 5px;"><?=$description->input()?></td>
						</tr>
					<?php endfor; ?>
					</tbody>
				</table>
			</fieldset>
		</div>
	</div>

</div>
<?=$form->end()?>

<div id="controllers_list_area">
	<?php require 'controllers/list.phtml'; ?>
</div>

<div id="module_pages_list_area">
	<?php require 'pages/list.phtml'; ?>
</div>


<div id="module_menu_items_list_area">
	<?php require 'menu_items/list.phtml'; ?>
</div>


<?=$add_page_dialog->start()?>
	<div id="add_page_form_area">
		<?php require 'add_page_form.phtml' ?>
	</div>

<?=$add_page_dialog->footer()?>
	<?=UI::button_save(Tr::_('Add page'))->setOnclick('JetStudio.Modules.editModule.addPage.send()')?>
<?=$add_page_dialog->end()?>


<?=$add_controller_dialog->start()?>
	<div id="add_controller_form_area">
		<?php require 'add_controller_form.phtml' ?>
	</div>
<?=$add_controller_dialog->footer()?>
	<?=UI::button_save(Tr::_('Add page'))->setOnclick('JetStudio.Modules.editModule.addController.send()')?>
<?=$add_controller_dialog->end()?>


<?=$add_menu_item_dialog->start()?>
	<div id="create_menu_item_form_form_area">
		<?php require 'add_menu_item_form.phtml'; ?>
	</div>

<?=$add_menu_item_dialog->footer()?>
	<?=UI::button_save(Tr::_('Add menu item'))->setOnclick('JetStudio.Modules.editModule.addMenuItem.send()')?>
<?=$add_menu_item_dialog->end()?>



<?=$delete_content_dialog->start()?>
	<?=Tr::_('Do You really want to delete this content item ?');?>
<?=$delete_content_dialog->footer()?>
	<form method="post" action="<?=Modules::getActionUrl('page/content/delete')?>" id="delete_content_form">
		<input type="hidden" name="site" value=""/>
		<input type="hidden" name="page" value=""/>
		<input type="hidden" name="index" value="0"/>
	<?=UI::button_delete()->setType('submit');?>
	</form>
<?=$delete_content_dialog->end()?>


<?=$delete_module_dialog->start()?>
	<?=Tr::_('Do You really want to delete this module?');?>
<?=$delete_module_dialog->footer()?>
	<?=UI::button_delete()->setUrl( Modules::getActionUrl('delete') ); ?>
<?=$delete_module_dialog->end()?>


<?php
echo $module_wizard_select_dialog->start();
	foreach( Modules_Wizard::getList() as $wizard ):
		?>
		<b><?=$wizard->getTitle()?></b>
		<p><?=$wizard->getDescription()?></p>
		<div align="right">
			<?=UI::button(Tr::_('Create'))->setClass('info')->setOnclick("JetStudio.Modules.Wizard.select('".$wizard->getName()."')")?>
		</div>
		<hr/>
		<?php
	endforeach;
echo $module_wizard_select_dialog->end();
?>

<?=$module_wizard_setup_dialog->start()?>
	<iframe id="module_wizard_setup_form_area" style="width: 1000px;height: 500px;border: 1px inset #c9c9c9"></iframe>
<?=$module_wizard_setup_dialog->end()?>
