<?php
use Jet\Tr;
use Jet\Mvc_Page;
?>
<div style="width: 100%;vertical-align: middle;text-align: center;">
	<a href="<?=Mvc_Page::get('admin/classic/articles')->getURL(); ?>" class="btn btn-default" style="width: 200px;">
		<jetml_icon icon="module/JetExample.Articles/module" size="large"></jetml_icon>
		<?=Tr::_('Articles');?>
	</a>
	<a href="<?=Mvc_Page::get('admin/classic/images')->getURL(); ?>" class="btn btn-default" style="width: 200px;">
		<jetml_icon icon="module/JetExample.Images/module" size="large"></jetml_icon>
		<?=Tr::_('Images');?>
	</a>

	<br/>
	<br/>
	<br/>

	<a href="<?=Mvc_Page::get('admin/classic/roles')->getURL(); ?>" class="btn btn-default" style="width: 200px;">
		<jetml_icon icon="module/JetExample.AdminRoles/module" size="large"></jetml_icon>
		<?=Tr::_('Manage roles');?>
	</a>

	<a href="<?=Mvc_Page::get('admin/classic/users')->getURL(); ?>" class="btn btn-default" style="width: 200px;">
		<jetml_icon icon="module/JetExample.AdminUsers/module" size="large"></jetml_icon>
		<?=Tr::_('Manage users');?>
	</a>
</div>