<?php
/**
 *
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license http://www.php-jet.net/license/license.txt
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
$prefix = '__profiler__';
?>
<div id="__profiler__" class="__error">
	<div class="__close_btn" onclick="document.getElementById('__profiler__').style.display='none';">&#x2715;</div>
	<div class="__title">
		PROFILER ERROR
	</div>
	<div class="__error_msg">
		<?=$this->save_error;?>
	</div>
</div>
