<?php
/**
 *
 * @copyright Copyright (c) Miroslav Marek <mirek.marek@web-jet.cz>
 * @license http://www.php-jet.net/license/license.txt
 * @author Miroslav Marek <mirek.marek@web-jet.cz>
 */
?>
<div id="__profiler__" style="position: fixed; top: 0;right: 0;background-color: #c9c9c9;padding: 5px;font-family: Helvetica, Arial, sans-serif;border: 1px inset #ffffff;font-size:14px;">
	<div style="display: table">
		<div style="display: table-row">
			<div style="display:table-cell;padding: 0 20px 0 0;border: none;">
				<span onclick="document.getElementById('__profiler__').style.display='none';">X</span>
			</div>
			<div style="display:table-cell;padding: 0 20px 0 0;border: none;">
				<?=$this->save_error;?>
			</div>
		</div>
	</div>
</div>
