<?php
use Jet\UI;
use Jet\Mvc;

?>
<div style="position: absolute;top:15px; right: 15px;">
	<?php foreach( Mvc::getBase()->getLocales() as $locale ): ?>
		<?php if( $locale->toString() == Mvc::getLocale()->toString() ): ?>
			<?= UI::flag( $locale ) ?>
		<?php else:
			$equal_page = Mvc::getPage( locale: $locale );
			if( !$equal_page ) {
				$equal_page = Mvc::getHomePage( locale: $locale );
			}
			?>
			<a href="<?= $equal_page->getURL() ?>"><?= UI::flag( $locale ) ?></a>
		<?php endif; ?>
	<?php endforeach; ?>
</div>
