<?php
use Jet\Tr;
use Jet\UI;
use Jet\Mvc;
use Jet\Mvc_Page;

?>

<div style="position: absolute;top:15px; right: 15px;">
	<?php foreach( Mvc::getCurrentSite()->getLocales() as $locale ): ?>
		<?php if( $locale->toString()==Mvc::getCurrentLocale()->toString() ): ?>
			<?=UI::flag( $locale )?>
		<?php else:
			$equal_page = Mvc_Page::get( null, $locale );
			if( !$equal_page ) {
				$equal_page = Mvc_Page::get( Mvc_Page::HOMEPAGE_ID, $locale );
			}
			?>
			<a href="<?=$equal_page->getURL()?>"><?=UI::flag( $locale )?></a>
		<?php endif; ?>
	<?php endforeach; ?>
</div>
