<?php
use Jet\Tr;
use Jet\Mvc_View;
use Jet\Form;

/**
 * @var Mvc_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 10 ] );
?>

<div class="card" style="margin-top: 40px;">
	<div class="card-body">
		<div class="card-title"><h5><?=Tr::_( 'Please change your password' )?></h5></div>

		<?=$form->start()?>

		<?=$form->field( 'current_password' )?>
		<?=$form->field( 'password' )?>

		<input type="submit" value="<?=Tr::_( 'Change password' );?>" class="btn btn-primary" style="float: right"/>
		<?=$form->end()?>
	</div>
</div>


