<?php
use Jet\Tr;
use Jet\UI;
use Jet\Mvc;
use Jet\Mvc_Page;

?>

<div class="card">
	<div class="card-body">
		<?php require '_language_select.phtml'; ?>
		<div class="card-title"><h5><?=Tr::_( 'Account is blocked' )?></h5></div>

		<table>
			<tr>
				<td style="padding: 5px;">
					<?=UI::icon( 'times-circle' )->setSize( 50 )?>
				</td>
				<td>
					<?=Tr::_( '<b>Your account is blocked!</b><br/>Please contact your system administrator.' );?>
				</td>
			</tr>
		</table>

		<div style="padding-top: 10px">
			<a href="?logout" class="btn btn-light"><?=Tr::_( 'Logout' );?></a>
		</div>
	</div>
</div>
