<?php
use Jet\Tr;
use Jet\UI;
use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'login_form' );

$form->field( 'username' )->setPlaceholder( 'username' );
$form->field( 'password' )->setPlaceholder( 'password' );

?>


<div class="card">
	<div class="card-body">
		<?php require '_language_select.phtml'; ?>

		<div class="card-title"><h5><?=Tr::_( 'Sign In' )?></h5></div>
		<?=$form->start()?>
		<?php if( $form->getCommonMessage() ): ?>
			<div id="login-alert" class="alert alert-danger">
				<?=$form->getCommonMessage()?>
			</div>
		<?php endif; ?>

		<div style="margin-bottom: 25px" class="input-group">
			<div class="input-group-prepend">
				<span class="input-group-text"><?=UI::icon( 'user' )?></span>
			</div>
			<?=$form->field( 'username' )->input()?>
		</div>

		<div style="margin-bottom: 25px" class="input-group">
			<div class="input-group-prepend">
				<span class="input-group-text"><?=UI::icon( 'lock' )->setTag( 'i' )?></span>
			</div>
			<?=$form->field( 'password' )->input()?>
		</div>


		<div style="margin-top:10px" class="form-group">
			<div class="col-sm-12 controls">
				<div style="float: right">
					<input type="submit" class="btn btn-primary" value="<?=Tr::_( 'Sign In' )?>"/>
				</div>
			</div>
		</div>

		<?=$form->end()?>

	</div>
</div>

