<?php

use Jet\Tr;
use Jet\UI;
use Jet\Mvc_View;
use Jet\Form;

/**
 * @var Mvc_View $this
 * @var Form $form
 */
$form = $this->getRaw( 'form' );

$form->setDefaultLabelWidth( [Form::LJ_SIZE_MEDIUM => 2] );
$form->setDefaultFieldWidth( [Form::LJ_SIZE_MEDIUM => 10] );
?>

<div class="card">
	<h5 class="card-header">
		<?= Tr::_( 'Please change your password' ) ?>
		<?php require '_language_select.phtml'; ?>
	</h5>
	<?= $form->start() ?>
	<div class="card-body">
		<table>
			<tr>
				<td style="padding: 5px;">
					<?= UI::icon( 'exclamation-circle' )->setSize( 50 ) ?>
				</td>
				<td>
					<?= Tr::_( '<b>Your password expired.</b><br/>Please change your password.' ); ?>
				</td>
			</tr>
		</table>

		<div style="padding-top: 30px">
			<?= $form->field( 'password' ) ?>
		</div>

		<div class="text-right">
			<a href="?logout" class="btn btn-light"><?= Tr::_( 'Logout' ); ?></a>
			<input type="submit" value="<?= Tr::_( 'Change password' ); ?>" class="btn btn-primary"/>
		</div>
	</div>
	<?= $form->end() ?>
</div>

