<?php
use Jet\Tr;
use Jet\UI;
use Jet\Mvc_View;
use Jet\Form;

/**
 * @var Mvc_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );

$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 8 ] );
?>

<div class="card">
	<div class="card-body">
		<?php require '_language_select.phtml'; ?>

		<div class="card-title"><h5><?=Tr::_( 'Please change your password' )?></h5></div>

		<table>
			<tr>
				<td style="padding: 5px;">
					<?=UI::icon( 'exclamation-circle' )->setSize( 50 )?>
				</td>
				<td>
					<?=Tr::_( '<b>Your password expired.</b><br/>Please change your password.' );?>
				</td>
			</tr>
		</table>


		<div style="padding-top: 30px">
			<?=$form->start()?>

			<?=$form->field( 'password' )?>

			<input type="submit" value="<?=Tr::_( 'Change password' );?>" class="btn btn-primary"/>
			<a href="?logout" class="btn btn-light"><?=Tr::_( 'Logout' );?></a>

			<?=$form->end()?>
		</div>

	</div>
</div>

