<?php
namespace JetExampleApp;
use Jet\Mvc_Layout;
use Jet\Tr;

/**
 * @var Installer_Step_Controller[] $steps
 * @var Mvc_Layout                  $this
 */
$steps = $this->getRaw( 'steps' );
?>
<html>
<head>
	<title><?=Tr::_( 'PHP Jet - Example Project Installer' );?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>
	<jet_layout_header_suffix/>
	<link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"/>
	<link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
	<script src="//code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
	<style type="text/css">
		.stepPrev {

		}

		.stepCurrent {
			font-weight: bolder;
		}

		.stepNext {
			color: #c9c9c9;
		}

		.stepSub {
			padding-left: 10px;
		}
	</style>

</head>
<body style="margin: 0;padding: 0;background-color: #e9e9e9;">
<div class="container" id="container" style="width: 100%">

	<div class="row">
		<div class="col-md-12" style="background-color: #000000;color: #ffffff;font-size: 18px;font-weight: bolder;">
			<div style="padding: 4px;">
				<?=Tr::_( 'PHP Jet - Example Project Installer' );?>
			</div>
		</div>
	</div>

	<div class="row" style="">
		<div class="col-md-2" style="height: 100%;">
			<?php foreach( $steps as $step ):
				$class = '';
				if( $step->getIsSubStep() ) {
					$class = ' stepSub';
				}
				?>
				<?php if( $step->getIsPast() ): ?>
				<div class="stepPrev<?=$class;?>">
					<?php if( $step->getIsAvailable() ): ?>
						<a href="<?=$step->getURL();?>"><?=$step->getLabel();?></a>
					<?php else: ?>
						<?=$step->getLabel();?>
					<?php endif; ?>
				</div>
			<?php endif; ?>
				<?php if( $step->getIsCurrent() ): ?>
				<div class="stepCurrent<?=$class;?>"><?=$step->getLabel();?></div>
			<?php endif; ?>
				<?php if( $step->getIsFuture() ): ?>
				<div class="stepNext<?=$class;?>"><?=$step->getLabel();?></div>
			<?php endif; ?>
			<?php endforeach; ?>
		</div>
		<div class="col-md-10" style="background-color: #ffffff;min-height: 100%;">
			<div style="padding: 10px;">
				<jet_layout_main_position/>
			</div>
		</div>
	</div>

</div>

</body>
</html>