<?php
namespace JetApplication;
use Jet\Mvc_Layout;
use Jet\Tr;

/**
 * @var Installer_Step_Controller[] $steps
 * @var Mvc_Layout                  $this
 */
$steps = $this->getRaw( 'steps' );

$this->requireJavascriptFile( JQUERY_JS_URL );
$this->requireCssFile( BOOTSTRAP_CSS_URL );
$this->requireCssFile(FONT_AWESOME_CSS_URL);
$this->requireCssFile(FLAGS_CSS_URL);
?>
<html>
<head>
	<title><?=Tr::_( 'PHP Jet - Example Project Installer' );?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>

	<style type="text/css">

		#container {
			background-color: #111111;
			width: 100%
		}

		.title-area {
			background-color: #000000;
			color: #ffffff;
			font-size: 18px;
			font-weight: bolder;
			padding: 10px;
		}

		.progress-area {
			height: 100%;
		}

		.step {
			padding: 5px;
		}
		.step-prev {

		}

		.step-prev a {
			color: #cccccc;
		}

		.step-current {
			background-color: #eeeeee;
			padding: 5px;
			font-weight: bolder;
		}

		.step-next {
			color: #666666;
		}

		.step-sub {
			padding-left: 10px;
		}

		.main {
			background-color: #ffffff;
			min-height: 100%;
			padding: 10px;;
		}

	</style>

</head>
<body style="margin: 0;padding: 0;background-color: #e9e9e9;">
<div class="container" id="container">

	<div class="row">
		<div class="col-md-12 title-area">
			<?=Tr::_( 'PHP Jet - Example Project Installer' );?>
		</div>
	</div>

	<div class="row">
		<div class="col-md-2 progress-area">
			<?php foreach( $steps as $step ):
				$class = '';
				if( $step->getIsSubStep() ) {
					$class = ' step-sub';
				}
				?>
				<?php if( $step->getIsPast() ): ?>
				<div class="step step-prev<?=$class;?>">
					<?php if( $step->getIsAvailable() ): ?>
						<a href="<?=$step->getURL();?>"><?=$step->getLabel();?></a>
					<?php else: ?>
						<?=$step->getLabel();?>
					<?php endif; ?>
				</div>
			<?php endif; ?>
				<?php if( $step->getIsCurrent() ): ?>
				<div class="step step-current<?=$class;?>"><?=$step->getLabel();?></div>
			<?php endif; ?>
				<?php if( $step->getIsFuture() ): ?>
				<div class="step step-next<?=$class;?>"><?=$step->getLabel();?></div>
			<?php endif; ?>
			<?php endforeach; ?>
		</div>
		<div class="col-md-10 main">
			<h1><?=Installer::getCurrentStepController()->getLabel()?></h1>
			<hr/>
			<jet_layout_main_position/>
		</div>
	</div>

</div>

</body>
</html>