<?php
namespace JetApplicationModule\JetExample\Content\Images;

use Jet\Mvc_View;

/**
 * @var Mvc_View  $this
 */

?>
<?php require 'parts/js.phtml'; ?>

<?php require 'parts/toolbar.phtml' ?>

<div class="row">
	<?php  require 'parts/galleries.phtml'; ?>

	<div class="col-md-9 main-col">

		<div id="edit_form_area">
			<?php require 'parts/edit-form.phtml' ?>
		</div>

		<div class="well">
			<div id="upload_form_area">
				<?php require 'parts/upload-form.phtml' ?>
			</div>

			<div id="images_area">
				<?php  require 'parts/images.phtml'; ?>
			</div>

		</div>
	</div>
</div>
