<?php

use Jet\MVC_View;
use Jet\Form_Renderer;

/**
 * @var MVC_View $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'checkbox' );
}

$field = $r->getField();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$attrs = [
	'type' => 'checkbox',
	'name' => $field->getTagNameValue(),
	'id' => $field->getId(),
	'value' => 1
];

if($field->getIsReadonly()) {
	$attrs['disabled'] = 'disabled';
}

if($field->getValue()) {
	$attrs['checked'] = 'checked';
}
?>
<div class="<?= $r->getCssClasses() ?>">
	<input <?=$r->renderAttributes($attrs)?>/>

	<label class="form-check-label" for="<?= $field->getId() ?>"><?= $r->getField()->getLabel() ?></label>
</div>