<?php

use Jet\Mvc_View;
use Jet\Form_Renderer;
use Jet\Form_Field_File;
use Jet\Data_Text;

/**
 * @var Mvc_View $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

/**
 * @var Form_Field_File $field
 */
$field = $r->getField();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$attrs = [
	'type' => 'file',
	'name' => $field->getTagNameValue(),
	'id' => $field->getId(),
];

if( $field->getIsReadonly() ) {
	$attrs['disabled'] = 'disabled';
}
if( $field->getIsRequired() ) {
	$attrs['required'] = 'required';
}
if( $field->getPlaceholder() ) {
	$attrs['placeholder'] = Data_Text::htmlSpecialChars( $field->getPlaceholder() );
}

if( $field->getAllowMultipleUpload() ) {
	$attrs['multiple'] = 'multiple';
}
if( $field->getAllowedMimeTypes() ) {
	$attrs['accept'] = implode( '|', $field->getAllowedMimeTypes() );
}

$attrs['value'] = '';

?>
<input <?=$r->renderAttributes($attrs)?>/>