<?php

use Jet\MVC_View;
use Jet\Form_Renderer;
use Jet\Form_Field_Select;
use Jet\Data_Text;

/**
 * @var MVC_View $this
 * @var Form_Renderer $r
 * @var Form_Field_Select $field
 */
$r = $this->getRaw( 'element' );


$field = $r->getField();
$value = $field->getValue();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$container_class = 'radio';
if($field->getIsReadonly()) {
	$container_class = 'radio disabled';
}

$attrs = $r->getStdInputFieldAttributes('radio');

?>
<?php foreach( $field->getSelectOptions() as $key => $option ):
	$attrs['value'] = Data_Text::htmlSpecialChars( $key );
	?>

	<div class="<?= $container_class ?>">
		<input <?=$r->renderAttributes($attrs)?>/>
		<label class="form-check-label" for="<?= $field->getId() ?>"><?= $option ?></label>
	</div>
<?php endforeach; ?>
