<?php

use Jet\MVC_View;
use Jet\Form_Renderer_Field_WYSIWYG;
use Jet\Form_Field_WYSIWYG;

/**
 * @var MVC_View $this
 * @var Form_Renderer_Field_WYSIWYG $r
 * @var Form_Field_WYSIWYG $field
 */
$r = $this->getRaw( 'renderer' );
$field = $r->getField();



//-----------------------------------------------------------------------------------

/** @noinspection PhpStatementHasEmptyBodyInspection */
if( !$r->getEditorCSSFiles() ) {
	//$r->appendWYSIWYGEditorCSSFile( URI: '//cdn.tiny.cloud/1/no-api-key/tinymce/5/skins/lightgray/skin.min.css', media: '');
}

if( !$r->getEditorJavaScriptFiles() ) {
	$r->setEditorJavaScriptFiles([
	    '//cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js',
	]);
}

if( !$r->getEditorConfig() ) {
	$r->setEditorConfig([
	    
	    'mode'                    => 'exact',
	    //'theme'                   => 'silver',
	    //'skin'                    => false,
	    'apply_source_formatting' => true,
	    'remove_linebreaks'       => false,
	    'entity_encoding'         => 'raw',
	    'convert_urls'            => false,
	    'verify_html'             => true,
	    
	    'force_br_newlines' => false,
	    'force_p_newlines'  => false,
	    'forced_root_block' => '',
	    
	    
	    //'plugins'       => 'advlist autolink lists link image charmap print preview hr anchor pagebreak searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking save table contextmenu directionality template paste textcolor colorpicker textpattern imagetools',
	    'paste_as_text'     => true,
	    
	    //'content_css' => '/css/wysiwyg.css',
    ]);
}

if( !$r->getEditorInitializeCodeGenerator() ) {
	$r->setEditorInitializeCodeGenerator( function( Form_Field_WYSIWYG $field, array $editor_config ) {
	    
	    $editor_config['selector'] = '#' . $field->getId();
	    
	    if( $field->getIsReadonly() ) {
		    $editor_config['readonly'] = 1;
	    }
	    
	    /** @noinspection JSUnresolvedVariable */
	    /** @noinspection BadExpressionStatementJS */
	    return '<script>'
		    . 'tinymce.init(' . json_encode( $editor_config ) . ')'
		    . '</script>' . PHP_EOL;
	    
    } );
}


//-----------------------------------------------------------------------------------
/*
if( !$r->getEditorCSSFiles() ) {
	$r->appendWYSIWYGEditorCSSFile( URI: '//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css', media: '');
}

if( !$r->getEditorJavaScriptFiles() ) {
	$r->setEditorJavaScriptFiles([
	    '//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js'
	]);
}

if( !$r->getEditorConfig() ) {
	$r->setEditorConfig([
		'height' => 500,
	]);
}

if( !$r->getEditorInitializeCodeGenerator() ) {
	
	$r->setEditorInitializeCodeGenerator( function( Form_Field_WYSIWYG $field, array $editor_config ) {
	    return '<script type="text/javascript">'
		    .'$("#'.$field->getId().'").summernote('.json_encode($editor_config).');'
		    .'</script>'.PHP_EOL;
	});
}
*/
//-----------------------------------------------------------------------------------

?>
<textarea <?=$r->renderTagAttributes()?>><?= $field->getValueRaw() ?></textarea>

<?= $r->generateEditorInitializeCode(); ?>
