<?php
namespace JetStudio;


use Jet\Http_Request;
use Jet\Tr;

$current = Forms::getCurrentClass();

if( !$current ) {
	return;
}

$current_property_name = Forms::getCurrentPropertyName();
?>

<table style="width: 100%">
	<tr>
		<td colspan="3"><b><?= Tr::_( 'Properties' ) ?></b></td>
	</tr>
	<?php foreach( $current->getProperties() as $property ): ?>
		<tr>
			<td>
				<?php if( $current_property_name == $property->getName() ): ?>
					<b class="badge badge-info"><?= $property->getName() ?></b>
				<?php else: ?>
					<a href="<?= Http_Request::currentURI( ['property' => $property->getName()], [
						'action'
					] ) ?>"><?= $property->getName() ?></a>
				<?php endif; ?>
			</td>

			<td style="width: 200px;font-size: 11px;">
				<div style="padding-top: 4px;">
				</div>

			</td>
			<td style="width: 150px">
				<?= $property->getIcons() ?>
			</td>
		</tr>

	<?php endforeach; ?>
</table>
