<?php

namespace JetStudio;

use Jet\Tr;
use Jet\UI;
use Jet\UI_dialog;

$delete_menu_item_dialog = UI::dialog( 'delete_menu_item_dialog', Tr::_( 'Delete menu' ), UI_dialog::SIZE_LARGE );

echo $delete_menu_item_dialog->start();
echo Tr::_( 'Do you really want to delete this menu item?' );
echo $delete_menu_item_dialog->footer();
echo UI::button_delete()->setUrl( Modules::getActionUrl( 'menu_item/delete' ) );
echo $delete_menu_item_dialog->end();
