<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

$current = DataModels::getCurrentModel();

if(!$current) {
	return;
}
?>

<div>
	<?php foreach($current->getOuterRelations() as $relation):
		$this->setVar('relation', $relation);

		?>
		<div>
			<div class="card" id="relation_panel_<?=$relation->getInternalId()?>">
				<div class="card-header" id="relation_header_area_<?=$relation->getInternalId()?>" data-toggle="collapse" data-target="#relation_detail_area_<?=$relation->getInternalId()?>">
					<?php require 'list/item-header.phtml';  ?>
				</div>

				<div class="card-body collapse" id="relation_detail_area_<?=$relation->getInternalId()?>">
					<?php require 'list/item-body.phtml';  ?>
				</div>
			</div>

		</div>
	<?php endforeach; ?>
</div>
