<?php
namespace JetApplicationModule\Jet\BreadcrumbNavigation;
use Jet;

/**
 * @var Jet\Mvc_NavigationData_Breadcrumb_Abstract[] $data
 */
$data = $this->data;
?>
<div>
<hr/>
	<?php foreach( $data as $d ): ?>
		<?php if(!$d->getIsLast()): ?>
			<a href="<?=$d->getURI(); ?>"><?=$d->getTitle(); ?></a>&nbsp;&gt;&nbsp;
		<?php else: ?>
			<b><?=$d->getTitle(); ?></b>
		<?php endif; ?>
	<?php endforeach; ?>

<hr/>
</div>
