<?php

use Jet\MVC_Layout;
use Jet\MVC;
use Jet\Tr;

/**
 * @var MVC_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html lang="<?= MVC::getLocale()->getLanguage() ?>">
<head>
	<?php require 'parts/head.phtml'; ?>
</head>
<body>
<div class="container-fluid">
	<div class="page-header card text-white bg-dark">
		<div class="card-body">
			<h1><?= Tr::_( 'Hello WORLD!' ) ?></h1>
			<small><?= Tr::_( 'PHP Jet Example Application' ); ?></small>
		</div>
	</div>

	<jet_module module="UI.Web" action="breadcrumbNavigation" view="default" is_cacheable="true"/>

	<div class="row">
		<div class="col-md-3">
			<jet_module module="UI.Web" action="main_menu" is_cacheable="true"/>
			<jet_layout_position name="left"/>
		</div>
		<div class="col-md-7" style="padding-top: 10px;padding-bottom: 20px;">
			<jet_layout_main_position/>
		</div>
		<div class="col-md-2">
			<div class="well well-small">
				<jet_module module="Test.MVC" action="test_mvc_info" is_cacheable="true"/>
			</div>
			<jet_layout_position name="right"/>
		</div>
	</div>
</div>
</body>
</html>