<?php

use Jet\MVC_Layout;
use Jet\Tr;
use Jet\UI;
use Jet\MVC;
use Jet\Auth;
use Jet\UI_icon;

/**
 * @var MVC_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html lang="<?= MVC::getLocale()->getLanguage() ?>">
<head>
	<?php require 'parts/head.phtml'; ?>
</head>
<body>
<div class="container-fluid">
	<div class="page-header card text-white bg-danger">
		<div class="card-body">
			<h1><?= UI::icon( 'user-secret' )->setSize( UI_icon::SIZE_EXTRA_LARGE ) ?> <?= Tr::_( 'Secret area!' ) ?></h1>
			<small><?= Tr::_( 'PHP Jet Example Application' ); ?></small>
		</div>
	</div>

	<div class="row no-gutters">
		<div class="col-md-9">
			<jet_module module="UI.Web" action="breadcrumbNavigation" view="secret"/>
		</div>
		<div class="col-md-3">
			<jet_module module="Login.Web" action="current_user_bar"/>
		</div>
	</div>

	<div class="row">
		<?php if( Auth::getCurrentUser() ): ?>
			<div class="col-md-3">
				<jet_module module="UI.Web" action="secret_area_menu"/>
				<jet_layout_position name="left"/>
			</div>
			<div class="col-md-9" style="padding-top: 10px;padding-bottom: 20px;">
				<jet_layout_main_position/>
			</div>
		<?php else: ?>
			<div class="col-md-12" style="padding-top: 10px;padding-bottom: 20px;">
				<div class="container-fluid">
					<jet_layout_main_position/>
				</div>
			</div>
		<?php endif; ?>
	</div>
</div>

</body>
</html>