<?php

use Jet\MVC_Layout;
use Jet\MVC;
use Jet\Tr;

/**
 * @var MVC_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html lang="<?= MVC::getLocale()->getLanguage() ?>">
<head>
	<?php require 'parts/head.phtml'; ?>
</head>
<body>
<div class="container-fluid">
	<div class="text-white bg-dark" style="display: grid;grid-template-columns: 200px 1fr;align-items: center">
		<div><img src="https://php-jet.net/images/logo-st.svg" style="width: 180px;height: auto"></div>
		<div style="padding: 10px;">
			<b><?= Tr::_( 'Hello WORLD!' ) ?></b><br>
			<small><?= Tr::_( 'Example Application' ); ?></small>
		</div>
	</div>
	
	<div class="row no-gutters">
		<div class="col-md-9">
			<jet_module module="Web.UI" action="breadcrumbNavigation" view="default" is_cacheable="true"/>
		</div>
		<div class="col-md-3">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="text-right">
						<jet_module module="Web.Visitor.Login" action="current_user_bar"/>
						<jet_module module="Web.Visitor.SignUp" action="sign_up_link"/>
					</li>
				</ol>
			</nav>
		</div>
	</div>
	
	

	<div class="row">
		<div class="col-md-3">
			<jet_module module="Web.UI" action="main_menu" is_cacheable="true"/>
			<jet_layout_position name="left"/>
		</div>
		<div class="col-md-7" style="padding-top: 10px;padding-bottom: 20px;">
			<jet_layout_main_position/>
		</div>
		<div class="col-md-2">
			<div class="well well-small">
				<jet_module module="Test.MVC" action="test_mvc_info" is_cacheable="true"/>
			</div>
			<jet_layout_position name="right"/>
		</div>
	</div>
</div>
</body>
</html>