<?php

use Jet\MVC_Layout;
use Jet\Tr;
use Jet\UI;
use Jet\MVC;
use Jet\Auth;
use Jet\UI_icon;

/**
 * @var MVC_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html lang="<?= MVC::getLocale()->getLanguage() ?>">
<head>
	<?php require 'parts/head.phtml'; ?>
</head>
<body>
<div class="container-fluid">
	<div class="text-white bg-danger" style="display: grid;grid-template-columns: 200px 1fr;align-items: center">
		<div><img src="https://php-jet.net/images/logo-st.svg" style="width: 180px;height: auto"></div>
		<div style="padding: 10px;">
			<b><?= UI::icon( 'user-secret' )->setSize( UI_icon::SIZE_NORMAL ) ?> <?= Tr::_( 'Secret area!' ) ?></b><br>
			<small><?= Tr::_( 'Example Application' ); ?></small>
		</div>
	</div>

	<div class="row no-gutters">
		<div class="col-md-9">
			<jet_module module="Web.UI" action="breadcrumbNavigation" view="secret"/>
		</div>
		<div class="col-md-3">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="text-right">
						<jet_module module="Web.Auth.Login" action="current_user_bar"/>
						<jet_module module="Web.Auth.SignUp" action="sign_up_link"/>
					</li>
				</ol>
			</nav>
			
		</div>
	</div>

	<div class="row">
		<?php if( Auth::getCurrentUser() ): ?>
			<div class="col-md-3">
				<jet_module module="Web.UI" action="secret_area_menu"/>
				<jet_layout_position name="left"/>
			</div>
			<div class="col-md-9" style="padding-top: 10px;padding-bottom: 20px;">
				<jet_layout_main_position/>
			</div>
		<?php else: ?>
			<div class="col-md-12" style="padding-top: 10px;padding-bottom: 20px;">
				<div class="container-fluid">
					<jet_layout_main_position/>
				</div>
			</div>
		<?php endif; ?>
	</div>
</div>

</body>
</html>