<?php

use Jet\Mvc_Layout;
use Jet\Tr;
use Jet\UI;
use Jet\Mvc;
use Jet\Auth;

/**
 * @var Mvc_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html lang="<?= Mvc::getLocale()->getLanguage() ?>">
<head>
	<?php require 'parts/head.phtml'; ?>
</head>
<body>
<div class="container-fluid">
	<div class="page-header card text-white bg-danger">
		<div class="card-body">
			<h1><?= UI::icon( 'user-secret' )->setSize( 40 ) ?> <?= Tr::_( 'Secret area!' ) ?></h1>
			<small><?= Tr::_( "PHP Jet Example Application" ); ?></small>
		</div>
	</div>

	<jet_module module="UI.Web" action="breadcrumbNavigation" view="secret"/>

	<div class="row">
		<?php if( Auth::getCurrentUser() ): ?>
			<div class="col-md-3">
				<jet_module module="UI.Web" action="secret_area_menu"/>
				<jet_layout_position name="left"/>
			</div>
			<div class="col-md-9" style="padding-top: 10px;padding-bottom: 20px;">
				<jet_layout_main_position/>
			</div>
		<?php else: ?>
			<div class="col-md-12" style="padding-top: 10px;padding-bottom: 20px;">
				<div class="container-fluid">
					<jet_layout_main_position/>
				</div>
			</div>
		<?php endif; ?>
	</div>
</div>

</body>
</html>