<?php

namespace JetStudio;

use Jet\MVC_View;
use Jet\Form;
use Jet\Tr;
use Jet\UI;
use Jet\UI_dialog;

/**
 * @var MVC_View $this
 * @var DataModel_Definition_Model_Interface $related
 * @var Form $form
 */

$form = $this->getRaw( 'form' );
$related = $this->getRaw( 'related' );

echo $form->start();

echo $form->getCommonMessage();

echo $form->field( 'related_model_class_name' );
echo $form->field( 'join_type' );

$form->setDoNotTranslateTexts( true );
foreach( $related->getProperties() as $property ) {
	if( !$form->fieldExists( 'glue_' . $property->getName() ) ) {
		continue;
	}

	echo $form->field( 'glue_' . $property->getName() );
}

echo UI::dialog( '', '', UI_dialog::SIZE_LARGE )->footer();
echo $form->end();

echo UI::button_save( Tr::_( 'Create' ) )->setOnClick( 'DataModel.relation.create.createSend();return false;' );


