<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

$dialog = UI::dialog('dialog_create_new_menu', Tr::_('Create a new Menu'), 600);

echo $dialog->start();
?>
	<div id="<?=Menus_Menu::getCreateForm()->getId()?>_form_area">
		<?php require 'form.phtml'; ?>
	</div>
	<?php
echo $dialog->footer();
echo UI::button_save(Tr::_('Create'))->setOnclick('Menus.createMenu.createSend()');
echo $dialog->end();

