<?php

namespace JetStudio;

use Jet\UI;
use Jet\Tr;
use Jet\UI_dialog;

$dialog = UI::dialog( 'dialog_create_new_menu', Tr::_( 'Create a new Menu' ), UI_dialog::SIZE_LARGE );

echo $dialog->start();
?>
	<div id="<?= Menus_Menu::getCreateForm()->getId() ?>_form_area">
		<?php require 'form.phtml'; ?>
	</div>
	<?php
echo $dialog->footer();
echo UI::button_save( Tr::_( 'Create' ) )->setOnClick( 'Menus.createMenu.createSend()' );
echo $dialog->end();

