<?php
namespace JetApplicationModule\JetExample\AdminUIManager;
use Jet;

/**
 * @var Jet\Data_Paginator $paginator
 */
$paginator = $this->paginator;
?>

<?php if($paginator->getPagesCount()>1): ?>
	<table>
		<tr>
			<td nowrap style="width: 80px;">[<?php echo $paginator->getShowFrom();?>-<?php echo $paginator->getShowTo();?>/<?php echo $paginator->getDataItemsCount();?>]</td>

			<td style="width: 60px;">
				<?php if( ($p_URL=$paginator->getPrevPageURL()) ): ?>
					<a href="<?php echo $p_URL; ?>" class="btn btn-info">&lt;</a>
				<?php endif ?>
			</td>
			<td style="width: 260px;text-align: center">
				<?php
				$pages = $paginator->getPagesURL();

				$s_index = $paginator->getCurrentPageNo()-3;
				$e_index = $paginator->getCurrentPageNo()+3;
				if($s_index<1) {
					$e_index = $e_index+($s_index*-1)+1;
					$s_index=1;
				}

				if($e_index>count($pages)) {
					$e_index = count($pages);
					$s_index = $e_index-6;
					if($s_index<1) {
						$s_index = 1;
					}
				}


				for($p_no=$s_index; ($p_no<=$e_index && isset($pages[$p_no])) ;$p_no++):
					$p_URL = $pages[$p_no];

					?>
					<?php if($p_no==$paginator->getCurrentPageNo()): ?>
					<strong><?php echo $p_no; ?></strong>
				<?php else: ?>
					<a href="<?php echo $p_URL; ?>"><?php echo $p_no; ?></a>
				<?php endif; ?>
				<?php endfor; ?>
			</td>
			<td style="width: 60px;">
				<?php if( ($p_URL=$paginator->getNextPageURL()) ): ?>
					<a href="<?php echo $p_URL; ?>" class="btn btn-info">&gt;</a>
				<?php endif ?>
			</td>

		</tr>
	</table>
<?php endif; ?>
