<?php
namespace JetApplicationModule\Visitor\SignUp;

use Jet\Auth;
use Jet\MVC_Page_Interface;
use Jet\MVC_View;use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View   $this
 * @var MVC_Page_Interface $page
 */

$page = $this->getRaw('page');
?>
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="text-right">
			<?php if(!Auth::getCurrentUser()): ?>
			<a href="<?=$page->getURL()?>"><?=UI::icon('user-plus')?> <?=Tr::_('Sign up')?></a>
			<?php endif; ?>
			&nbsp;
		</li>
	</ol>
</nav>