<?php
namespace JetStudioModule\ApplicationModules;

use Jet\MVC_View;
use JetStudio\JetStudio_UI;

/**
 * @var MVC_View $this
 */

$current = Main::getCurrentModule();

if( !$current ) {
	return;
}

$form = $current->getCloneForm();

?>

<?= $form->start() ?>
<input type="hidden" name="generate" value="0"/>

<?= JetStudio_UI::messages(); ?>

<div class="form-fields" style="grid-template-columns: 0.7fr 2fr;">
	<?= $form->field( 'module_name' ) ?>
	<?= $form->field( 'module_label' ) ?>
	<?= $form->field( 'vendor' ) ?>
	<?= $form->field( 'version' ) ?>
</div>

<?= $form->end() ?>