<?php
namespace JetApplicationModule\JetExample\Content\Images;

use Jet\UI;
use Jet\Form;
use Jet\Mvc_View;

use JetApplication\Application;

/**
 * @var Mvc_View                     $this
 * @var Form                         $edit_form
 */

$edit_form = $this->getRaw( 'edit_form' );

$edit_form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 1 ] );
$edit_form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 5 ] );
?>


	<?=$edit_form->start()?>


<?php foreach( Application::getWebSite()->getLocales() as $locale ):
	$field = $edit_form->field( '/localized/'.$locale.'/title' );

	echo $field->row()->start();
		echo $field->error();
		?>
			<label for="<?=$field->getId()?>" class="col-md-1 control-label"><?=$locale->getLanguageName()?> <?=UI::flag($locale)?></label>
		<?php

		echo $field->container()->start();
			echo $field->input();
		echo $field->container()->end();

	echo $field->row()->end();

endforeach;?>


	<div class="form-group row">
		<div class="col-md-1"></div>
		<div class="col-md-5">
			<?php if( !$edit_form->getIsReadonly() ):
				echo UI::button_save()->setClass('default');
			endif; ?>
		</div>
	</div>
	<?=$edit_form->end()?>
