<?php
namespace JetApplicationModule\JetExample\Content\Images;

use Jet\UI;

use Jet\Tr;
use Jet\Form;
use Jet\Mvc_View;
use Jet\UI_button;

/**
 * @var Mvc_View                     $this
 * @var Gallery                      $gallery
 * @var Form                         $upload_form
 * @var Form                         $edit_form
 * @var Controller_Admin_Main_Router $router
 */
$gallery = $this->getRaw( 'gallery' );
$router = $this->getController()->getControllerRouter();

$parent_id = $gallery ? $gallery->getIdObject() : '';

?>
<div class="row toolbar">
	<div class="col-xs-12 col-md-3">
		<?=$this->getRaw( 'search_form' ) ?>
	</div>
	<div class="col-xs-12 col-md-9">
		<?php if( ( $add_uri = $router->getAddURI( $parent_id ) ) && ( !$gallery || !$gallery->getIsNew() ) ):
			echo UI::button_create( Tr::_( 'Create a new gallery' ) )->setUrl( $add_uri );
		endif;

		echo '&nbsp;';

		if( $gallery && !$gallery->getIsNew() && ($delete_uri = $router->getDeleteURI( $gallery->getId() )) ):
			echo UI::button_delete( Tr::_('Delete this gallery') )->setUrl( $delete_uri )->setSize(UI_button::SIZE_EXTRA_SMALL);
		endif; ?>
	</div>
</div>



