<?php
/**
 *
 * @copyright Copyright (c) 2011-2017 Miroslav Marek <mirek.marek.2m@gmail.com>
 * @license http://www.php-jet.net/license/license.txt
 * @author Miroslav Marek <mirek.marek.2m@gmail.com>
 */
namespace JetApplicationModule\Test\ORM;

use Jet\DataModel_Backend;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View $this
 * @var Test_Abstract[] $tests
 * @var DataModel_Backend[] $backends
 */

$backends = $this->getRaw('backends');
$tests = $this->getRaw('tests');

?>
<h1><?=Tr::_('ORM tests')?></h1>
<?php

foreach( $backends as $backend_name=>$backend ) {
	?>
	<h2><?=$backend_name?></h2>
	<?php
	DataModel_Backend::setCustomBackend( Model_A1::class,  $backend );

	foreach( $tests as $t ) {
		?>
		<h3><?=$t->getTitle()?></h3>

		<pre><?php $t->test();?></pre>
		<?php


	}
}
