<?php
namespace JetApplicationModule\JetExample\Content\Images;

use Jet\DataModel_Fetch_Object_Assoc;
use Jet\UI;
use Jet\Mvc_Layout;
use Jet\Mvc_View;
use Jet\Mvc;

/**
 * @var Mvc_View                               $this
 * @var Gallery                                $gallery
 */

$gallery = $this->getRaw( 'gallery' );

Mvc_Layout::getCurrentLayout()->requireCssFile('https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.9.0/css/lightbox.css');
Mvc_Layout::getCurrentLayout()->requireJavascriptFile('https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.9.0/js/lightbox.js');
?>

<div class="row">
	<?php foreach( $gallery->getChildren() as $gallery ): ?>
		<a href="<?=$gallery->getLocalized()->getURL()?>" class="img-thumbnail"
		   style="width: 120px;height: 120px;text-align: center;overflow: hidden;margin: 3px;border:none;">
			<?=UI::icon( 'folder-o' )->setSize( 80 )?>
			<br/>
			<?=$gallery->getTitle();?>
		</a>
	<?php endforeach; ?>
</div>

<div class="row">
	<?php foreach( $gallery->getImages() as $image ):
		/**
		 * @var Gallery_Image $image
		 */
		?>
		<div style="float:left;margin: 10px;overflow: hidden;">
			<div class="thumbnail" style="height: 155px;width: 200px;padding:10px;overflow: hidden">
				<a href="<?=$image->getURI();?>" data-lightbox="example-set">
					<div style="width:180px;height:135px;background-position:center;background-repeat:no-repeat;background-image: url('<?=$image->getThumbnail( 180, 135 );?>');"></div>
				</a>
			</div>
		</div>
	<?php endforeach; ?>
</div>