<?php

use Jet\Mvc_Layout;
use Jet\Tr;
use Jet\UI;
use Jet\Mvc;
use Jet\Auth;
use Jet\SysConf_URI;

/**
 * @var Mvc_Layout $this
 */

require 'parts/init_libs.php';
?>
<!DOCTYPE html>
<html lang="<?= Mvc::getCurrentLocale()->getLanguage() ?>">
<head>
	<title><?= Mvc::getCurrentSite()->getLocalizedData( Mvc::getCurrentLocale() )->getTitle() ?>
		: <?= Mvc::getCurrentPage()->getTitle() ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta http-equiv="content-language" content="<?= Mvc::getCurrentLocale()->getLanguage(); ?>"/>
	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>

	<link rel="icon" href="<?= SysConf_URI::getImages() ?>favicon.png" type="image/png">
</head>
<body>
<div class="container-fluid">
	<div class="page-header card text-white bg-danger">
		<div class="card-body">
			<h1><?= UI::icon( 'user-secret' )->setSize( 40 ) ?> <?= Tr::_( 'Secret area!' ) ?></h1>
			<small><?= Tr::_( "PHP Jet Example Application" ); ?></small>
		</div>
	</div>

	<jet_module module="UI.Web" action="breadcrumbNavigation" view="secret"/>

	<div class="row">
		<?php if( Auth::getCurrentUser() ): ?>
			<div class="col-md-3">
				<jet_module module="UI.Web" action="secret_area_menu"/>
				<jet_layout_position name="left"/>
			</div>
			<div class="col-md-9" style="padding-top: 10px;padding-bottom: 20px;">
				<jet_layout_main_position/>
			</div>
		<?php else: ?>
			<div class="col-md-12" style="padding-top: 10px;padding-bottom: 20px;">
				<div class="container-fluid">
					<jet_layout_main_position/>
				</div>
			</div>
		<?php endif; ?>
	</div>
</div>

</body>
</html>