<?php
/**
 * @var Jet\Form $form
 */
$form = $this->form;

?>
<jet_form name="<?=$form->getName();?>">
	<jet_form_common_error_message class="formError"/>
	<div class="form-group">
		<jet_form_field_label name="backend_type"/>
		<jet_form_field_error_msg name="backend_type" class="form-error"/>
		<jet_form_field name="backend_type" class="form-control"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="history_enabled"/>
		<jet_form_field_error_msg name="history_enabled" class="form-error"/>
		<jet_form_field name="history_enabled"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="history_backend_type"/>
		<jet_form_field_error_msg name="history_backend_type" class="form-error"/>
		<jet_form_field name="history_backend_type" class="form-control"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="cache_enabled"/>
		<jet_form_field_error_msg name="cache_enabled" class="form-error"/>
		<jet_form_field name="cache_enabled"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="cache_backend_type"/>
		<jet_form_field_error_msg name="cache_backend_type" class="form-error"/>
		<jet_form_field name="cache_backend_type" class="form-control"/>
	</div>

	<input type="submit" class="btn btn-primary" value="<?=Jet\Tr::_('Next', [], Jet\Translator::COMMON_NAMESPACE);?>"/>
</jet_form>