<?php
namespace JetStudio;

use Jet\UI;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Menus_Menu_Item $item
 */


$item = $this->getRaw('menu_item');

$tabs_prefix = 'menu_items_'.$item->getNamespaceId().'_'.$item->getMenuId().'_'.$item->getId().'_';

$this->setVar('form_field_prefix', '');
$this->setVar('tabs_prefix', $tabs_prefix);

$form = $item->getEditForm();
$form->setName( 'menu_item_edit_form_'.$item->getNamespaceId().'_'.$item->getMenuId().'_'.$item->getId() );

$form->setAction( Modules::getActionUrl('menu_item/edit', [
	'namespace' => $item->getNamespaceId(),
	'menu' => $item->getMenuId(),
	'item' => $item->getId()
]) );

$this->setVar('form', $form );
$this->setVar('save_button', UI::button_save()->setOnclick("JetStudio.Modules.editModule.editMenuItem.send('".$form->getId()."')")->setType('button') );

echo $form->start();
echo $this->render( 'menus/edit_menu_item/form' );
echo $form->end();