<?php
namespace JetStudio;

use Jet\UI;
use Jet\Mvc_View;
use Jet\UI_button;
use Jet\Tr;

/**
 * @var Mvc_View $this
 * @var Menus_Menu_Item $item
 */


$item = $this->getRaw('menu_item');

$delete_dialog_id = 'menu_item_delete_dialog_'.$item->getNamespaceId().'_'.$item->getMenuId().'_'.$item->getId();

?>
<table style="width: 100%">
	<tr>
		<td>
			<b style="font-size: 16px"><?=$item->getLabel()?></b>
			<span style="font-size: 10px"> <?=$item->getId()?></span>
		</td>
		<td align="right">
			<?=UI::button_delete(Tr::_('Delete this menu item'))->setOnclick("$('#{$delete_dialog_id}').modal('show');")->setSize(UI_button::SIZE_EXTRA_SMALL)?>
		</td>
	</tr>
</table>
