<?php
namespace JetStudio;

use Jet\Application_Modules;
use Jet\Tr;
use Jet\UI;
use Jet\Form;
use Jet\Mvc_View;
use Jet\UI_button;

/**
 * @var Mvc_View $this
 */

$current = Modules::getCurrentModule();

if(
	!$current ||
	!$current->getMenuItemsList()
) {
	return;
}
?>
<legend><?=Tr::_('Menu items')?></legend>

<fieldset style="margin-bottom: 40px;">

	<?php foreach( Menus::getMenuNamespaces() as $namespace ):
		if(!$current->getMenuItemsList($namespace->getInternalId())) {
			continue;
		}
		?>
		<div style="padding-left: 30px;">
			<h4><?=Tr::_('Menu namespace: <b>%namespace%</b>', ['namespace'=>$namespace->getName()])?></h4>
			<div style="padding-left: 30px;">
				<?php foreach( $namespace->getMenus() as $menu ):
					if(!($items=$current->getMenuItemsList($namespace->getInternalId(), $menu->getId()))) {
						continue;
					}
					?>
					<h4><?=Tr::_('Menu: <b>%menu%</b>', ['menu'=>$menu->getLabel()])?></h4>
					<div style="padding-left: 30px;">
						<div style="padding-bottom: 40px">

							<?php foreach( $items as $item ):
								$this->setVar('menu_item', $item);
								?>
								<div class="card panel-info">
									<div
										class="card-header"
										data-toggle="collapse"
										id="menu_item_<?=$item->getNamespaceId()?>_<?=$item->getMenuId()?>_<?=$item->getId()?>_head"
										data-target="#menu_item_<?=$item->getNamespaceId()?>_<?=$item->getMenuId()?>_<?=$item->getId()?>">
										<?php require 'item-head.phtml'; ?>
									</div>
									<div class="card-body collapse" id="menu_item_<?=$item->getNamespaceId()?>_<?=$item->getMenuId()?>_<?=$item->getId()?>">
										<div id="menu_item_<?=$item->getNamespaceId()?>_<?=$item->getMenuId()?>_<?=$item->getId()?>_form_area">
											<?php require 'item-body.phtml'; ?>
										</div>
									</div>
								</div>
							<?php endforeach; ?>

						</div>
					</div>
				<?php endforeach; ?>
			</div>
		</div>

	<?php endforeach; ?>
</fieldset>



<?php
foreach( Menus::getMenuNamespaces() as $namespace ):
	foreach( $namespace->getMenus() as $menu ):
		$items = $current->getMenuItemsList( $namespace->getInternalId(), $menu->getId() );
		foreach( $items as $item ):
			$delete_dialog_id = 'menu_item_delete_dialog_' . $item->getNamespaceId() . '_' . $item->getMenuId() . '_' . $item->getId();

			$delete_dialog = UI::dialog($delete_dialog_id, Tr::_('Delete menu item?'), 600);

			echo $delete_dialog->start();
			echo Tr::_('Do you really want to delete menu item <b>%menu_item%</b> ?', [
				'menu_item' => $item->getLabel().' ('.$item->getId().')'
			]);
			echo $delete_dialog->footer();
			echo UI::button_delete()->setUrl( Modules::getActionUrl('menu_item/delete', [
				'namespace' => $item->getNamespaceId(),
				'menu' => $item->getMenuId(),
				'item' => $item->getId()
			]) );
			echo $delete_dialog->end();

		endforeach;
	endforeach;
endforeach;
?>
