<?php
namespace JetStudio;

use Jet\SysConf_Jet_Modules;use Jet\Tr;
use Jet\Form_Renderer;
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_dialog;

/**
 * @var MVC_View $this
 */

$current = Modules::getCurrentModule();

if( !$current ) {
	return;
}

$form = $current->getEditForm();

$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 6
] );
?>

<?= $form->start() ?>
<input type="hidden" name="generate" value="0"/>

<?= Application_UI::messages(); ?>

<legend>
	<?= Tr::_( 'Module' ) ?>
	<span style="font-weight: bolder"><?= $current->getLabel() ?></span> <span
			style="color: #aaaaaa;font-size: 12px;"><?= $current->getName() ?></span>
</legend>


<?= $form->field( 'module_name' ) ?>
<?= $form->field( 'module_label' ) ?>
<?= $form->field( 'vendor' ) ?>
<?= $form->field( 'version' ) ?>
<?= $form->field( 'description' ) ?>
<?= $form->field( 'is_mandatory' ) ?>
<?= $form->field( 'is_active' ) ?>
<?= $form->field( 'is_installed' ) ?>

<legend><?= Tr::_( 'ACL actions' ) ?></legend>
<div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-6">
		<fieldset style="margin-bottom: 40px;">
			<table>
				<thead>
				<tr>
					<th><?= Tr::_( 'Action' ) ?></th>
					<th><?= Tr::_( 'Description' ) ?></th>
				</tr>
				</thead>
				<tbody>
				<?php for( $m = 0; $m < Modules_Manifest::MAX_ACL_ACTION_COUNT; $m++ ):
					$prefix = '/ACL_action/' . $m;

					if( !$form->fieldExists( $prefix . '/action' ) ) {
						break;
					}

					$action = $form->field( $prefix . '/action' );
					$action->input()->addCustomCssStyle( 'width:300px;' );
					$description = $form->field( $prefix . '/description' );
					$description->input()->addCustomCssStyle( 'width:300px;' );

					?>
					<tr>
						<td style="padding: 5px;"><?= $action->input() ?></td>
						<td style="padding: 5px;"><?= $description->input() ?></td>
					</tr>
				<?php endfor; ?>
				</tbody>
			</table>
		</fieldset>
	</div>
</div>

<?= $form->end() ?>

<?= $this->render( 'page/create/dialog' ) ?>
<?= $this->render( 'menu_item/create/dialog' ) ?>

<?php
$delete_module_info = UI::dialog(
	id: 'delete_module_info',
	title: Tr::_('How to delete module?'),
	size: UI_dialog::SIZE_LARGE
);

echo $delete_module_info->start();

?>
<b><?=Tr::_('Deleting a module is potential risc operation!')?></b>
<br><br>
<p><?=Tr::_('But it is possible for sure and it is very easy.')?></p>

<ol start="1">
	<?php if($current->isMandatory()): ?>
	<li><?=Tr::_('This module is <b>marked as mandatory</b>.<br><br>Please change manually this definition in the manifest file:<br><b>%manifest_path%</b>', [
			'manifest_path' => $current->getModuleDir().SysConf_Jet_Modules::getManifestFileName()
		])?>
		<br><br>
		<?=Tr::_('And then reload Jet Studio')?>
		<br><br>
	</li>
	<?php endif; ?>
	
	<?php if($current->isActivated()):?>
	<li>
		<?=Tr::_('Deactivate module by this tool using <b>"Deactivate" button</b>.')?>
		<br><br>
	</li>
	<?php endif; ?>
	
	<?php if($current->isInstalled()): ?>
	<li>
		<?=Tr::_('Uninstall module by this tool using <b>"Uninstall" button</b>.')?>
		<br><br>
	</li>
	<?php endif; ?>
	
	<li>
		<?=Tr::_('Manually delete directory:<br><b>%module_dir%</b>', [
				'module_dir'=>$current->getModuleDir()
		])?>
		<br><br>
	</li>
</ol>
<?php
echo $delete_module_info->end();

?>

