<?php
namespace JetStudio;

use Jet\Tr;
use Jet\UI;
use Jet\MVC_View;
use Jet\UI_button;

/**
 * @var MVC_View $this
 */

$current = Modules::getCurrentModule();

if( !$current ) {
	return;
}

$form = $current->getEditForm();

?>

<?= UI::button_save()->setOnClick( "$('#" . $form->getId() . "').submit()" ) ?>

<?php if( $current->isInstalled() ):
	if( !$current->isMandatory() ):
		if( $current->isActivated() ):
			?>
			<?= UI::button( Tr::_( 'Deactivate' ) )->setUrl( Modules::getActionUrl( 'deactivate' ) )->setClass( UI_button::CLASS_DANGER ) ?>
		<?php
		else:
			?>
			<?= UI::button( Tr::_( 'Activate' ) )->setUrl( Modules::getActionUrl( 'activate' ) )->setClass( UI_button::CLASS_SUCCESS ) ?>
		<?php
		endif;
		?>
		<?= UI::button( Tr::_( 'Uninstall' ) )->setUrl( Modules::getActionUrl( 'uninstall' ) )->setClass( UI_button::CLASS_DANGER ) ?>
	<?php
	endif;
else:
	?>
	<?= UI::button( Tr::_( 'Install' ) )->setUrl( Modules::getActionUrl( 'install' ) )->setClass( UI_button::CLASS_INFO ) ?>
	<?= UI::button( Tr::_( 'Install and activate' ) )->setUrl( Modules::getActionUrl( 'install_activate' ) )->setClass( UI_button::CLASS_SUCCESS ) ?>
<?php endif; ?>

<?= UI::button_create( Tr::_( 'Add page' ) )->setOnClick( 'Modules.editModule.addPage.openDialog()' ) ?>
<?= UI::button_create( Tr::_( 'Add menu item' ) )->setOnClick( 'Modules.editModule.addMenuItem.openDialog()' ) ?>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<?= UI::button_delete( Tr::_('Delete this module') )->setOnClick("$('#delete_module_info').modal('show');");