<?php
use Jet\Mvc;
use Jet\Mvc_View;
use Jet\Mvc_Page;
use Jet\SysConf_URI;
use Jet\UI;

/**
 * @var Mvc_View   $this
 * @var Mvc_Page[] $pages
 */
$pages = $this->getRaw( 'site_tree_current' );

$admin_page = Mvc_Page::get( Mvc_Page::HOMEPAGE_ID, null, 'admin' );
$secret_area_page = Mvc_Page::get( 'secret_area' );


$show_menu = function( $pages, $level=0 ) use ( &$show_menu ) {
	/**
	 * @var Mvc_Page[] $pages
	 */

	if( !$pages ) return;


	$current_page_key = Mvc::getCurrentPage()->getKey();
	$padding = 10+($level*25);

	foreach( $pages as $page ):
		if(
			!$page->getIsActive() ||
			$page->getIsSecret()
		) {
			continue;
		}

		?>
			<?php if( $current_page_key==$page->getKey() ): ?>
			<li class="list-group-item active" style="padding-left: <?=$padding;?>px;">
				<?=$page->getMenuTitle();?>
			</li>
			<?php else: ?>
			<li class="list-group-item" style="padding-left: <?=$padding;?>px;">
				<a href="<?=$page->getURL();?>"><?=$page->getMenuTitle();?></a>
			</li>
			<?php endif; ?>
			<?php $show_menu( $page->getChildren(), $level+1 ); ?>
		<?php
	endforeach;

};

?>


<div class="card bg-light text-dark">
	<div class="card-body">
		<ul class="list-group list-group-flush">
			<?php $show_menu( $pages ); ?>
		</ul>

		<ul>

		</ul>
		<?php if( $secret_area_page ): ?>
			<a href="<?=$secret_area_page->getURL()?>" rel="nofollow"><?=$secret_area_page->getMenuTitle()?></a><br/>
		<?php endif; ?>

		<?php if( $admin_page ): ?>
			<a href="<?=$admin_page->getURL()?>" rel="nofollow"><?=$admin_page->getMenuTitle()?></a><br/>
		<?php endif; ?>

			<a href="<?=SysConf_URI::getBase()?>_tools/studio/" rel="nofollow" target="_blank">Jet Studio</a><br/>
	</div>
</div>