<?php
use Jet\Mvc;
use Jet\Mvc_View;
use Jet\Mvc_Page;
use Jet\UI;


/**
 * @var Mvc_View   $this
 * @var Mvc_Page[] $pages
 */
$pages = $this->getRaw( 'site_tree_current' );


$show_menu = function( $pages ) use ( &$show_menu ) {
	/**
	 * @var Mvc_Page[] $pages
	 */

	if( !$pages ) return;


	$current_page_key = Mvc::getCurrentPage()->getKey();
	?>
	<ul>
		<?php foreach( $pages as $page ):
			if(
				!$page->getIsActive() ||
				$page->getIsSecret()
			) {
				continue;
			}
			?>
			<li>
				<?php if( $current_page_key==$page->getKey() ): ?>
					<i><?=$page->getMenuTitle();?></i>
				<?php else: ?>
					<a href="<?=$page->getURL();?>"><?=$page->getMenuTitle();?></a>
				<?php endif; ?>
				<?php $show_menu( $page->getChildren() ); ?>
			</li>
		<?php endforeach; ?>
	</ul>
	<?php

};

$tabs = [];
foreach( Mvc::getCurrentSite()->getLocales() as $locale ) {
	$tabs[$locale->toString()] = UI::flag( $locale ).'&nbsp;'.$locale->getLanguageName( $locale );
}

$tabs = UI::tabs(
		$tabs,
		function( $locale ) {
			$equal_page = Mvc_Page::get( null, $locale );

			if( !$equal_page ) {
				$equal_page = Mvc_Page::get( Mvc_Page::HOMEPAGE_ID, $locale );
			}

			return $equal_page->getURL();

		},
		Mvc::getCurrentLocale()->toString()
);
?>



<?=$tabs?>

<div class="panel panel-default panel-body" style="border-top: none;border-radius: 0px;box-shadow: 2px 2px 2px #aaaaaa;">
<?php $show_menu( $pages ); ?>

<?php
$secret_area_page = Mvc_Page::get( 'secret_area' );

if( $secret_area_page ): ?>
	<a href="<?=$secret_area_page->getURL()?>" rel="nofollow"><?=$secret_area_page->getMenuTitle()?></a><br/>
<?php endif;

$admin_page = Mvc_Page::get( '_homepage_', null, 'admin' );

if( $admin_page ): ?>
	<a href="<?=$admin_page->getURL()?>" rel="nofollow"><?=$admin_page->getMenuTitle()?></a><br/>
<?php endif; ?>
</div>