<?php
use Jet\Mvc;
use Jet\Mvc_View;
use Jet\Mvc_Page;
use Jet\UI;

/**
 * @var Mvc_View   $this
 * @var Mvc_Page[] $pages
 */
$pages = $this->getRaw( 'site_tree_current' );

if(!Mvc::getCurrentPage()->accessAllowed()) {
	return;
}


$show_menu = function( $pages, $level=0 ) use ( &$show_menu ) {
	/**
	 * @var Mvc_Page[] $pages
	 */

	if( !$pages ) {
		return;
	}

	$current_page_key = Mvc::getCurrentPage()->getKey();
	$padding = 10+($level*25);

	foreach( $pages as $page ):
			if( 
				!$page->getIsActive() ||
				!$page->getIsSecret() ||
				!$page->accessAllowed()
			) {
				continue;
			}

			$icon = '';
			if($page->getIcon()) {
				$icon = UI::icon($page->getIcon()).' ';
			}

			?>
			<?php if( $current_page_key==$page->getKey() ): ?>
			<li class="list-group-item active" style="padding-left: <?=$padding;?>px;">
				<?=$icon?><?=$page->getMenuTitle();?>
			</li>
		<?php else: ?>
			<li class="list-group-item" style="padding-left: <?=$padding;?>px;">
				<?=$icon?><a href="<?=$page->getURL();?>"><?=$page->getMenuTitle();?></a>
			</li>
		<?php endif; ?>
			<?php $show_menu( $page->getChildren(), $level+1 ); ?>
		<?php
	endforeach;

};
?>


<div class="card bg-danger text-white">
	<div class="card-body">
		<ul class="list-group list-group-flush">
			<?php $show_menu( $pages ); ?>
		</ul>
	</div>
</div>
