<?php
namespace JetStudio;

use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;
/**
 * @var Mvc_View $this
 * @var Pages_Page $page
 */

$page = $this->getRaw('page');

$dialog = UI::dialog('dialog_create_new_page_content', Tr::_('Add content'), 1000);

echo $dialog->start();
?>
	<div id="<?=Pages_Page_Content::getCreateForm( $page )->getId()?>_form_area">
		<?php
		require 'form.phtml';
		?>
	</div>
	<?php
echo $dialog->footer();
echo UI::button_save(Tr::_('Add'))->setOnclick('Pages.editPage.content.createSend()');
echo $dialog->end();

