<?php

namespace JetStudio;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_dialog;

/**
 * @var MVC_View $this
 * @var Pages_Page $page
 */

$dialog = UI::dialog( 'dialog_create_new_page_content', Tr::_( 'Add content' ), UI_dialog::SIZE_EXTRA_LARGE );

echo $dialog->start();
?>
	<div id="content_create_form_area">
		<?php
		require 'form.phtml';
		?>
	</div>
	<?php
echo $dialog->footer();
echo UI::button_save( Tr::_( 'Add' ) )->setOnClick( 'Pages.editPage.content.createSend()' );
echo $dialog->end();

