<?php

use Jet\UI_dataGrid;
use Jet\UI;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var UI_dataGrid $grid
 */
$grid = $this->getRaw( 'grid' );
?>
<tr>
	<?php foreach( $grid->getColumns() as $column ):
		$style = $column->getCssStyle() ? ' style="' . $column->getCssStyle() . '"' : '';
		$class = $column->getCssClass() ? ' class="' . $column->getCssClass() . '"' : '';
		?>
		<th<?= $class; ?><?= $style; ?> nowrap="">

			<?php if( $column->getAllowSort() ): ?>
				<?php if( $column->isSortByAsc() ): ?>
					<?= UI::icon( 'sort-amount-down-alt' )->setSize( 11 ) ?>
				<?php else: ?>
					<a href="<?= $grid->getSortURL( $column->getName() ); ?>">
						<?= UI::icon( 'sort-amount-down-alt' )->setSize( 11 ) ?>
					</a>
				<?php endif; ?>
			<?php endif; ?>
			<?= $column->getTitle(); ?>

			<?php if( $column->getAllowSort() ): ?>
				<?php if( $column->isSortByDesc() ): ?>
					<?= UI::icon( 'sort-amount-down' )->setSize( 11 ) ?>
				<?php else: ?>
					<a href="<?= $grid->getSortURL( $column->getName(), true ); ?>">
						<?= UI::icon( 'sort-amount-down' )->setSize( 11 ) ?>
					</a>
				<?php endif; ?>
			<?php endif; ?>
		</th>
	<?php endforeach; ?>
</tr>
