<?php
namespace JetStudio;

use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Pages_Page $page
 */

$page = $this->getRaw( 'page' );
$what = $this->getRaw( 'what' );


echo $this->render( 'page/' . $what . '/edit/toolbar' );
?>

<?= Tr::_( 'Page' ) ?> <span style="font-weight: bolder"><?= $page->getName() ?></span> <span
		style="color: #aaaaaa;font-size: 12px;"><?= $page->getId() ?></span>


