<?php

namespace JetStudio;

use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this ;
 */

$key = DataModels::getCurrentKey();

$form = $key->getEditForm();

$form->setDefaultLabelWidth( [
	Form::LJ_SIZE_MEDIUM => 2
] );
$form->setDefaultFieldWidth( [
	Form::LJ_SIZE_MEDIUM => 10
] );


echo $form->start();

echo $form->field( 'name' );
echo $form->field( 'type' );
echo $form->field( 'properties' );

echo $form->end();

