<?php

namespace JetStudio;

use Jet\Form_Renderer;
use Jet\MVC_View;

/**
 * @var MVC_View $this ;
 */

$key = DataModels::getCurrentKey();

$form = $key->getEditForm();

$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 10
] );


echo $form->start();

echo $form->field( 'name' );
echo $form->field( 'type' );
echo $form->field( 'properties' );

echo $form->end();

