<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;
use Jet\MVC;

$this->setVar( 'what', Pages::whatToEdit() );
$this->setVar( 'page', Pages::getCurrentPage() );

?>
<?= $this->render( 'js' ); ?>

<?php if( Pages::getCurrentPage() ): ?>
	<div class="row toolbar" id="main-toolbar">
		<div class="col-md-3">
			<div class="dropdown" style="display: inline-block">
				<button class="btn btn-light dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
				        aria-expanded="false">
					<?= UI::flag( Pages::getCurrentLocale() ) ?>
					<span style="font-weight: bolder;font-size: 16px;"><?= Pages::getCurrentBase()->getName() ?></span>
				</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					<?php foreach( Bases::getBases() as $base ): ?>
						<div class="dropdown-item" style="padding-bottom: 10px;">
							<strong><?= $base->getName() ?></strong>
							<?php foreach( $base->getLocales() as $locale ):
								$link = Pages::getActionUrl( '', [], MVC::HOMEPAGE_ID, $locale, $base->getId() );
								?>
								<div style="width: 300px;padding: 10px;">
									<a href="<?= $link ?>"><?= UI::flag( $locale ) ?></a>
									<a href="<?= $link ?>"><?= $locale->getName() ?></a>
								</div>
							<?php endforeach; ?>
						</div>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
		<div class="col-md-9" style="padding: 0;">
			<?= UI::button_create( Tr::_( 'Create a new page' ) )->setOnClick( 'Pages.createPage.openDialog()' ) ?>
			<?= $this->render( 'page/toolbar' ); ?>
		</div>
	</div>


	<div class="row" id="main-col">
		<div class="col-md-3" style="padding: 0;">
			<?= $this->render( 'pages_tree' ); ?>
		</div>
		<div class="col-md-9" style="padding: 0;">
			<?= $this->render( 'page/edit' ); ?>
		</div>
	</div>


<?php else: ?>
	<div class="row">
		<div class="col-md-12">
			<?= $this->render( 'dashboard' ); ?>
		</div>
	</div>
<?php endif; ?>


<?= $this->render( 'page/create/dialog' ); ?>
