<?php

namespace JetStudio;


use Jet\Data_Tree_Node;
use Jet\UI_badge;
use Jet\UI;
use Jet\Tr;
use Jet\MVC;

$UI_tree = UI::tree( Pages::getCurrentPageTree() );
$UI_tree->setRootId( MVC::HOMEPAGE_ID );
//$UI_tree->setShowAll(true);
$UI_tree->setSelectedId( Pages::getCurrentPageId() );

$renderer = function( Data_Tree_Node $node ) {

	$page = Pages::getPage( $node->getId() );
	
	$edit_url = Pages::getActionUrl( '', [], $node->getId() );
	
	$node_data = $node->getData();
	$module = '';
	if(is_array($node_data) && !empty($node_data['module_name'])) {
		$module = $node_data['module_name'];
		$edit_url = Modules::getActionUrl('', [
				'module' => $module,
				'page' => Pages::getCurrentBaseId().'.'.$node->getId()
			]);
	}

	if( !$page->getIsActive() ):
		echo UI::badge(UI_badge::DANGER, UI::icon( 'times' )->setTitle( Tr::_( 'Is not active' ) ));
	endif;
	?>
	<a href="<?= $edit_url ?>" style="font-size: 16px;"><?= $node->getLabel() ?></a>

	<span style="font-size: 11px;">
	<?php

	if( $page->getIsSecret() ): echo '&nbsp;&nbsp;' . UI::icon( 'user-secret' )->setTitle( Tr::_( 'Is secret' ) ); endif;
	if( $page->getSSLRequired() ): echo '&nbsp;&nbsp;' . UI::icon( 'lock' )->setTitle( Tr::_( 'SSL required' ) ); endif;

	if( $page->getOutput() ):
		echo '&nbsp;&nbsp;' . UI::icon( 'file' )->setTitle( Tr::_( 'Is static page' ) );
	endif;
	?>
	</span>
	<?php
	if($module):
		?>
		<br><small class="text-info"><?=Tr::_('Source module: ')?><a href="<?=Modules::getActionUrl('', ['module' => $module])?>" class="text-primary"><?=$module?></a></small>
		<?php
	endif;

};

$UI_tree->setRendererNormal( $renderer );
$UI_tree->setRendererOpened( $renderer );
$UI_tree->setRendererSelected( $renderer );


echo $UI_tree->render();