<?php
namespace JetStudio;


use Jet\Data_Tree_Node;
use Jet\UI_tree;
use Jet\UI;
use Jet\Tr;

$UI_tree = new UI_tree();
$UI_tree->setData( Pages::getCurrentPageTree() );
$UI_tree->setRootId(Pages_Page::HOMEPAGE_ID);
//$UI_tree->setShowAll(true);
$UI_tree->setSelectedId( Pages::getCurrentPageId() );

$renderer = function( Data_Tree_Node $node ) {

	$page = Pages::getPage( $node->getId() );

	?>
	<a href="<?=Pages::getActionUrl('', [], $node->getId())?>" style="font-size: 16px;"><?=$node->getLabel()?></a>

	<span style="font-size: 11px;">
	<?php

	if(!$page->getIsActive()): echo '&nbsp;&nbsp;'.UI::icon('times')->setTitle(Tr::_('Is not active')); endif;
	//if($page->getIsActive()): echo '&nbsp;&nbsp;'.UI::icon('check')->setTitle(Tr::_('Is active')); endif;
	if($page->getIsSecret()): echo '&nbsp;&nbsp;'.UI::icon('user-secret')->setTitle(Tr::_('Is secret')); endif;
	if($page->getSSLRequired()): echo '&nbsp;&nbsp;'.UI::icon('lock')->setTitle(Tr::_('SSL required')); endif;

	if($page->getOutput()):
		echo '&nbsp;&nbsp;'.UI::icon('file')->setTitle(Tr::_('Is static page'));
	else:
		if($page->getIsSubApp()):
			echo '&nbsp;&nbsp;'.UI::icon('cogs')->setTitle(Tr::_('Is Sub Application'));
		endif;
	endif;
	?>
	</span>
	<?php

};

$UI_tree->setRendererNormal( $renderer );
$UI_tree->setRendererOpened( $renderer );
$UI_tree->setRendererSelected( $renderer );


echo $UI_tree->render();