<?php
namespace JetApplication\Installer;

use Jet\Form;
use Jet\Form_Renderer;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Form $form
 */
$form = $this->getRaw( 'form' );
$form->renderer()->setDefaultLabelWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 0] );
$form->renderer()->setDefaultFieldWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 6] );
?>

<?= $form->start() ?>
<?php foreach( $form->getFields() as $field ): ?>
	<?= $field ?>
<?php endforeach; ?>

<?= Installer::buttonNextSubmit(); ?>
<?= $form->end() ?>
