<?php
namespace JetApplication;

use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );
$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 0 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 6 ] );
?>

<?=$form->start()?>
<?php foreach( $form->getFields() as $field ): ?>
	<?=$field?>
<?php endforeach; ?>

<?=Installer::buttonNext();?>
<?=$form->end()?>
