<?php
namespace JetApplicationModule\Admin\EventViewer\REST;

use Jet\UI_button;
use Jet\UI;
use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View  $this
 * @var Listing   $listing
 */
$listing = $this->getRaw('listing');

$grid = $listing->getGrid();
$filter_form = $listing->getFilterForm();


$grid->getColumn( Listing_Column_ID::KEY )->addCustomCssStyle( 'width:120px;' );

?>

<?=$filter_form->start()?>
<div class="row toolbar">

	<div class="col-md-3 col-sm-12">
		<?=$listing->filter(Listing_Filter_Search::KEY)->renderForm()?>
		
		<?php require 'list/export.phtml'; ?>
	</div>
	<div class="col-md-9 col-sm-12">
		<table>
			<tr>
				<?=$listing->filter(Listing_Filter_DateTime::KEY)->renderForm()?>
			</tr>
			<tr>
				<?=$listing->filter(Listing_Filter_EventClass::KEY)->renderForm()?>
				<td></td>
				<?=$listing->filter(Listing_Filter_Event::KEY)->renderForm()?>
			</tr>
			<tr>
				<?=$listing->filter(Listing_Filter_User::KEY)->renderForm()?>
				<td colspan="3"></td>
			</tr>
			<tr>
				<?=$listing->filter(Listing_Filter_ContextObject::KEY)->renderForm()?>
				<td colspan="3"></td>

				<td><?=UI::button(Tr::_('Filter'))->setClass( UI_button::CLASS_PRIMARY )->setType( UI_button::TYPE_SUBMIT )?></td>
			</tr>
		</table>

	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
