<table class="table table-striped">
	<thead>
		<tr>
			<th><?=Jet\Tr::_('Class');?></th>
			<th><?=Jet\Tr::_('Status');?></th>
		</tr>
	</thead>
	<?php foreach($this->result as $class=>$state): ?>
	<tr>
		<td><?=$class;?></td>
		<?php if($state===true): ?>
		<td><div class="OK">OK</div></td>
		<?php else: ?>
		<td><div class="error"><?=$state;?></div></td>
		<?php endif; ?>
	</tr>
	<?php endforeach; ?>
</table>


<?php if($this->OK): ?>
<form method="post">
<input type="hidden" name="go" value="1">
<input type="submit" value="<?=Jet\Tr::_('Next', array(), Jet\Translator::COMMON_NAMESPACE);?>" class="btn btn-primary"/>
</form>
<?php endif; ?>