<?php

use Jet\MVC_View;
use Jet\Form_Renderer;
use Jet\Form_Field_Select;
use Jet\Data_Text;

/**
 * @var MVC_View $this
 * @var Form_Renderer $r
 * @var Form_Field_Select $field
 */
$r = $this->getRaw( 'element' );


if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

$field = $r->getField();
$value = $field->getValue();

//var_dump($value);die();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$attrs = [
	'id' => $field->getId(),
	'multiple' => 'multiple',
];

if( $field->getIsReadonly() ) {
	$attrs['disabled'] = 'disabled';
}
if( $field->getIsRequired() ) {
	$attrs['required'] = 'required';
}

?>
<select name="<?= $field->getTagNameValue() ?>[]" <?=$r->renderAttributes($attrs)?>>
	<?php foreach( $field->getSelectOptions() as $val => $label ):

		$selected = false;

		if(
			is_array( $value ) &&
			!empty( $value )
		) {
			foreach( $value as $val_in ) {
				if( (string)$val == (string)$val_in ) {
					$selected = true;
					break;
				}
			}
		} else {
			if( $val == $value ) {
				$selected = true;
			}
		}

		$css = $label->getSelectOptionCss();
		$selected = $selected ? ' selected="selected"' : '';

		?><option value="<?=Data_Text::htmlSpecialChars( $val )?>" <?=$css?><?=$selected?>><?=Data_Text::htmlSpecialChars( $label )?></option><?php
	endforeach; ?>
</select>
