<?php

use Jet\MVC_View;
use Jet\Form_Renderer;
use Jet\Data_Text;

/**
 * @var MVC_View $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

$field = $r->getField();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$attrs = [
	'type' => 'password',
	'name' => $field->getTagNameValue(),
	'id' => $field->getId(),
	//'value' => $field->getValue()
];

if( $field->getPlaceholder() ) {
	$attrs['placeholder'] = Data_Text::htmlSpecialChars( $field->getPlaceholder() );
}
if( $field->getIsReadonly() ) {
	$attrs['readonly'] = 'readonly';
}
if( $field->getIsRequired() ) {
	$attrs['required'] = 'required';
}

?>
<input <?=$r->renderAttributes($attrs)?>/>
