<?php

use Jet\MVC_View;
use Jet\Form_Renderer;
use Jet\Form_Field_Select;
use Jet\Data_Text;

/**
 * @var MVC_View $this
 * @var Form_Renderer $r
 * @var Form_Field_Select $field
 */
$r = $this->getRaw( 'element' );


$field = $r->getField();
$value = $field->getValue();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$container_class = 'radio';
if($field->getIsReadonly()) {
	$container_class = 'radio disabled';
}

$attrs = $r->getStdInputFieldAttributes('radio');

$c = 0;
foreach( $field->getSelectOptions() as $key => $option ):
	$c++;

	$_attrs = $attrs;

	$id = $field->getId().'__'.$c;

	$_attrs['id'] = $id;
	$_attrs['value'] = Data_Text::htmlSpecialChars( $key );

	if($key==$field->getValue()) {
		$_attrs['checked'] = 'checked';
	}
	?>
	<div class="<?= $container_class ?>">
		<input <?=$r->renderAttributes($_attrs)?>/>
		<label class="form-check-label" for="<?= $id ?>"><?= $option ?></label>
	</div>
<?php endforeach; ?>
