<?php

namespace JetStudio;

use Jet\Form_Renderer;use Jet\Tr;use Jet\UI;

$current = DataModels::getCurrentProperty();


$form = $current->getEditForm();
$form->renderer()->setDefaultLabelWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 2] );
$form->renderer()->setDefaultFieldWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 9] );

echo $form->start();

$default_fields = [
	'type',
	'name',
	'database_column_name',

	'is_id',
	'is_key',
	'is_do_not_export',
];

foreach( $default_fields as $fn ) {
	if( !$form->fieldExists( $fn ) ) {
		continue;
	}

	echo $form->field( $fn );
}


$current->showEditFormFields();

?>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-9">
			<?=UI::button(Tr::_('Form field definition'))->setUrl(Forms::getDefinitionUrl( DataModels::getCurrentClassName(), $current->getName() ))->setClass('info')?><br><br>
		</div>
	</div>
	<?php


echo $form->end();
