<?php
namespace JetApplicationModule\JetExample\TestModule2;
use Jet;

/**
 * @var Jet\Form $form
 */
$form = $this->form;

/**
 * @var Jet\Form $page_form
 */
$page_form = $this->page_form;

?>
M2: Test Action 2

<table>
	<tr>
		<td>Current site ID:</td>
		<td><?=Jet\Mvc::getCurrentSiteID();?></td>
	</tr>
	<tr>
		<td>Current locale:</td>
		<td><?=Jet\Mvc::getCurrentLocale();?></td>
	</tr>
	<tr>
		<td>Current page ID:</td>
		<td><?=Jet\Mvc::getCurrentPageID();?></td>
	</tr>
</table>

<p>
	<?php if($this->form_sent): ?>
	Form SENT:
	<table>
		<?php foreach($this->form_values as $k=>$v): ?>
		<tr>
			<td><?=$k;?>:</td>
			<td><?=$v;?></td>
		</tr>
		<?php endforeach; ?>
	</table>
	<?php endif; ?>

	<?=$form->helper_getBasicHTML();?>
</p>



<p>

<?=$page_form->helper_getBasicHTML();?>

</p>

<?php
//foreach( Jet\Mvc::getCurrentPage()->getChildren() as $chld ) {
//	echo (string)$chld->getID().JET_EOL;
//}
?>