<?php
namespace JetApplicationModule\JetExample\TestModule2;
use Jet;
use Jet\Form;
use Jet\Mvc;

/**
 * @var Form $form
 */
$form = $this->form;

?>
M2: Test Action 2

<table>
	<tr>
		<td>Current site ID:</td>
		<td><?=Mvc::getCurrentSite()->getID();?></td>
	</tr>
	<tr>
		<td>Current locale:</td>
		<td><?=Mvc::getCurrentLocale();?></td>
	</tr>
	<tr>
		<td>Current page ID:</td>
		<td><?=Mvc::getCurrentPage()->getID();?></td>
	</tr>
</table>

<p>
	<?php if($this->form_sent): ?>
	Form SENT:
	<table>
		<?php foreach($this->form_values as $k=>$v): ?>
		<tr>
			<td><?=$k;?>:</td>
			<td><?=$v;?></td>
		</tr>
		<?php endforeach; ?>
	</table>
	<?php endif; ?>

	<?=$form->helper_getBasicHTML();?>
</p>



<p>

<?php //echo $page_form->helper_getBasicHTML(); ?>

</p>

<?php
//foreach( Mvc::getCurrentPage()->getChildren() as $chld ) {
//	echo (string)$chld->getID().JET_EOL;
//}
?>