<?php
use Jet\Form;
use Jet\Tr;
use Jet\Form_Field_FileImage;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form[] $forms
 */

$forms = $this->getRaw('forms');

?>
<?=Tr::_('M2: Test Action 2')?>

<h2><?=Tr::_('Forms test')?></h2>
<p>
    <?php foreach( $forms as $form_name=>$d ):
        $form = $d['form'];
        //$form->setIsReadonly();
    ?>
    <fieldset style="margin-bottom: 40px">
        <legend><?=$d['title']?></legend>
        <?php
        echo $form->start();
        foreach($form->getFields() as $field)
            echo $field;

        if(!$form->getIsReadonly()):
        ?>
        <div class="row">
            <div class="col-md-offset-4">
                <input type="submit" class="btn btn-default" value="<?=Tr::_('Submit')?>"/>
            </div>
        </div>
        <?php endif; ?>
        <?=$form->end()?>




        <?php if($d['form_sent']): ?>
            <hr>
            <?=Tr::_('Form sent:')?>

            <?php if($form_name=='upload_image_form'):
                /**
                 * @var Form_Field_FileImage $image_field
                 */
                $image_field = $form->getField('upload_image');

                ?>
                <img src="<?=JET_PUBLIC_URI?>test_uploads/<?=$image_field->getFileName()?>">
            <?php else: ?>
                <table>
                    <?php foreach($d['form_values'] as $k=>$v): ?>
                        <tr>
                            <td><?=$k?>:</td>
                            <td><?=is_array($v) ? implode(',',$v) : $v?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            <?php endif; ?>
        <?php endif; ?>

    </fieldset>
    <?php endforeach; ?>




</p>

