<?php
/**
 * @var Jet\Form $form
 */
$form = $this->form;

?>
<jet_form name="<?=$form->getName();?>">
	<jet_form_common_error_message class="formError"/>

	<div class="form-group">
		<jet_form_field_label name="backend_type"/>
		<jet_form_field_error_msg name="backend_type" class="form-error"/>
		<jet_form_field name="backend_type" class="form-control"/>
	</div>
	<div class="form-group checkbox">
		<jet_form_field_label name="auto_append_unknown_phrase"/>
		<jet_form_field_error_msg name="auto_append_unknown_phrase" class="form-error"/>
		<jet_form_field name="auto_append_unknown_phrase"/>
	</div>
	<?=\Jet\Installer::buttonNext();?>
</jet_form>
