<?php
namespace JetApplicationModule\Content\Images\Browser;

use Jet\UI;
use Jet\MVC_View;
use Jet\UI_icon;
use JetApplication\Content_Gallery;

/**
 * @var MVC_View $this
 * @var Content_Gallery[] $galleries
 */

$galleries = $this->getRaw( 'galleries' );

?>

<div class="row">
	<?php foreach( $galleries as $gallery ): ?>
		<a href="<?= $gallery->getLocalized()->getURL() ?>" class="img-thumbnail"
		   style="width: 120px;height: 120px;text-align: center;overflow: hidden;margin: 3px;border:none">
			<?= UI::icon( 'folder' )->setSize( UI_icon::SIZE_ULTRA_LARGE ) ?>
			<br/>
			<?= $gallery->getTitle(); ?>
		</a>
	<?php endforeach; ?>
</div>
