<?php

namespace JetApplication\Installer;

use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form $form
 */

$form = $this->getRaw( 'form' );
$form->setDefaultLabelWidth( [Form::LJ_SIZE_MEDIUM => 2] );
$form->setDefaultFieldWidth( [Form::LJ_SIZE_MEDIUM => 4] );
?>
<?= $form->start() ?>
<?= $form->message() ?>

<?= $form->field( 'username' ) ?>
<?= $form->field( 'password' ) ?>

<?= Installer::buttonNext(); ?>
<?= $form->end() ?>