<?php

use Jet\MVC_View;
use Jet\Form_Renderer_Field_Input;

/**
 * @var MVC_View $this
 * @var Form_Renderer_Field_Input $r
 */
$r = $this->getRaw( 'renderer' );
$field = $r->getField();

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'checkbox' );
}

if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$r->setFieldType('checkbox');

$attrs = [
	'value' => 1
];

if($field->getIsReadonly()) {
	$attrs['disabled'] = 'disabled';
}

if($field->getValue()) {
	$attrs['checked'] = 'checked';
}

$r->setCustomTagAttributes($attrs);
?>
<div class="<?= implode(' ', $r->getCssClasses()) ?>">
	<input <?=$r->renderTagAttributes()?>/>

	<label class="form-check-label" for="<?= $field->getId() ?>"><?= $r->getField()->getLabel() ?></label>
</div>