<?php

use Jet\Mvc_View;
use Jet\Form_Renderer;

/**
 * @var Mvc_View $this
 * @var Form_Renderer $r
 */
$r = $this->getRaw( 'element' );

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

$field = $r->getField();
if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

$value = '';

if( $field->getValue() ) {
	$date = new DateTime( $field->getValue() );
	$value = $date->format( 'Y-m-d\TH:i' );
}

?>
<input <?=$r->renderAttributes( $r->getStdInputFieldAttributes('datetime-local') )?>/>
