<?php

use Jet\MVC_View;
use Jet\Form_Renderer_Field_Input;
use Jet\Form_Field_Float;

/**
 * @var MVC_View $this
 * @var Form_Renderer_Field_Input $r
 * @var Form_Field_Float $field
 */
$r = $this->getRaw( 'renderer' );
$field = $r->getField();

$r->setInputType('number');

if( !$r->getBaseCssClasses() ) {
	$r->setBaseCssClass( 'form-control' );
}

if( $field->getLastErrorCode() ) {
	$r->addCustomCssClass( 'is-invalid' );
}

if( $field->getMinValue() !== null ) {
	$r->setCustomTagAttribute('min', $field->getMinValue());
}

if( $field->getMaxValue() !== null ) {
	$r->setCustomTagAttribute('max', $field->getMaxValue());
}

$r->setCustomTagAttribute('step', $field->getStep());
?>
<input <?=$r->renderTagAttributes()?>/>