<?php
use Jet\Navigation_Breadcrumb_Item;
use Jet\Mvc_View;
use Jet\Navigation_Breadcrumb;

/**
 * @var Mvc_View                              $this
 * @var Navigation_Breadcrumb_Item[] $data
 */
$data = Navigation_Breadcrumb::getItems()
?>
<ol class="breadcrumb">
	<?php foreach( $data as $d ): ?>
		<?php if( !$d->getIsLast() ): ?>
			<li><a href="<?=$d->getURL();?>"><?=$d->getTitle();?></a></li>
		<?php else: ?>
			<li class="active"><?=$d->getTitle();?></li>
		<?php endif; ?>
	<?php endforeach; ?>
</ol>
