<?php
use Jet\Mvc_View;
use Jet\Navigation_Breadcrumb;
use Jet\UI;

/**
 * @var Mvc_View $this
 */
$items = Navigation_Breadcrumb::getItems();
?>
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li><?=UI::icon('skull-crossbones')?>&nbsp;</li>
		<?php foreach( $items as $item ): ?>
			<?php if( $item->getIsActive() ): ?>
				<li class="breadcrumb-item active">
					<?php if( !$item->getIsLast() ): ?>
						<a href="<?=$item->getURL();?>"><?=$item->getTitle();?></a>
					<?php else: ?>
						<?=$item->getTitle();?>
					<?php endif; ?>
				</li>
			<?php else: ?>
				<li class="breadcrumb-item">
					<?php if( !$item->getIsLast() ): ?>
						<a href="<?=$item->getURL();?>"><?=$item->getTitle();?></a>
					<?php else: ?>
						<?=$item->getTitle();?>
					<?php endif; ?>
				</li>
			<?php endif; ?>
		<?php endforeach; ?>
	</ol>
</nav>