<?php

use Jet\Mvc_View;
use Jet\Navigation_Breadcrumb;
use Jet\UI;
use Jet\Mvc;
use Jet\Mvc_Page;

/**
 * @var Mvc_View $this
 */
$items = Navigation_Breadcrumb::getItems();
?>
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<?php foreach( Mvc::getCurrentBase()->getActiveLocales() as $locale ): ?>
			<li style="margin-right: 20px;">
				<?php if( $locale->toString() == Mvc::getCurrentLocale()->toString() ): ?>
					<span class="badge badge-info"><?= UI::flag( $locale ) ?>&nbsp;<?= $locale->getLanguageName( $locale ) ?></span>
				<?php else:
					$eq_page = Mvc_Page::get( null, $locale );
					if( !$eq_page ) {
						$eq_page = Mvc_Page::get( Mvc_Page::HOMEPAGE_ID, $locale );
					}
					?>
					<a href="<?= $eq_page->getURL() ?>"><?= UI::flag( $locale ) ?>
						&nbsp;<?= $locale->getLanguageName( $locale ) ?></a>
				<?php endif; ?>
			</li>
		<?php endforeach; ?>


		<li><?= UI::icon( 'skull-crossbones' ) ?>&nbsp;</li>
		<?php foreach( $items as $item ): ?>
			<?php if( $item->getIsActive() ): ?>
				<li class="breadcrumb-item active">
					<?php if( !$item->getIsLast() ): ?>
						<a href="<?= $item->getURL(); ?>"><?= $item->getTitle(); ?></a>
					<?php else: ?>
						<?= $item->getTitle(); ?>
					<?php endif; ?>
				</li>
			<?php else: ?>
				<li class="breadcrumb-item">
					<?php if( !$item->getIsLast() ): ?>
						<a href="<?= $item->getURL(); ?>"><?= $item->getTitle(); ?></a>
					<?php else: ?>
						<?= $item->getTitle(); ?>
					<?php endif; ?>
				</li>
			<?php endif; ?>
		<?php endforeach; ?>
	</ol>
</nav>