<?php
use JetExampleApp\Installer;
use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form $form
 */

$form = $this->getRaw('form');
$form->setDefaultLabelWidth(2);
$form->setDefaultFieldWidth(4);
?>
<?=$form->start()?>
	<?=$form->message()?>

	<?=$form->field('login')?>
	<?=$form->field('password')?>
	<?=$form->field('email')?>

	<?=Installer::buttonNext();?>
<?=$form->end()?>


<form method="post">
	<input type="hidden" name="go" value="1">
	<?=Installer::buttonNextSkipIt()?>

</form>