<?php
use Jet\Form;
use JetExampleApp\Installer;
/**
 * @var Form $form
 */

$form = $this->form;
$form->setDefaultLabelWidth(2);
$form->setDefaultFieldWidth(4);
?>
<?=$form->start()?>
	<?=$form->message()?>

	<?=$form->field('login')?>
	<?=$form->field('password')?>
	<?=$form->field('email')?>

	<?=Installer::buttonNext();?>
<?=$form->end()?>


<form method="post">
	<input type="hidden" name="go" value="1">
	<?=Installer::buttonNextSkipIt()?>

</form>