<?php
namespace JetStudioModule\ApplicationModuleWizard\Basic;

use Jet\UI_button;
use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View $this
 * @var Main $wizard
 */
$wizard = $this->getRaw( 'wizard' );


$setup_form = $wizard->getSetupForm();

?>
<?= $setup_form->start() ?>
<div class="section-title"><?= Tr::_( 'Main module parameters' ) ?></div>

<div class="form-fields" style="grid-template-columns: 0.3fr 1fr;">
<?= $setup_form->field( 'NAME' ) ?>

<?= $setup_form->field( 'LABEL' ) ?>
<?= $setup_form->field( 'DESCRIPTION' ) ?>
<?= $setup_form->field( 'AUTHOR' ) ?>
<?= $setup_form->field( 'LICENSE' ) ?>
<?= $setup_form->field( 'COPYRIGHT' ) ?>
</div>

<div style="text-align: right">
	<?= UI::button_save( Tr::_( 'Create' ) )->setClass( UI_button::CLASS_PRIMARY )->setIcon( 'magic' ) ?>
</div>
<?= $setup_form->end() ?>

