<?php
namespace JetStudioModule\InputCatchers;


use Jet\MVC_View;
use JetStudio\JetStudio_UI;

/**
 * @var MVC_View $this
 */

$what_to_edit = '';

$class = Main::getCurrentClass();

$property = Main::getCurrentProperty();

?>
<script type="text/javascript">
	const Forms = {
		search: {
			reset: function () {
				$('#class_search').val('');

				$('.class_list_item').show();
				$('#current-item').show();
			},
			search: function () {
				$('#current-item').hide();

				let value = $('#class_search').val();

				if (!value) {
					Modules.search.reset();
					return;
				}

				value = value.toLowerCase();

				$('.class_list_item').each(function (index, row) {
					row = $(row);

					const name = row.data('name').toLowerCase();

					if (
						name.includes(value)
					) {
						row.show();
					} else {
						row.hide();
					}

				});

			}
		},
		generateViewScript: () => {
			$('#generated_form_view_script').load( '<?=Main::getActionUrl('generate_view_script')?>' );
			$('#generate_view_script_dialog').modal('show');
		},
	};
</script>

<div style="display: grid;grid-template-columns: 1fr 2fr;gap: 10px">
	<div>
		<?= $this->render( 'list' ); ?>
	</div>
	<div>
		<div class="toolbar" id="main-toolbar">
			<?php if( $class ): ?>
				<?php
				if($property) {
					if($property->getInputCatcherDefinition()) {
						require 'property/edit/toolbar.phtml';
					} else {
						require 'property/set_type/toolbar.phtml';
					}
				}
				?>
			<?php endif; ?>
		</div>
		
		<div id="main-col">
			<br>
			<div class="container-fluid">
			<?= JetStudio_UI::messages(); ?>
			
			<?php
			if($class) {
				if($property) {
					if($property->getInputCatcherDefinition()) {
						require 'property/edit/form.phtml';
					} else {
						require 'property/set_type/form.phtml';
					}
				}
			}
			?>
			</div>
		</div>
	</div>
</div>
