<?php

namespace JetStudio;

use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this ;
 * @var Form $form
 */

$form = $this->getRaw( 'form' );

$form->setDefaultLabelWidth( [Form::LJ_SIZE_MEDIUM => 4] );
$form->setDefaultFieldWidth( [Form::LJ_SIZE_MEDIUM => 8] );

$form->field( 'namespace' )->input()->addJsAction( 'onchange', "DataModel.create.generateScriptPath(this.form)" );
$form->field( 'class_name' )->input()->addJsAction( 'onkeyup', "DataModel.create.generateScriptPath(this.form);DataModel.create.generateModelName(this.form);" );

echo $form->start();
echo $form->field( 'type' );
echo $form->field( 'N_class_name' );

echo $form->getCommonMessage();

echo $form->field( 'namespace' );
echo $form->field( 'class_name' );
echo $form->field( 'model_name' );
echo $form->field( 'script_path' );

foreach( $form->getFields() as $field ) {
	if( !str_starts_with( $field->getName(), 'related_' ) ) {
		continue;
	}

	echo $field;
}


echo $form->end();
