<?php
namespace JetApplicationModule\JetExample\Articles;
use Jet;
use JetApplicationModule\JetExample\UIElements\DataGrid;
use Jet\Mvc_MicroRouter;
use Jet\Tr;
use Jet\Locale;

/**
 * @var DataGrid $grid
 */
$grid = $this->grid;


/**
 * @var Mvc_MicroRouter $router
 */
$router = $this->router;

$c_edit = $grid->getColumn('_edit_');
$c_edit->setDisplayCallback( function( Article $item ) use ( $router) {
	?>
	<?php if($router->getActionAllowed('edit')): ?>
	<a href="<?=$router->getActionURI('edit', $item);?>" class="btn btn-default btn-xs"><?=Tr::_('Edit');?></a>
	<?php endif; ?>
	&nbsp;
	<?php if($router->getActionAllowed('delete')): ?>
	<a href="<?=$router->getActionURI('delete', $item);?>" class="btn btn-danger btn-xs"><?=Tr::_('Delete');?></a>
	<?php endif; ?>
	<?php
} );
$c_edit->setAllowSort(false);
$c_edit->setCssStyle( 'width:120px;' );

$grid->getColumn('title')->setDisplayCallback( function( Article $item ) use ( $router) {
	?>
	<?php if($router->getActionAllowed('edit')): ?>
	<a href="<?=$router->getActionURI('edit', $item);?>"><?=$item->getTitle();?></a>
	<?php else: ?>
	<a href="<?=$router->getActionURI('view', $item);?>"><?=$item->getTitle();?></a>
	<?php endif; ?>
	<?php
} );

$c_date_time = $grid->getColumn('date_time');
$c_date_time->setDisplayCallback( function( Article $item ) {
	echo Locale::dateAndTime( $item->getDateTime() );
} );

$c_date_time->setCssStyle( 'width:200px;' );

?>

<div style="padding: 10px;">

<?php if($router->getActionAllowed('add')): ?>
<a href="<?=$router->getActionURI('add');?>" class="btn btn-primary"><?=Tr::_('Create new article');?></a>
<?php endif; ?>

<?=$grid->render(); ?>

</div>
