<?php
use JetApplicationModule\JetExample\Articles\Article;
use Jet\Mvc_Controller_Router;
use Jet\Tr;
use Jet\Mvc;

/**
 * @var Article $article
 */
$article = $this->article;

/**
 * @var Mvc_Controller_Router $router
 */
$router = $this->router;

?>

<div style="padding: 10px;">

	<a href="<?=Mvc::getCurrentPageURI();?>" class="btn btn-default"><?=Tr::_('&lt Back');?></a>

	<p>
	<?=Tr::_('Do you really want to delete this article?');?>
	<br/>
	<a href="<?=$router->getActionURI('edit', $article);?>" style="font-weight: bolder;font-size: 20px;"><?=$article->getTitle();?></a>
	</p>

	<form action="?delete=<?=rawurlencode($article->getIdObject());?>" method="post">
		<input type="hidden" name="delete" value="yes">
		<input type="submit" value="<?=Tr::_('YES! Delete it!');?>" class="btn btn-danger"/>
	</form>
</div>