<?php
namespace JetApplicationModule\JetExample\Articles;
use Jet;

/**
 * @var Article $article
 */
$article = $this->article;
?>

<div style="padding: 10px;">

	<a href="?" class="btn btn-default"><?=Jet\Tr::_('&lt Back');?></a>

	<p>
	<?=Jet\Tr::_('Do you really want to delete this article?');?>
	<br/>
	<a href="?ID=<?=rawurlencode($article->getID());?>" style="font-weight: bolder;font-size: 20px;"><?=$article->getTitle();?></a>
	</p>

	<form action="?delete=<?=rawurlencode($article->getID());?>" method="post">
		<input type="hidden" name="delete" value="yes">
		<input type="submit" value="<?=Jet\Tr::_('YES! Delete it!');?>" class="btn btn-danger"/>
	</form>
</div>