<?php
namespace JetApplicationModule\JetExample\Articles;
use Jet;
use Jet\Mvc;
use Jet\Tr;

?>
<div style="padding: 10px;">

<a href="<?=Mvc::getCurrentURI();?>" class="btn btn-warning"><?=Tr::_('&lt; go back');?></a>

<jet_form name="Article">
	<jet_form_common_error_message class="formError"/>

	<jet_form_field name="ID"/>
	<div class="form-group">
		<jet_form_field_label name="locale"/>
		<jet_form_field_error_msg name="locale" class="error"/>
		<jet_form_field name="locale" class="form-control"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="title"/>
		<jet_form_field_error_msg name="title" class="error"/>
		<jet_form_field name="title" class="form-control"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="annotation"/>
		<jet_form_field_error_msg name="annotation" class="error"/>
		<jet_form_field name="annotation" class="form-control" style="height: 200px;"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="text"/>
		<jet_form_field_error_msg name="text" class="error"/>
		<jet_form_field name="text" class="form-control" style="height: 600px;"/>
	</div>
	<div class="form-group">
		<jet_form_field_label name="date_time"/>
		<jet_form_field_error_msg name="date_time" class="error"/>
		<jet_form_field name="date_time" class="form-control"/>
		<jet_form_field_time name="date_time" class="form-control"/>
	</div>

	<?php if($this->has_access): ?>
	<input type="submit" value="<?=$this->btn_label;?>" class="btn btn-primary"/>
	<?php endif; ?>
</jet_form>

</div>