<?php
Jet\Mvc::requireSiteCssFile( 'main.css' );
Jet\Mvc::requireCssFile( '//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css' );
Jet\Mvc::requireSiteJavascriptFile( 'test.js' );
?>
<!DOCTYPE html>
<html>
<head>
	<title>Test : %JET_SITE_TITLE% - %JET_PAGE_TITLE%</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="%JET_LANGUAGE%" />

	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>

	<jet_layout_header_suffix/>
</head>
<body class="%DOJO_THEME%">
<div style="display: none;">
	<jet_layout_body_prefix/>
</div>

<div class="row">
	<div class="col-md-12">
		<h1><?=Jet\Tr::_("Hello WORLD!");?></h1>

		<jet_layout_position name="top"/>
	</div>
</div>

<div class="row">
	<div class="clear"></div>

	<div class="col-md-2">
		<jet_module data-module-name="JetExample.TestModule" data-action="main_menu"/>
		<jet_layout_position name="left"/>
	</div>
	<div class="col-md-5">
		<jet_module data-module-name="JetExample.BreadcrumbNavigation" data-action-parameters="{view:default}" />
		<jet_layout_main_position/>
	</div>
	<div class="col-md-5">
		<jet_layout_position name="right"/>
	</div>
</div>


<div style="display: none;">
	<jet_layout_body_suffix/>
</div>
</body>
</html>