<?php
namespace JetApplication;

use Jet\Form;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );
$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 4 ] );

$form->field( 'locale' )->input()->addJsAction( 'onchange', 'this.form.submit();' );
?>

<?=$form->start()?>
<?=$form->field( 'locale' )?>
<?=$form->end()?>

<?php Installer::continueForm(); ?>