<?php
namespace JetApplication;

use Jet\Form;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View $this
 * @var Form     $form
 */
$form = $this->getRaw( 'form' );
$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 4 ] );

$form->field( 'locale' )->input()->addJsAction( 'onchange', 'this.form.submit();' );
?>
<h1><?=Tr::_( 'Welcome!' );?></h1>

<?=$form->start()?>
<?=$form->field( 'locale' )?>
<?=$form->end()?>

<form method="post">
	<input type="hidden" name="go" value="1">
	<?=Installer::buttonNext();?>
</form>