<?php

namespace JetApplication\Installer;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var MVC_View $this
 */
?>


	<?php foreach( Installer::getAvailableLocales() as $locale ): ?>
	<div style="padding: 10px">
		<?php if( $locale->toString() == Installer::getCurrentLocale()->toString() ): ?>
			<?= UI::flag( $locale ) ?>&nbsp;&nbsp;<b><?= $locale->getLanguageName( $locale ) ?></b>
			<br/>
			<a href="?locale=<?= $locale ?>"><?= Tr::_( 'Please choose your language', [], Installer::getCurrentStepName(), $locale ) ?></a>
		<?php else: ?>
			<?= UI::flag( $locale ) ?>&nbsp;&nbsp;<?= $locale->getLanguageName( $locale ) ?>
			<br/>
			<a href="?locale=<?= $locale ?>"><?= Tr::_( 'Please choose your language', [], Installer::getCurrentStepName(), $locale ) ?></a>
		<?php endif; ?>
	</div>
<?php endforeach; ?>

<?= Installer::continueForm() ?>