<b>PHP INTL extension (module) is not installed and/or activated</b><br>
<a href="https://www.php.net/manual/en/book.intl.php" target="_blank">PHP Internationalization Functions</a> extension must be activated.
<br>
<br>
<b>PHP INTL extenze (modul) není nainstalován a/nebo aktivován</b><br>
<a href="https://www.php.net/manual/en/book.intl.php" target="_blank">PHP extenze lokalizačních funkcí</a> musí být nainstalována a aktivní.<br>
