<?php
namespace JetStudio;

use Jet\Http_Request;
use Jet\Tr;
use Jet\MVC_View;
use Jet\UI;
use Jet\UI_badge;

/**
 * @var MVC_View $this
 */

$module = Modules::getCurrentModule();

if( !$module ) {
	return;
}

$menu_items = $module->getMenuItems();
if(!$menu_items->getList()) {
	return;
}

$current_menu_item = Modules::getCurrentMenuItem();
?>
<table class="table table-striped">
	<tr>
		<td><b><?= Tr::_( 'Menu items' ) ?></b></td>
	</tr>
	<?php foreach( Menus::getSets() as $set_id => $set ):

		if( !$menu_items->getList( $set->getName() ) ) {
			continue;
		}

		foreach( $set->getMenus() as $menu_id => $menu ):
			if( !($items = $menu_items->getList( $set->getName(), $menu->getId() )) ) {
				continue;
			}
			?>
			<tr>
				<td style="font-size: 10px;padding-left: 20px;"><b><?= $set_id ?> / <?= $menu_id ?></b></td>
			</tr>
			<?php

			foreach( $items as $item ):
				?>
				<tr>
					<td style="padding-left: 50px;">
						<?php if( $current_menu_item && $current_menu_item->getFullId() == $item->getFullId() ):
							echo UI::badge(UI_badge::INFO, $item->getId());
						else: ?>
							<a href="<?= Http_Request::currentURI( ['menu_item' => $item->getFullId()], [
								'page',
								'action'
							] ) ?>"><?= $item->getId() ?></a>
						<?php endif; ?>
					</td>
				</tr>
			<?php
			endforeach;
		endforeach;
	endforeach; ?>
</table>
