<?php
namespace JetStudio;

use Jet\Form;
use Jet\Form_Field;
use Jet\MVC_View;
use Jet\Form_Renderer;use Jet\Tr;

/**
 * @var MVC_View $this
 * @var Form $form
 */
$form = $this->getRaw('definition_form');
if(!$form) {
	return;
}

$fields = $form->getFields(true);


$form->renderer()
	->setDefaultLabelWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 2] )
	->setDefaultFieldWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 9] );


echo $form->start();

foreach($fields['main'] as $field) {
	echo $field;
}

if(isset($fields['other'])) {
	foreach($fields['other'] as $field) {
		echo $field;
	}
}

?>
<legend><?=Tr::_('Error messages')?></legend>
<?php
$form->renderer()
	->setDefaultLabelWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 3] )
	->setDefaultFieldWidth( [Form_Renderer::LJ_SIZE_MEDIUM => 8] );

foreach(array_keys($fields['error_messages']) as $i):
	$code_field = $form->getField( '/error_messages/'.$i.'/code' );
	$message_field = $form->getField( '/error_messages/'.$i.'/message' );
	
	if($code_field->getType()==Form_Field::TYPE_HIDDEN) {
		echo $code_field;
		echo $message_field;
		
		continue;
	}
	
	$code_field->container()->setWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 3
	]);
	
	$message_field->container()->setWidth([
		Form_Renderer::LJ_SIZE_MEDIUM => 8
	]);
	?>
	<div class="row">
		
		<?=$code_field->container()->start()?>
			<?=$code_field->input()?>
			<?=$code_field->help()?>
			<?=$code_field->error()?>
		<?=$code_field->container()->end()?>
		
		<?=$message_field->container()->start()?>
			<?=$message_field->input()?>
			<?=$message_field->help()?>
			<?=$message_field->error()?>
		<?=$message_field->container()->end()?>
		
	</div>
	<?php
	
endforeach;


echo $form->end();