<title>Jet Example Application</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style type="text/css">
	html, body, #main{
		font: 12pt Arial,Myriad,Tahoma,Verdana,sans-serif;
		width: 100%;
		height: 100%;
	}

	.form-error {
		clear: none;
		background-color: #ff0000;
		color: #ffffff;
		padding: 3px;
	}
	.editAreaBn a {
		color: black;
	}

	.editAreaBn img {
		padding: 0;
	}


    .jet-uploader-file-item-box {
        position: relative;
        margin: 5px;
        min-height: 130px;
    }
    .jet-uploader-file-item-icon-box {
        position: absolute;
        top:5px;
        left: 5px;
        width: 104px;
        height: 104px;
        vertical-align: middle;
        text-align: center;

    }
    .jet-uploader-file-item-icon {
        max-width:100px;
        max-height:100px;

    }

    .jet-uploader-file-item-file-name {
        position: absolute;
        top:0;
        left: 120px;
        padding-top: 20px;
        font-weight: bolder;
    }
    .jet-uploader-file-item-file-size {
        position: absolute;
        top:40px;
        left: 120px;
        font-size: 11px;
    }
    .jet-uploader-file-item-progress-bar-area {
        position: absolute;
        top:60px;
        left: 120px;

    }
    .jet-uploader-file-item-message-area {
        position: absolute;
        top:60px;
        left: 120px;

    }


	.jet-uploader-file-item-box-in-progress {
		background-color: #c9c9c9;
	}

	.jet-uploader-file-item-box-uploaded {
		background-color: #aaffaa;
	}

	.jet-uploader-file-item-box-error {
		background-color: #ffbbbb;
	}
</style>


<jet_layout_meta_tags/>
<jet_layout_javascripts/>
<jet_layout_header_suffix/>