<?php
namespace JetApplicationModule\ManageAccess\Administrators\Roles;

use JetApplication\Auth_Administrator_Role as Role;

use Jet\Form;
use Jet\UI_dataGrid;
use Jet\UI;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var UI_dataGrid $grid
 * @var Form $filter_form
 */
$router = $this->getController()->getControllerRouter();
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );

$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( Role $item ) use ( $router ) {
		if( ($delete_uri = $router->action( 'delete' )->URI( $item->getId() )) ):
			echo UI::button_delete(' ')->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL );
			echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
		endif;

		if( ($edit_uri = $router->action( 'edit' )->URI( $item->getId() )) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL );
		endif;

	}
);
$c_edit->addCustomCssStyle( 'width:180px;' );
$grid->getColumn( 'id' )->addCustomCssStyle( 'width:120px;' );


$grid->getColumn( 'id' )->setRenderer(
	function( Role $item ) use ( $router ) {
		$edit_uri = $router->action( 'edit' )->URI( $item->getId() );

		?><a href="<?= $edit_uri ?>"><?= $item->getId(); ?></a><?php
	}
);

$grid->getColumn( 'name' )->setRenderer(
	function( Role $item ) use ( $router ) {
		$edit_uri = $router->action( 'edit' )->URI( $item->getId() );

		?><a href="<?= $edit_uri ?>"><?= $item->getName(); ?></a><?php
	}
);
$grid->getColumn( 'description' )->setRenderer(
	function( Role $item ) {
		echo $item->getDescription();
	}
);
?>

<?= $filter_form->start() ?>
<div class="row toolbar">
	<div class="col-xs-5 col-md-2">
		<?php if( ($add_uri = $router->action( 'add' )->URI()) ): ?>
			<?= UI::button_create( Tr::_( 'Create a new Role' ) )->setUrl( $add_uri ) ?>
		<?php endif; ?>
	</div>
	<div class="col-xs-7 col-md-3">
		<?= $filter_form->field( 'search' )->input() ?>
	</div>
</div>
<?= $filter_form->end() ?>

<div class="row">
	<div class="col-md-12">
		<?= $grid->render(); ?>
	</div>
</div>
