<?php
namespace JetExampleApp;

use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Form     $form
 */

$form = $this->getRaw( 'form' );
$form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 2 ] );
$form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 4 ] );
?>
<?=$form->start()?>
<?=$form->message()?>

<?=$form->field( 'locale' )?>
<?=$form->field( 'username' )?>
<?=$form->field( 'password' )?>
<?=$form->field( 'email' )?>

<?=Installer::buttonNext();?>
<?=$form->end()?>