<?php
namespace JetStudio;

use Jet\Form_Renderer;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Pages_Page $page
 */

$page = $this->getRaw( 'page' );

$form = $page->getEditForm_callback();

$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 2
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 6
] );


$class_field = $form->field( 'output_callback_class' );
$method_field = $form->field( 'output_callback_method' );
?>
<?= $form->start() ?>

<?= $class_field->row()->start() ?>
<div class="input-group" style="padding-left: 15px;margin-right: 15px;">
	<span class="input-group-prepend"><span class="input-group-text"></span></span>
	<?= $class_field->input() ?>
	<span class="input-group-prepend"><span class="input-group-text">::</span></span>
	<?= $method_field->input() ?>
	<span class="input-group-append"><span class="input-group-text">( Jet\MVC_Page $page )</span></span>
</div>
<?= $class_field->row()->end() ?>

<?= $form->end() ?>
