<?php
namespace JetStudio;

use Jet\Form_Renderer;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Pages_Page $page
 */

$page = $this->getRaw( 'page' );

$form = $page->getEditForm_callback();

$form->renderer()->setDefaultLabelWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 1
] );
$form->renderer()->setDefaultFieldWidth( [
	Form_Renderer::LJ_SIZE_MEDIUM => 8
] );


?>
<?= $form->start() ?>

<?=$form->field('output_callback');?>

<?= $form->end() ?>
