<?php

namespace JetStudio;

use Jet\MVC_View;

/**
 * @var MVC_View $this
 */

$page = Modules::getCurrentPage();
$what = Modules::getCurrentPage_whatToEdit();

$app_part = Application::getCurrentPart();
Application::setCurrentPart( 'pages' );

$view = Application::getView();
Modules::setupPageForms();

$view->setVar( 'page', $page );
$view->setVar( 'what', $what );

echo $view->render( 'page/edit' );

Application::setCurrentPart( $app_part );