<?php

namespace JetStudio;

use Jet\Tr;
use Jet\MVC_View;
use Jet\UI;

/**
 * @var MVC_View $this
 */
/**
 * @var MVC_View $this
 */

$page = Modules::getCurrentPage();
$what = Modules::getCurrentPage_whatToEdit();

$app_part = Application::getCurrentPart();
Application::setCurrentPart( 'pages' );

$view = Application::getView();
Modules::setupPageForms();

$view->setVar( 'page', $page );
$view->setVar( 'what', $what );

echo $view->render( 'page/toolbar' );

Application::setCurrentPart( $app_part );

echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
echo UI::button_delete( Tr::_( 'Delete this page' ) )->setOnClick( "$('#page_delete_dialog').modal('show')" );

$delete_dialog = UI::dialog( 'page_delete_dialog', Tr::_( 'Delete this page?' ) );

echo $delete_dialog->start();
echo Tr::_( 'Do you really want to delete this page?' );
echo $delete_dialog->footer();
echo UI::button_delete()->setUrl( Modules::getActionUrl( 'page/delete' ) );
echo $delete_dialog->end();