<?php
namespace JetStudio;


use Jet\Tr;use Jet\UI;
use Jet\UI_button;
use Jet\UI_dialog;

$what_to_edit = '';

$class = Forms::getCurrentClass();

$property = Forms::getCurrentProperty();

$generate_view_script_dialog = UI::dialog('generate_view_script_dialog', Tr::_('Generated view script'), UI_dialog::SIZE_EXTRA_LARGE);
?>
<script type="text/javascript">
	const Forms = {
		generateViewScript: () => {
			$('#generated_form_view_script').load( '<?=Forms::getActionUrl('generate_view_script')?>' );
			$('#generate_view_script_dialog').modal('show');
		},
	};
</script>

<div class="row toolbar" id="main-toolbar">
	
	<div class="col-md-1" style="padding: 0;">
	</div>
	<div class="col-md-3 text-right" style="padding: 0 10px 0 0;">
	</div>
	<div class="col-md-8" style="padding: 0">
		<?php if( $class ): ?>
		<?php
		if($property) {
			if($property->getFieldDefinition()) {
				require 'property/edit/toolbar.phtml';
			} else {
				require 'property/set_type/toolbar.phtml';
			}
		}
		?>
		<?=UI::button( Tr::_('Generate view script') )->setClass(UI_button::CLASS_LIGHT)->setOnClick('Forms.generateViewScript();')?>
		<?php endif; ?>
	</div>
</div>

<div class="row" id="main-col">
	<?php if( $class ): ?>
		<div class="col-md-4" style="padding: 0;">
			<?= Application::getView()->render( 'list' ); ?>
		</div>
		<div class="col-md-8" style="padding: 10px">
			<?=Application::getGeneralView()->render( 'messages' );?>
			<div class="container-fluid">
				
				<?php
				if($property) {
					if($property->getFieldDefinition()) {
						require 'property/edit/form.phtml';
					} else {
						require 'property/set_type/form.phtml';
					}
				}
				?>
			</div>
		</div>
	<?php else: ?>
		<div class="col-md-12">
			<?= Application::getView()->render( 'list' ); ?>
		</div>
	<?php endif; ?>
</div>

<?=$generate_view_script_dialog->start()?>
<textarea style="width: 100%;height: 500px;" id="generated_form_view_script"></textarea>
<?=$generate_view_script_dialog->end()?>
