<?php

namespace JetStudio;


$what_to_edit = '';

$class = Forms::getCurrentClass();


?>

<div class="row toolbar" id="main-toolbar">
	
	<div class="col-md-1" style="padding: 0;">
	</div>
	<div class="col-md-3 text-right" style="padding: 0 10px 0 0;">
	</div>
	<div class="col-md-8" style="padding: 0">
		<?php if( $what_to_edit ): ?>
		
		<?php endif; ?>
	</div>
</div>

<div class="row" id="main-col">
	<?php if( $class ): ?>
		<div class="col-md-4" style="padding: 0;">
			<?= Application::getView()->render( 'list' ); ?>
		</div>
		<div class="col-md-8" style="padding: 10px">
			<?php
			echo Application::getGeneralView()->render( 'messages' );
			
			$what_to_edit = Forms::getCurrentWhatToEdit();
			?>
			<div class="container-fluid">
				<?php require $what_to_edit . '/edit/form.phtml'; ?>
			</div>
		</div>
	<?php else: ?>
		<div class="col-md-12">
			<?= Application::getView()->render( 'list' ); ?>
		</div>
	<?php endif; ?>
</div>
