<?php
use Jet\UI_dataGrid;
use Jet\Mvc_View;

/**
 * @var Mvc_View    $this
 * @var UI_dataGrid $grid
 */
$grid = $this->getRaw( 'grid' );
?>
<tbody>
<?php foreach( $grid->getData() as $i => $item ): ?>
	<tr>
		<?php foreach( $grid->getColumns() as $column ):
			$callback = $column->getDisplayCallback();
			?>
			<td>
				<?=$callback( $item, $i );?>
			</td>
		<?php endforeach; ?>
	</tr>
<?php endforeach; ?>
</tbody>
