<?php
use JetUI\dataGrid;
use JetUI\UI;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var dataGrid $grid
 */
$grid = $this->getRaw( 'grid' );
?>
<table class="table table-striped">

	<thead>
	<tr>
		<?php foreach( $grid->getColumns() as $column ):
			$style = $column->getCssStyle() ? ' style="'.$column->getCssStyle().'"' : '';
			$class = $column->getCssClass() ? ' class="'.$column->getCssClass().'"' : '';
			?>
			<th<?=$class;?><?=$style;?>>

				<?php if( $column->getAllowSort() ): ?>
					<?php if( $column->getSortByAsc() ): ?>
						<?=UI::icon( 'sort-amount-asc' )->setSize( 11 )?>
					<?php else: ?>
						<a href="<?=$grid->getSortURL( $column->getName() );?>">
							<?=UI::icon( 'sort-amount-asc' )->setSize( 11 )?>
						</a>
					<?php endif; ?>
				<?php endif; ?>
				<?=$column->getTitle();?>

				<?php if( $column->getAllowSort() ): ?>
					<?php if( $column->getSortByDesc() ): ?>
						<?=UI::icon( 'sort-amount-desc' )->setSize( 11 )?>
					<?php else: ?>
						<a href="<?=$grid->getSortURL( $column->getName(), true );?>">
							<?=UI::icon( 'sort-amount-desc' )->setSize( 11 )?>
						</a>
					<?php endif; ?>
				<?php endif; ?>
			</th>
		<?php endforeach; ?>
	</tr>
	</thead>
