<?php
use Jet\UI_dataGrid;
use Jet\UI;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View    $this
 * @var UI_dataGrid $grid
 */
$grid = $this->getRaw( 'grid' );

$paginator = $grid->getPaginator();
?>

<?php if( $paginator->getPagesCount()>1 ):
	$pages = $paginator->getPagesURL();

	$s_index = $paginator->getCurrentPageNo()-3;
	$e_index = $paginator->getCurrentPageNo()+3;
	if( $s_index<1 ) {
		$e_index = $e_index+( $s_index*-1 )+1;
		$s_index = 1;
	}

	if( $e_index>count( $pages ) ) {
		$e_index = count( $pages );
		$s_index = $e_index-6;
		if( $s_index<1 ) {
			$s_index = 1;
		}
	}

	?>
	<tfoot>
	<tr>
		<td colspan="<?=count( $grid->getColumns() );?>">
			<div>
				<?=Tr::_(
					'%FROM% - %TO% / total count: %COUNT%', [
					'FROM'  => $paginator->getShowFrom(), 'TO' => $paginator->getShowTo(),
					'COUNT' => $paginator->getDataItemsCount(),
				], Tr::COMMON_NAMESPACE
				)?>
			</div>

			<nav>

				<ul class="pagination pagination-sm">
					<?php if( ( $p_URL = $paginator->getFirstPageURL() ) ): ?>
						<li>
							<a href="<?=$p_URL?>" aria-label="<?=Tr::_( 'Firts', [], Tr::COMMON_NAMESPACE )?>">
								<?=UI::icon( 'backward' )?>
							</a>
						</li>

					<?php endif ?>
					<?php if( ( $p_URL = $paginator->getPrevPageURL() ) ): ?>
						<li>
							<a href="<?=$p_URL?>" aria-label="<?=Tr::_( 'Previous', [], Tr::COMMON_NAMESPACE )?>">
								<?=UI::icon( 'chevron-left' )?>
							</a>
						</li>
					<?php endif ?>


					<?php
					for( $p_no = $s_index; ( $p_no<=$e_index&&isset( $pages[$p_no] ) ); $p_no++ ):
						$p_URL = $pages[$p_no];

						?>
						<?php if( $p_no==$paginator->getCurrentPageNo() ): ?>
						<li class="active"><a href="<?=$p_URL?>"><?=$p_no?></a></li>
					<?php else: ?>
						<li><a href="<?=$p_URL?>"><?=$p_no?></a></li>
					<?php endif; ?>
					<?php endfor; ?>


					<?php if( ( $p_URL = $paginator->getNextPageURL() ) ): ?>
						<li>
							<a href="<?=$p_URL?>" aria-label="<?=Tr::_( 'Next', [], Tr::COMMON_NAMESPACE )?>">
								<?=UI::icon( 'chevron-right' )?>
							</a>
						</li>
					<?php endif ?>
					<?php if( ( $p_URL = $paginator->getLastPageURL() ) ): ?>
						<li>
							<a href="<?=$p_URL?>" aria-label="<?=Tr::_( 'Last', [], Tr::COMMON_NAMESPACE )?>">
								<?=UI::icon( 'forward' )?>
							</a>
						</li>
					<?php endif ?>

				</ul>
			</nav>

		</td>
	</tr>
	</tfoot>

<?php endif; ?>
