<?php
namespace JetStudio;

use Jet\UI_messages;

if(!DataModels::getCurrentModel()) {
	return;
}
$class = DataModels::getCurrentModel()->createClass();

$errors = [];
$warnings = [];

if( $class ) {
	$errors = $class->getErrors();
	$warnings = $class->getWarnings();
}


echo Application::getGeneralView()->render('messages');

foreach( $warnings as $warning ) {
	echo '<div style="padding: 5px">'.UI_messages::createWarning( $warning ).'</div>';
}

foreach( $errors as $error ) {
	echo '<div style="padding: 5px">'.UI_messages::createDanger( $error ).'</div>';
}

$what_to_edit = DataModels::getCurrentWhatToEdit();
?>
<div class="container-fluid">
	<?php require $what_to_edit.'/form.phtml'; ?>
</div>
