<?php
namespace JetStudio;

use Jet\Tr;
use Jet\Form;
use Jet\UI_messages;

$current = DataModels::getCurrentModel();

$form = $current->getEditForm();

$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);
$form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 10
]);

$class = DataModels::getCurrentModel()->createClass();

$errors = [];
$warnings = [];

if( $class ) {
	$errors = $class->getErrors();
	$warnings = $class->getWarnings();
}


echo Application::getGeneralView()->render('messages');

foreach( $warnings as $warning ) {
	echo '<div style="padding: 5px">'.UI_messages::createWarning( $warning ).'</div>';
}

foreach( $errors as $error ) {
	echo '<div style="padding: 5px">'.UI_messages::createDanger( $error ).'</div>';
}

?>
<legend><?=Tr::_('DataModel parameters')?></legend>

<?=$form->start()?>

<?php $current->showEditFormFields()?>

<?=$form->end()?>

