<?php
namespace JetApplicationModule\JetExample\Test\REST;

use Jet\Mvc_View;
use Jet\Form;
use Jet\UI;
use Jet\Tr;

/**
 *
 * @var Mvc_View $this
 * @var Form $form
 * @var Client $client
 */

$form = $this->getRaw('form');
$client = $this->getRaw('client');
?>
<h1><?=Tr::_('REST API Tests - client login')?></h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="panel-title"><?=Tr::_( 'Sign In' )?></div>
			</div>

			<div class="panel-body">
				<?php
				echo $form->start();
				echo $form->getField('username');
				echo $form->getField('password');

				?>
				<div style="margin-top:10px" class="form-group">
					<div class="col-sm-12 controls">
						<div style="float: right">
							<?=UI::button()->setLabel( Tr::_('Sign In') )->setType('submit');?>
						</div>
					</div>
				</div>

				<?php
				echo $form->end();
				?>

			</div>
		</div>
	</div>
</div>


<?php if($client): ?>
<div class="row">
	<div class="col-md-12">
		<h3><?=Tr::_('Request')?></h3>
		<h4><?=Tr::_('Header')?></h4>
		<pre><?=$client->request()?></pre>
		<?php if($client->requestBody()): ?>
			<h4><?=Tr::_('Body')?></h4>
			<pre><?=is_string($client->requestBody()) ? $client->requestBody(): var_dump($client->requestBody())?></pre>
			<h4><?=Tr::_('Data')?></h4>
			<pre><?=var_export( $client->requestData(), true )?></pre>
		<?php endif; ?>


		<h3><?=Tr::_('Response')?></h3>
		<h4><?=Tr::_('Header')?></h4>
		<pre><?=$client->responseHeader()?></pre>
		<h4><?=Tr::_('Body')?></h4>
		<pre><?=$client->responseBody()?></pre>
		<h4><?=Tr::_('Data')?></h4>
		<pre><?=var_export($client->responseData(), true)?></pre>
	</div>
</div>
<?php endif;?>