<?php
namespace JetApplicationModule\JetExample\Test\REST;

use Jet\Http_Request;
use Jet\Tr;
/**
 *
 */


/*
$cl = new Client( $_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW'] );

$cl->get('article')['items'];
*/

$test_client = $this->getRaw('test_client');

?>
<div class="container">
	<div class="row">
		<h1><?=Tr::_('REST tests')?></h1>
	</div>
	<div class="row">
		<div class="col-md-4">
			<h2><?=Tr::_('Articles')?></h2>
			<ul>
				<li><a href="<?=Http_Request::currentURL(['test'=>'article_get_list'])?>"><?=Tr::_('Get list')?></a></li>

				<li><a href="<?=Http_Request::currentURL(['test'=>'article_get_unknown'])?>"><?=Tr::_('Get data - unknown (error simulation)')?></a></li>

				<li><a href="<?=Http_Request::currentURL(['test'=>'article_get_one'])?>"><?=Tr::_('Get data')?></a></li>

			</ul>
		</div>
		<div class="col-md-8">
			<?php if( isset($test_client) ): ?>
				<h3><?=Tr::_('Request')?></h3>
				<pre><?=$test_client->request()?></pre>

				<h3><?=Tr::_('Response')?></h3>
				<h4><?=Tr::_('Header')?></h4>
				<pre><?=$test_client->responseHeader()?></pre>
				<h4><?=Tr::_('Body')?></h4>
				<pre><?=$test_client->responseHeader()?></pre>
				<h4><?=Tr::_('Data')?></h4>
				<pre><?=var_export($test_client->responseData(), true)?></pre>
			<?php endif; ?>
		</div>
	</div>

</div>

