<?php
namespace JetApplicationModule\JetExample\Test\REST;

use Jet\Http_Request;
use Jet\Tr;
use Jet\Mvc_View;
/**
 *
 * @var Mvc_View $this
 * @var Test_Abstract $selected_test
 */


$tests = $this->getRaw('tests');
$selected_test = $this->getRaw('selected_test');

?>
<div class="container">
	<div class="row">
		<h1><?=Tr::_('REST tests')?></h1>
	</div>
	<div class="row">
		<div class="col-md-4">
			<?php foreach($tests as $tests_data): ?>
				<h2><?=$tests_data['title']?></h2>
				<ul>
					<?php foreach($tests_data['tests'] as $test):
					/**
					 * @var Test_Abstract $test
					 */
					if(!$test->isEnabled()) {
						continue;
					}

					if($test->isSelected()):
						?>
						<li><strong><?=$test->getTitle()?></strong></li>
						<?php
					else:
						?>
						<li><a href="<?=Http_Request::currentURL(['test'=>$test->getId()])?>"><?=$test->getTitle()?></a></li>
						<?php
					endif;
					endforeach; ?>
				</ul>
			<?php endforeach; ?>
		</div>
		<div class="col-md-8">
			<?php if( $selected_test ):
				$selected_test->showResult();
			endif; ?>
		</div>
	</div>

</div>

