<?php
namespace JetStudio;


?>

<script type="text/javascript">
    if(!window['JetStudio']) {
    	var JetStudio = {};
    }

	JetStudio.DataModel = {
		create: {
			openDialog: function() {
				$('#dialog_create_new_data_model').modal('show');
			},
			createSend: function() {
				JetAjaxForm.submit(
					'<?=DataModel_Definition_Model_Main::getCreateForm()->getId()?>',
					{
						onSuccess: function( form, response_data ) {
							location = '?'
                                +'&model='+encodeURIComponent(response_data['new_model_id'])
						}
					}
				);
			}
		},

        edit: {
	        showSQLCreate: function(){
	        	$.ajax(
					'<?=DataModels::getActionUrl('generate/SQL_create')?>'
		        ).done( function( data ) {
		        	$('#SQL_create_result').val(data);
			        $('#dialog_SQL_create').modal('show');
		        } );
            },

	        showSQLUpdate: function(){
		        $.ajax(
			        '<?=DataModels::getActionUrl('generate/SQL_update')?>'
		        ).done( function( data ) {
			        $('#SQL_update_result').val(data);
			        $('#dialog_SQL_update').modal('show');
		        } );
	        },

	        showClassSource: function(){
		        $.ajax(
			        '<?=DataModels::getActionUrl('generate/class_source')?>'
		        ).done( function( data ) {
			        $('#class_source_result').val(data);
			        $('#dialog_class_source').modal('show');
		        } );
	        },


		    defaultOrderBy: {
		    	selectItem: function( id ) {
		    		var values_field = $('#edit_model_form__default_order_by');
                    var values = values_field.val();

                    if(values.length) {
	                    values = values.split('|');
                    } else {
                    	values = new Array();
                    }

				    values.push('+'+id);
				    values = values.join('|');

				    $('.order_by_options_item[data-id="'+id+'"]').hide();

				    values_field.val( values );

				    JetStudio.DataModel.edit.defaultOrderBy.actualizeSelected();
                },

			    unSelectItem: function( id ) {
				    $('.order_by_options_item[data-id="'+id+'"]').show();
				    var values_field = $('#edit_model_form__default_order_by');

				    var values = values_field.val().split('|');

				    var val = '';
				    var e_id = '';
				    var new_values = new Array();

				    for(var i=0;i<values.length;i++) {
				    	val = values[i];
					    e_id = val.substr(1);

					    if(id!=e_id) {
						    new_values.push(val);
                        }
				    }

				    new_values = new_values.join('|');

				    $('#edit_model_form__default_order_by').val( new_values );

				    JetStudio.DataModel.edit.defaultOrderBy.actualizeSelected();
                },


			    setSort: function( id, sort ) {
				    var values_field = $('#edit_model_form__default_order_by');

				    var values = values_field.val().split('|');

				    var val = '';
				    var e_id = '';
				    var o_sort = '';
				    var new_values = new Array();

				    for(var i=0;i<values.length;i++) {
					    val = values[i];
					    o_sort = val.substr(0, 1);
					    e_id = val.substr(1);

					    if(id==e_id) {
						    new_values.push(sort+e_id);
					    } else {
					    	new_values.push(val);
                        }
				    }

				    new_values = new_values.join('|');

				    $('#edit_model_form__default_order_by').val( new_values );

				    $('.order_by_options_item_selected[data-id="'+id+'"]').data('sort', sort);

				    JetStudio.DataModel.edit.defaultOrderBy.actualizeSelected();
			    },


                actualizeSelected: function() {
	                var values_field = $('#edit_model_form__default_order_by');
	                if(!values_field.length) {
	                	return;
                    }

	                var values = values_field.val().split('|');
		    		var selected_area = $('#order_by_options_selected');

		    		var html = '';
		    		var id = '';
		    		var label = '';
		    		var sort = '';

		    		if(values_field.val()) {
					    for(var i=0;i<values.length;i++) {
						    id = values[i];
						    sort = id.substr(0,1);
						    id = id.substr(1);
						    label = $('.order_by_options_item[data-id="'+id+'"]').data('label');

						    $('.order_by_options_item[data-id="'+id+'"]').hide();

						    html += '<div'
							    +' class="list-group-item order_by_options_item_selected"'
							    +' data-id="'+id+'"'
							    +' data-sort="'+sort+'"'
							    +'>';

					        html += '<i class="property-option-move ui-sortable-handle" style="cursor: ns-resize"><span class="fa fa-arrows-v" style="font-size:16px;padding-right: 5px"></span></i>';

						    html += '<span class="fa fa-minus" style="font-size:16px;padding-right: 5px" onclick="JetStudio.DataModel.edit.defaultOrderBy.unSelectItem(\''+id+'\')"></span>';

						    if(sort=='-') {
						        html += '<span class="fa fa-sort-alpha-desc" style="font-size:16px;padding-right: 5px" onclick="JetStudio.DataModel.edit.defaultOrderBy.setSort(\''+id+'\',\'+\')"></span>';
                            } else {
							    html += '<span class="fa fa-sort-alpha-asc" style="font-size:16px;padding-right: 5px" onclick="JetStudio.DataModel.edit.defaultOrderBy.setSort(\''+id+'\',\'-\')"></span>';
                            }
						    html += label;
						    html += '</div>';
					    }
                    }

		    		selected_area.html( html );

	                selected_area.sortable({
		                handle: 'i.property-option-move',
		                stop: function() {

		                	var new_values = new Array();

			                selected_area.find('.order_by_options_item_selected').each( function(i, item) {
				                var id = $(item).data('id');
				                var sort = $(item).data('sort');

				                new_values.push(sort+id);
			                });

			                $('#edit_model_form__default_order_by').val(new_values.join('|'));
		                }

	                });

                }
            }
        },


		key: {
			create: {
				openDialog: function() {
					$('#dialog_create_new_key').modal('show');
				},
				createSend: function() {
					JetAjaxForm.submit(
						'key_add_form',
						{
							onSuccess: function( form, response_data ) {
								location.reload();
							}
						}
					);
				}
			},

			delete: {
				openDialog: function() {
					$('#delete_key').modal('show');
				}
			}
		},

		relation: {
			create: {
				openDialog: function() {
					$('#dialog_create_new_relation').modal('show');
				},

				selectModel: function( related_model_id ) {
					$('#create_relation_form_area').load(
						'<?=DataModels::getActionUrl('relation/add_form')?>&related_model='+related_model_id
					);
				},
				createSend: function() {
					JetAjaxForm.submit(
						'create_external_relation_form',
						{
							onSuccess: function( form, response_data ) {
								location.reload();
							}
						}
					);
				}

			},

			delete: {
				openDialog: function() {
					$('#delete_relation').modal('show');
				}
			}
		},

		property: {
			create: {
				openDialog: function() {
					$('#dialog_create_new_property').modal('show');
				},
				createSend: function() {
					JetAjaxForm.submit(
						'<?=DataModel_Definition_Property::getCreateForm()->getId()?>',
						{
							onSuccess: function( form, response_data ) {
								JetStudio.DataModel.property.initPropertiesSort();

								var id_controller_field = $('#edit_model_form__id_controller_class');
								if(id_controller_field.length) {
									id_controller_field.val( response_data['id_controller_class'] );
								}
							}
						}
					);
				}
			},

			edit: {
				form_field_types: <?=json_encode( DataModel_Definition_Property::getFormFieldTypes() )?>,
				selectFormFieldType: function( property_id, selected_type ) {

					$('.ffd-property-'+property_id).hide();
					$('.ffd-em-property-'+property_id).hide();

					if(!JetStudio.DataModel.property.edit.form_field_types[selected_type]) {
						return;
					}

					var d = JetStudio.DataModel.property.edit.form_field_types[selected_type];

					var i;
					var required_option;
					for( i in  d.required_options) {
						required_option = d.required_options[i];

						$('.ffd-property-'+property_id+'.ffd-option-'+required_option).show();
					}

					var required_em;
					for( i in  d.required_error_messages) {
						required_em = d.required_error_messages[i];

						$('.ffd-em-property-'+property_id+'.ffd-em-'+required_em).show();
					}


				},

				save: function( property_id ) {
					JetAjaxForm.submit(
						'property_edit_form_'+property_id,
						{
							onSuccess: function( form, response_data ) {
								var id_controller_field = $('#edit_model_form__id_controller_class');
								if(id_controller_field.length) {
									id_controller_field.val( response_data['id_controller_class'] );
								}

								var header = $('#property_panel_'+property_id);
								header.removeClass('panel-default');
								header.removeClass('panel-primary');
								header.removeClass('panel-success');
								header.removeClass('panel-info');
								header.removeClass('panel-warning');
								header.removeClass('panel-danger');

								header.addClass('panel-'+response_data['head_css_class']);
							}
						}
					);

				}
			},

			initPropertiesSort: function() {
				var sort_area = $('#property_sort_area');

				sort_area.sortable({
					handle: 'i.property-option-move',
					stop: function() {

						sort_area.find('.property-sort-item').each( function(i, item) {
							var id = $(item).data('property-id');

							$('#sort_properties_form__p_'+id).val(i);
						});



						JetAjaxForm.submit(
							'sort_properties_form',
							{
								onSuccess: function() {
									JetStudio.DataModel.property.initPropertiesSort();
								}
							}
						);
					}

				});

			}

		},


        generateClassName: function( model_name, class_name_field_id ) {
			var class_name = model_name.toLowerCase();

	        class_name = class_name.split('_');

	        var part = '';
	        for( var i in class_name ) {
	        	part = class_name[i];

		        class_name[i] = part.charAt(0).toUpperCase() + part.slice(1);
            }

            class_name = class_name.join('_');

	        $( '#'+class_name_field_id ).val(class_name);
        }
	};

	$(document).ready(function() {
		JetStudio.DataModel.property.initPropertiesSort();
		JetStudio.DataModel.edit.defaultOrderBy.actualizeSelected()
    });
</script>
