<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;


?>
<?=Application::getView()->render('js');?>

<div class="row toolbar" id="main-toolbar" style="height: 50px;">
	<div class="col-md-4" style="padding: 0px;">
			<?php if(
				(
					!DataModels::getCurrentModel() ||
					DataModels::getCurrentModel()->canHaveRelated()
				)
			): ?>
				<?=UI::button_create(Tr::_('Create new DataModel'))->setOnclick('JetStudio.DataModel.create.openDialog()')?>
			<?php endif; ?>
	</div>
	<div class="col-md-8" style="padding: 0px">
		<?=Application::getView()->render('model_edit/toolbar');?>
	</div>
</div>

<div class="row" id="main-col">
	<div class="col-md-4" style="padding: 0px;">
		<?=Application::getView()->render('list');?>
	</div>
	<div class="col-md-8" style="padding: 10px">
		<?=Application::getView()->render('model_edit/edit');?>
	</div>
</div>





<?=Application::getView()->render('create_data_model/dialog');?>
<?=Application::getView()->render('create_property/dialog');?>
<?=Application::getView()->render('create_key/dialog');?>
<?=Application::getView()->render('create_relation/dialog');?>

<?php
$dialog_SQL_create = UI::dialog('dialog_SQL_create', Tr::_('SQL - create'), 800);

echo $dialog_SQL_create->start();
?>
	<textarea id="SQL_create_result" style="width: 770px;height: 400px;"></textarea>
	<?php
echo $dialog_SQL_create->end();


$dialog_SQL_update = UI::dialog('dialog_SQL_update', Tr::_('SQL - update'), 800);

echo $dialog_SQL_update->start();
?>
	<textarea id="SQL_update_result" style="width: 770px;height: 400px;"></textarea>
	<?php
echo $dialog_SQL_update->end();



$dialog_class_source = UI::dialog('dialog_class_source', Tr::_('Class source code'), 800);

echo $dialog_class_source->start();
?>
	<textarea id="class_source_result" style="width: 770px;height: 400px;"></textarea>
	<?php
echo $dialog_class_source->end();

echo $this->render('delete_key/dialog');

echo $this->render('delete_relation/dialog');
