<?php
namespace JetStudio;

use Jet\Tr;
use Jet\UI_messages;

$problematic_classes = DataModels::getProblematicClasses();
?>

<div style="padding: 20px;">
	<h1><?= Tr::_( 'Upsss .... ' ); ?></h1>
	<p><?= Tr::_( 'I am sorry, but there are some troubles ...' ) ?></p>

	<?php foreach( $problematic_classes as $class ): ?>
		<b><?= $class->getFullClassName() ?></b><br/>
		<?= $class->getScriptPath() ?>
		<?= UI_messages::createDanger( $class->getError() ) ?>
	<?php endforeach; ?>

</div>
