<?php
use JetApplicationModule\JetExample\Images\Gallery;

use JetUI\tree;

use Jet\Mvc_Controller_Router;
use Jet\Data_Tree;
use Jet\Data_Tree_Node;
use Jet\Tr;
use Jet\Form;
use Jet\Mvc;
use JetUI\UI;

/**
 * @var Mvc_Controller_Router $router
 * @var Data_Tree $galleries
 * @var Gallery $gallery
 * @var Form $upload_form
 * @var Form $edit_form
 */
$router = $this->router;
$galleries = $this->galleries;
$gallery = $this->gallery;
$upload_form = $this->upload_form;
$edit_form = $this->edit_form;


$tree = new tree();

$tree->setData( $galleries );
$tree->setSelectedId( $this->selected_id );

/** @noinspection PhpUnusedParameterInspection */
$tree->setNormalDisplayCallback( function( Data_Tree_Node $node ) use ( $router)  {
	?>
	<?php if($router->getActionAllowed('edit')): ?>
		<a href="<?=$router->getActionURI('edit', $node->getId());?>"><?=$node->getLabel();?></a>
	<?php else: ?>
		<a href="<?=$router->getActionURI('view', $node->getId());?>"><?=$node->getLabel();?></a>
	<?php endif; ?>
	<?php
} );

/** @noinspection PhpUnusedParameterInspection */
$tree->setSelectedDisplayCallback( function( Data_Tree_Node $node ) {
	?>
	<strong><?=$node->getLabel();?></strong>
	<?php
});

$tree->setOpenedDisplayCallback( function( Data_Tree_Node $node ) use ( $router)  {
	if($node->getIsRoot()):
		?>
		<a href="<?=Mvc::getCurrentPageURI();?>" style="font-style: italic;"><?=$node->getLabel();?></a>
		<?php
		return;
	endif;
	?>
	<?php if($router->getActionAllowed('edit')): ?>
		<a href="<?=$router->getActionURI('edit', $node->getId());?>" style="font-style: italic;"><?=$node->getLabel();?></a>
	<?php else: ?>
		<a href="<?=$router->getActionURI('view', $node->getId());?>" style="font-style: italic;"><?=$node->getLabel();?></a>
	<?php endif; ?>
<?php
});

?>


<div class="col-md-12 main-col" style="padding-top: 5px;">
<div class="row">
	<div class="col-md-2">
		<?php if(
			$router->getActionAllowed('add') &&
			(
				!$gallery ||
				!$gallery->getIsNew()
			)
		):
			$parent_id = $gallery ? $gallery->getIdObject(): Gallery::ROOT_ID;
			?>
		<div style="padding: 5px;">
			<?=UI::button_create(Tr::_('Create new gallery'))->setUrl($router->getActionURI('add', $parent_id))?>
		</div>
		<?php endif; ?>

		<?=$tree->render();?>

	</div>
	<div class="col-md-9">

		<?php if($gallery):
			$edit_form->setDefaultLabelWidth(2);
			$edit_form->setDefaultFieldWidth(5);
			?>

			<?=$edit_form->start()?>

				<fieldset>
					<?=$edit_form->field('title')?>

					<?php if(!$edit_form->getIsReadonly()):
						echo UI::button_save();
					endif; ?>
				</fieldset>
			<?=$edit_form->end()?>

			<?php if($upload_form):
				$upload_form->setDefaultLabelWidth(2);
				$upload_form->setDefaultFieldWidth(5);

			?>
			<div>
				<?=$upload_form->start()?>

				<?=$upload_form->field('file')?>
				<?=$upload_form->field('overwrite_if_exists')?>

				<?=UI::button_save(Tr::_('Upload'))?>
				<?=$upload_form->end()?>
			</div>
			<?php endif; ?>

			<?php if(
				$gallery &&
				$gallery->getIsSaved()
			): ?>

				<?php
				$images=$gallery->getImages();
				if( count($images) ): ?>
				<form action="?ID=<?=$gallery->getIdObject();?>&amp;delete_images" method="post">
					<div class="row">
						<?php foreach( $images as $image ): ?>
							<div class="col-md-2">
								<div class="thumbnail">
									<a href="<?=$image->getURI();?>">
										<img src="<?=$image->getThumbnail(150, 150)->getURI();?>" alt="Lights" style="width:100%">
										<div class="caption">
											<p>
												<input type="checkbox" name="images[]" value="<?=$image->getIdObject();?>" id="image_<?=$image->getIdObject();?>">
												<?=$image->getFileName();?>
											</p>
										</div>
									</a>
								</div>
							</div>
						<?php endforeach; ?>
					</div>

					<?php if($this->can_delete_image): ?>
						<?=UI::button_delete(Tr::_('Delete selected images'))->setType('submit')?>
					<?php endif; ?>
				</form>
				<?php endif; ?>
			<?php endif; ?>

		<?php endif; ?>
	</div>
</div>
</div>