<?php
namespace JetApplicationModule\JetExample\Images;

use Jet\Mvc_View;

/**
 * @var Mvc_View  $this
 */

?>
<?php require 'parts/js.phtml'; ?>

<div class="col-md-12 main-col" style="padding-top: 5px;">
	<div class="row">
		<div class="col-md-12">
			<div class="toolbar">
				<?php require 'parts/toolbar.phtml' ?>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-2">
			<?php  require 'parts/tree.phtml'; ?>
		</div>
		<div class="col-md-9">

			<div id="edit_form_area">
				<?php require 'parts/edit-form.phtml' ?>
			</div>

			<div class="well">
				<div id="upload_form_area">
					<?php require 'parts/upload-form.phtml' ?>
				</div>

				<div id="images_area">
					<?php  require 'parts/images.phtml'; ?>
				</div>

			</div>


		</div>
	</div>
</div>