<?php
const JET_DEVEL_MODE = true;

const JET_DEBUG_PROFILER_ENABLED = false;

const JET_LAYOUT_CSS_PACKAGER_ENABLED = true;
const JET_LAYOUT_JS_PACKAGER_ENABLED = true;

const JET_TRANSLATOR_AUTO_APPEND_UNKNOWN_PHRASE = true;

const JET_CACHE_LOAD = false;
const JET_CACHE_SAVE = false;

const JET_CACHE_REFLECTION_LOAD = JET_CACHE_LOAD;
const JET_CACHE_REFLECTION_SAVE = JET_CACHE_SAVE;

const JET_CACHE_DATAMODEL_DEFINITION_LOAD = JET_CACHE_LOAD;
const JET_CACHE_DATAMODEL_DEFINITION_SAVE = JET_CACHE_SAVE;

const JET_CACHE_CONFIG_DEFINITION_LOAD = JET_CACHE_LOAD;
const JET_CACHE_CONFIG_DEFINITION_SAVE = JET_CACHE_SAVE;

const JET_CACHE_AUTOLOADER_LOAD = JET_CACHE_LOAD;
const JET_CACHE_AUTOLOADER_SAVE = JET_CACHE_SAVE;

const JET_CACHE_MVC_SITE_LOAD = JET_CACHE_LOAD;
const JET_CACHE_MVC_SITE_SAVE = JET_CACHE_SAVE;

const JET_CACHE_MVC_PAGE_LOAD = JET_CACHE_LOAD;
const JET_CACHE_MVC_PAGE_SAVE = JET_CACHE_SAVE;


const JET_IO_CHMOD_MASK_DIR = 0777;
const JET_IO_CHMOD_MASK_FILE = 0666;

const JET_HIDE_HTTP_REQUEST = true;

const JET_CHARSET = 'UTF-8';

const JET_TIMEZONE = 'Europe/Prague';

const JET_TAB = "\t";
const JET_EOL = PHP_EOL;
