<?php
namespace JetStudio;

require_once 'parts/init_libs.php';

use Jet\Tr;
use Jet\UI_messages;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>PHP Jet Studio</title>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>
</head>


<body style="width: 100%;height: 100%">

	<jet_layout_main_position/>

</body>

</html>