<?php
namespace JetStudio;

require_once 'parts/init_libs.php';

use Jet\Http_Request;
use Jet\Locale;
use Jet\SysConf_URI;
use Jet\UI;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>PHP Jet Studio</title>

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<jet_layout_meta_tags/>
	<jet_layout_css/>
	<jet_layout_javascripts/>


</head>


<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="<?=SysConf_URI::getBase()?>">Jet Studio</a>

	<div class="collapse navbar-collapse" id="mainNavBar">
		<ul class="nav navbar-nav">
		</ul>

		<ul class="navbar-nav ml-auto">

			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<span><?=UI::flag( Locale::getCurrentLocale() )?></span>
					<span class="caret"></span>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
					<?php foreach( Application::getLocales() as $locale ): ?>
						<a class="dropdown-item" href="<?=Http_Request::currentURI(['std_locale' =>$locale->toString()])?>">
							<?=UI::flag( $locale )?>
							<?=$locale->getLanguageName( $locale )?>
						</a>
					<?php endforeach; ?>
				</div>
			</li>


		</ul>

	</div>
</nav>


<div class="container" style="margin-top: 50px;">
	<div class="row align-items-center">
		<div class="col-12 justify-content-center">
			<jet_layout_main_position/>
		</div>
	</div>
</div>


</body>

</html>