<?php
namespace JetStudio;

use Jet\Http_Request;

?>

<script type="text/javascript">

	const Modules = {
		search: {
			reset: function () {
				$('#module_search').val('');

				$('.module_list_item').show();
			},
			search: function () {

				let value = $('#module_search').val();

				if (!value) {
					Modules.search.reset();
					return;
				}

				value = value.toLowerCase();

				$('.module_list_item').each(function (index, row) {
					row = $(row);

					const name = row.data('name').toLowerCase();
					const label = row.data('label').toLowerCase();

					if (
						name.includes(value) ||
						label.includes(value)
					) {
						row.show();
					} else {
						row.hide();
					}

				});

			}
		},
		editModule: {
			addPage: {
				openDialog: function () {
					Modules.editModule.addPage.toggleFields($('#add_page_form__base_id').val());
					$('#add_page_dialog').modal('show');
				},

				generateId: function (name) {
					const base_id = $('#add_page_form__base_id').val();

					$.ajax({
						url: '<?=Modules::getActionUrl( 'page/generate_id' )?>&name=' + encodeURIComponent(name) + '&base_id=' + encodeURIComponent(base_id),
						dataType: 'json',
						success: function (result) {
							$('#add_page_form__page_id').val(result.id);
						}
					});
				},

				toggleFields: function (base_id) {
					if (base_id) {
						$('#add_page_form__page_id').attr('readonly', false);
						$('#add_page_form__page_name').attr('readonly', false);
					} else {
						$('#add_page_form__page_id').attr('readonly', true);
						$('#add_page_form__page_name').attr('readonly', true);
					}
				},

				send: function () {
					JetAjaxForm.submit(
						'add_page_form',
						{
							onSuccess: function (form, response_data) {
								location = '<?=Http_Request::currentURI()?>&page=' + response_data.id;
							}
						}
					);

				}
			},
			editPage: {
				addContent: function (form_id) {
					JetAjaxForm.submit(
						form_id,
						{
							onSuccess: function (form, response_data) {
							}
						}
					);
				},
				removeContent: function (base_id, page_id, index) {
					const form = $('#delete_content_form')[0]
					form['base'].value = base_id;
					form['page'].value = page_id;
					form['index'].value = index;

					$('#delete_content').modal('show');
				}

			},

			addMenuItem: {
				openDialog: function () {
					$('#add_menu_item_dialog').modal('show');
				},

				send: function () {
					JetAjaxForm.submit(
						'create_menu_item_form',
						{
							onSuccess: function (form, response_data) {
								location = '<?=Http_Request::currentURI()?>&menu_item=' + response_data.id;
							}
						}
					);
				},
				generateId: function (name) {
					$.ajax({
						url: '<?=Modules::getActionUrl( 'menu_item/generate_id' )?>&name=' + encodeURIComponent(name),
						dataType: 'json',
						success: function (result) {
							$('#create_menu_item_form__id').val(result.id);
						}
					});
				}
			}


		},


		Wizard: {
			select: function (wizard) {
				$('#module_wizard_select_dialog').modal('hide');

				$('#module_wizard_setup_dialog').modal('show');

				$('#module_wizard_setup_form_area')[0].src = '<?=Modules::getActionUrl( 'module_wizard/setup' )?>&wizard=' + encodeURIComponent(wizard);

			}
		},
		deleteModule: {
			openDialog: function () {
				$('#delete_module').modal('show');
			}
		}
	}


	const Pages = {
		createPage: {
			openDialog: function () {
				$('#dialog_create_new_page').modal('show');
			},
			createSend: function () {
				JetAjaxForm.submit(
					'<?=Pages_Page::getCreateForm()->getId()?>',
					{
						onSuccess: function (form, response_data) {
							location = '<?=Http_Request::currentURI()?>&page=' + encodeURIComponent(response_data['new_page_id'])
						}
					}
				);
			},
			generateId: function (name) {
				$.ajax({
					url: '<?=Modules::getActionUrl( 'page/generate_id' )?>&name=' + encodeURIComponent(name),
					dataType: 'json',
					success: function (result) {
						$('#page_create_form__id').val(result.id);
					}
				});
			}
		},
		editPage: {
			content: {
				moduleSearch: {
					reset: function() {
						$('#create_page_content_module_search').val('');

						$('.create_page_content_module_row').show();
					},
					search: function() {
						
						let value = $('#create_page_content_module_search').val();

						if(!value) {
							Pages.editPage.content.moduleSearch.reset();
							return;
						}

						value = value.toLowerCase();

						$('.create_page_content_module_row').each( function (index, row) {
							row = $(row);

							const name = row.data('name').toLowerCase();
							const label = row.data('label').toLowerCase();

							if(
								name.includes( value ) ||
								label.includes( value )
							) {
								row.show();
							} else {
								row.hide();
							}

						} );

					}
				},
				
				moduleSelected: function (module_name, row) {
					let controllers = $('#create_page_content_form__controller_name');
					let controller_action = $('#create_page_content_form__controller_action');
					let module_name_input = $("#create_page_content_form__module_name");
					let controller_area = $('#create_page_content_module_controller')[0];

					$('.create_page_content_module_row').removeClass('table-info');
					$(row).addClass('table-info');
					

					module_name_input.val(module_name);
					
					controllers.empty();
					controller_action.empty();

					controller_area.style.visibility='hidden';

					controllers.removeClass('is-invalid');
					controller_action.removeClass('is-invalid');

					$.ajax({
						url: '<?=Modules::getActionUrl( 'page/get_module_controllers' )?>&module=' + encodeURIComponent(module_name),
						dataType: 'json',
						success: function (result) {
							$.each(result['controllers'], function (name) {
								controllers.append($('<option></option>').attr('value', name).text(name));
							});

							controllers.val(result['default_controller']);

							$.each(result['actions'], function (name) {
								controller_action.append($('<option></option>').attr('value', name).text(name));
							});

							controller_area.style.visibility='visible';
							
						}
					});
				},
				controllerSelected: function (controller) {
					let module_name = $("#create_page_content_form__module_name");
					let controller_action = $('#create_page_content_form__controller_action');

					controller_action.empty();

					$.ajax({
						url: '<?=Modules::getActionUrl( 'page/get_module_controller_actions' )?>&module=' + encodeURIComponent(module_name.val()) + '&controller=' + encodeURIComponent(controller),
						dataType: 'json',
						success: function (result) {

							$.each(result.actions, function (name) {
								controller_action.append($('<option></option>').attr('value', name).text(name));
							});
						}
					});
				},

				addContent: function () {
					$('#dialog_create_new_page_content').modal('show');
				},

				createSend: function () {
					JetAjaxForm.submit(
						'create_page_content_form',
						{
							onSuccess: function (form, response_data) {
							}
						}
					);
				},

				deleteContent: function (index) {
					$('#delete_content_form__index').val(index);
					$('#delete_content').modal('show');
				},

				deleteContentSend: function () {
					$('#delete_content_form').submit();
				}
			}
		},

		deletePage: {
			openDialog: function () {
				$('#delete_page').modal('show');
			}
		}

	}

</script>
