<?php
namespace JetStudio;

use Jet\Http_Request;

?>

<script type="text/javascript">

	const Modules = {
		editModule: {
			addPage: {
				openDialog: function () {
					Modules.editModule.addPage.toggleFields($('#add_page_form__base_id').val());
					$('#add_page_dialog').modal('show');
				},

				generateId: function (name) {
					const base_id = $('#add_page_form__base_id').val();

					$.ajax({
						url: '<?=Modules::getActionUrl( 'page/generate_id' )?>&name=' + encodeURIComponent(name) + '&base_id=' + encodeURIComponent(base_id),
						dataType: 'json',
						success: function (result) {
							$('#add_page_form__page_id').val(result.id);
						}
					});
				},

				toggleFields: function (base_id) {
					if (base_id) {
						$('#add_page_form__page_id').attr('readonly', false);
						$('#add_page_form__page_name').attr('readonly', false);
					} else {
						$('#add_page_form__page_id').attr('readonly', true);
						$('#add_page_form__page_name').attr('readonly', true);
					}
				},

				send: function () {
					JetAjaxForm.submit(
						'add_page_form',
						{
							onSuccess: function (form, response_data) {
								location = '<?=Http_Request::currentURI()?>&page=' + response_data.id;
							}
						}
					);

				}
			},
			editPage: {
				addContent: function (form_id) {
					JetAjaxForm.submit(
						form_id,
						{
							onSuccess: function (form, response_data) {
							}
						}
					);
				},
				removeContent: function (base_id, page_id, index) {
					const form = $('#delete_content_form')[0]
					form['base'].value = base_id;
					form['page'].value = page_id;
					form['index'].value = index;

					$('#delete_content').modal('show');
				}

			},

			addMenuItem: {
				openDialog: function () {
					$('#add_menu_item_dialog').modal('show');
				},

				send: function () {
					JetAjaxForm.submit(
						'create_menu_item_form',
						{
							onSuccess: function (form, response_data) {
								location = '<?=Http_Request::currentURI()?>&menu_item=' + response_data.id;
							}
						}
					);
				},
				generateId: function (name) {
					$.ajax({
						url: '<?=Modules::getActionUrl( 'menu_item/generate_id' )?>&name=' + encodeURIComponent(name),
						dataType: 'json',
						success: function (result) {
							$('#create_menu_item_form__id').val(result.id);
						}
					});
				}
			}


		},


		Wizard: {
			select: function (wizard) {
				$('#module_wizard_select_dialog').modal('hide');

				$('#module_wizard_setup_dialog').modal('show');

				$('#module_wizard_setup_form_area')[0].src = '<?=Modules::getActionUrl( 'module_wizard/setup' )?>&wizard=' + encodeURIComponent(wizard);

			}
		},
		deleteModule: {
			openDialog: function () {
				$('#delete_module').modal('show');
			}
		}
	}


	const Pages = {
		createPage: {
			openDialog: function () {
				$('#dialog_create_new_page').modal('show');
			},
			createSend: function () {
				JetAjaxForm.submit(
					'<?=Pages_Page::getCreateForm()->getId()?>',
					{
						onSuccess: function (form, response_data) {
							location = '<?=Http_Request::currentURI()?>&page=' + encodeURIComponent(response_data['new_page_id'])
						}
					}
				);
			},
			generateId: function (name) {
				$.ajax({
					url: '<?=Modules::getActionUrl( 'page/generate_id' )?>&name=' + encodeURIComponent(name),
					dataType: 'json',
					success: function (result) {
						$('#page_create_form__id').val(result.id);
					}
				});
			}
		},
		editPage: {
			content: {
				moduleSelected: function (module_name, ids) {
					let controllers = $('#' + ids['controller_name']);
					let controller_action = $('#' + ids['controller_action']);

					controllers.empty();
					controller_action.empty();

					$('#create_page_content_form__controller_name').removeClass('is-invalid');
					$('#create_page_content_form__controller_action').removeClass('is-invalid');

					$.ajax({
						url: '<?=Modules::getActionUrl( 'page/get_module_controllers' )?>&module=' + encodeURIComponent(module_name),
						dataType: 'json',
						success: function (result) {
							$.each(result['controllers'], function (name) {
								controllers.append($('<option></option>').attr('value', name).text(name));
							});

							controllers.val(result['default_controller']);

							$.each(result['actions'], function (name) {
								controller_action.append($('<option></option>').attr('value', name).text(name));
							});
						}
					});
				},
				controllerSelected: function (controller, ids) {
					let module_name = $('#' + ids['module_mame']);
					let controller_action = $('#' + ids['controller_action']);

					controller_action.empty();

					$.ajax({
						url: '<?=Modules::getActionUrl( 'page/get_module_controller_actions' )?>&module=' + encodeURIComponent(module_name.val()) + '&controller=' + encodeURIComponent(controller),
						dataType: 'json',
						success: function (result) {

							$.each(result.actions, function (name) {
								controller_action.append($('<option></option>').attr('value', name).text(name));
							});
						}
					});

					console.debug(module_name, ids);
				},

				addContent: function () {
					$('#dialog_create_new_page_content').modal('show');
				},

				createSend: function () {
					JetAjaxForm.submit(
						'create_page_content_form',
						{
							onSuccess: function (form, response_data) {
							}
						}
					);
				},

				deleteContent: function (index) {
					$('#delete_content_form__index').val(index);
					$('#delete_content').modal('show');
				},

				deleteContentSend: function () {
					$('#delete_content_form').submit();
				}
			}
		},

		deletePage: {
			openDialog: function () {
				$('#delete_page').modal('show');
			}
		}

	}

</script>
