<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

?>
<?=Application::getView()->render('js');?>

<?php if(Modules::getCurrentModule()): ?>
<div class="row">
	<div class="col-md-3" style="padding: 0px;">
		<div class="toolbar">
			<?=UI::button_create(Tr::_('Create a new module'))->setOnclick('JetStudio.Modules.createModule.openDialog()')?>
			<?=UI::button(Tr::_('Wizard'))->setOnclick("$('#module_wizard_select_dialog').modal('show');")->setIcon('magic')?>
		</div>
		<div class="container-fluid">
			<?=Application::getView()->render('models_list');?>
		</div>
	</div>
	<div class="col-md-9" style="padding: 0px">
		<?=Application::getView()->render('module_edit/edit');?>
	</div>
</div>
<?php else: ?>
<div class="row">
	<div class="col-md-12">
		<?=Application::getView()->render('module_edit/dashboard');?>

	</div>
</div>
<?php endif; ?>


<?=Application::getView()->render('create_module/dialog');?>
<?=Application::getView()->render('delete_module/dialog');?>
