<?php
namespace JetStudio;

use Jet\Http_Request;
use Jet\Tr;
use Jet\UI;
use Jet\UI_badge;
use Jet\UI_icon;


$showIcons = function( Modules_Manifest $module ) {
	if( $module->isMandatory() ):
		echo UI::badge(UI_badge::INFO, UI::icon( 'exclamation-triangle' )->setTitle( Tr::_( 'Is mandatory' ) )->setSize(UI_icon::SIZE_SMALL) );
	endif;
	
	if( $module->isInstalled() ):
		echo UI::badge(UI_badge::SUCCESS,  UI::icon( 'check' )->setTitle( Tr::_( 'Is installed' ) )->setSize(UI_icon::SIZE_SMALL)  );
	else:
		echo UI::badge(UI_badge::DANGER,  UI::icon( 'times' )->setTitle( Tr::_( 'Is not installed' ) )->setSize(UI_icon::SIZE_SMALL)  );
	endif;
	
	echo '&nbsp;';
	
	if( $module->isActivated() ):
		echo UI::badge(UI_badge::SUCCESS,  UI::icon( 'check' )->setTitle( Tr::_( 'Is activated' ) )->setSize(UI_icon::SIZE_SMALL)  );
	else:
		echo UI::badge(UI_badge::DANGER,  UI::icon( 'times' )->setTitle( Tr::_( 'Is not activated' ) )->setSize(UI_icon::SIZE_SMALL)  );
	endif;
	
};
?>
<?=Application_UI::search(
		id: 'module_search',
		placeholder: Tr::_('Search for module ...'),
		search_action: 'Modules.search.search()',
		search_reset_action: 'Modules.search.reset()') ?>

<table class="table table-striped">
	<?php
	$module = Modules::getCurrentModule();
	if( $module ):
		?>
		<tr>
			<td style="width: 100px;">
				<?php $showIcons( $module ); ?>
			</td>
			<td>

				<?php if( !Modules::getCurrentMenuItem() && !Modules::getCurrentPage() ):
					echo UI::badge(UI_badge::INFO, $module->getName())->addCustomCssStyle('font-size: 20px;');
				else: ?>
					<a href="<?= Http_Request::currentURI( [], [
						'menu_item',
						'page',
						'action'
					] ) ?>" style="font-weight: bolder;font-size: 20px;"><?= $module->getName() ?></a>
				<?php endif; ?>
				<br/>
				<span style="font-size: 12px;"><?= $module->getLabel() ?></span>
				<?php require 'menu_item/list.phtml' ?>
				<?php require 'page/list.phtml' ?>
				<br>
			</td>
		</tr>
	<?php endif; ?>


	<?php foreach( Modules::getModules() as $module ):
		if( $module->getName() == Modules::getCurrentModuleName() ) {
			continue;
		}
		?>
		<tr class="module_list_item"
		    data-name="<?=$module->getName()?>"
		    data-label="<?=$module->getLabel()?>"
			>
			<td style="width: 100px;">
				<?php $showIcons( $module ); ?>
			</td>
			<td>
				<a href="<?= Http_Request::currentURI( ['module' => $module->getName()], [
					'menu_item',
					'page',
					'action'
				] ) ?>"><?= $module->getName() ?></a><br/>
				<span style="font-size: 12px;"><?= $module->getLabel() ?></span>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
