<?php
namespace JetStudio;

use Jet\UI;
use Jet\Tr;

if(!DataModels::getCurrentModel()) {
    return;
}

$dialog = UI::dialog('delete_data_model', Tr::_('Delete this DataModel'), 600);

echo $dialog->start();
	?>
    <?=Tr::_('Do You really want to delete data model <strong>%model_name%</strong> (class %class_name%) ?', [
	'model_name' => DataModels::getCurrentModel()->getModelName(),
	'class_name' => DataModels::getCurrentModel()->getClassName()
    ]);?>
	<?php
echo $dialog->footer();
	echo UI::button_delete()->setUrl( DataModels::getActionUrl('delete') );
echo $dialog->end();

