<?php
use JetExampleApp\Installer;
use Jet\Form;
use Jet\Mvc_View;
use Jet\Tr;

use JetExampleApp\Application_Config_Emails;

/**
 * @var Mvc_View $this
 * @var Application_Config_Emails $config
 * @var Form $form
 */

$config = $this->getRaw('config');
$form = $this->getRaw('form');
$form->setDefaultLabelWidth(1);
?>
<h2><?=Tr::_('Set the mail sender')?></h2>
<?=$form->start()?>
<?php foreach(Installer::getSelectedLocales() as $locale): ?>

	<legend><?=$locale->getName();?></legend>

	<?=$form->field('/'.$locale.'/email')?>
	<?=$form->field('/'.$locale.'/name')?>

<?php endforeach; ?>

<?=Installer::buttonNext()?>

<?=$form->end()?>
