<?php

use Jet\UI_dataGrid;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var UI_dataGrid $grid
 */
$grid = $this->getRaw( 'grid' );

?>
<table class="table table-striped">
	<thead>
	<?= $grid->getCustomHeader() ?>
	<?= $grid->renderHeader(); ?>
	</thead>
	<tbody>
	<?= $grid->renderBody() ?>
	</tbody>
	<tfoot>
	<?= $grid->getCustomFooter() ?>
	<?= $grid->renderPaginator() ?>
	</tfoot>
</table>
