<?php

use Jet\UI_icon;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var UI_icon $i
 */
$i = $this->getRaw( 'element' );

$res = '';

$style = '';

if( $i->getSize() ) {
	$i->addCustomCssStyle( 'font-size:' . $i->getSize() . 'px;' );
}
if( $i->getWidth() ) {
	$i->addCustomCssStyle( 'width:' . $i->getWidth() . 'px;' );
}
if( $i->getColor() ) {
	$i->addCustomCssStyle( 'color:' . $i->getColor() . ';' );
}

$i->setBaseCssClass('fa fa-'. $i->getIcon() );
$i->setCustomTagAttribute('title', $i->getTitle());

$tag = $i->getTag();
?><<?=$tag.$i->renderTagAttributes()?>></<?= $tag ?>>