<?php
namespace JetApplication;

use Jet\Mvc_View;

use Jet\UI_messages;
use Jet\UI;
use Jet\Tr;

/**
 * @var Mvc_View            $this
 * @var CompatibilityTester $tester
 */
$tester = $this->getRaw( 'tester' );

?>

<table class="table table-striped">
	<tbody>
	<?php foreach( $tester->getTestResults() as $test_result ):
		if( $test_result->getPassed() ) {
			$icon = UI::icon( 'check' );
			$css_class = '';
		} else {
			if( $test_result->getIsWarning() ) {
				$icon = UI::icon( 'meh-o' );
				$css_class = 'warning';
			} else {
				$icon = UI::icon( 'frown-o' );
				$css_class = 'danger';
			}
		}
		?>
		<tr class="<?=$css_class;?>">
			<td><?=$icon?></td>
			<td><b><?=$test_result->getTitle();?></b><br/><?=$test_result->getDescription();?></td>
			<td><?=$test_result->getResultMessage();?></td>
		</tr>
		<?php
	endforeach; ?>
	</tbody>
</table>

<?php if( $tester->isCompatible() ):
	if( !$tester->hasWarnings() ):
		echo UI_messages::createSuccess( Tr::_( 'The system is fully compatible!' ) );
	else:
		echo UI_messages::createWarning( Tr::_( 'The system is compatible. Please take care about warnings!' ) );
	endif;
	?>
	<form method="post">
		<input type="hidden" name="go" value="1">
		<?=Installer::buttonNext();?>
	</form>
	<?php
else:
	echo UI_messages::createDanger( Tr::_( 'Sorry, but the system is tom compatible!' ) );
endif; ?>
