<?php

namespace JetStudio;

use Jet\UI;
use Jet\Tr;
use Jet\UI_dialog;

$current_model = DataModels::getCurrentModel();
if( !$current_model ) {
	return;
}

$dialog = UI::dialog( 'dialog_create_new_key', Tr::_( 'Create a new Key' ), UI_dialog::SIZE_LARGE );


echo $dialog->start();
?>
	<div id="key_add_form_area">
		<?php require 'form.phtml'; ?>
	</div>
	<?php

echo $dialog->footer();
echo UI::button_save( Tr::_( 'Create' ) )->setOnClick( 'DataModel.key.create.createSend()' );
echo $dialog->end();

