<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<jet_layout_part name="header"/>
</head>
<body class="%DOJO_THEME%">
	<jet_layout_body_prefix/>

	<jet_layout_part name="dialogs"/>

	<jet_module:JetExample\BreadcrumbNavigation view="default"/>

	<div style="position: absolute;top:18px; right: 10px;">
		<?=Jet\Tr::_("Current user: %USERNAME%", array("USERNAME"=>Jet\Auth::getCurrentUser()->getLogin()));?>
		[<a href="?logout"><?=Jet\Tr::_("LOGOUT");?></a>]
	</div>

	<jet_layout_main_position/>
	<jet_layout_body_suffix/>
</body>
</html>