<?php
namespace JetStudio;

use Jet\Form;
use Jet\Mvc_View;

/**
 * @var Mvc_View $this
 * @var Pages_Page $page
 */

$page = $this->getRaw('page');

$form = $page->getEditForm_content();

$form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 2
]);
$form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 6
]);

?>
<?=$form->start()?>
	<div style="min-height: 600px;margin-bottom: 40px;">
		<div style="padding: 10px;">
			<?=$form->field('layout_script_name')?>
		</div>
		<div id="content_list_area">
			<?php require 'content/list.phtml'; ?>
		</div>
	</div>
<?=$form->end()?>
