<?php
namespace JetApplicationModule\Web\Visitor\SignUp;

use Jet\MVC_View;
use Jet\Tr;
use Jet\UI;
use Jet\UI_icon;
use JetApplication\Application_Web_Pages;

/**
 * @var MVC_View $this
 */

$secret_area_page = Application_Web_Pages::secretArea();
?>
<h1><?=UI::icon('user-plus')->setSize(UI_icon::SIZE_EXTRA_LARGE)?> <?=Tr::_('Thank you for your sign up')?></h1>

<p>Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Maecenas sollicitudin. Integer in sapien. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Praesent in mauris eu tortor porttitor accumsan. Integer imperdiet lectus quis justo. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Praesent dapibus. Mauris dictum facilisis augue. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>

<a href="<?=$secret_area_page->getURL()?>"><?=Tr::_('Continue')?></a>