<?php
namespace JetApplicationModule\Jet\DefaultAdminUI;
use Jet;
?>
<ul>
	<li><a href="<?=Jet\Mvc_Pages::getURI("admin_roles"); ?>"><?=Jet\Tr::_("Manage roles");?></a></li>
	<li><a href="<?=Jet\Mvc_Pages::getURI("admin_users"); ?>"><?=Jet\Tr::_("Manage users");?></a></li>
</ul>

<jetml_layout_container id="_jet_main_border_" gutters="false" style="width:100%;height:600px;">

	<jetml_layout_tabs region="center" tabPosition="top" id="_jet_modules_tabs_">
	</jetml_layout_tabs>

	<jetml_layout_toolbar region="bottom">
		<jetml_form_button title="Pages" icon="module/Jet\AdminPages/module" onClick="Jet.modules.CURRENT_MODULE.openModule('Jet\\AdminPages');" />
		<jetml_form_button title="Articles" icon="module/Jet\Articles/module" onClick="Jet.modules.CURRENT_MODULE.openModule('Jet\\Articles');" />
		<jetml_form_button title="Images" icon="module/Jet\Images/module" onClick="Jet.modules.CURRENT_MODULE.openModule('Jet\\Images');" />
		<jetml_form_button title="Roles" icon="module/Jet\AdminRoles/module" onClick="Jet.modules.CURRENT_MODULE.openModule('Jet\\AdminRoles');" />
		<jetml_form_button title="Users" icon="module/Jet\AdminUsers/module" onClick="Jet.modules.CURRENT_MODULE.openModule('Jet\\AdminUsers');" />
		<jetml_form_button title="Form test" icon="module/Jet\TestModule/module" onClick="Jet.modules.CURRENT_MODULE.openModule('Jet\\TestModule');" />

		<jetml_form_button title="test Jet.alert" onClick="Jet.alert('Alert text!', 'Alert title', function() {alert('onOk');});" />
		<jetml_form_button title="test Jet.confirm" onClick="Jet.confirm('Confirm text!', 'Confirm title', function() {alert('onYes');}, function() {alert('onNo');});" />
	</jetml_layout_toolbar>
</jetml_layout_container>
