<?php
/**
 * @var Jet\Form $form
 */
$form = $this->form;
?>
<jet_form name="<?=$form->getName();?>">
	<jet_form_common_error_message class="formError"/>
	<table>
		<tr>
			<td valign="top"><jet_form_field_label name="backend_type"/></td>
			<td><jet_form_field_error_msg name="backend_type" class="error"/><jet_form_field name="backend_type"/></td>
		</tr>
		<tr>
			<td valign="top"><jet_form_field_label name="auto_append_unknown_phrase"/></td>
			<td><jet_form_field_error_msg name="auto_append_unknown_phrase" class="error"/><jet_form_field name="auto_append_unknown_phrase"/></td>
		</tr>
	</table>
	<input type="submit" value="<?=Jet\Tr::_('Next', array(), Jet\Translator::COMMON_NAMESPACE);?>"/>
</jet_form>
