<?php
namespace JetApplicationModule\JetExample\Images;

use Jet\UI;
use Jet\Form;
use Jet\Mvc_View;
use Jet\Mvc_Site;

/**
 * @var Mvc_View                     $this
 * @var Form                         $edit_form
 */

$edit_form = $this->getRaw( 'edit_form' );

$edit_form->setDefaultLabelWidth( [ Form::LJ_SIZE_MEDIUM => 1 ] );
$edit_form->setDefaultFieldWidth( [ Form::LJ_SIZE_MEDIUM => 5 ] );
?>


	<?=$edit_form->start()?>
<?php foreach( Mvc_Site::getAllLocalesList( false ) as $locale ):
	$field = $edit_form->field( '/localized/'.$locale.'/title' );
	$field->setLabel( UI::flag($locale).'&nbsp;'.$field->getLabel() );

	echo $field;
endforeach;?>


	<div class="form-group row">
		<div class="col-md-1"></div>
		<div class="col-md-5">
			<?php if( !$edit_form->getIsReadonly() ):
				echo UI::button_save()->setClass('default');
			endif; ?>
		</div>
	</div>
	<?=$edit_form->end()?>
