<?php
namespace JetApplicationModule\JetExample\Images;

use Jet\UI_tree;

use Jet\Data_Tree;
use Jet\Data_Tree_Node;
use Jet\Mvc;
use Jet\Mvc_View;

/**
 * @var Mvc_View                     $this
 * @var Data_Tree                    $galleries
 * @var Gallery                      $gallery
 * @var Controller_Admin_Main_Router $router
 */
$galleries = $this->getRaw( 'galleries' );
$gallery = $this->getRaw( 'gallery' );
$router = $this->getController()->getControllerRouter();

$tree = new UI_tree();

$tree->setData( $galleries );
$tree->setSelectedId( $this->getRaw( 'selected_id' ) );

$parent_id = $gallery ? $gallery->getIdObject() : '';

/** @noinspection PhpUnusedParameterInspection */
$tree->setNormalDisplayCallback(
	function( Data_Tree_Node $node ) use ( $router ) {
		?>
		<a href="<?=$router->getEditOrViewURI( $node->getId() );?>"><?=$node->getLabel();?></a>
		<?php
	}
);

/** @noinspection PhpUnusedParameterInspection */
$tree->setSelectedDisplayCallback(
	function( Data_Tree_Node $node ) {
		?>
		<strong><?=$node->getLabel();?></strong>
		<?php
	}
);

$tree->setOpenedDisplayCallback(
	function( Data_Tree_Node $node ) use ( $router ) {
		if( $node->getIsRoot() ):
			?>
			<a href="<?=Mvc::getCurrentPage()->getURI();?>" style="font-style: italic;"><?=$node->getLabel();?></a>
			<?php
			return;
		endif;
		?>
		<a href="<?=$router->getEditOrViewURI( $node->getId() );?>"
		   style="font-style: italic;"><?=$node->getLabel();?></a>
		<?php
	}
);

?>
<?=$tree->render();?>
