<?php

namespace JetStudioModule\DataModel;

$form = DataModel_Definition_Model_Main::getCreateForm();

$form->field( 'namespace' )->input()->addJsAction( 'onchange', 'DataModel.create.generateScriptPath(this.form)' );
$form->field( 'class_name' )->input()->addJsAction( 'onkeyup', 'DataModel.create.generateScriptPath(this.form);DataModel.create.generateModelName(this.form);' );

echo $form->start();
echo $form->getCommonMessage();
?>
<div class="form-fields" style="grid-template-columns: 0.5fr 2fr">
<?php
echo $form->field( 'type' );
echo $form->field( 'namespace' );
echo $form->field( 'class_name' );
echo $form->field( 'model_name' );
echo $form->field( 'script_path' );

echo $form->field( 'id_controller_class' );
echo $form->field( 'id_property_name' );
?>
</div>
<?php
echo $form->end();

