<?php
namespace JetStudio\ModuleWizard\BasicAdminDataHandler;

use Jet\Form;
use Jet\Http_Request;
use Jet\Mvc_View;
use Jet\Tr;
use Jet\UI;

/**
 * @var Mvc_View $this
 * @var Wizard $wizard
 */
$wizard = $this->getRaw('wizard');

$select_data_form = $wizard->getSelectDataModelForm();

$setup_form = $wizard->getSetupForm();

$select_data_form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 3
]);
$select_data_form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 10
]);


$setup_form->setDefaultLabelWidth([
	Form::LJ_SIZE_MEDIUM => 4
]);
$setup_form->setDefaultFieldWidth([
	Form::LJ_SIZE_MEDIUM => 8
]);


$select_data_form->field('data_model')->input()->addJsAction('onchange', 'this.form.submit()');

?>
<legend><?=Tr::_('DataModel')?></legend>
<?=$select_data_form->start()?>
<?=$select_data_form->field('data_model')?>
<?=$select_data_form->end()?>


<?php if($wizard->getDataModelClassname()):?>
	<?=$setup_form->start()?>
	<legend><?=Tr::_('Main module parameters')?></legend>

	<?=$setup_form->field('NAME')?>

	<?=$setup_form->field('LABEL')?>
	<?=$setup_form->field('DESCRIPTION')?>
	<?=$setup_form->field('AUTHOR')?>
	<?=$setup_form->field('LICENSE')?>
	<?=$setup_form->field('COPYRIGHT')?>




















	<legend><?=Tr::_('DataModel parameters')?></legend>
	<?=$setup_form->field('DATA_MODEL_CLASS_NAME')?>
	<?=$setup_form->field('DATA_MODEL_CLASS_ALIAS')?>

	<?=$setup_form->field('ITEM_VAR_NAME')?>

	<?=$setup_form->field('ID_PROPERTY')?>
	<?=$setup_form->field('ITEM_ID_GETTER')?>

	<?=$setup_form->field('NAME_PROPERTY')?>
	<?=$setup_form->field('ITEM_NAME_GETTER')?>

	<legend><?=Tr::_('Menu item')?></legend>
	<?=$setup_form->field('TARGET_MENU')?>
	<?=$setup_form->field('MENU_ITEM_ID')?>

	<legend><?=Tr::_('Page')?></legend>
	<?=$setup_form->field('PAGE_SITE_ID')?>
	<?=$setup_form->field('PAGE_ID')?>
	<?=$setup_form->field('PAGE_TITLE')?>
	<?=$setup_form->field('PAGE_ICON')?>
	<?=$setup_form->field('PAGE_PATH_FRAGMENT')?>

	<legend><?=Tr::_('Texts')?></legend>
	<?=$setup_form->field('TXT_MSG_CREATED')?>
	<?=$setup_form->field('TXT_MSG_UPDATED')?>
	<?=$setup_form->field('TXT_MSG_DELETED')?>
	<?=$setup_form->field('TXT_BN_DETAIL')?>
	<?=$setup_form->field('TXT_BN_EDIT')?>
	<?=$setup_form->field('TXT_BN_DELETE')?>
	<?=$setup_form->field('TXT_LISTING_TITLE_ID')?>
	<?=$setup_form->field('TXT_LISTING_TITLE_NAME')?>
	<?=$setup_form->field('TXT_DELETE_CONFIRM_QUESTION')?>
	<?=$setup_form->field('TXT_BTN_NEW')?>

	<legend><?=Tr::_('Logger')?></legend>
	<?=$setup_form->field('LOG_EVENT_CREATED')?>
	<?=$setup_form->field('LOG_EVENT_CREATED')?>
	<?=$setup_form->field('LOG_EVENT_DELETED')?>

	<legend><?=Tr::_('ACL')?></legend>
	<?=$setup_form->field('ACL_ENTITY_NAME')?>
	<?=$setup_form->field('ACL_ENTITY_CONST_NAME')?>

	<div align="right">
		<?=UI::button_save(Tr::_('Create'))->setClass('primary')->setIcon('magic')?>
	</div>
	<?=$setup_form->end()?>
<?php endif; ?>
<br/><br/>

