<?php
namespace JetStudioModule\Validators;
use Jet\Tr;
use Jet\UI;
use Jet\UI_button;
use JetStudio\JetStudio;

?>
&nbsp;&nbsp;&nbsp;

<?=UI::button(Tr::_('ORM definition'))->setUrl(
	JetStudio::getModule_DataModel()?->getPropertyEditURL( Main::getCurrentClassName(), Main::getCurrentPropertyName() )??''
)->setClass( UI_button::CLASS_SECONDARY )?>

<?=UI::button(Tr::_('Form field definition'))->setUrl(
	JetStudio::getModule_Forms()?->getPropertyEditURL( Main::getCurrentClassName(), Main::getCurrentPropertyName() )??''
)->setClass( UI_button::CLASS_INFO )?>

<?=UI::button(Tr::_('InputCathcer definition'))->setUrl(
	JetStudio::getModule_InputCatchers()?->getPropertyEditURL( Main::getCurrentClassName(), Main::getCurrentPropertyName() )??''
)->setClass( UI_button::CLASS_SUCCESS )?>
