<?php
namespace Jet;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-05 at 20:02:27.
 */
class Form_Parser_TagDataTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var Form_Parser_TagData
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		//$this->object = new Form_Parser_TagData();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	/**
	 * @covers Jet\Form_Parser_TagData::getTag
	 * @todo   Implement testGetTag().
	 */
	public function testGetTag() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Form_Parser_TagData::getName
	 * @todo   Implement testGetName().
	 */
	public function testGetName() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Form_Parser_TagData::getOriginalString
	 * @todo   Implement testGetOriginalString().
	 */
	public function testGetOriginalString() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Form_Parser_TagData::getProperties
	 * @todo   Implement testGetProperties().
	 */
	public function testGetProperties() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Form_Parser_TagData::getProperty
	 * @todo   Implement testGetProperty().
	 */
	public function testGetProperty() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Form_Parser_TagData::getPropertyIsSet
	 * @todo   Implement testGetPropertyIsSet().
	 */
	public function testGetPropertyIsSet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Form_Parser_TagData::setProperty
	 * @todo   Implement testSetProperty().
	 */
	public function testSetProperty() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Jet\Form_Parser_TagData::unsetProperty
	 * @todo   Implement testUnsetProperty().
	 */
	public function testUnsetProperty() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
