<?php
use JetApplicationModule\JetExample\Images\Gallery;
use JetApplicationModule\JetExample\Images\Gallery_Image;
use Jet\DataModel_Fetch_Object_Assoc;

/**
 * @var DataModel_Fetch_Object_Assoc|Gallery[] $children
 */
$children = $this->children;

/**
 * @var Gallery $gallery
 */
$gallery = $this->gallery;

$images = [];
if($gallery) {
	$images = $gallery->getImages();
}
?>

<div class="row">
<?php foreach( $children as $gallery ): ?>
	<a href="<?=rawurlencode($gallery->getTitle());?>/" class="img-thumbnail" style="width: 130px;height: 120px;text-align: center;overflow: hidden;margin: 3px;">
		<img src="<?=JET_PUBLIC_URI?>icons/folder.png">
		<br/>
		<?=$gallery->getTitle();?>
	</a>
<?php endforeach; ?>
</div>

<div class="row">
<?php foreach( $images as $image ):
    /**
     * @var Gallery_Image $image
     */
    $thumbnail = $image->getThumbnail( 120, 120 );
	?>
	<div class="col-xs-6 col-md-3">
		<a href="<?=$image->getURI();?>" target="_blank" class="thumbnail"><img src="<?=$thumbnail->getURI();?>"/></a>
	</div>
<?php endforeach; ?>
</div>