<?php
namespace JetStudio;

use Jet\Tr;
use Jet\UI;
use Jet\MVC_View;
use Jet\UI_dialog;

/**
 * @var MVC_View $this
 */

$add_page_dialog = UI::dialog( 'add_page_dialog', Tr::_( 'Add page' ), UI_dialog::SIZE_LARGE );
?>

<?= $add_page_dialog->start() ?>
<div id="add_page_form_area">
	<?= $this->render( 'page/create/form' ) ?>
</div>
<?= $add_page_dialog->footer() ?>
<?= UI::button_save( Tr::_( 'Add page' ) )->setOnClick( 'Modules.editModule.addPage.send()' ) ?>
<?= $add_page_dialog->end() ?>




