<?php
namespace JetApplicationModule\Content\Articles\Admin;

use Jet\UI;

use Jet\MVC_View;
use JetApplicationModule\Content\Articles\Entity\Article;

/**
 * @var MVC_View $this
 * @var Article $item
 */

$item = $this->getRaw('item');
$router = $this->getController()->getControllerRouter();

foreach( Article::getLocales() as $locale ):
	$URI = $router->action( 'edit' )->URI( $item->getId() );
	$title = $item->getLocalized( $locale )->getTitle();
	
	echo UI::flag( $locale ) . '&nbsp;<a href="' . $URI . '">' . $title . '</a><br/>';
endforeach;
