<?php
namespace %<NAMESPACE>%;

use %<DATA_MODEL_CLASS_NAME>% as %<DATA_MODEL_CLASS_ALIAS>%;

use Jet\Http_Request;
use Jet\UI;
use Jet\Mvc_View;
use Jet\Tr;

/**
 * @var Mvc_View   $this
 * @var %<DATA_MODEL_CLASS_ALIAS>%       $%<ITEM_VAR_NAME>%
 */
$%<ITEM_VAR_NAME>% = $this->getRaw( '%<ITEM_VAR_NAME>%' );
$router = $this->getController()->getControllerRouter();

?>

<div class="row">
	<div class="col-md-12" id="main-col">

		<?=UI::button_goBack()?>
		<p>
			<?=Tr::_( '%<TXT_DELETE_CONFIRM_QUESTION>%' );?>
			<br/>
			<a href="<?=$router->action('edit')->URI( $%<ITEM_VAR_NAME>%->%<ITEM_ID_GETTER>%() );?>"
			   style="font-weight: bolder;font-size: 20px;"><?=$%<ITEM_VAR_NAME>%->getName();?> (<?=$%<ITEM_VAR_NAME>%->%<ITEM_NAME_GETTER>%();?>)</a>
		</p>

		<form action="<?=Http_Request::currentURI()?>" method="post">
			<input type="hidden" name="delete" value="yes">
			<?=UI::button_delete()->setType( 'submit' )?>
		</form>
	</div>
</div>