<?php
namespace %<NAMESPACE>%;

use %<DATA_MODEL_CLASS_NAME>% as %<DATA_MODEL_CLASS_ALIAS>%;

use Jet\Http_Request;
use Jet\UI;
use Jet\MVC_View;
use Jet\Tr;

/**
 * @var MVC_View   $this
 * @var %<DATA_MODEL_CLASS_ALIAS>%       $%<ITEM_VAR_NAME>%
 */
$%<ITEM_VAR_NAME>% = $this->getRaw( '%<ITEM_VAR_NAME>%' );
$router = $this->getController()->getControllerRouter();

?>
<div class="col d-flex justify-content-center">

	<div class="card" style="margin-top:50px;">
		<div class="card-body">
			<p>
				<?=Tr::_( '%<TXT_DELETE_CONFIRM_QUESTION>%' );?>
				<br/>
				<a href="<?=$router->action('edit')->URI( $%<ITEM_VAR_NAME>%->%<ITEM_ID_GETTER>%() );?>"
				   style="font-weight: bolder;font-size: 20px;"><?=$%<ITEM_VAR_NAME>%->%<ITEM_NAME_GETTER>%();?> (<?=$%<ITEM_VAR_NAME>%->%<ITEM_NAME_GETTER>%();?>)</a>
			</p>

			<div style="display: inline-block;width: 50%">
				<?= UI::button_goBack() ?>
			</div>
			<div style="display: inline-block;width: 45%;text-align: right">
				<form action="<?= Http_Request::currentURI() ?>" method="post">
					<input type="hidden" name="delete" value="yes">
					<?= UI::button_delete()->setType( 'submit' ) ?>
				</form>
			</div>
		</div>
	</div>
</div>
