<?php
namespace %<NAMESPACE>%;

use %<DATA_MODEL_CLASS_NAME>% as %<DATA_MODEL_CLASS_ALIAS>%;

use Jet\UI;
use Jet\UI_dataGrid;
use Jet\UI_button;

use Jet\Tr;
use Jet\MVC_View;
use Jet\Form;

/**
 * @var MVC_View     $this
 * @var UI_dataGrid  $grid
 * @var Form         $filter_form
 */
$grid = $this->getRaw( 'grid' );
$filter_form = $this->getRaw( 'filter_form' );
$router = $this->getController()->getControllerRouter();


$c_edit = $grid->getColumn( '_edit_' );
$c_edit->setRenderer(
	function( %<DATA_MODEL_CLASS_ALIAS>% $item ) use ( $router ) {
		if( ( $delete_uri = $router->action('delete')->URI( $item->%<ITEM_ID_GETTER>%() ) ) ):
			echo UI::button_delete(' ')->setUrl( $delete_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
			echo '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
		endif;
		if( ( $edit_uri = $router->action('edit')->URI( $item->%<ITEM_ID_GETTER>%() ) ) ):
			echo UI::button_edit()->setUrl( $edit_uri )->setSize( UI_button::SIZE_EXTRA_SMALL);
		endif;

	}
);
$c_edit->addCustomCssStyle( 'width:200px;' );

$grid->getColumn( '%<ID_PROPERTY>%' )->addCustomCssStyle( 'width:120px;' );

$grid->getColumn( '%<ID_PROPERTY>%' )->setRenderer(
	function( %<DATA_MODEL_CLASS_ALIAS>% $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->%<ITEM_ID_GETTER>%() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->%<ITEM_ID_GETTER>%();?></a>
		<?php
	}
);


$grid->getColumn( '%<NAME_PROPERTY>%' )->setRenderer(
	function( %<DATA_MODEL_CLASS_ALIAS>% $item ) use ( $router ) {
		$edit_uri = $router->action('edit')->URI( $item->%<ITEM_ID_GETTER>%() );
		?>
		<a href="<?=$edit_uri;?>"><?=$item->%<ITEM_NAME_GETTER>%();?></a>
		<?php
	}
);

?>

<?=$filter_form->start()?>
<div class="row toolbar">
	<?php if( ( $add_uri = $router->action('add')->URI() ) ): ?>
		<div class="col-md-2 col-sm-12">
			<?=UI::button_create( Tr::_( '%<TXT_BTN_NEW>%' ) )->setUrl( $add_uri )?>
		</div>
	<?php endif; ?>

	<div class="col-md-3 col-sm-12">
		<?=$filter_form->field('search')->input()?>
	</div>
	<div class="col-md-4 col-sm-12">
	</div>

</div>
<?=$filter_form->end()?>

<div class="row">
	<div class="col-md-12">
		<?=$grid->render();?>
	</div>
</div>
