<?php

use JetApplicationModule\Content\Articles\Entity\Article;
use Jet\Tr;
use Jet\Locale;
use Jet\MVC_View;

/**
 * @var MVC_View $this
 * @var Article $article
 */
$article = $this->getRaw( 'article' );
?>

<h1><?= $article->getTitle(); ?></h1>

<div>
	<?= Tr::_( 'Date:' ); ?>
	<?= Locale::dateAndTime( $article->getDateTime() ); ?>
</div>

<p>
	<?= $article->getAnnotation(); ?>
</p>

<?= $article->getText(); ?>

