<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	
	<title></title>
</head>

<body>
	<div class="dbg-fata-error" >
		<div class="dbg-fata-error-title">
			&#128163; Fatal error
		</div>
		
		<div class="dbg-links">
			<?php require 'links.phtml'; ?>
		</div>
	</div>

	<?php
	require_once 'css.phtml';
	require_once 'js.phtml';
	
	require 'error.phtml';
	?>
</body>
</html>

