<?php
use Jet\Tr;
use Jet\Mvc_Page;
use Jet\Auth;
use Jet\Mvc;

//TODO: bootstrap podporovat jako DoJo
Mvc::requireCssFile('//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php require 'parts/header.phtml'; ?>
</head>
<body>
	<jet_layout_body_prefix/>

	<div class="container" id="container" style="width: 100%">
		<div class="row" style="background-color: #000000;color: #ffffff;">
			<div style="float: left">
				<h1><?=Tr::_("PHP Jet Example Application - Administration");?></h1>
			</div>

			<div class="btn btn-default" style="float:right;margin: 10px;">
				<?=Tr::_('Current user: %USERNAME%', ['USERNAME' => Auth::getCurrentUser()->getLogin()]);?>
				<a href="<?=Mvc_Page::get('admin/logout')->getURL(); ?>" class="btn btn-danger"><?=Tr::_('LOGOUT');?></a>
			</div>

		</div>

		<div class="row">
			<jet_module module="JetExample.BreadcrumbNavigation" view="admin"/>
		</div>
		<div class="row">
			<jet_layout_main_position/>
		</div>
	</div>

	<?php /*

	<jet_layout_body_suffix/>
    */ ?>
</body>
</html>