<?php
use Jet\Tr;
use Jet\Mvc_Page;
use Jet\Auth;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php require 'parts/header.phtml'; ?>
	<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css"/>
</head>
<body>
	<jet_layout_body_prefix/>

	<div style="position: absolute;top:12px; left: 10px;">
		<jet_module data-module-name="JetExample.BreadcrumbNavigation" data-action-parameters="{view:'default'}"/>
	</div>

	<div style="position: absolute;top:5px; right: 10px;">
		<?=Tr::_('Current user: %USERNAME%', array('USERNAME' => Auth::getCurrentUser()->getLogin()));?>
		<a href="<?=Mvc_Page::get('admin/logout')->getURL(); ?>" class="btn btn-default"><?=Tr::_('LOGOUT');?></a>
	</div>

	<div style="height: 25px;"></div>

	<hr/>

	<jet_layout_main_position/>
	<jet_layout_body_suffix/>
</body>
</html>