<?php
use Jet\Tr;
use Jet\Mvc_Page;
use Jet\Auth;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php require 'parts/header.phtml'; ?>
</head>
<body class="%DOJO_THEME%">



	<jet_layout_body_prefix/>

    <?php require 'parts/dialogs.phtml'; ?>


	<?php /*
	<div>
	User: <?=Auth::getCurrentUser()->getLogin(); ?>
		[<a href="<?=Mvc_Page::get('admin/logout')->getURL(); ?>">LOGOUT</a>]
	</div>
 */ ?>

	<jet_layout_main_position/>
	<jet_layout_body_suffix/>
</body>
</html>